[[driver-get-the-driver]]
= Get the driver

:maven-artifact-info: http://search.maven.org/#artifactdetails%7Corg.neo4j.driver%7Cneo4j-java-driver%7C{java-driver-version}%7Cjar


[[driver-versions]]
== Versions

Consult the version table to determine which version of the driver to use with a particular version of Neo4j.

.Supported versions
[options='header']
|===
| Driver version | Neo4j version | Bolt protocol version
| 1.1            | 3.1           | 1
| 1.1            | 3.0 <*>       | 1
| 1.0            | 3.1 <*>       | 1
| 1.0            | 3.0           | 1
|===

<*> Driver versions 1.0 and 1.1 work with both Neo4j 3.0 and 3.1.
To take advantage of the Causal Cluster mode in Neo4j 3.1 and use features such as bookmarking and routing, it is necessary to use version 1.1 of the driver.


== Acquire the driver

You can download the driver source or acquire it with one of the dependency managers for your language.

.Acquire the driver
[.tabbed-example]
====
[.include-with-dotnet]
======
Using NuGet in Visual Studio:

[source, csharp, subs="attributes, specialcharacters"]
----
PM> Install-Package Neo4j.Driver -Version {dotnet-driver-version}
----
======

[.include-with-java]
======
When using Maven, add this to your _pom.xml_ file:

[source, xml, subs="attributes, specialcharacters"]
----
<dependencies>
    <dependency>
        <groupId>org.neo4j.driver</groupId>
        <artifactId>neo4j-java-driver</artifactId>
        <version>{java-driver-version}</version>
    </dependency>
</dependencies>
----

For Gradle or Grails, this is how to add the dependency:

[source, groovy, subs="attributes, specialcharacters"]
----
compile 'org.neo4j.driver:neo4j-java-driver:{java-driver-version}'
----

For other build systems, see {maven-artifact-info}[information available at Maven Central].
======

[.include-with-javascript]
======
[source, shell, subs="attributes, specialcharacters"]
----
npm install neo4j-driver@{javascript-driver-version}
----
======

[.include-with-python]
======
[source, shell, subs="attributes, specialcharacters"]
----
pip install neo4j-driver=={python-driver-version}
----
======
====

