[[driver-use-the-driver]]
= Use the driver

Each Neo4j driver has a database object for creating a driver.
To use a driver, follow this pattern:

. Ask the _database_ object for a new driver.
. Ask the _driver_ object for a new session.
. Ask the _session_ object to create a transaction.
. Use the _transaction_ object to run statements.
  It returns an object representing the result.
. Process the _result_.
. Close the session.

// TODO: Below example should use explicit transactions.

[.tabbed-example]
.Use the driver
====
[.include-with-dotnet]
======
For a minimal working example, the following imports are necessary.

[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=minimal-example-import]
----

These can then be used to run a statement against the server.

[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=minimal-example]
----
======

[.include-with-java]
======
For a minimal working example, the following imports are necessary.

[source, java]
----
include::{java-examples}/MinimalWorkingExample.java[tags=minimal-example-import]
----

These can then be used to run a statement against the server.

[source, java]
----
include::{java-examples}/MinimalWorkingExample.java[tags=minimal-example]
----
======

[.include-with-javascript]
======
For a minimal working example, the following imports are necessary.

[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=minimal-example-import]
----

These can then be used to run a statement against the server.

[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=minimal-example]
----
======

[.include-with-python]
======
For a minimal working example, the following imports are necessary.

[source, python]
----
include::{python-examples}/test_examples.py[tags=minimal-example-import]
----

These can then be used to run a statement against the server.

[source, python]
----
include::{python-examples}/test_examples.py[tags=minimal-example]
----
======
====

It is also possible to run statements directly from the session object.
The session will then take care of opening and closing the transaction.
This can be convenient for individual read-only queries.
// TODO: Insert why it is not advisable for write queries.
