// This doc is also sourced in the Aura Developer Hub.
// Because of that, cross-links are absolute and
// source blocks have copy=true .

The Neo4j Python driver is the official library to interact with a Neo4j instance through a Python application.

At the hearth of Neo4j lies <<Cypher>>, the query language to interact with a Neo4j database.
While this guide does not _require_ you to be a seasoned Cypher querier, it is going to be easier to focus on the Python-specific bits if you already know some Cypher.
For this reason, although this guide does _also_ provide a gentle introduction to Cypher along the way, consider checking out link:https://neo4j.com/docs/getting-started/cypher/[Getting started -> Cypher] for a more detailed walkthrough of graph databases modelling and querying if this is your first approach.
You may then apply that knowledge while following this guide to develop your Python application.


[#install]
== Install

Install the Neo4j Python driver with `pip`:

[source, bash, copy=true]
----
pip install neo4j
----

link:https://neo4j.com/docs/python-manual/current/install/[More info on installing the driver]


[#connect]
== Connect to the database

Connect to a database by creating a <<Driver>> object and providing a URL and an authentication token.
Once you have a `Driver` instance, use the `.verify_connectivity()` method to ensure that a working connection can be established.

[source, python, copy=true]
----
from neo4j import GraphDatabase

# URI examples: "neo4j://localhost", "neo4j+s://xxx.databases.neo4j.io"
URI = "{neo4j-database-uri}"
AUTH = ("{neo4j-username}", "{neo4j-password}")

with GraphDatabase.driver(URI, auth=AUTH) as driver:
    driver.verify_connectivity()
----

link:https://neo4j.com/docs/python-manual/current/connect/[More info on connecting to a database]


[#create-graph]
== Create an example graph

Run a Cypher query with the method `Driver.execute_query()`.
Do not hardcode or concatenate parameters: use placeholders and specify the parameters as keyword arguments.

.Create two `Person` nodes and a `KNOWS` relationship between them
[source, python, copy=true]
----
summary = driver.execute_query("""
    CREATE (a:Person {name: $name})
    CREATE (b:Person {name: $friendName})
    CREATE (a)-[:KNOWS]->(b)
    """,
    name="Alice", friendName="David",
    database_="neo4j",
).summary
print("Created {nodes_created} nodes in {time} ms.".format(
    nodes_created=summary.counters.nodes_created,
    time=summary.result_available_after
))
----

link:https://neo4j.com/docs/python-manual/current/query-simple/[More info on querying the database]


[#query-graph]
== Query a graph

To retrieve information from the database, use the Cypher clause `MATCH`:

.Retrieve all `Person` nodes who like other `Person` s
[source, python, copy=true]
----
records, summary, keys = driver.execute_query("""
    MATCH (p:Person)-[:KNOWS]->(:Person)
    RETURN p.name AS name
    """,
    database_="neo4j",
)

# Loop through results and do something with them
for record in records:
    print(record.data())  # obtain record as dict

# Summary information
print("The query `{query}` returned {records_count} records in {time} ms.".format(
    query=summary.query, records_count=len(records),
    time=summary.result_available_after
))
----

link:https://neo4j.com/docs/python-manual/current/query-simple/[More info on querying the database]


[#close]
== Close connections and sessions

Unless you created them using the `with` statement, call the `.close()` method on all `Driver` and `Session` instances to release any resources still held by them.

[source, python, copy=true]
----
from neo4j import GraphDatabase


driver = GraphDatabase.driver(URI, auth=AUTH)
session = driver.session(database="neo4j")

# session/driver usage

session.close()
driver.close()
----
