[[configuration]]
= Configuration

// TODO: Confirm which configuration items are actually _uniform_.

In addition to the Bolt URL, the driver can be configured for:

* session pool size
* session pool behavior
* authentication strategies
* logging

[options='header', cols='2,5,1m']
|===
| Name                  | Description                                | Default
| Session pool size (*) | Max number of sessions per URL.            | 50
| Logging               | Provide a logging facility for the driver. | N/A
|===

(*) The .NET and Python drivers provide _idle session pool size_, which is the maximum number of idle sessions to be pooled by the driver.
There is no limit to how many sessions that can be created, but a maximum limits how many sessions will be buffered after they are returned to the session pool.

[.tabbed-example]
.Example: Create a driver with configuration
====
[include-with-dotnet]
--
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=configuration]
----
--

[include-with-java]
--
[source, java]
----
include::{java-examples}/Examples.java[tags=configuration]
----
--

[include-with-javascript]
--
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=configuration]
----
--

[include-with-python]
--
[source, python]
----
include::{python-examples}/test_examples.py[tag=configuration]
----
--
====


[[authentication-encryption]]
== Encryption and authentication

The Neo4j drivers support encrypting the traffic between the Neo4j driver and the Neo4j instance using SSL/TLS.
Neo4j will by default allow both encrypted and unencrypted connections from drivers.
This can be modified to require encryption for all connections.
Please see \{some-handy-attribute-for-the-correct-page-in-the-manual\} for information on how to do that.

We strongly encourage using encryption to keep authentication credentials and data stored in Neo4j secure.
Those drivers that are able to do so will use encryption by default.
Because of technical limitations, the .NET driver does not have encryption enabled by default.
Similarly, JavaScript driver does not have encryption enabled by default when running inside a web browser.


== Enabling encryption

While most drivers default to enabling encryption, it is good practice to configure encryption explicitly.
This makes it clear that encryption is used for other developers reading the code and minimizes the risk of mistakes from relying on defaults.
Encryption should only be turned off in a trusted internal network.

[.tabbed-example]
.Example: Configure driver to require TLS encryption
====
[include-with-dotnet]
--
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=tls-require-encryption]
----
--

[include-with-java]
--
[source, java]
----
include::{java-examples}/Examples.java[tags=tls-require-encryption]
----
--
[include-with-javascript]
--
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=tls-require-encryption]
----
--
[include-with-python]
--
[source, python]
----
include::{python-examples}/test_examples.py[tag=tls-require-encryption]
----
--
====


== Trust

When establishing an encrypted connection the identity of the remote peer must be verified.
Without verification of identity, communication is vulnerable to so-called "man-in-the-middle" attacks.
Because of this, Neo4j drivers do not offer a way to establish encrypted connections without also establishing trust.

Two trust strategies are available:

* Trust on first use.
* Trust signed certificate.

_Trust on first use_ means that the driver will trust the first connection to a host to be safe and intentional.
On subsequent connections, the driver will verify that it communicates with the same host as on the first connection.
To ensure that this authentication strategy is valid the first connection to the server must be established in a trusted network environment.

This strategy is similar to the default strategy used by the `ssh` command line tool and provides a good degree of security with no configuration.
For this reason it is the default strategy on all platforms that support it.

[CAUTION]
--
Due to technical limitations, this strategy is not available if you are using the .NET platform or if you are using the JavaScript driver inside a web browser.
--

// TODO: Why is trust-on-first-use not implemented in the C# driver? Will it be?
// Answer: Because .NET's cross-platform APIs don't give us what we need to do it :( There's work underway to remedy this.

[.tabbed-example]
.Example: Configure driver to trust on first use
====
[include-with-dotnet]
--
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=tls-trust-on-first-use]
----
--
[include-with-java]
--
[source, java]
----
include::{java-examples}/Examples.java[tags=tls-trust-on-first-use]
----
--
[include-with-javascript]
--
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=tls-trust-on-first-use]
----
--
[include-with-python]
--
[source, python]
----
include::{python-examples}/test_examples.py[tag=tls-trust-on-first-use]
----
--
====

_Trust signed certificate_ means that the driver will only connect to a Neo4j instance if it provides a certificate trusted by the driver.
In this scenario, one or more trusted certificate are installed in the driver.
The server then authenticates itself to the driver with a certificate signed by one of the trusted certificates known to the driver.

The way to install a trusted certificate into a driver varies for differ drivers.
The Java driver directly accepts the file path to the trusted certificate and would load the certificate automatically during runtime.
The .NET and Python drivers require that the certificate be imported into the operating system's trusted certificate store.

[.tabbed-example]
.Example: Configure driver to trust signed certificate
====
[include-with-dotnet]
--
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=tls-signed]
----
--

[include-with-java]
--
[source, java]
----
include::{java-examples}/Examples.java[tags=tls-signed]
----
--
[include-with-javascript]
--
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=tls-signed]
----
--
[include-with-python]
--
[source, python]
----
include::{python-examples}/test_examples.py[tag=tls-signed]
----
--
====


== Authenticate user

While the encrypted communication is established between a Neo4j driver and the server, the server may also require the driver to provide authentication credentials for the user connecting to the database.
Authentication credentials are required if the server is configured to have authentication enabled.
// See 'Securing Neo4j Server' (http://neo4j.com/docs/3.0.0-SNAPSHOT/security-server.html) for more information.

[.tabbed-example]
.Example: Connecting the driver to the server with authentication credentials
====
[include-with-dotnet]
--
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=connect-with-basic-auth]
----
--

[include-with-java]
--
[source, java]
----
include::{java-examples}/Examples.java[tags=connect-with-basic-auth]
----
--
[include-with-javascript]
--
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=connect-with-basic-auth]
----
--
[include-with-python]
--
[source, python]
----
include::{python-examples}/test_examples.py[tag=connect-with-basic-auth]
----
--
====

If communication between driver and server are is not encrypted, authentication credentials are sent as plain text.
It is highly recommended to use authentication with encryption.

[NOTE]
--
When connecting to Neo4j for the first time, the user must change the default password.
Given a fresh installed Neo4j server, if a driver tries to connect to the Neo4j server with the default password, the attempt would probably fail with an error saying that the credentials are expired and a password reset is required.
In this case, the user need to log in the Neo4j server via the browser to change the default password.
--
