[[configuration]]
= Configuration

The only configuration necessary to use a driver is a Bolt URL.

[[url-format]]
== URL Format

The Bolt URL follows the standard URL pattern of `scheme://hostname:port`.
The point of configuration is contained in the scheme.
The simplest Bolt URL uses `bolt` for schema on the default Neo4j port: `bolt://localhost:7474`.

To do the following, the server must be configured:

* To connect to Neo4j on a different port.
* To disable default security.
* To manually control the use of a WebSocket.

// TODO Better example

The driver is then configured to connect to the server in the desired way by altering the URL.
For example, `bolt+ssl://server:1234` would connect using SSL to `server` on port `1234`.

[[ssl-tls]]
== SSL / TLS

Traffic using the Neo4j Drivers is encrypted by default, using SSL/TLS.
If you want unencrypted communication you can configure the Neo4j server to listen to a different port.
Please see \{some-handy-attribute-for-the-correct-page-in-the-manual\} for information on how to do that.

// It looks like there will be no way to turn on/off in Driver.
// Possibly not mention this much beyond: "Please see server docs for configuration."
