[[configuration]]
= Configuration

// TODO: Confirm which configuration items are actually _uniform_.

In addition to the Bolt URL, the driver can be configured for:

* connection pool size
* connection pool behavior
* authentication strategies
* logging

[options='header', cols='2,5,1m']
|===
| Name                 | Description                                                                                                          | Default

| Connection pool size | Max number of connections per URL.                                                                                   | 10
| Idle time            | Connections that have been unused for longer than this threshold will be tested to verify that they are still alive. | 10
| Logging              | Provide a logging facility for the driver.                                                                           | N/A
|===

// TODO: Fix C# example to configure connection pool size.

[.tabbed-example]
.Example: Create a driver with configuration
====
[include-with-dotnet]
--
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=configuration]
----
--

[include-with-java]
--
[source, java]
----
include::{java-examples}/Examples.java[tags=configuration]
----
--

[include-with-javascript]
--
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=configuration]
----
--

[include-with-python]
--
[source, python]
----
include::{python-examples}/test_examples.py[tag=configuration]
----
--
====


[[authentication-encryption]]
== Authentication and encryption

All Neo4j drivers support encrypting the traffic between the Neo4j driver and the Neo4j instance using SSL/TLS.
Neo4j will by default allow both encrypted and unencrypted connections from drivers.
This can be modified to require encryption for all connections.
Please see \{some-handy-attribute-for-the-correct-page-in-the-manual\} for information on how to do that.

We strongly encourage using encryption to keep authentication credentials and data stored in Neo4j secure.
Because of this most drivers will turn encryption on by default.
However, due to technical limitations, the .NET driver does not have encryption enabled by default.
For similar reasons, the JavaScript driver does not have encryption enabled by default when running inside a Web Browser.

// TODO: What are we trying to say here?
//       If we want to say that the server can be configured to use a different port and to not use encryption,
//       they need to find (create) content in the Manual that we can link to.


=== Enabling encryption

While most drivers default to enabling encryption, it is good practice to configure encryption explicitly.
This makes it clear encryption is used for other developers reading the code and minimizes the risk of mistakes from relying on defaults.

[.tabbed-example]
.Example: Configure driver to require TLS encryption
====
[include-with-dotnet]
--
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=tls-require-encryption]
----
--

[include-with-java]
--
[source, java]
----
include::{java-examples}/Examples.java[tags=tls-require-encryption]
----
--
[include-with-javascript]
--
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=tls-require-encryption]
----
--
[include-with-python]
--
[source, python]
----
include::{python-examples}/test_examples.py[tag=tls-require-encryption]
----
--
====

=== Trust

When establishing an encrypted connection, it needs to be verified that the remote peer is who we expected to connect to.
Without verifying this, an attacker can easily perform a so-called "man-in-the-middle" attack, tricking the driver to establish an encrypted connection with her instead of the Neo4j Instance.
Because of this, Neo4j drivers do not offer a way to establish encrypted connections without also establishing trust.

Two trust strategies are available:

* Trust on first use.
* Trust signed certificate.

_Trust on first use_ means that the driver will trust the first connection to a host to be safe and intentional.
On subsequent connections, the driver will verify that the host is the same as on that first connection.

Users of the `ssh` command line tool will recognize this as similar to the default trust strategy used there.
This strategy allows a good degree of security with no configuration.
Because of this, it is the default strategy on all platforms that support it.

Due to technical limitations, this strategy is not available if you are using the .NET platform or if you are using the JavaScript driver inside a Web Browser.

// TODO: Why is trust-on-first-use not implemented in the C# driver? Will it be?
// Answer: Because .NET's cross-platform APIs don't give us what we need to do it :( There's work underway to remedy this.

[.tabbed-example]
.Example: Configure driver to trust on first use
====
[include-with-dotnet]
--
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=tls-trust-on-first-use]
----
--

[include-with-java]
--
[source, java]
----
include::{java-examples}/Examples.java[tags=tls-trust-on-first-use]
----
--
[include-with-javascript]
--
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=tls-trust-on-first-use]
----
--
[include-with-python]
--
[source, python]
----
include::{python-examples}/test_examples.py[tag=tls-trust-on-first-use]
----
--
====

_Trust signed certificate_ means that the driver will only connect to a host if it presents a trusted certificate.
A trusted certificate means either a certificate explicitly configured to be trusted by the driver or, more commonly, a certificate signed by a certificate the driver trusts.
All drivers support this trust strategy.

[.tabbed-example]
.Example: Configure driver to trust signed certificate
====
[include-with-dotnet]
--
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=tls-signed]
----
--

[include-with-java]
--
[source, java]
----
include::{java-examples}/Examples.java[tags=tls-signed]
----
--
[include-with-javascript]
--
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=tls-signed]
----
--
[include-with-python]
--
[source, python]
----
include::{python-examples}/test_examples.py[tag=tls-signed]
----
--
====
