[[configuration]]
= Configuration

// TODO: Confirm which configuration items are actually _uniform_.

In addition to the Bolt URL, the driver can be configured for:

* session pool size
* session pool behavior
* authentication strategies
* logging

[options='header', cols='2,5,1m']
|===
| Name                  | Description                                | Default
| Session pool size (*) | Max number of sessions per URL.            | 50
| Logging               | Provide a logging facility for the driver. | N/A
|===

(*) The .NET and Python drivers provide _idle session pool size_, which is the maximum number of idle sessions to be pooled by the driver.
There is no limit to how many sessions that can be created, but a maximum limits how many sessions will be buffered after they are returned to the session pool.

[.tabbed-example]
.Example: Create a driver with configuration
====
[include-with-dotnet]
--
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=configuration]
----
--

[include-with-java]
--
[source, java]
----
include::{java-examples}/Examples.java[tags=configuration]
----
--

[include-with-javascript]
--
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=configuration]
----
--

[include-with-python]
--
[source, python]
----
include::{python-examples}/test_examples.py[tag=configuration]
----
--
====


[[authentication-encryption]]
== Encryption and authentication

All Neo4j drivers support encrypting the traffic between the Neo4j driver and the Neo4j instance using SSL/TLS.
Neo4j will by default allow both encrypted and unencrypted connections from drivers.
This can be modified to require encryption for all connections.
Please see \{some-handy-attribute-for-the-correct-page-in-the-manual\} for information on how to do that.

We strongly encourage using encryption to keep authentication credentials and data stored in Neo4j secure.
Because of this most drivers will turn encryption on by default.
However, due to technical limitations, the .NET driver does not have encryption enabled by default.
For similar reasons, the JavaScript driver does not have encryption enabled by default when running inside a Web Browser.


=== Encryption

The driver can be configured to turn on or off TLS encryption.
Encryption should only be turned off in a trusted, internal network.
While most drivers default to enabling encryption, it is good practice to configure encryption explicitly.
This makes it clear encryption is used for other developers reading the code and minimizes the risk of mistakes from relying on defaults.

[.tabbed-example]
.Example: Configure driver to require TLS encryption
====
[include-with-dotnet]
--
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=tls-require-encryption]
----
--

[include-with-java]
--
[source, java]
----
include::{java-examples}/Examples.java[tags=tls-require-encryption]
----
--
[include-with-javascript]
--
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=tls-require-encryption]
----
--
[include-with-python]
--
[source, python]
----
include::{python-examples}/test_examples.py[tag=tls-require-encryption]
----
--
====


=== Trust

When establishing an encrypted connection, it needs to be verified that the remote peer is who we expected to connect to.
Without verifying this, an attacker can easily perform a so-called "man-in-the-middle" attack, tricking the driver to establish an encrypted connection with her instead of the Neo4j Instance.
Because of this, Neo4j drivers do not offer a way to establish encrypted connections without also establishing trust.

Two trust strategies are available:

* Trust on first use.
* Trust signed certificate.

_Trust on first use_ means that the driver will trust the first connection to a host to be safe and intentional.
On subsequent connections, the driver will verify that it communicates with the same host as on the first connection.
To ensure that this authentication strategy is valid, the first connection to the server must be established in a trusted network environment.

This strategy is the same as the default strategy used by the `ssh` command line tool.
It provides a good degree of security with no configuration.
For this reason it is the default strategy on all platforms that support it.

Because of technical limitations this strategy is not available for the .NET platform or when using the JavaScript driver inside a web browser.

[.tabbed-example]
.Example: Configure driver to trust on first use
====
[include-with-dotnet]
--
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=tls-trust-on-first-use]
----
--

[include-with-java]
--
[source, java]
----
include::{java-examples}/Examples.java[tags=tls-trust-on-first-use]
----
--
[include-with-javascript]
--
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=tls-trust-on-first-use]
----
--
[include-with-python]
--
[source, python]
----
include::{python-examples}/test_examples.py[tag=tls-trust-on-first-use]
----
--
====

_Trust signed certificate_ means that the driver will only connect to a Neo4j server if it provides a certificate trusted by the driver.
A trusted certificate is a certificate explicitly configured to be trusted by the driver or, more commonly, a certificate signed by a certificate the driver trusts.
All drivers support this trust strategy.

The way to install a trusted certificate for use by a driver varies for different drivers.
The Java driver directly accepts the file path to the trusted certificate and loads the certificate automatically at runtime.
The .NET and Python drivers require the certificate to first be installed into the operating system's trusted certificate store.

[.tabbed-example]
.Example: Configure driver to trust signed certificate
====
[include-with-dotnet]
--
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=tls-signed]
----
--

[include-with-java]
--
[source, java]
----
include::{java-examples}/Examples.java[tags=tls-signed]
----
--
[include-with-javascript]
--
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=tls-signed]
----
--
[include-with-python]
--
[source, python]
----
include::{python-examples}/test_examples.py[tag=tls-signed]
----
--
====


=== Authenticate user

While the encrypted communication is established between a Neo4j driver and the server, the server may also require the driver to provide authentication credentials for the user connecting to the database.
Authentication credentials are required if the server is configured to have authentication enabled.
// See 'Securing Neo4j Server' (http://neo4j.com/docs/3.0.0-SNAPSHOT/security-server.html) for more information.

[.tabbed-example]
.Example: Connecting the driver to the server with authentication credentials
====
[include-with-dotnet]
--
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=connect-with-basic-auth]
----
--

[include-with-java]
--
[source, java]
----
include::{java-examples}/Examples.java[tags=connect-with-basic-auth]
----
--
[include-with-javascript]
--
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=connect-with-basic-auth]
----
--
[include-with-python]
--
[source, python]
----
include::{python-examples}/test_examples.py[tag=connect-with-basic-auth]
----
--
====

If communication between driver and server are is not encrypted, authentication credentials are sent as plain text.
It is highly recommended to use authentication with encryption.

[NOTE]
--
When connecting to Neo4j for the first time, the user must change the default password.
Given a fresh installed Neo4j server, if a driver tries to connect to the Neo4j server with the default password, the attempt would probably fail with an error saying that the credentials are expired and a password reset is required.
In this case, the user need to log in the Neo4j server via the browser to change the default password.
--
