[[configuration]]
= Configuration


[.tabbed-example]
.Create a driver with default configuration
====
[include-with-java]
--
[source,java]
----
include::{java-examples}/Examples.java[tags=configuration]
----
--

[include-with-javascript]
--
[source,javascript]
----
COMING SOON
----
--

[include-with-python]
--
[source,python]
----
COMING SOON
----
--
====


The minimal configuration necessary to use a Neo4j driver is a Bolt URL.

[[ssl-tls]]
== SSL / TLS

Traffic using the Neo4j Drivers is encrypted by default, using SSL/TLS.
If you want unencrypted communication you can configure the Neo4j server to listen to a different port.
Please see \{some-handy-attribute-for-the-correct-page-in-the-manual\} for information on how to do that.

// Nigel: It looks like there will be no way to turn on/off in Driver.
// Possibly not mention this much beyond: "Please see server docs for configuration."


[[configuration]]
== Configuration

In addition to the Bolt URL, the driver can be configured for:

* connection pool size
* connection pool behavior
* authentication strategies
* logging

[options='header', cols='2,5,1m']
|===
| Name                 | Description                                                                                                          | Default

| Connection pool size | Max number of connections per URL.                                                                                   | 10
| Idle time            | Connections that have been unused for longer than this threshold will be tested to verify that they are still alive. | 10
| Logging              | Provide a logging facility for the driver.                                                                           | ?
|===


=== Security

The driver can be configured to use TLS encryption.

[.tabbed-example]
.Configure driver to require TLS encryption
====
[include-with-java]
--
[source,java]
----
include::{java-examples}/Examples.java[tags=tls-require-encryption]
----
--
[include-with-javascript]
--
[source,javascript]
----
COMING SOON
----
--
[include-with-python]
--
[source,python]
----
COMING SOON
----
--
====

Two authentication strategies are available:

* Trust on first use.
* Trust signed certificate.

_Trust on first use_ means that the driver will trust the first connection to a host to be safe and intentional.
On subsequent connections, the driver will verify that the host is the same as on that first connection.

[.tabbed-example]
.Configure driver to trust on first use
====
[include-with-java]
--
[source,java]
----
include::{java-examples}/Examples.java[tags=tls-trust-on-first-use]
----
--
[include-with-javascript]
--
[source,javascript]
----
COMING SOON
----
--
[include-with-python]
--
[source,python]
----
COMING SOON
----
--
====

_Trust signed certificate_ means that the driver will only connect to a host if it presents a trusted, signed certificate.

[.tabbed-example]
.Configure driver to trust signed certificate
====
[include-with-java]
--
[source,java]
----
include::{java-examples}/Examples.java[tags=tls-signed]
----
--
[include-with-javascript]
--
[source,javascript]
----
COMING SOON
----
--
[include-with-python]
--
[source,python]
----
COMING SOON
----
--
====
