[[configuration]]
= Configuration

// TODO: Confirm which configuration items are actually _uniform_.

In addition to the Bolt URL, the driver can be configured for:

* connection pool size
* connection pool behavior
* authentication strategies
* logging

[options='header', cols='2,5,1m']
|===
| Name                 | Description                                                                                                          | Default

| Connection pool size | Max number of connections per URL.                                                                                   | 10
| Idle time            | Connections that have been unused for longer than this threshold will be tested to verify that they are still alive. | 10
| Logging              | Provide a logging facility for the driver.                                                                           | N/A
|===

// TODO: Fix C# example to configure connection pool size.

[.tabbed-example]
.Example: Create a driver with configuration
====
[include-with-dotnet]
--
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=configuration]
----
--

[include-with-java]
--
[source, java]
----
include::{java-examples}/Examples.java[tags=configuration]
----
--

[include-with-javascript]
--
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=configuration]
----
--

[include-with-python]
--
[source, python]
----
include::{python-examples}/test_examples.py[tag=configuration]
----
--
====


[[authentication-encryption]]
== Authentication and encryption

With default configuration, traffic between a Neo4j driver and server is encrypted with SSL/TLS.
To use unencrypted communication the Neo4j server can be configured to listen on a different port.
Please see \{some-handy-attribute-for-the-correct-page-in-the-manual\} for information on how to do that.

// TODO: What are we trying to say here?
//       If we want to say that the server can be configured to use a different port and to not use encryption,
//       they need to find (create) content in the Manual that we can link to.


=== Security

// TODO: Why give an example of configuring TLS if it is the default?

The driver can be configured to use TLS encryption.

[.tabbed-example]
.Example: Configure driver to require TLS encryption
====
[include-with-dotnet]
--
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=tls-require-encryption]
----
--

[include-with-java]
--
[source, java]
----
include::{java-examples}/Examples.java[tags=tls-require-encryption]
----
--
[include-with-javascript]
--
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=tls-require-encryption]
----
--
[include-with-python]
--
[source, python]
----
include::{python-examples}/test_examples.py[tag=tls-require-encryption]
----
--
====

Two authentication strategies are available:

* Trust on first use.
* Trust signed certificate.

_Trust on first use_ means that the driver will trust the first connection to a host to be safe and intentional.
On subsequent connections, the driver will verify that the host is the same as on that first connection.

// TODO: Why is trust-on-first-use not implemented in the C# driver? Will it be?

[.tabbed-example]
.Example: Configure driver to trust on first use
====
[include-with-dotnet]
--
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=tls-trust-on-first-use]
----
--

[include-with-java]
--
[source, java]
----
include::{java-examples}/Examples.java[tags=tls-trust-on-first-use]
----
--
[include-with-javascript]
--
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=tls-trust-on-first-use]
----
--
[include-with-python]
--
[source, python]
----
include::{python-examples}/test_examples.py[tag=tls-trust-on-first-use]
----
--
====

_Trust signed certificate_ means that the driver will only connect to a host if it presents a trusted, signed certificate.

[.tabbed-example]
.Example: Configure driver to trust signed certificate
====
[include-with-dotnet]
--
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=tls-signed]
----
--

[include-with-java]
--
[source, java]
----
include::{java-examples}/Examples.java[tags=tls-signed]
----
--
[include-with-javascript]
--
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=tls-signed]
----
--
[include-with-python]
--
[source, python]
----
include::{python-examples}/test_examples.py[tag=tls-signed]
----
--
====
