[[driver-client-applications]]
= Client applications

[abstract]
--
This section describes how to manage database connections within an application.
--


[[driver-driver-object]]
== The driver object

A Neo4j client application will require a driver object instance in order to provide access to the database.
This object instance should be made available to all parts of the application that need to interact with Neo4j.
In languages where <<term-thread-safety, thread safety>> is an issue, the driver can be considered thread-safe.

[TIP]
.A note on lifecycle
--
Applications will typically construct a driver instance on startup and destroy it on exit.
Destroying a driver instance will immediately shut down any connections previously opened via that driver; for drivers that contain a connection pool, the entire pool will be shut down.
--

To construct a driver instance, a <<driver-connection-uris, connection URI>> and <<driver-authentication, authentication information>> must be supplied.
Additional configuration details can be supplied if required.
All of these details are immutable for the lifetime of the driver.
Therefore, if multiple configurations are required (such as when working with multiple database users) then multiple driver objects must be used.

An example of driver construction and destruction can be seen below:

[.tabbed-example]
.The driver lifecycle
====
[.include-with-dotnet]
======
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=driver-lifecycle]
----
======

[.include-with-java]
======
[source, java]
----
include::{java-examples}/DriverLifecycleExample.java[tags=driver-lifecycle]
----
======

[.include-with-javascript]
======
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=driver-lifecycle]
----
======

[.include-with-python]
======
[source, python]
----
include::{python-examples}/driver_lifecycle_example.py[tags=driver-lifecycle]
----
======
====


[[driver-connection-uris]]
== Connection URIs

A connection URI identifies a graph database and how to connect to it.
The official Neo4j drivers currently support the following URI schemes and driver object types:

.Available URI schemes
[options="header"]
|===
| URI Scheme     | Driver object type
| bolt           | Direct driver
| bolt+routing   | Routing driver
|===


=== Direct drivers (bolt)

A Direct driver is created via a `bolt` URI, for example: `bolt://localhost:7687`.
This kind of driver is used to maintain connections to a single database server and is typically used when working with a single Neo4j instance or when targeting a specific member of a cluster.
Note that a Routing driver is preferable when working with a causal cluster.


=== Routing drivers (bolt+routing)

A Routing driver is created via a `bolt+routing` URI, for example: `bolt+routing://graph.example.com:7687`.
The address in the URI must be that of a core server.
This kind of driver uses the <<term-bolt-routing-protocol, Bolt Routing Protocol>> and works in tandem with the cluster to route transactions to available cluster members.
 
=== Routing drivers with routing context

Routing drivers with routing context are an available option when using drivers of version 1.3 or above together with a Neo4j cluster of version 3.2 or above.
In such a setup, a routing driver can include a preferred routing context via the query part of the `bolt+routing` URI.
Below is an example using a routing context of `{region: europe, country: sw}`:

`bolt+routing://graph.example.com:7687/?region=europe&country=sw`

The driver communicates the routing context to the cluster.
It then obtains refined routing information back from the cluster, based on information suggested in the routing context.
In the example above, the driver communicates that it prefers to route queries to the servers located in the country Sweden in the region Europe.

[NOTE]
.Server-side configuration to enable Routing drivers with routing context
====
A prerequisite for using a Routing driver with routing context is that the Neo4j database is operated on a <<operations-manual#causal-clustering, Causal Cluster>> with the <<operations-manual#multi-dc-intro, Multi-data center licensing option>> enabled.
Additionally, the routing contexts must be defined within the cluster as routing _policies_.
For details on how to configure multi-data center routing policies for a Causal Cluster, please refer to <<operations-manual#multi-dc-load-balancing, Operations Manual -> Causal Clustering>>.
====


[[driver-authentication]]
== Authentication

Authentication details are provided as an auth token which contains the user names, passwords or other credentials required to access the database.
Neo4j supports multiple authentication standards but uses basic authentication by default.


[[driver-authentication-basic]]
=== Basic authentication

The basic authentication scheme is backed by a password file stored within the server and requires applications to provide a user name and password.
For this, use the basic auth helper:

[.tabbed-example]
.Basic authentication
====
[.include-with-dotnet]
======
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=basic-auth]
----
======

[.include-with-java]
======
[source, java]
----
include::{java-examples}/BasicAuthExample.java[tags=basic-auth]
----
======

[.include-with-javascript]
======
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=basic-auth]
----
======

[.include-with-python]
======
[source, python]
----
include::{python-examples}/auth_example.py[tags=basic-auth]
----
======
====

[NOTE]
--
The basic authentication scheme can also be used to authenticate against an LDAP server.
--

=== Kerberos authentication

The Kerberos authentication scheme provides a simple way to create a Kerberos authentication token with a base64 encoded server authentication ticket. 
The best way to create a Kerberos authentication token is shown below:

[.tabbed-example]
.Kerberos authentication
====
[.include-with-dotnet]
======
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=kerberos-auth]
----
======

[.include-with-java]
======
[source, java]
----
include::{java-examples}/KerberosAuthExample.java[tags=kerberos-auth]
----
======

[.include-with-javascript]
======
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=kerberos-auth]
----
======

[.include-with-python]
======
[source, python]
----
include::{python-examples}/kerberos_auth_example.py[tags=kerberos-auth]
----
======
====

[NOTE]
--
The Kerberos authentication token can only be understood by the server if the server has the link:{kerberos-add-on-base-uri}[Kerberos Add-on] installed.
--


[[driver-authentication-custom]]
=== Custom authentication

For advanced deployments, where a custom security provider has been built, the custom authentication helper can be used.

[.tabbed-example]
.Custom authentication
====
[.include-with-dotnet]
======
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=custom-auth]
----
======

[.include-with-java]
======
[source, java]
----
include::{java-examples}/CustomAuthExample.java[tags=custom-auth]
----
======

[.include-with-javascript]
======
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=custom-auth]
----
======

[.include-with-python]
======
[source, python]
----
include::{python-examples}/custom_auth_example.py[tags=custom-auth]
----
======
====


[[driver-configuration]]
== Configuration


[[driver-configuration-encryption]]
=== Encryption

TLS encryption is enabled for all connections by default.
This can be disabled through configuration as follows:

[.tabbed-example]
.Unencrypted
====
[.include-with-dotnet]
======
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=config-unencrypted]
----
======

[.include-with-java]
======
[source, java]
----
include::{java-examples}/ConfigUnencryptedExample.java[tags=config-unencrypted]
----
======

[.include-with-javascript]
======
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=config-unencrypted]
----
======

[.include-with-python]
======
[source, python]
----
include::{python-examples}/config_unencrypted_example.py[tags=config-unencrypted]
----
======
====

The server can be modified to require encryption for all connections.
Please see the <<operations-manual#connectors, Operations Manual -> Configure Neo4j connectors>> for more information.

An attempt to connect to a server using an encryption setting not allowed by that server will result in a <<driver-service-unavailable, _Service unavailable_>> status.


[[driver-configuration-trust]]
=== Trust

During a TLS handshake, the server provides a certificate to the client application.
The application can choose to accept or reject this certificate based on one of the following trust strategies:

.Trust strategies
[options="header"]
|===
| Trust strategy                        | Description
| `TRUST_ALL_CERTIFICATES` (default)    | Accept any certificate provided by the server
| `TRUST_CUSTOM_CA_SIGNED_CERTIFICATES` | Accept any certificate that can be verified against a custom CA
| `TRUST_SYSTEM_CA_SIGNED_CERTIFICATES` | Accept any certificate that can be verified against the system store
|===



[.tabbed-example]
.Trust
====
[.include-with-dotnet]
======
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=config-trust]
----
======

[.include-with-java]
======
[source, java]
----
include::{java-examples}/ConfigTrustExample.java[tags=config-trust]
----
======

[.include-with-javascript]
======
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=config-trust]
----
======

[.include-with-python]
======
[source, python]
----
include::{python-examples}/config_trust_example.py[tags=config-trust]
----
======
====


[[driver-config-connection-pool-management]]
=== Connection pool management

The driver maintains a pool of connections. The pooled connections are reused by sessions and transaction to avoid overhead added by establishing new connections every time to run a query.
The connection pool always start with an empty pool. New connections are created on demand by sessions and transactions to run queries. When a sessions or a transaction has done query execution with a connection, the connection will be returned to the pool to be reused.

Application users could tune connection pool settings to fit the driver for different usecases based on client performace requirement and database resourse consumption limit. 

The detailed description of the available connection pool settings via driver configuratoin are listed bellow:

* `MaxConnectionLifetime` - Default value: 1h. Pooled connections older than this threshold will be closed and removed from the pool. Such removal happens during connection acquisition so that new session is never backed by an old connection. Setting this option to a low value will cause a high connection churn and might result in a performance drop. It is recommended to set driver's maximum lifetime to a value smaller than the maximum lifetime configured in its application system infrastructure (such as operation system, router, load balancer, proxy, firewall, etc.). Negative values result in lifetime not being checked.

* `MaxConnectionPoolSize` - Default value: a large number such as 100 but vary in drivers. It defines the maximum total number of connections allowed to be managed by the connection pool per host. In other words, for direct driver this sets the max amount of connections towards a single database. While for routing driver this sets the max amount of connections towards each cluster member. When a session or transaction tries to acquire connection and pool is at its full capacity, then the session or transaction has to wait until a free connection is availble in the pool or the request to acquire a new connection times out. The connection acquiring timeout is configured via `connectionAcquisitionTimeout`.

* `ConnectionAcquisitionTimeout` - Default value: 1m. This setting limits amount of time a session or transaction can spend waiting for a free connection to appear in the pool before throwing an exception. Exception in this case is `ClientException`. Timeout only applies when connection pool is at its max capacity.

[.tabbed-example]
.Connection pool management
====
[.include-with-dotnet]
======
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=config-connection-pool]
----
======

[.include-with-java]
======
[source, java]
----
include::{java-examples}/ConfigConnectionPoolExample.java[tags=config-connection-pool]
----
======

[.include-with-javascript]
======
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=config-connection-pool]
----
======

[.include-with-python]
======
[source, python]
----
include::{python-examples}/config_connection_pool_example.py[tags=config-connection-pool]
----
======
====


[[driver-load-balancing-strategy]]
=== Load balancing strategy
For the routing driver, the driver contains a simple load balancer to route queries evenly among many cluster members. The built-in load balancer provides two strategies: `Least-connected` (Default) and `round-robin`. The `least-connection` strategy in general gives a better performance as it takes query execution time and server load into consideration when distrbuting queries among the cluster memebers. The 1.5 drivers adopt `least-connected` as default load balancing strategy. 

[.tabbed-example]
.Load balancing strategy
====
[.include-with-dotnet]
======
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=config-load-balancing-strategy]
----
======

[.include-with-java]
======
[source, java]
----
include::{java-examples}/ConfigLoadBalancingStrategyExample.java[tags=config-load-balancing-strategy]
----
======

[.include-with-javascript]
======
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=config-load-balancing-strategy]
----
======

[.include-with-python]
======
[source, python]
----
include::{python-examples}/config_load_balancing_strategy_example.py[tags=config-load-balancing-strategy]
----
======
====


[[driver-configuration-connection-timeout]]
=== Connection timeout

To configure the maximum time allowed to establish a connection, pass a duration value to the driver configuration.
For example:

[.tabbed-example]
.Connection timeout
====
[.include-with-dotnet]
======
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=config-connection-timeout]
----
======

[.include-with-java]
======
[source, java]
----
include::{java-examples}/ConfigConnectionTimeoutExample.java[tags=config-connection-timeout]
----
======

[.include-with-javascript]
======
[source, javascript]
----
This feature is not available in the Javascript driver.
----
======

[.include-with-python]
======
[source, python]
----
include::{python-examples}/config_connection_timeout_example.py[tags=config-connection-timeout]
----
======
====


[[driver-configuration-max-retry-time]]
=== Max retry time

To configure retry behavior, supply a value for the maximum time in which to keep attempting retries of transaction functions.
For example:

[.tabbed-example]
.Max retry time
====
[.include-with-dotnet]
======
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=config-max-retry-time]
----
======

[.include-with-java]
======
[source, java]
----
include::{java-examples}/ConfigMaxRetryTimeExample.java[tags=config-max-retry-time]
----
======

[.include-with-javascript]
======
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=config-max-retry-time]
----
======

[.include-with-python]
======
[source, python]
----
include::{python-examples}/config_max_retry_time_example.py[tags=config-max-retry-time]
----
======
====

Note that the time specified here does not take into account the running time of the unit of work itself, merely a limit after which retries will no longer be attempted.


[[driver-service-unavailable]]
== Service unavailable

A Service unavailable status will be signalled when the driver is no longer able to establish communication with the server, even after retries.
Encountering this condition usually indicates a fundamental networking or database problem.
Applications should be designed to cater for this eventuality.

[.tabbed-example]
.Service unavailable
====
[.include-with-dotnet]
======

[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=service-unavailable]
----
======

[.include-with-java]
======

[source, java]
----
include::{java-examples}/ServiceUnavailableExample.java[tags=service-unavailable]
----
======

[.include-with-javascript]
======

[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=service-unavailable]
----
======

[.include-with-python]
======

[source, python]
----
include::{python-examples}/service_unavailable_example.py[tags=service-unavailable]
----
======
====


