[[driver-sessions-transactions]]
= Sessions and transactions

[abstract]
--
This section describes how to create units of work and provide a logical context for that work.
--


[[driver-sessions]]
== Sessions

A session is a container for a sequence of transactions.
Sessions borrow connections from a pool as required and so should be considered lightweight and disposable.
In languages where <<term-thread-safety, thread safety>> is an issue, a session should _not_ be considered thread-safe.

In languages that support them, sessions are usually scoped within a context block.
This ensures that they are properly closed and that any underlying connections are released and not leaked.

[.tabbed-example]
.Session
====
[.include-with-dotnet]
======

[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=session]
----
======

[.include-with-java]
======

[source, java]
----
include::{java-examples}/SessionExample.java[tags=session]
----
======

[.include-with-javascript]
======

[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=session]
----
======

[.include-with-python]
======

[source, python]
----
include::{python-examples}/session_example.py[tags=session]
----
======
====


[[driver-transactions]]
== Transactions

Transactions are atomic units of work consisting of one or more Cypher statement executions.
A transaction is executed within a session.

To execute a Cypher statement, two pieces of information are required: the statement template and a keyed set of parameters.
The template is a string containing placeholders that are substituted with parameter values at runtime.
While it is possible to run non-parameterized Cypher, good programming practice is to use parameters in Cypher statements.
This allows for caching of statements within the Cypher engine, which is beneficial for performance.
Parameter values should adhere to <<cypher-values>>.

The Neo4j driver API provides for three forms of transaction:

* Auto-commit transactions
* Transaction functions
* Explicit transactions

Of these, only <<driver-transactions-transaction-functions, transaction function>> can be automatically replayed on failure.


[[driver-transactions-auto-commit]]
=== Auto-commit Transactions

An auto-commit transaction is a simple but limited form of transaction.
Such a transaction consists of only one Cypher statement, cannot be automatically replayed on failure, and cannot take part in a <<driver-transactions-causal-chaining, causal chain>>.

An auto-commit transaction is invoked using the `session.run` method:

[.tabbed-example]
.Auto-commit transaction
====
[.include-with-dotnet]
======

[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=autocommit-transaction]
----
======

[.include-with-java]
======

[source, java]
----
include::{java-examples}/AutocommitTransactionExample.java[tags=autocommit-transaction]
----
======

[.include-with-javascript]
======

[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=autocommit-transaction]
----
======

[.include-with-python]
======

[source, python]
----
include::{python-examples}/autocommit_transaction_example.py[tags=autocommit-transaction]
----
======
====

Auto-commit transactions are sent to the network and acknowledged immediately.
This means that multiple transactions cannot share network packets, thereby exhibiting a lesser network efficiency than other forms of transaction.

Auto-commit transactions are intended to be used for simple use cases such as when learning Cypher or writing one-off scripts.
It is not recommended to use auto-commit transactions in production environments or when performance or resilience are a primary concern.

However, Auto-commit transactions are the only way to execute `<<query-using-periodic-commit-hint, USING PERIODIC COMMIT>>` Cypher statements.


[[driver-transactions-transaction-functions]]
=== Transaction functions

Transaction functions are the recommended form for containing transactional units of work.
This form requires minimal boilerplate code and allows for a clear separation of database queries and application logic.

[.tabbed-example]
.Transaction function
====
[.include-with-dotnet]
======
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=transaction-function]
----
======

[.include-with-java]
======
[source, java]
----
include::{java-examples}/TransactionFunctionExample.java[tags=transaction-function]
----
======

[.include-with-javascript]
======
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=transaction-function]
----
======

[.include-with-python]
======
[source, python]
----
include::{python-examples}/transaction_function_example.py[tags=transaction-function]
----
======
====

Transaction functions are also able to handle connection problems and transient errors using an automatic retry mechanism.
This retry capability can be <<driver-configuration-max-retry-time, configured>> on Driver construction.

Any query results obtained within a transaction function should be consumed within that function.
Transaction functions can return values but these should be derived values rather than raw results.


[[driver-transactions-explicit]]
=== Explicit transactions

Explicit transactions are the longhand form of transaction functions, providing access to explicit `BEGIN`, `COMMIT` and `ROLLBACK` operations.
While this form is useful for a handful of use cases, it is recommended to use transaction functions wherever possible.


[[driver-transactions-cypher-errors]]
=== Cypher errors

When executing Cypher, it is possible for an exception to be thrown by the Cypher engine.
Each such exception is associated with a <<status-codes, status code>> that describes the nature of the error and a message that provides more detail.

The error classifications are listed in the table below.

.Error classifications
[options="header"]
|===
| Classification 	| Description
|ClientError            | The client application has caused an error.
The application should amend and retry the operation.

|DatabaseError          | The server has caused an error.
Retrying the operation will generally be unsuccessful.

|TransientError         | A temporary error has occurred.
The application should retry the operation.
|===


[[driver-transactions-causal-chaining]]
== Causal chaining

When working with a causal cluster, the transactions in a session will automatically be causally chained.
This means that for any two transactions, it is guaranteed that the second transaction will begin only after the first has been successfully committed.
This is true even if the transactions are physically carried out on different cluster members.

Causal chaining is carried out by passing <<term-bookmark, bookmarks>> between transactions in a session.
Each bookmark records a point in transactional history and is used to instruct the cluster to carry out work in a particular sequence.
Bookmarks are returned from the server to the client on the successful commit of a transaction and may be supplied as parameters to new transactions.
Passing bookmarks into a transaction causes the executing server to block until it has caught up with the latest of these bookmarks.

It is possible both to construct a session based on one or more existing bookmarks, and to extract a bookmark from a session.
This functionality allows multiple sessions to be chained together.

When running multiple independent transactions, it is recommended to use separate sessions.
This avoids the small latency overhead of the causal chain.

[TIP]
--
If you try to extract a bookmark from a database which is not running in Causal Cluster mode, you will receive a `null` result.
--


[[driver-transactions-access-mode]]
== Access modes

Transactions can be executed in either `read` or `write` mode.
In a causal cluster, each transaction will be routed to an appropriate server based on the mode.
When using a single instance, all transactions will be passed to that one server.
Routing Cypher by identifying reads and writes can improve the utilization of available cluster resources:
as read servers are typically more plentiful than write servers, it is beneficial to direct as much as possible of read transactions to read servers.
Doing so helps keeping write servers available for write transactions.

Note that the driver does not parse Cypher and cannot determine whether a transaction is intended to carry out read or write operations.
As a result of this, a `write` transaction tagged for `read` will be sent to a read server, but will fail on execution.

[.tabbed-example]
.Read-write transaction
====
[.include-with-dotnet]
======
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=read-write-transaction]
----
======

[.include-with-java]
======
[source, java]
----
include::{java-examples}/ReadWriteTransactionExample.java[tags=read-write-transaction]
----
======

[.include-with-javascript]
======
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=read-write-transaction]
----
======

[.include-with-python]
======
[source, python]
----
include::{python-examples}/read_write_transaction_example.py[tags=read-write-transaction]
----
======
====


== Asynchronous programming

[NOTE]
--
Java, .NET and JavaScript all support asynchronous programming.
The examples here highlight specifically how Java and .NET provide for this programming model alongside their blocking API.
--

In addition to the methods listed in the previous sections, there also exist several asynchronous methods which allow for better integration with applications written in an asynchronous style.
Asynchronous methods are named as their synchronous counterparts but with an additional _async_ prefix.

[.tabbed-example]
.Asynchronous programming examples
========
[.include-with-dotnet]
======

.Auto-commit transactions
[source, csharp]
----
include::{dotnet-examples}/ExamplesAsync.cs[tags=async-autocommit-transaction]
----

.Transaction functions
[source, csharp]
----
include::{dotnet-examples}/ExamplesAsync.cs[tags=async-transaction-function]
----

.Explicit transactions
[source, csharp]
----
include::{dotnet-examples}/ExamplesAsync.cs[tags=async-explicit-transaction]
----

[IMPORTANT]
--
It is always important to close the session object and it is suggested to keep *session.CloseAsync* in a _finally_ block to make sure all resources (such as network connection) obtained by the session will always be cleaned up properly.
The session *close* method also enforces rolling back of the last uncommitted or failed transaction in this session.
Thus it is optional to put *tx.CommitAsync* or *tx.RollbackAsync* in a _finally_ block as long as the *close* of session where the transaction is created will be executed in an outer _finally_ block.
--

======

[.include-with-java]
======

.Auto-commit transactions
[source, java]
----
include::{java-examples}/AsyncAutocommitTransactionExample.java[tags=async-autocommit-transaction]
----

.Transaction functions
[source, java]
----
include::{java-examples}/AsyncTransactionFunctionExample.java[tags=async-transaction-function]
----

.Explicit transactions
[source, java]
----
include::{java-examples}/AsyncExplicitTransactionExample.java[tags=async-explicit-transaction]
----

[IMPORTANT]
--
It is important to close the session object to make sure all resources (such as network connections) obtained by the session are cleaned up properly.
It is therefore suggested to always do `Session#closeAsync()` at the end of the whole `CompletionStage` chain.
Sessions should be closed regardless of whether the completes normally or exceptionally.
Closing the session also enforces the rollback of the last uncommitted or failed transaction in the session.
Thus it is optional to roll back the transaction using `Transaction#rollbackAsync()`, as long as the session is closed at the end of the full chain.
--

======
========
