[glossary]
[[terminology]]
= Terminology

This chapter explains the terminology used in the Neo4j Driver manual.
This section provides cross-linked summaries of common terms.

In some cases, multiple terms may be used for the same or a similar concept.
//An asterisk (*) to the right of a term indicates that the term is commonly used for Neo4j and Cypher.
// TODO not sure we need that

[glossary]
[[term-bolt]]bolt::
The protocol used by Neo4j drivers to communicate with the server.

[[term-driver]]driver::
An interface for operating the Neo4j database.
The Neo4j drivers implement the <<term-bolt, Bolt>> protocol.

[[term-result]]result::
The result of running a <<term-statement, statement>>.
A result can contains a stream of <<term-record, records>> and a <<term-summary, summary>>.

[[term-record]]result record::
An ordered map of keys and values.
A <<term-driver, Neo4j driver>> returns <<term-result, results>> as a stream of records.

[[term-summary]]result summary::
Information about the result of a <<term-statement, statement>>.
Can contain statistics about changes to the database or the execution plan for a statement that includes a `PROFILE` or `EXPLAIN` directive.

[[term-retain]]retain result::
COMING SOON

[[term-session]]session::
A session wraps a conversation between a client application and the Neo4j server.
It runs <<term-statement, statements>> and returns <<term-result, results>>.

[[term-statement]]statement::
COMING SOON
