[[driver-terminology]]
= Terminology

[abstract]
--
This section lists the relevant terminology related to drivers in Neo4j.
--

The following terms are relevant to drivers in Neo4j:

[[term-acquire-connection]]Acquire (connection)::
To borrow a connection that is not currently in use from a connection pool.
[[term-bolt]]Bolt messaging protocol::
Bolt is a Neo4j proprietary binary protocol used for communication between client applications and database servers.
[[term-bolt-routing-protocol]]Bolt routing protocol::
The steps required for a driver to obtain a routing table from a cluster member.
[[term-bolt-server]]Bolt server::
A Neo4j instance that can accept incoming Bolt connections.
[[term-bookmark]]Bookmark::
A marker for a point in the transactional history of Neo4j.
[[term-client-application]]Client application::
A piece of software that interacts with a database server via a driver.
[[term-cluster-member]]Cluster member::
A server that is part of a Causal Cluster.
[[term-connection]]Connection::
A persistent communication channel between a client application and a database server.
[[term-connection-pool]]Connection pool::
A set of connections maintained for quick access that can be acquired and released as required.
[[term-cypher-type-system]]Cypher type system::
The types used by Cypher.
See <<cypher-values>>.
[[term-direct-driver]]Direct driver::
A Driver that can connect to a single server address.
[[term-driver-object]]Driver (object)::
A globally accessible controller for all database access.
[[term-driver-package]]Driver (package)::
A software library that provides access to Neo4j from a particular programming language.
The Neo4j drivers implement the <<term-bolt, Bolt>> protocol.
[[term-parameters]]Parameters::
A keyed set of values than can be injected into a statement template, such as:

[source,cypher]
----
{""name"": ""Alice""}
----
[[term-record]]Record::
A keyed, ordered container for one or more values.
[[term-release-connection]]Release (connection)::
To return a connection back into a connection pool after use.
[[term-role]]Role (clustering)::
An operation that can be carried out by a cluster member (e.g. `read`, `write`).
[[term-routing-driver]]Routing driver::
A Driver that can route traffic to multiple members of a cluster using the routing protocol.
[[term-routing-table]]Routing table::
A set of server addresses that identify cluster members associated with roles.
[[term-server-address]]Server address::
A combination of host name and port or IP address and port that targets a server.
[[term-session]]Session::
A causally linked sequence of transactions.
[[term-statement]]Statement::
A non parameterised piece of Cypher or a combination of Cypher statement template and parameters, such as:
[source,cypher]
----
CREATE (a:Person {name: 'Alice'})
CREATE (a:Person {name: $name}) + {""name"": ""Alice""}
----
[[term-statement-result]]Statement result::
The stream of records that are returned on execution of a statement.
[[term-statement-template]]Statement template::
"A parameterised Cypher string, such as:

[source,cypher]
----
CREATE (a:Person {name: $name})"
----

[[term-thread-safety]]Thread safety::
See https://en.wikipedia.org/wiki/Thread_safety.
//!!!!!!!!!!!!!!!!!!!!!! Fix link.
[[term-thread-safe]]Thread-safe::
See Thread safety.
[[term-transaction]]Transaction::
An atomic unit of work.
[[term-value]]Value::
A unit of data belonging to the Cypher type system.

//[[term-driver]]driver::
//An interface for operating the Neo4j database.
//The Neo4j drivers implement the <<term-bolt, Bolt>> protocol.
//
//[[term-result]]result::
//The result of running a <<term-statement, statement>>.
//A result can contains a stream of <<term-record, records>> and a <<term-summary, summary>>.
//
//[[term-record]]result record::
//An ordered map of keys and values.
//A <<term-driver, Neo4j driver>> returns <<term-result, results>> as a stream of records.
//
//[[term-summary]]result summary::
//Information about the result of a <<term-statement, statement>>.
//Can contain statistics about changes to the database or the execution plan for a statement that includes a `PROFILE` or `EXPLAIN` directive.
//
//[[term-session]]session::
//A session wraps a conversation between a client application and the Neo4j server.
//It runs <<term-statement, statements>> and returns <<term-result, results>>.

