[[driver-cypher-values]]
= Working with Cypher values

[abstract]
--
This section describes the types and values used by Cypher and how they map to native language types.
--


[[driver-neo4j-type-system]]
== The Cypher type system

Drivers translate between application language types and the Cypher type system.
To pass parameters and process results, it is important to know the basics of the Cypher type system and to understand how the Cypher types are mapped in the driver.

Cypher types are split into two groups: basic types and graph structure types.
While query results can contain any of these, only basic types can be used as parameters.


[[driver-basic-types]]
=== Basic types

The basic types are:

* Boolean
* Integer
* Float
* String
* List
* Map


[NOTE]
--
For information on how to work with `null` in Cypher, please refer to <<cypher-working-with-null>>.
--


[[driver-graph-types]]
=== Graph structure types

In addition to the basic types which can be used both for parameters and results, the following Cypher types are valid for results only:

* Node
* Relationship
* Path

When streaming a result, the server takes snapshots of the original graph structure values to pass back to the client.
While the original entity IDs are included in these snapshots, no permanent link is retained back to the underlying server-side entities, which may be deleted or otherwise altered independently of the client copies.

Graph structures may not be used as parameters because it depends on application context whether such a parameter would be passed by reference or by value, and Cypher provides no mechanism to denote this.
Equivalent functionality is available by simply passing either the ID for pass by reference, or an extracted map of properties for pass by value.


[[driver-type-mappings]]
=== Type mappings

The Neo4j driver maps Cypher types to native language types as depicted in the table below.

[.tabbed-example]
.Map Neo4j types to native language types
====
[.include-with-dotnet]
======
[options="header", cols="m, m"]
|===
| Neo4j        | .NET
| Null         | null
| Boolean      | System.Boolean
| Integer      | System.Int64
| Float        | System.Double
| String       | System.String
| List         | System.Collections.Generic.IList<T>
| Map          | System.Collections.IDictionary<TKey, TValue>
| Node         | Neo4j.Driver.V1.INode
| Relationship | Neo4j.Driver.V1.IRelationship
| Path         | Neo4j.Driver.V1.IPath
|===
======

[.include-with-java]
======
[options="header", cols="m, m"]
|===
| Neo4j        | Java
| Null         | null
| Boolean      | java.lang.Boolean
| Integer      | java.lang.Long
| Float        | java.lang.Double
| String       | java.lang.String
| List         | java.util.List<T>
| Map          | java.util.Map<K, V>
| Node         | org.neo4j.driver.v1.types.Node
| Relationship | org.neo4j.driver.v1.types.Relationship
| Path         | org.neo4j.driver.v1.types.Path
|===
======

[.include-with-javascript]
======
[options="header", cols="m, m"]
|===
| Neo4j        | JavaScript
| Null         | null
| Boolean      | Boolean
| Integer      | Integer (*)
| Float        | Number
| String       | String
| List         | Array
| Map          | Object
| Node         | Node
| Relationship | Relationship
| Path         | Path
|===
****
(*) As JavaScript does not support 64-bit unsigned integers natively, the driver provides an `Integer` type to allow such values to be accurately represented in result data.
****
======

[.include-with-python]
======
[options="header", cols="m, m"]
|===
| Neo4j        | Python
| Null         | None
| Boolean      | bool
| Integer      | int/long (†)
| Float        | float
| String       | str/unicode (†)
| List         | list
| Map          | dict
| Node         | Node
| Relationship | Relationship
| Path         | Path
|===

.(†) Python versions
****
In Python 2, a Cypher `Integer` is mapped to `int` and a Cypher `String` to `str`.

In Python 3, a Cypher `Integer` is mapped to `long` and a Cypher `String` to `unicode`.
****

======
====


[[driver-result]]
== Statement results

A statement result is comprised of a stream of records.
The result is typically handled by the receiving application as it arrives, although it is also possible to retain all or part of a result for future consumption.

image::driver-result-stream.svg[title="Result stream", role="middle"]


[[driver-result-record]]
=== Records

A record provides an immutable view of part of a result.
It is an ordered map of keys and values.
As values within a record are both keyed and ordered, that value can be accessed either by position (0-based integer) or by key (string).


[[driver-result-buffer]]
=== The buffer

image::driver-result-buffer.svg[title="Result buffer", role="middle"]

Most drivers contain a result buffer.
This provides a staging point for results, and divides result handling into _fetching_ (moving from the network to the buffer) and _consuming_ (moving from the buffer to the application).

If results are consumed in the same order as they are produced, records merely pass through the buffer; if they are consumed out of order, the buffer will be utilized to retain records until they are consumed by the application.
For large results, this may require a significant amount of memory and impact performance. For this reason, it is recommended to consume results in order wherever possible.


[[driver-result-consume]]
=== Consuming the stream

Query results will often be consumed as a stream.
Drivers provide a language-idiomatic way to iterate through a result stream.

[.tabbed-example]
.Consuming the stream
====
[.include-with-dotnet]
======
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=result-consume]
----
======

[.include-with-java]
======
[source, java]
----
include::{java-examples}/ResultConsumeExample.java[tags=result-consume]
----
======

[.include-with-javascript]
======
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=result-consume]
----
======

[.include-with-python]
======
[source, python]
----
include::{python-examples}/result_consume_example.py[tags=result-consume]
----
======
====


[[driver-result-retain]]
=== Retaining results

The result record stream is available until another statement is run in the session, or until the current transaction is closed.
To hold on to the results beyond this scope, the results need to be explicitly retained.
For retaining results, each driver offers methods that collect the result stream and translate it into standard data structures for that language.
Retained results can be processed while the session is free to take on the next workload.
The saved results can also be used directly to run a new statement.



[.tabbed-example]
.Retain results for further processing
====
[.include-with-dotnet]
======
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=result-retain]
----
======
[.include-with-java]
======
[source, java]
----
include::{java-examples}/ResultRetainExample.java[tags=result-retain]
----
======
[.include-with-javascript]
======
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=result-retain]
----
======
[.include-with-python]
======
[source, python]
----
include::{python-examples}/result_retain_example.py[tags=result-retain]
----
======
====


[[driver-result-summary]]
== Statement result summaries

Supplementary information such as query statistics, timings and server information can be obtained from the statement result summary.
If this detail is accessed before the entire result has been consumed, the remainder of the result will be buffered.

See also the <<driver-api-docs, language-specific driver API documentation>>.
