[[driver-cypher-values]]
= Working with Cypher values

[abstract]
--
This section describes the types and values used by Cypher and how they map to native language types.
--


[[driver-neo4j-type-system]]
== The Cypher type system

Drivers translate between application language types and the Cypher type system.
To pass parameters and process results, it is important to know the basics of how Cypher works with types and to understand how the Cypher types are mapped in the driver.

The table below shows the available data types.
All can be potentially found in results although not all can be used as parameters.

====
[options="header", cols=",,"]
|===
| Cypher Type | Parameter | Result
| `null`* | ✔ | ✔
| `List`  | ✔ | ✔
| `Map`   | ✔ | ✔
| `Boolean` | ✔ | ✔
| `Integer` | ✔ | ✔
| `Float` | ✔ | ✔
| `String` | ✔ | ✔
| `ByteArray` | ✔ | ✔
| `Date` | ✔ | ✔
| `Time` | ✔ | ✔
| `LocalTime` | ✔ | ✔
| `DateTime` | ✔ | ✔
| `LocalDateTime` | ✔ | ✔
| `Duration` | ✔ | ✔
| `Point` | ✔ | ✔
| `Node`** | | ✔
| `Relationship`** | | ✔
| `Path`** | | ✔
|===

+*+ The null marker is not a type but a placeholder for absence of value.
For information on how to work with null in Cypher, please refer to <<cypher-working-with-null>>.

+**+ Nodes, relationships and paths are passed in results as snapshots of the original graph entities.
   While the original entity IDs are included in these snapshots, no permanent link is retained back to the underlying server-side entities, which may be deleted or otherwise altered independently of the client copies.
   Graph structures may not be used as parameters because it depends on application context whether such a parameter would be passed by reference or by value, and Cypher provides no mechanism to denote this.
   Equivalent functionality is available by simply passing either the ID for pass-by-reference, or an extracted map of properties for pass-by-value.
====

The Neo4j driver maps Cypher types to and from native language types as depicted in the table below.
Custom types (those not available in the language or standard library) are highlighted in *bold*.

[.tabbed-example]
.Map Neo4j types to native language types
====
[.include-with-dotnet]
======
[options="header", cols=","]
|===
| Neo4j type        | .NET type
| `null` | `null`
| `List` | `IList<object>`
| `Map` | `IDictionary<string, object>`
| `Boolean` | `bool`
| `Integer` | `long`
| `Float` | `double`
| `String` | `string`
| `ByteArray` | `byte[]`
| `Date` | *`LocalDate`*
| `Time` | *`OffsetTime`*
| `LocalTime` | *`LocalTime`*
| `DateTime`* | *`ZonedDateTime`*
| `LocalDateTime` | *`LocalDateTime`*
| `Duration` | *`Duration`*
| `Point` | *`Point`*
| `Node` | *`INode`*
| `Relationship` | *`IRelationship`*
| `Path` | *`IPath`*
|===

+*+ Time zone names adhere to the https://www.iana.org/time-zones[IANA system], rather than the https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/default-time-zones[Windows system].
Inbound conversion is carried out using http://cldr.unicode.org/development/development-process/design-proposals/extended-windows-olson-zid-mapping[Extended Windows-Olson zid mapping] as defined by Unicode CLDR.
======

[.include-with-java]
======
[options="header", cols="m,"]
|===
| Neo4j type        | Java type
| null | `null`
| List | `List<Object>`
| Map | `Map<String, Object>`
| Boolean | `boolean`
| Integer | `long`
| Float | `double`
| String | `String`
| ByteArray | `byte[]`
| Date | `LocalDate`
| Time | `OffsetTime`
| LocalTime | `LocalTime`
| DateTime | `ZonedDateTime`
| LocalDateTime | `LocalDateTime`
| Duration | *`IsoDuration`**
| Point | *`Point`*
| Node | *`Node`*
| Relationship | *`Relationship`*
| Path | *`Path`*
|===

+*+ A `Duration` or `Period` passed as a parameter will always be implicitly converted to `IsoDuration`.    
======

[.include-with-javascript]
======
[options="header", cols="m,"]
|===
| Neo4j type        | JavaScript type
| null | `null`
| List | `Array`
| Map | `Object`
| Boolean | `Boolean`
| Integer | *`Integer`**
| Float | `Number`
| String | `String`
| ByteArray | `Int8Array`
| Date | *`Date`*
| Time | *`Time`*
| LocalTime | *`LocalTime`*
| DateTime | *`DateTime`*
| LocalDateTime | *`LocalDateTime`*
| Duration | *`Duration`*
| Point | *`Point`*
| Node | *`Node`*
| Relationship | *`Relationship`*
| Path | *`Path`*
|===

+*+ JavaScript has no native integer type so a custom type is provided. For convenience, this can be disabled through configuration so that the native Number type is used instead. Note that this can lead to a loss of precision.
======

[.include-with-python]
======
[options="header", cols="m,,"]
|===
| Neo4j type        | Python 2 type | Python 3 type
| null | `None` | `None`
| List | `list` | `list`
| Map | `dict` | `dict`
| Boolean | `bool` | `bool`
| Integer | `int / long`* | `int`
| Float | `float` | `float`
| String | `unicode`** | `str`
| ByteArray | `bytearray` | `bytearray`
| Date | *`neotime.Date`* | *`neotime.Date`*
| Time | *`neotime.Time`*† | *`neotime.Time`*†
| LocalTime | *`neotime.Time`*†† | *`neotime.Time`*††
| DateTime | *`neotime.DateTime`*† | *`neotime.DateTime`*†
| LocalDateTime | *`neotime.DateTime`*†† | *`neotime.DateTime`*††
| Duration | *`neotime.Duration`**** | *`neotime.Duration`****
| Point | *`Point`* | *`Point`*
| Node | *`Node`* | *`Node`*
| Relationship | *`Relationship`* | *`Relationship`*
| Path | *`Path`* | *`Path`*
|===

+*+ While Cypher uses 64-bit signed integers, `int` can only hold integers up to `sys.maxint` in Python 2; `long` is used for values above this.

+**+ In Python 2, a `str` passed as a parameter will always be implicitly converted to `unicode` via UTF-8.

+***+ A `timedelta` passed as a parameter will always be implicitly converted to `neotime.Duration`.

† Where tzinfo is not None.

†† Where tzinfo is None.
======
====


[[driver-result]]
== Statement results

A statement result is comprised of a stream of records.
The result is typically handled by the receiving application as it arrives, although it is also possible to retain all or part of a result for future consumption.

image::driver-result-stream.svg[title="Result stream", role="middle"]


[[driver-result-record]]
=== Records

A record provides an immutable view of part of a result.
It is an ordered map of keys and values.
As values within a record are both keyed and ordered, that value can be accessed either by position (0-based integer) or by key (string).


[[driver-result-buffer]]
=== The buffer

image::driver-result-buffer.svg[title="Result buffer", role="middle"]

Most drivers contain a result buffer.
This provides a staging point for results, and divides result handling into _fetching_ (moving from the network to the buffer) and _consuming_ (moving from the buffer to the application).

If results are consumed in the same order as they are produced, records merely pass through the buffer; if they are consumed out of order, the buffer will be utilized to retain records until they are consumed by the application.
For large results, this may require a significant amount of memory and impact performance. For this reason, it is recommended to consume results in order wherever possible.


[[driver-result-consume]]
=== Consuming the stream

Query results will often be consumed as a stream.
Drivers provide a language-idiomatic way to iterate through a result stream.

[.tabbed-example]
.Consuming the stream
====
[.include-with-dotnet]
======
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=result-consume]
----
======

[.include-with-java]
======
[source, java]
----
include::{java-examples}/ResultConsumeExample.java[tags=result-consume]
----
======

[.include-with-javascript]
======
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=result-consume]
----
======

[.include-with-python]
======
[source, python]
----
include::{python-examples}/result_consume_example.py[tags=result-consume]
----
======
====


[[driver-result-retain]]
=== Retaining results

The result record stream is available until another statement is run in the session, or until the current transaction is closed.
To hold on to the results beyond this scope, the results need to be explicitly retained.
For retaining results, each driver offers methods that collect the result stream and translate it into standard data structures for that language.
Retained results can be processed while the session is free to take on the next workload.
The saved results can also be used directly to run a new statement.



[.tabbed-example]
.Retain results for further processing
====
[.include-with-dotnet]
======
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=result-retain]
----
======
[.include-with-java]
======
[source, java]
----
include::{java-examples}/ResultRetainExample.java[tags=result-retain]
----
======
[.include-with-javascript]
======
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=result-retain]
----
======
[.include-with-python]
======
[source, python]
----
include::{python-examples}/result_retain_example.py[tags=result-retain]
----
======
====


[[driver-result-summary]]
== Statement result summaries

Supplementary information such as query statistics, timings and server information can be obtained from the statement result summary.
If this detail is accessed before the entire result has been consumed, the remainder of the result will be buffered.

See also the <<driver-api-docs, language-specific driver API documentation>>.
