[[driver-bookmarking]]
= Bookmarking

Using a Bolt driver with a Causal Cluster provides causal consistency for the application.
This means that the application is guaranteed to always have a consistent view of related data.
This is exposed to the application through bookmarking.

After carrying out work in a session a bookmark is created.
The bookmark is a pointer to the work.
When a new session is created for other, related work the bookmark is used.
The bookmark ensures that the dependency of this later work on the previous is respected.
Whether or not the data has been replicated to every corner of the cluster, the bookmark guarantees that whichever instance services the next session will be up to speed with previous work.

Writing to the cluster we create a bookmark representing the logical position of the work.

.Create a bookmark
====
[source, java]
----
include::{extended-examples-java}/BookmarkingExample.java[tags=create-bookmark]
----
====


Having created the bookmark, we use it in a subsequent session when reading from the cluster.
The session will be serviced by an instance that is aware of the bookmarked work.
The view of the data is consistent for the application.


.Use a bookmark
====
[source, java]
----
include::{extended-examples-java}/BookmarkingExample.java[tags=use-bookmark]
----
====

