[[run-statement]]
= Run a statement

The session can run statements directly.
If a statement is run directly from a session, the session will take care of wrapping it in a transaction.


.Running a statement
[.tabbed-example]
====
[include-with-java]
--
[source,java]
----
include::{java-examples}[tags=statement]
----
--

[include-with-javascript]
--
[source,javascript]
----
include::{javascript-examples}[tags=statement]
----
--

[include-with-python]
--
[source,python]
----
include::{python-examples}[tags=statement]
----
--
====

It is always recommended to use parameters, but it is possible to run a query with literal values as well.

[IMPORTANT]
.Why it's important to use parameters
====
Using parameters have significant performance and security benefits, including:

* It allows the query planner to reuse its plans, which makes queries much more efficient.
* It protects the database from Cypher injection attacks, where malicious query clauses are added from poorly typed or filtered input.
====

.Running a statement without parameters
[.tabbed-example]
====
[include-with-java]
--
[source,java]
----
include::{java-examples}[tags=statement-without-parameters]
----
--

[include-with-javascript]
--
[source,javascript]
----
include::{javascript-examples}[tags=statement-without-parameters]
----
--

[include-with-python]
--
[source,python]
----
include::{python-examples}[tags=statement-without-parameters]
----
--
====


== Manual Transaction Management

The session can also create explicit transactions to be managed manually.
This allows for more fine-grained control.

.Running a statement in a manually managed transaction
[.tabbed-example]
====
[include-with-java]
--
[source,java]
----
include::{java-examples}[tags=transaction-commit]
----
--

[include-with-javascript]
--
[source,javascript]
----
include::{javascript-examples}[tags=transaction-commit]
----
--

[include-with-python]
--
[source,python]
----
include::{python-examples}[tags=transaction-commit]
----
--
====

The manually managed transaction can also be rolled back.

[.tabbed-example]
.Rolling back a manually managed transaction
====
[include-with-java]
--
[source, java]
----
include::{java-examples}[tags=transaction-rollback]
----
--
[include-with-javascript]
--
[source, javascript]
----
include::{javascript-examples}[tags=transaction-rollback]
----
--
[include-with-python]
--
[source, python]
----
include::{python-examples}[tags=transaction-rollback]
----
--
==== 
