[[driver-transactions]]
= Transaction management

:java-reference-transactions: {java-reference-base-uri}/#transactions

When the session runs a statement directly, it creates an implicit transaction.
The session can also create explicit transactions to be managed manually.
When explicitly told to begin a new transaction, the session will return a transaction object.
The transaction object allows for fine-grained transaction control.

[NOTE]
--
For details on transactions in Neo4j see the {java-reference-transactions}[Neo4j Java Developer Reference].
--

// TODO: This and the following examples are not realistic and don't explain the use of manual transaction management.
//       We need realistic examples.

.Example: Run a statement in a manually managed transaction
[.tabbed-example]
====
[include-with-dotnet]
======
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=transaction-commit]
----
======

[include-with-java]
======
[source, java]
----
include::{java-examples}/Examples.java[tags=transaction-commit]
----
======

[include-with-javascript]
======
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=transaction-commit]
----
======

[include-with-python]
======
[source, python]
----
include::{python-examples}/test_examples.py[tags=transaction-commit]
----
======
====

The manually managed transaction can also be rolled back.

[.tabbed-example]
.Example: Roll back a manually managed transaction
====
[include-with-dotnet]
======
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=transaction-rollback]
----
======

[include-with-java]
======
[source, java]
----
include::{java-examples}/Examples.java[tags=transaction-rollback]
----
======
[include-with-javascript]
======
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=transaction-rollback]
----
======
[include-with-python]
======
[source, python]
----
include::{python-examples}/test_examples.py[tags=transaction-rollback]
----
======
====
