// This doc is also sourced in the Aura Developer Hub.
// Because of that, cross-links are absolute,
// source blocks have copy=true , and Antora attributes
// (version) are explicitly resolved.

The Neo4j Java driver is the official library to interact with a Neo4j instance through a Java application.

At the hearth of Neo4j lies <<Cypher>>, the query language to interact with a Neo4j database.
While this guide does not _require_ you to be a seasoned Cypher querier, it is going to be easier to focus on the Java-specific bits if you already know some Cypher.
For this reason, although this guide does _also_ provide a gentle introduction to Cypher along the way, consider checking out link:https://neo4j.com/docs/getting-started/cypher/[Getting started -> Cypher] for a more detailed walkthrough of graph databases modelling and querying if this is your first approach.
You may then apply that knowledge while following this guide to develop your Java application.


[#install]
== Install

Add the Neo4j Java driver to the list of dependencies in the `pom.xml` of your Maven project:

[source, xml, subs="attributes+", copy=true]
----
<dependency>
    <groupId>org.neo4j.driver</groupId>
    <artifactId>neo4j-java-driver</artifactId>
    <version>5.28.7</version>
</dependency>
----

link:https://neo4j.com/docs/java-manual/current/install/[More info on installing the driver]


[#connect]
== Connect to the database

Connect to a database by creating a `Driver` object and providing a URL and an authentication token.
Once you have a `Driver` instance, use the `.verifyConnectivity()` method to ensure that a working connection can be established.

[source, java, role=nocollapse, copy=true]
----
package demo;

import org.neo4j.driver.AuthTokens;
import org.neo4j.driver.GraphDatabase;

public class App {

    public static void main(String... args) {

        // URI examples: "neo4j://localhost", "neo4j+s://xxx.databases.neo4j.io"
        final String dbUri = "{neo4j-database-uri}";
        final String dbUser = "{neo4j-username}";
        final String dbPassword = "{neo4j-password}";

        try (var driver = GraphDatabase.driver(dbUri, AuthTokens.basic(dbUser, dbPassword))) {
            driver.verifyConnectivity();
            System.out.println("Connection established.");
        }
    }
}
----

link:https://neo4j.com/docs/java-manual/current/connect/[More info on connecting to a database]


[#create-graph]
== Create an example graph

Run a Cypher query with the method `Driver.executableQuery()`.
Do not hardcode or concatenate parameters: use placeholders and specify the parameters as a map through the `.withParameters()` method.

.Create two `Person` nodes and a `KNOWS` relationship between them
[source, java, copy=true]
----
// import java.util.Map;
// import java.util.concurrent.TimeUnit;
// import org.neo4j.driver.QueryConfig;

var result = driver.executableQuery("""
    CREATE (a:Person {name: $name})
    CREATE (b:Person {name: $friendName})
    CREATE (a)-[:KNOWS]->(b)
    """)
    .withParameters(Map.of("name", "Alice", "friendName", "David"))
    .withConfig(QueryConfig.builder().withDatabase("neo4j").build())
    .execute();

// Summary information
var summary = result.summary();
System.out.printf("Created %d records in %d ms.%n",
    summary.counters().nodesCreated(),
    summary.resultAvailableAfter(TimeUnit.MILLISECONDS));
----

link:https://neo4j.com/docs/java-manual/current/query-simple/[More info on querying the database]


[#query-graph]
== Query a graph

To retrieve information from the database, use the Cypher clause `MATCH`:

.Retrieve all `Person` nodes who know other persons
[source, java, copy=true]
----
// import java.util.concurrent.TimeUnit;
// import org.neo4j.driver.QueryConfig;

var result = driver.executableQuery("""
    MATCH (p:Person)-[:KNOWS]->(:Person)
    RETURN p.name AS name
    """)
    .withConfig(QueryConfig.builder().withDatabase("neo4j").build())
    .execute();

// Loop through results and do something with them
var records = result.records();
records.forEach(r -> {
    System.out.println(r);  // or r.get("name").asString()
});

// Summary information
var summary = result.summary();
System.out.printf("The query %s returned %d records in %d ms.%n",
    summary.query(), records.size(),
    summary.resultAvailableAfter(TimeUnit.MILLISECONDS));
----

link:https://neo4j.com/docs/java-manual/current/query-simple/[More info on querying the database]


[#close]
== Close connections and sessions

Unless you created them with `try-with-resources` statements, call the `.close()` method on all `Driver` and `Session` instances to release any resources still held by them.

[source, java, test-skip, copy=true]
----
session.close();
driver.close();
----
