[[python-driver-client-applications]]
= Client applications

include::{common-content}/client-applications.adoc[tag=abstract]


[[python-driver-driver-object]]
== The Driver Object

include::{common-content}/client-applications.adoc[tag=object-pt1]

To construct a driver instance, a <<python-driver-connection-uris, connection URI>> and <<python-driver-authentication, authentication information>> must be supplied.

include::{common-content}/client-applications.adoc[tag=object-pt2]

.The driver lifecycle
====
[source, python]
----
include::{python-examples}/test_driver_lifecycle_example.py[tags=driver-lifecycle-import]
----

[source, python]
----
include::{python-examples}/test_driver_lifecycle_example.py[tags=driver-lifecycle]
----
====

[[python-driver-connection-uris]]
== Connection URIs

include::{common-content}/client-applications.adoc[tag=uris]

[NOTE]
====
https://neo4j.com/aura/[*Neo4j Aura*] is a *_secure hosted service_* backed by full certificates signed by a root certificate authority.

To connect to *Neo4j Aura*, driver users must *_enable encryption_* and the complete set of certificate checks (the latter of which are enabled by default).

For more information, see <<python-driver-configuration-examples>> below.
====

include::{common-content}/client-applications.adoc[tag=default-security-changes]


[[python-initial-address-resolution]]
=== Initial address resolution

include::{common-content}/client-applications.adoc[tag=initial-address-resolution]


[[python-dns-resolution]]
==== DNS resolution

include::{common-content}/client-applications.adoc[tag=dns-resolution]


[[python-custom-middleware]]
==== Custom middleware

include::{common-content}/client-applications.adoc[tag=custom-middleware]


[[python-driver-resolver-function]]
==== Resolver function

include::{common-content}/client-applications.adoc[tag=resolver-function]

.Custom Address Resolver
======
[source, python]
----
include::{python-examples}/test_custom_resolver_example.py[tags=custom-resolver-import]
----

[source, python]
----
include::{python-examples}/test_custom_resolver_example.py[tags=custom-resolver]
----
======


[[python-driver-routing-table]]
=== Routing table

include::{common-content}/client-applications.adoc[tag=routing-table]


[[python-driver-routing-context]]
=== Routing context

include::{common-content}/client-applications.adoc[tag=routing-context]


[[python-driver-configuration-examples]]
=== Examples

include::{common-content}/client-applications.adoc[tag=examples-pt1]

In a clustered environment, the URI address will resolve to one of more of the core members; for standalone installations, this will simply point to that server address.
The `ROUTING_CONTEXT` option allows for customization of the routing table and is discussed in more detail in <<python-driver-routing-context>>.

include::{common-content}/client-applications.adoc[tag=examples-pt2]

.Connecting to a service
The tables below illustrate examples of how to connect to a service with routing:

.Neo4j Aura, secured with full certificate
[cols="<15s,<85a"]
|===
| Product
| Neo4j Aura

| Security
| Secured with full certificate

| Code snippet
|
[source, python]
----
GraphDatabase.driver("neo4j+s://graph.example.com:7687", auth)
----

For Python Driver versions before 4.0.0 you need this snippet instead:
[source, python]
----
GraphDatabase.driver("neo4j://graph.example.com:7687", auth,
    "encrypted"=True, "trust"=TRUST_SYSTEM_CA_SIGNED_CERTIFICATES)
----

| Comments
| This is the default (and only option) for Neo4j Aura.
|===

.Neo4j 4.x, unsecured
[cols="<15s,<85a"]
|===
| Product
| Neo4j 4.x

| Security
| Unsecured

| Code snippet
|
[source, python]
----
GraphDatabase.driver("neo4j://graph.example.com:7687", auth)
----

| Comments
| This is the default for Neo4j 4.x series
|===

.Neo4j 4.x, secured with full certificate
[cols="<15s,<85a"]
|===
| Product
| Neo4j 4.x

| Security
| Secured with full certificate

| Code snippet
|
[source, python]
----
GraphDatabase.driver("neo4j+s://graph.example.com:7687", auth)
----

For Python Driver versions before 4.0.0 you need this snippet instead:
[source, python]
----
GraphDatabase.driver("neo4j://graph.example.com:7687", auth,
    "encrypted"=True, "trust"=TRUST_SYSTEM_CA_SIGNED_CERTIFICATES)
----
|===

.Neo4j 4.x, secured with self-signed certificate
[cols="<15s,<85a"]
|===
| Product
| Neo4j 4.x

| Security
| Secured with self-signed certificate

| Code snippet
|
[source, python]
----
neo4j.driver("neo4j+ssc://graph.example.com:7687", auth)
----

For Python Driver versions before 4.0.0 you need this snippet instead:
[source, python]
----
GraphDatabase.driver("neo4j://graph.example.com:7687", auth,
    "encrypted"=True, "trust"=TRUST_ALL_CERTIFICATES)
----
|===

.Neo4j 3.x, secured with full certificate
[cols="<15s,<85a"]
|===
| Product
| Neo4j 3.x

| Security
| Secured with full certificate

| Code snippet
|
[source, python]
----
neo4j.driver("neo4j+s://graph.example.com:7687", auth)
----

For Python Driver versions before 4.0.0 you need this snippet instead:
[source, python]
----
GraphDatabase.driver("neo4j://graph.example.com:7687", auth,
    "encrypted"=True, "trust"=TRUST_SYSTEM_CA_SIGNED_CERTIFICATES)
----
|===

.Neo4j 3.x, secured with self-signed certificate
[cols="<15s,<85a"]
|===
| Product
| Neo4j 3.x

| Security
| Secured with self-signed certificate

| Code snippet
|
[source, python]
----
neo4j.driver("neo4j+ssc://graph.example.com:7687", auth)
----

For Python Driver versions before 4.0.0 you need this snippet instead:
[source, python]
----
GraphDatabase.driver("neo4j://graph.example.com:7687", auth,
    "encrypted"=True, "trust"=TRUST_ALL_CERTIFICATES)
----

| Comments
| This is the default for Neo4j 3.x series
|===

.Neo4j 3.x, unsecured
[cols="<15s,<85a"]
|===
| Product
| Neo4j 3.x

| Security
| Unsecured

| Code snippet
|
[source, python]
----
neo4j.driver("neo4j://graph.example.com:7687", auth)
----
|===

[NOTE]
To connect to a service without routing, you can replace `neo4j` with `bolt`.


[[python-driver-authentication]]
== Authentication

include::{common-content}/client-applications.adoc[tag=authentication]


[[python-driver-authentication-basic]]
=== Basic authentication

include::{common-content}/client-applications.adoc[tag=authentication-basic]

.Basic authentication
======
[source, python]
----
include::{python-examples}/test_basic_auth_example.py[tags=basic-auth-import]
----

[source, python]
----
include::{python-examples}/test_basic_auth_example.py[tags=basic-auth]
----
======

include::{common-content}/client-applications.adoc[tag=authentication-basic-note]


[[python-driver-authentication-kerberos]]
=== Kerberos authentication

include::{common-content}/client-applications.adoc[tag=authentication-kerberos]

.Kerberos authentication
======
[source, python]
----
include::{python-examples}/test_kerberos_auth_example.py[tags=kerberos-auth-import]
----

[source, python]
----
include::{python-examples}/test_kerberos_auth_example.py[tags=kerberos-auth]
----
======

include::{common-content}/client-applications.adoc[tag=authentication-kerberos-note]

[[python-driver-authentication-bearer]]
=== Bearer authentication

include::{common-content}/client-applications.adoc[tag=authentication-bearer]

.Import bearer authentication
======
[source, python]
----
include::{python-examples}/test_bearer_auth_example.py[tags=bearer-auth-import]
----

[source, python]
----
include::{python-examples}/test_bearer_auth_example.py[tags=bearer-auth]
----
======

[[python-driver-authentication-custom]]
=== Custom authentication

include::{common-content}/client-applications.adoc[tag=authentication-custom]

.Custom authentication
======
[source, python]
----
include::{python-examples}/test_custom_auth_example.py[tags=custom-auth-import]
----

[source, python]
----
include::{python-examples}/test_custom_auth_example.py[tags=custom-auth]
----
======


[[python-driver-configuration]]
== Configuration

//include::{common-content}/client-applications.adoc[tag=configuration-ConnectionAcquisitionTimeout]
link:https://neo4j.com/docs/api/python-driver/{neo4j-version}/api.html#connection-acquisition-timeout[`ConnectionAcquisitionTimeout`]::

The maximum amount of time in secondsfootnote:[Other drivers may use milliseconds instead of seconds for this configuration.] a session will wait when requesting a connection from the connection pool.
For connection pools where all connections are currently being used and the `MaxConnectionPoolSize` limit has been reached, a session will wait this duration for a connection to be made available.
Since the process of acquiring a connection may involve creating a new connection, *_ensure that the value of this configuration is higher than the configured_* `ConnectionTimeout`.
+
Setting a low value will allow for transactions to *_fail fast_* when all connections in the pool have been acquired by other transactions.
Setting a higher value will result in these transactions being queued, increasing the chances of eventually acquiring a connection at the cost of longer time to receive feedback on failure.
Finding an optimal value may require an element of experimentation, taking into consideration the expected levels of parallelism within your application as well as the `MaxConnectionPoolSize`.
+
*Default:* 60.0
+
*Type:* float
+
.Configure connection pool
======
[source, python]
----
include::{python-examples}/test_config_connection_pool_example.py[tags=config-connection-pool-import]
----

[source, python]
----
include::{python-examples}/test_config_connection_pool_example.py[tags=config-connection-pool]
----
======

//include::{common-content}/client-applications.adoc[tag=configuration-ConnectionTimeout]
link:https://neo4j.com/docs/api/python-driver/{neo4j-version}/api.html#connection-timeout[`ConnectionTimeout`]::

The maximum amount of time in secondsfootnote:[Other drivers may use milliseconds instead of seconds for this configuration.] to wait for a TCP connection to be established.
Connections are only created when a session requires one unless there is an available connection in the connection pool.
The driver maintains a pool of open connections which can be loaned to a session when one is available.
If a connection is not available, then an attempt to create a new connection (provided the `MaxConnectionPoolSize` limit has not been reached) is made with this configuration option, providing the maximum amount of time to wait for the connection to be established.
+
In environments with high latency and high occurrences of connection timeouts it is recommended to configure a higher value.
For lower latency environments and quicker feedback on potential network issues configure with a lower value.
+
*Default:* 30.0
+
*Type:* float
+
.Configure connection timeout
======
[source, python]
----
include::{python-examples}/test_config_connection_timeout_example.py[tags=config-connection-timeout-import]
----

[source, python]
----
include::{python-examples}/test_config_connection_timeout_example.py[tags=config-connection-timeout]
----
======

`CustomResolver`::

Specify a custom server address resolver used by the routing driver to resolve the initial address used to create the driver.
See <<python-driver-resolver-function>> for more details.

include::{common-content}/client-applications.adoc[tag=configuration-Encryption]
+
.Unencrypted configuration
======
[source, python]
----
include::{python-examples}/test_config_unencrypted_example.py[tags=config-unencrypted-import]
----

[source, python]
----
include::{python-examples}/test_config_unencrypted_example.py[tags=config-unencrypted]
----
======

//include::{common-content}/client-applications.adoc[tag=configuration-MaxConnectionLifetime]
link:https://neo4j.com/docs/api/python-driver/{neo4j-version}/api.html#max-connection-lifetime[`MaxConnectionLifetime`]::

The maximum duration in secondsfootnote:[Other drivers may use milliseconds instead of seconds for this configuration.] the driver will keep a connection for before being removed from the pool.
Note that while the driver will respect this value, it is possible that the network environment will close connections inside this lifetime.
This is beyond the control of the driver.
The check on the connection’s lifetime happens when a session requires a connection.
If the available connection’s lifetime is over this limit it is closed and a new connection is created, added to the pool and returned to the requesting session.
Changing this configuration value would be useful in environments where users don’t have full control over the network environment and wish to proactively ensure all connections are ready.
+
Setting this option to a low value will cause a high connection churn rate, and can result in a performance drop.
It is recommended to pick a value smaller than the maximum lifetime exposed by the surrounding system infrastructure (such as operating system, router, load balancer, proxy and firewall).
Negative values result in lifetime not being checked.
+
*Default:* 3600
+
*Type:* float

include::{common-content}/client-applications.adoc[tag=configuration-MaxConnectionPoolSize]
+
*Default:* 100 connections

//include::{common-content}/client-applications.adoc[tag=configuration-MaxTransactionRetryTime]
link:https://neo4j.com/docs/api/python-driver/{neo4j-version}/api.html#max-transaction-retry-time[`MaxTransactionRetryTime`]::

The maximum amount of time in secondsfootnote:[Other drivers may use milliseconds instead of seconds for this configuration.] that a managed transaction will retry for before failing.
Queries that are executed within a managed transaction gain the benefit of being retried when a transient error occurs.
When this happens the transaction is retired multiple times up to the `MaxTransactionRetryTime`.
+
Configure this option higher in high latency environments or if you are executing many large transactions which could limit the number of times that they are retired and therefore their chance to succeed.
Configure lower in low latency environments and where your workload mainly consists of many smaller transactions.
Failing transactions faster may highlight the reasons behind the transient errors making it easier to fix underlying issues.
+
*Default:* 30.0
+
*Type:* float
+
.Configure maximum retry time
======
[source, python]
----
include::{python-examples}/test_config_max_retry_time_example.py[tags=config-max-retry-time-import]
----

[source, python]
----
include::{python-examples}/test_config_max_retry_time_example.py[tags=config-max-retry-time]
----
======

include::{common-content}/client-applications.adoc[tag=configuration-TrustStrategy]
+
.Configure trusted certificates
======
[source, python]
----
include::{python-examples}/test_config_trust_example.py[tags=config-trust-import]
----

[source, python]
----
include::{python-examples}/test_config_trust_example.py[tags=config-trust]
----
======


[[python-driver-logging]]
== Logging

include::{common-content}/client-applications.adoc[tag=logging]

[source, python]
----
import sys

from neo4j.debug import watch

watch("neo4j", out=sys.stdout)
----

For more control, you can configure the logger manually:

[source, python]
----
import logging
import sys

# create a handler, e.g., to log to stdout
handler = logging.StreamHandler(sys.stdout)
# configure the handler to your liking
handler.setFormatter(logging.Formatter(
    "[%(levelname)-8s] %(threadName)s(%(thread)d) %(asctime)s  %(message)s"
))
# add the handler to the driver's logger
logging.getLogger("neo4j").addHandler(handler)
# make sure the logger logs on the desired log level
logging.getLogger("neo4j").setLevel(logging.DEBUG)
# from now on, DEBUG logging to stderr is enabled in the driver
----
