[[python-driver-client-applications]]
= Client applications

include::{common-content}/client-applications.adoc[tag=abstract]


[[python-driver-driver-object]]
== The Driver Object

include::{common-content}/client-applications.adoc[tag=object-pt1]

To construct a driver instance, a <<python-driver-connection-uris, connection URI>> and <<python-driver-authentication, authentication information>> must be supplied.

include::{common-content}/client-applications.adoc[tag=object-pt2]

.The driver lifecycle
[source, python]
----
include::{python-examples}/test_driver_lifecycle_example.py[tags=driver-lifecycle-import]
----

[source, python]
----
include::{python-examples}/test_driver_lifecycle_example.py[tags=driver-lifecycle]
----


[[python-driver-connection-uris]]
== Connection URIs

include::{common-content}/client-applications.adoc[tag=uris]

[NOTE]
====
https://neo4j.com/aura/[*Neo4j Aura*] is a *_secure hosted service_* backed by full certificates signed by a root certificate authority.

To connect to *Neo4j Aura*, driver users must *_enable encryption_* and the complete set of certificate checks (the latter of which are enabled by default).

For more information, see <<python-driver-configuration-examples>> below.
====

include::{common-content}/client-applications.adoc[tag=default-security-changes]


[[python-initial-address-resolution]]
=== Initial address resolution

include::{common-content}/client-applications.adoc[tag=initial-address-resolution]


[[python-dns-resolution]]
==== DNS resolution

include::{common-content}/client-applications.adoc[tag=dns-resolution]


[[python-custom-middleware]]
==== Custom middleware

include::{common-content}/client-applications.adoc[tag=custom-middleware]


[[python-driver-resolver-function]]
==== Resolver function

include::{common-content}/client-applications.adoc[tag=resolver-function]

.Custom Address Resolver
======
[source, python]
----
include::{python-examples}/test_custom_resolver_example.py[tags=custom-resolver-import]
----

[source, python]
----
include::{python-examples}/test_custom_resolver_example.py[tags=custom-resolver]
----
======


[[python-driver-routing-table]]
=== Routing table

include::{common-content}/client-applications.adoc[tag=routing-table]


[[python-driver-routing-context]]
=== Routing context

include::{common-content}/client-applications.adoc[tag=routing-context]


[[python-driver-configuration-examples]]
=== Examples

include::{common-content}/client-applications.adoc[tag=examples-pt1]

In a clustered environment, the URI address will resolve to one of more of the core members; for standalone installations, this will simply point to that server address.
The `ROUTING_CONTEXT` option allows for customization of the routing table and is discussed in more detail in <<python-driver-routing-context>>.

include::{common-content}/client-applications.adoc[tag=examples-pt2]

.Connecting to a service
The tables below illustrate examples of how to connect to a service with routing:

.Neo4j Aura, secured with full certificate
[cols="<15s,<85a"]
|===
| Product
| Neo4j Aura

| Security
| Secured with full certificate

| Code snippet
|
[source, python]
----
GraphDatabase.driver("neo4j+s://graph.example.com:7687", auth)
----

For Python Driver versions before 4.0.0 you need this snippet instead:
[source, python]
----
GraphDatabase.driver("neo4j://graph.example.com:7687", auth,
    "encrypted"=True, "trust"=TRUST_SYSTEM_CA_SIGNED_CERTIFICATES)
----

| Comments
| This is the default (and only option) for Neo4j Aura.
|===

.Neo4j 4.x, unsecured
[cols="<15s,<85a"]
|===
| Product
| Neo4j 4.x

| Security
| Unsecured

| Code snippet
|
[source, python]
----
GraphDatabase.driver("neo4j://graph.example.com:7687", auth)
----

| Comments
| This is the default for Neo4j 4.x series
|===

.Neo4j 4.x, secured with full certificate
[cols="<15s,<85a"]
|===
| Product
| Neo4j 4.x

| Security
| Secured with full certificate

| Code snippet
|
[source, python]
----
GraphDatabase.driver("neo4j+s://graph.example.com:7687", auth)
----

For Python Driver versions before 4.0.0 you need this snippet instead:
[source, python]
----
GraphDatabase.driver("neo4j://graph.example.com:7687", auth,
    "encrypted"=True, "trust"=TRUST_SYSTEM_CA_SIGNED_CERTIFICATES)
----
|===

.Neo4j 4.x, secured with self-signed certificate
[cols="<15s,<85a"]
|===
| Product
| Neo4j 4.x

| Security
| Secured with self-signed certificate

| Code snippet
|
[source, python]
----
neo4j.driver("neo4j+ssc://graph.example.com:7687", auth)
----

For Python Driver versions before 4.0.0 you need this snippet instead:
[source, python]
----
GraphDatabase.driver("neo4j://graph.example.com:7687", auth,
    "encrypted"=True, "trust"=TRUST_ALL_CERTIFICATES)
----
|===

.Neo4j 3.x, secured with full certificate
[cols="<15s,<85a"]
|===
| Product
| Neo4j 3.x

| Security
| Secured with full certificate

| Code snippet
|
[source, python]
----
neo4j.driver("neo4j+s://graph.example.com:7687", auth)
----

For Python Driver versions before 4.0.0 you need this snippet instead:
[source, python]
----
GraphDatabase.driver("neo4j://graph.example.com:7687", auth,
    "encrypted"=True, "trust"=TRUST_SYSTEM_CA_SIGNED_CERTIFICATES)
----
|===

.Neo4j 3.x, secured with self-signed certificate
[cols="<15s,<85a"]
|===
| Product
| Neo4j 3.x

| Security
| Secured with self-signed certificate

| Code snippet
|
[source, python]
----
neo4j.driver("neo4j+ssc://graph.example.com:7687", auth)
----

For Python Driver versions before 4.0.0 you need this snippet instead:
[source, python]
----
GraphDatabase.driver("neo4j://graph.example.com:7687", auth,
    "encrypted"=True, "trust"=TRUST_ALL_CERTIFICATES)
----

| Comments
| This is the default for Neo4j 3.x series
|===

.Neo4j 3.x, unsecured
[cols="<15s,<85a"]
|===
| Product
| Neo4j 3.x

| Security
| Unsecured

| Code snippet
|
[source, python]
----
neo4j.driver("neo4j://graph.example.com:7687", auth)
----
|===

[NOTE]
To connect to a service without routing, you can replace `neo4j` with `bolt`.


[[python-driver-authentication]]
== Authentication

include::{common-content}/client-applications.adoc[tag=authentication]


[[python-driver-authentication-basic]]
=== Basic authentication

include::{common-content}/client-applications.adoc[tag=authentication-basic]

.Basic authentication
======
[source, python]
----
include::{python-examples}/test_basic_auth_example.py[tags=basic-auth-import]
----

[source, python]
----
include::{python-examples}/test_basic_auth_example.py[tags=basic-auth]
----
======

include::{common-content}/client-applications.adoc[tag=authentication-basic-note]


[[python-driver-authentication-kerberos]]
=== Kerberos authentication

include::{common-content}/client-applications.adoc[tag=authentication-kerberos]

.Kerberos authentication
======
[source, python]
----
include::{python-examples}/test_kerberos_auth_example.py[tags=kerberos-auth-import]
----

[source, python]
----
include::{python-examples}/test_kerberos_auth_example.py[tags=kerberos-auth]
----
======

include::{common-content}/client-applications.adoc[tag=authentication-kerberos-note]


[[python-driver-authentication-custom]]
=== Custom authentication

include::{common-content}/client-applications.adoc[tag=authentication-custom]

.Custom authentication
======
[source, python]
----
include::{python-examples}/test_custom_auth_example.py[tags=custom-auth-import]
----

[source, python]
----
include::{python-examples}/test_custom_auth_example.py[tags=custom-auth]
----
======


[[python-driver-configuration]]
== Configuration

include::{common-content}/client-applications.adoc[tag=configuration-ConnectionAcquisitionTimeout]
+
.Configure connection pool
======
[source, python]
----
include::{python-examples}/test_config_connection_pool_example.py[tags=config-connection-pool-import]
----

[source, python]
----
include::{python-examples}/test_config_connection_pool_example.py[tags=config-connection-pool]
----
======

include::{common-content}/client-applications.adoc[tag=configuration-ConnectionTimeout]
+
.Configure connection timeout
======
[source, python]
----
include::{python-examples}/test_config_connection_timeout_example.py[tags=config-connection-timeout-import]
----

[source, python]
----
include::{python-examples}/test_config_connection_timeout_example.py[tags=config-connection-timeout]
----
======

`CustomResolver`::

Specify a custom server address resolver used by the routing driver to resolve the initial address used to create the driver.
See <<python-driver-resolver-function>> for more details.

include::{common-content}/client-applications.adoc[tag=configuration-Encryption]
+
.Unencrypted configuration
======
[source, python]
----
include::{python-examples}/test_config_unencrypted_example.py[tags=config-unencrypted-import]
----

[source, python]
----
include::{python-examples}/test_config_unencrypted_example.py[tags=config-unencrypted]
----
======

include::{common-content}/client-applications.adoc[tag=configuration-MaxConnectionLifetime]

include::{common-content}/client-applications.adoc[tag=configuration-MaxConnectionPoolSize]

include::{common-content}/client-applications.adoc[tag=configuration-MaxTransactionRetryTime]
+
.Configure maximum retry time
======
[source, python]
----
include::{python-examples}/test_config_max_retry_time_example.py[tags=config-max-retry-time-import]
----

[source, python]
----
include::{python-examples}/test_config_max_retry_time_example.py[tags=config-max-retry-time]
----
======

include::{common-content}/client-applications.adoc[tag=configuration-TrustStrategy]
+
.Configure trusted certificates
======
[source, python]
----
include::{python-examples}/test_config_trust_example.py[tags=config-trust-import]
----

[source, python]
----
include::{python-examples}/test_config_trust_example.py[tags=config-trust]
----
======


[[python-driver-logging]]
== Logging

include::{common-content}/client-applications.adoc[tag=logging]

[source, python]
----
from logging import getLogger, StreamHandler, DEBUG
handler = StreamHandler()
handler.setLevel(DEBUG)
getLogger("neo4j").addHandler(handler)
----
