[[python-driver-cypher-workflow]]
= Cypher workflow

include::{common-content}/cypher-workflow.adoc[tag=abstract]


== Overview

include::{common-content}/cypher-workflow.adoc[tag=overview]


[[python-driver-sessions]]
== Sessions

include::{common-content}/cypher-workflow.adoc[tag=sessions]

The session classes are described in <<python-driver-session-api>>.
For more details, please see the <<python-driver-api-docs, API documentation>>.


[[python-driver-transactions]]
== Transactions

include::{common-content}/cypher-workflow.adoc[tag=transactions]

To learn more about how to use unmanaged transactions, see <<python-driver-api-docs, API documentation>> for the relevant language.


[[python-driver-queries-results]]
== Queries and results

include::{common-content}/cypher-workflow.adoc[tag=queries-results]


[[python-driver-causal-chaining]]
== Causal chaining and bookmarks

include::{common-content}/cypher-workflow.adoc[tag=causal-chaining]

.Pass bookmarks
======
[source, python]
----
include::{python-examples}/test_pass_bookmarks_example.py[tags=pass-bookmarks-import]
----

[source, python]
----
include::{python-examples}/test_pass_bookmarks_example.py[tags=pass-bookmarks]
----
======


[[python-driver-access-modes-transaction]]
== Routing transactions using access modes

include::{common-content}/cypher-workflow.adoc[tag=access-modes-transaction]

.Read-write transaction
======
[source, python]
----
include::{python-examples}/test_read_write_transaction_example.py[tags=read-write-transaction]
----
======


[[python-driver-databases]]
== Databases and execution context

include::{common-content}/cypher-workflow.adoc[tag=databases]


[role=enterprise-edition]
[[python-database-selection]]
=== Database selection

include::{common-content}/cypher-workflow.adoc[tag=database-selection]

.Database selection on session creation
======
[source, python]
----
include::{python-examples}/test_database_selection_example.py[tags=database-selection-import]
----

[source, python]
----
include::{python-examples}/test_database_selection_example.py[tags=database-selection]
----
======


[[python-driver-type-mapping]]
== Type mapping

include::{common-content}/cypher-workflow.adoc[tag=type-mapping]

.Map Neo4j types to Python types
======
[options="header", cols="<40m,<60a"]
|===
| Neo4j Type | Python 3 Type
| null | `None`
| List | `list`
| Map | `dict`
| Boolean | `bool`
| Integer | `int`
| Float | `float`
| String | `str`
| ByteArray | `bytearray`
| Date | *`neo4j.time.Date`*
| Time | *`neo4j.time.Time`†*
| LocalTime | *`neo4j.time.Time`††*
| DateTime | *`neo4j.time.DateTime`†*
| LocalDateTime | *`neo4j.time.DateTime`††*
| Duration | *`neo4j.time.Duration`**
| Point | *`neo4j.spatial.Point`*
| Node | *`neo4j.graph.Node`*
| Relationship | *`neo4j.graph.Relationship`*
| Path | *`neo4j.graph.Path`*
|===

+*+ A `datetime.timedelta` object passed as a parameter will always be implicitly converted to `neo4j.time.Duration`

† Where `tzinfo` *_is not_* `None`

†† Where `tzinfo` *_is_* `None`
======


[[python-driver-temporal-types]]
=== Temporal Types

This section lists some basic usage of the temporal types provided by the Python Driver.


[[python-driver-temporal-types-datetime]]
==== `DateTime`

Represents an instant capturing the date, the time, and the timezone identifier.

[source, python]
----
include::{python-examples}/test_temporal_types_example.py[tags=temporal-types-datetime-import]
----

[source, python]
----
include::{python-examples}/test_temporal_types_example.py[tags=temporal-types-datetime]
----


[[python-driver-temporal-types-date]]
==== `Date`

Represents an instant capturing the date, but not the time, nor the timezone.

[source, python]
----
include::{python-examples}/test_temporal_types_example.py[tags=temporal-types-date-import]
----

[source, python]
----
include::{python-examples}/test_temporal_types_example.py[tags=temporal-types-date]
----


[[python-driver-temporal-types-time]]
==== `Time`

Represents an instant capturing the time of day, and the timezone offset in seconds, but not the date.

[source, python]
----
include::{python-examples}/test_temporal_types_example.py[tags=temporal-types-time-import]
----

[source, python]
----
include::{python-examples}/test_temporal_types_example.py[tags=temporal-types-time]
----


[[python-driver-temporal-types-local-datetime]]
==== `Local DateTime`

Represents an instant capturing the date and the time, but not the timezone.

[source, python]
----
include::{python-examples}/test_temporal_types_example.py[tags=temporal-types-local-datetime-import]
----

[source, python]
----
include::{python-examples}/test_temporal_types_example.py[tags=temporal-types-local-datetime]
----


[[python-driver-temporal-types-local-time]]
==== `Local Time`

Represents an instant capturing the time of day, but not the date, nor the timezone.

[source, python]
----
include::{python-examples}/test_temporal_types_example.py[tags=temporal-types-local-time-import]
----

[source, python]
----
include::{python-examples}/test_temporal_types_example.py[tags=temporal-types-local-time]
----


[[python-driver-temporal-types-duration]]
==== `Duration`

Represents an ISO 8601 duration.
Contains both date-based values (years, months, days) and time-based values (seconds, nanoseconds).

[source, python]
----
include::{python-examples}/test_temporal_types_example.py[tags=temporal-types-duration-import]
----

[source, python]
----
include::{python-examples}/test_temporal_types_example.py[tags=temporal-types-duration]
----


[[python-driver-geospatial-types]]
=== Geospatial Types

This section lists some basic usage of the geospatial types provided by the Python Driver.


[[python-driver-geospatial-types-cartesian]]
==== `CartesianPoint`

Represents 2 or 3 dimensional point in Cartesian space.

[source, python]
----
include::{python-examples}/test_geospatial_types_example.py[tags=geospatial-types-cartesian-import]
----

[source, python]
----
include::{python-examples}/test_geospatial_types_example.py[tags=geospatial-types-cartesian]
----


[[python-driver-geospatial-types-wgs84]]
==== `WGS84Point`

Represents an instant capturing the wgs84, but not the time, nor the timezone.

[source, python]
----
include::{python-examples}/test_geospatial_types_example.py[tags=geospatial-types-wgs84-import]
----

[source, python]
----
include::{python-examples}/test_geospatial_types_example.py[tags=geospatial-types-wgs84]
----


[[python-driver-exceptions-errors]]
== Exceptions and error handling

include::{common-content}/cypher-workflow.adoc[tag=exceptions-errors]


[[python-driver-exceptions-errors]]
== Exceptions and error handling

include::{common-content}/cypher-workflow.adoc[tag=exceptions-errors]
