= Neo4j Driver Documentation


== Contents

This repository contains the AsciiDoc and other sources to build the Neo4j Driver Manual.

The examples for each of the driver languages are generated out of each driver's source code repository:

* https://github.com/neo4j/neo4j-dotnet-driver[`neo4j-dotnet-driver`]
* https://github.com/neo4j/neo4j-go-driver[`neo4j-go-driver`]
* https://github.com/neo4j/neo4j-java-driver[`neo4j-java-driver`]
* https://github.com/neo4j/neo4j-javascript-driver[`neo4j-javascript-driver`]
* https://github.com/neo4j/neo4j-python-driver[`neo4j-python-driver`]


## Usage

1. Clone the repository and checkout the branch you want to build.
2. `npm install` to install the required node.js packages
3. To build and view the HTML:`npm start`


## Notes

This repo mostly functions in the same way as any other Antora repo, such as docs-getting-started, docs-java-reference. 

The key difference with driver-documentation is that it requires an extra step to fetch the api examples that appear in the docs.

This step uses the `fetch.js` script, which reads an Antora playbook (default: `preview.yml`) to determine which branches and which driver languages are included in the source content for when the playbook is used by Antora to generate HTML.

For every branch and language combination, the api examples are cloned to the relevant path in the driver-documentation repo.

When building HTML with a `preview.yml` playbook, only the active branch is used to generate output. In this case, the examples are cloned to a _/modules/_ path relevant to the driver language, for example _dotnet-manual/modules/api/examples_.

