= Neo4j Driver Documentation

:oracle-download: http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
:openjdk-download: http://openjdk.java.net/install/
:maven-download: https://maven.apache.org/download.cgi

== Building

Java JDK version 8 (preferred) or 7 is required.
See {oracle-download}[Oracle Java SE Development Kit 8 Downloads] or {openjdk-download}[OpenJDK].

=== Build with Gradle

[TIP]
The _gradlew_ / _gradlew.bat_ script will download Gradle on first run.
No previous install is needed (if one exists, it will be ignored).

[source,bash]
----
./gradlew
----

The HTML output will be generated in _build/asciidoc/html5/_.

To additionally build PDF output, do like this:

[source,bash]
----
./gradlew -Ppdf
----

The HTML output will be generated in _build/asciidoc/html5/_, the PDF in _build/asciidoc/pdf/_.

To update the dependencies use:

[source,bash]
----
./gradlew clean
./gradlew
----

=== Build with Maven

This requires {maven-download}[Apache Maven] 3.x to be installed on the system.

[source,bash]
----
mvn
----

The HTML output will be generated in _target/html/_, the PDF in _target/pdf/_.

To update the dependencies use:

[source,bash]
----
mvn clean compile
----

If you want to skip creating the PDF output, do:

[source,bash]
----
mvn -DskipPdf
----

If you want to skip creating the HTML output, do:

[source,bash]
----
mvn -DskipHtml
----
