= Coordinate parallel transactions

When working with a Neo4j cluster, <<causal_consistency>> is enforced by default in most cases, which guarantees that a query is able to read changes made by previous queries.
The same does not happen by default for multiple xref:transactions.adoc[transactions] running in parallel though.
In that case, you can use _bookmarks_ to have one transaction wait for the result of another to be propagated across the cluster before running its own work.
This is not a requirement, and *you should only use bookmarks if you _need_ casual consistency across different transactions*, as waiting for bookmarks can have a negative performance impact.

A _bookmark_ is a token that represents some state of the database.
By passing one or multiple bookmarks along with a query, the server will make sure that the query does not get executed before the represented state(s) have been established.


[#executablequery]
== Bookmarks with `.ExecutableQuery()`

When xref:query-simple.adoc[querying the database with `.ExecutableQuery()`], the driver manages bookmarks for you.
In this case, you have the guarantee that subsequent queries can read previous changes with no further action.

[source, csharp]
----
await driver.ExecutableQuery("<QUERY 1>").ExecuteAsync();

// subsequent .ExecutableQuery() calls will be causally chained

await driver.ExecutableQuery("<QUERY 2>").ExecuteAsync();  // can read result of <QUERY 1>
await driver.ExecutableQuery("<QUERY 3>").ExecuteAsync();  // can read result of <QUERY 2>
----

To disable bookmark management and causal consistency, use `enableBookmarkManager: false` in the query configuration.

[source, csharp]
----
await driver.ExecutableQuery("<QUERY>")
    .WithConfig(new QueryConfig(enableBookmarkManager: false))
    .ExecuteAsync();
----


[#single-session]
== Bookmarks within a single session

Bookmark management happens automatically for queries run within a single session, so you can trust that queries inside one session are causally chained.

[source, csharp]
----
using var session = driver.AsyncSession(conf => conf.WithDatabase("<database-name>"));
await session.ExecuteWriteAsync(async tx => await tx.RunAsync("<QUERY 1>"));
await session.ExecuteWriteAsync(async tx => await tx.RunAsync("<QUERY 2>"));  // can read QUERY 1
await session.ExecuteWriteAsync(async tx => await tx.RunAsync("<QUERY 3>"));  // can read QUERY 1,2
----


[#multiple-sessions]
== Bookmarks across multiple sessions

If your application uses multiple sessions, you may need to ensure that one session has completed all its transactions before another session is allowed to run its queries.

In the example below, `sessionA` and `sessionB` are allowed to run concurrently, while `sessionC` waits until their results have been propagated.
This guarantees the `Person` nodes `sessionC` wants to act on actually exist.

.Coordinate multiple sessions using bookmarks
[source, csharp]
----
using Neo4j.Driver;

const string dbUri = "<database-uri>";
const string dbUser = "<username>";
const string dbPassword = "<password>";

await using var driver = GraphDatabase.Driver(dbUri, AuthTokens.Basic(dbUser, dbPassword));
await driver.VerifyConnectivityAsync();

await createSomeFriends(driver);

async Task createSomeFriends(IDriver driver) {
    Bookmarks savedBookmarks = Bookmarks.From(new List<string>());  // to collect the sessions' bookmarks

    // Create the first person and employment relationship
    using var sessionA = driver.AsyncSession(conf => conf.WithDatabase("<database-name>"));
    await sessionA.ExecuteWriteAsync(tx => createPerson(tx, "Alice"));
    await sessionA.ExecuteWriteAsync(tx => employ(tx, "Alice", "Wayne Enterprises"));
    savedBookmarks += sessionA.LastBookmarks;  // <1>

    // Create the second person and employment relationship
    using var sessionB = driver.AsyncSession(conf => conf.WithDatabase("<database-name>"));
    await sessionB.ExecuteWriteAsync(tx => createPerson(tx, "Bob"));
    await sessionB.ExecuteWriteAsync(tx => employ(tx, "Bob", "LexCorp"));
    savedBookmarks += sessionB.LastBookmarks;  // <1>

    // Create a friendship between the two people created above
    using var sessionC = driver.AsyncSession(conf => conf
        .WithDatabase("<database-name>")
        .WithBookmarks(savedBookmarks)  // <2>
    );
    await sessionC.ExecuteWriteAsync(tx => createFriendship(tx, "Alice", "Bob"));
    await sessionC.ExecuteWriteAsync(tx => printFriendships(tx));
}

// Create a person node
async Task createPerson(IAsyncQueryRunner tx, string name) {
    await tx.RunAsync("MERGE (:Person {name: $name})", new { name = name });
}

// Create an employment relationship to a pre-existing company node
// This relies on the person first having been created.
async Task employ(IAsyncQueryRunner tx, string personName, string companyName) {
    await tx.RunAsync(@"
        MATCH (person:Person {name: $personName})
        MATCH (company:Company {name: $companyName})
        CREATE (person)-[:WORKS_FOR]->(company)
        ", new { personName = personName, companyName = companyName }
    );
}

// Create a friendship between two people
async Task createFriendship(IAsyncQueryRunner tx, string nameA, string nameB) {
    await tx.RunAsync(@"
        MATCH (a:Person {name: $nameA})
        MATCH (b:Person {name: $nameB})
        MERGE (a)-[:KNOWS]->(b)
        ", new { nameA = nameA, nameB = nameB }
    );
}

// Retrieve and display all friendships
async Task printFriendships(IAsyncQueryRunner tx) {
    var result = await tx.RunAsync("MATCH (a)-[:KNOWS]->(b) RETURN a.name, b.name");
    while (await result.FetchAsync()) {
        var record = result.Current;
        Console.WriteLine(record.Get<string>("a.name") + " knows " + record.Get<string>("b.name"));
    }
}
----

<1> Collect and combine bookmarks from different sessions using `AsyncSession.LastBookmarks`, storing them in a link:https://neo4j.com/docs/api/dotnet-driver/{dotnet-driver-version}/api/Neo4j.Driver.Bookmarks.html[`Bookmarks`] object.
<2> Use them to initialize another session with the `.WithBookmarks()` config method.

image:{common-image}/driver-passing-bookmarks.svg[]

[TIP]
The use of bookmarks can negatively impact performance, since all queries are forced to wait for the latest changes to be propagated across the cluster.
For simple use-cases, try to group queries within a single transaction, or within a single session.

////
Note: not possible on .NET

== Mix `.ExecutableQuery()` and sessions

To ensure causal consistency among transactions executed partly with `.ExecutableQuery()` and partly with sessions, you can retrieve the default bookmark manager for `ExecutableQuery` instances through `driver.executableQueryBookmarkManager()` and pass it to new sessions through the `.WithBookmarkManager()` config method.
This will ensure that all work is executed under the same bookmark manager and thus causally consistent.

[source, java]
----
// import org.neo4j.driver.Driver;
// import org.neo4j.driver.SessionConfig;

driver.executableQuery("<QUERY 1>").execute();

try (var session = driver.session(SessionConfig.builder()
    .withBookmarkManager(driver.executableQueryBookmarkManager())
    .build())) {

    // every query inside this session will be causally chained
    // (i.e., can read what was written by <QUERY 1>)
    session.executeWriteWithoutResult(tx -> tx.run("<QUERY 2>"));
}

// subsequent executableQuery calls will also be causally chained
// (i.e., can read what was written by <QUERY 2>)
driver.executableQuery("<QUERY 3>").execute();
----
////


ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::{common-partial}/glossary.adoc[]
include::../partials/glossary.adoc[]
endif::[]
