[[dotnet-driver-get-started]]
= Get started
:description: This section gives an overview of the official Neo4j .NET Driver and how to connect to a Neo4j database with a "Hello World" example. 


[[dotnet-driver-get-started-about]]
== About the official .NET driver

include::{common-partial}/get-started.adoc[tag=about]

In the general case, only the xref:client-applications.adoc#dotnet-driver-connection-uris[connection URI] needs to be modified when changes are made to the topology.

include::{common-partial}/get-started.adoc[tag=about-note]

[[dotnet-driver-get-started-installation]]
== Driver versions and installation

include::{common-partial}/get-started.adoc[tag=versions]

.Acquire the driver
======
The .NET driver is distributed via the NuGet Gallery.
To find the latest version of the driver, visit https://www.nuget.org/packages/Neo4j.Driver/.

*Dependencies*

* .NETStandard (^2.0)
* System.Net.NameResolution (^4.3.0)
* System.Net.Security (^4.3.2)
* System.Net.Sockets (^4.3.0)
* System.Runtime.InteropServices.RuntimeInformation (^4.3.0)
* System.Runtime.Serialization.Primitives (^4.3.0)
* System.Threading.Thread (^4.3.0)
* System.ValueTuple (^4.5.0)

The .NET Reactive API is under package `Neo4j.Driver.Reactive`.
It is built upon https://github.com/dotnet/reactive[`System.Reactive`].
There is no extra dependency required use .NET reactive API.

.Installation via Install-package
========
To install the latest version of the driver using NuGet in Visual Studio:

[source, csharp, subs="attributes, specialcharacters", indent=0]
----
PM> Install-Package Neo4j.Driver
----

It is also an option to install a certain version of the driver.

[source, csharp, subs="attributes, specialcharacters", indent=0]
----
PM> Install-Package Neo4j.Driver -Version $DOTNET_DRIVER_VERSION
----

The .Net driver uses asynchronous methods by default.
If you want to use blocking calls, the `Neo4j.Driver.Simple` NuGet package contains a set of extensions.
This can be found at https://www.nuget.org/packages/Neo4j.Driver.Simple/.
The initial examples make use of these extensions.

In the following example we are installing driver version {dotnet-driver-version}.

[source, csharp, subs="attributes, specialcharacters", indent=0]
----
PM> Install-Package Neo4j.Driver -Version {dotnet-driver-version}
----
========

The release notes for this driver are available https://github.com/neo4j/neo4j-dotnet-driver/releases[here].

======


[[dotnet-driver-get-started-hello-world-example]]
== A "Hello World" example

The example below shows the minimal configuration necessary to interact with *Neo4j* through the .NET driver:

.Hello World
======
[source, csharp, indent=0]
----
include::{dotnet-examples}/Examples.cs[tags=hello-world]
----

// [source, csharp, indent=0]
// ----
// include::{dotnet-examples}/Examples.cs[tags=hello-world-import]
// ----
======


[[dotnet-driver-api-docs]]
== Driver API docs

For a comprehensive listing of all driver functionality, please see the {api-docs-base-uri}/dotnet-driver/current/[.NET API reference documentation].
