= Installation

To start creating a Neo4j .NET application, you first need to install the .NET driver and get a Neo4j database instance to connect to.

[IMPORTANT]
The driver supports .NET 8.0 and 9.0.


[#install-driver]
== Install the driver

If you already have a .NET project, you can add the package link:https://www.nuget.org/packages/Neo4j.Driver[Neo4j.Driver] as a dependency.
For example, with the .NET CLI,

[source, bash]
----
dotnet add package Neo4j.Driver
----

.How to create a .NET project for a Neo4j .NET application?
[%collapsible]
====
To create a new project and add the Neo4j driver to it, assuming the .NET CLI is installed:

[source, bash]
----
mkdir dotnet-neo4j && cd dotnet-neo4j
dotnet new console
dotnet install package Neo4j.Driver
----

To compile and run, use `dotnet run`.
====

The latest version of the driver is guaranteed to work with all <<LTS>> releases of the Neo4j server, as well as with the current and next major releases.
The latest `6.x` driver supports connection to any Neo4j instances version 4.4, 5.x, and 2025.x.
For a detailed list of changes across versions, see the link:https://github.com/neo4j/neo4j-dotnet-driver/wiki/5.X-Change-Log[driver's changelog].


include::{common-partial}/install.adoc[tag=get-an-instance]


ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::{common-partial}/glossary.adoc[]
include::../partials/glossary.adoc[]
endif::[]
