= Installation

To start creating a Neo4j .NET application, you first need to install the .NET driver and get a Neo4j database instance to connect to.

[NOTE]
The driver supports the .NET Standard 2.0.
For supported versions of the .NET Framework, see the link:https://dotnet.microsoft.com/en-us/platform/dotnet-standard[.NET Standard page].


[#install-driver]
== Install the driver

If you already have a .NET project, you can add the package link:https://www.nuget.org/packages/Neo4j.Driver[Neo4j.Driver] as a dependency.
For example, with the .NET CLI,

[source, bash]
----
dotnet add package Neo4j.Driver
----

.How to create a .NET project for a Neo4j .NET application?
[%collapsible]
====
To create a new project and add the Neo4j driver to it, assuming the .NET CLI is installed:

[source, bash]
----
mkdir dotnet-neo4j && cd dotnet-neo4j
dotnet new console
dotnet install package Neo4j.Driver
----

To compile and run, use `dotnet run`.
====

Always use the latest version of the driver, as it will always work both with the previous Neo4j <<LTS>> release and with the current and next major releases.
The latest `5.x` driver supports connection to any Neo4j 5 and 4.4 instance, and will also be compatible with the next major Neo4j version.
For a detailed list of changes across versions, see the link:https://github.com/neo4j/neo4j-dotnet-driver/wiki/5.X-Change-Log[driver's changelog].

[TIP]
====
Beyond `Neo4j.Driver`, two other packages are available:

- link:https://www.nuget.org/packages/Neo4j.Driver.Simple[`Neo4j.Driver.Simple`], exposing synchronous APIs,
- link:https://www.nuget.org/packages/Neo4j.Driver.Reactive[`Neo4j.Driver.Reactive`], exposing reactive APIs.
====

include::{common-partial}/install.adoc[tag=get-an-instance]


ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::{common-partial}/glossary.adoc[]
include::../partials/glossary.adoc[]
endif::[]
