= Installation

To start creating a Neo4j .NET application, you first need to install the .NET driver and get a Neo4j database instance to connect to.

.Server compatibility
[IMPORTANT]
The latest driver in the `5.28.x` series supports connection to Neo4j instances version 4.4.x, 5.x, 2025.x, and 2026.x.
Some of the features introduced in the server in versions 2025.01 and later are not available via the driver version `5.28.x`; use link:https://neo4j.com/docs/dotnet-manual/current/[the latest version] instead.

[NOTE]
The driver supports the .NET Standard 2.0.
For supported versions of the .NET Framework, see the link:https://dotnet.microsoft.com/en-us/platform/dotnet-standard[.NET Standard page].


[#install-driver]
== Install the driver

If you already have a .NET project, you can add the package link:https://www.nuget.org/packages/Neo4j.Driver[Neo4j.Driver] as a dependency.

.Add the driver to a project with the .NET CLI
[source, bash, subs="attributes+"]
----
dotnet add package Neo4j.Driver --version {dotnet-driver-version-minor}
----

.How to create a .NET project for a Neo4j .NET application?
[%collapsible]
====
To create a new project and add the Neo4j driver to it, assuming the .NET CLI is installed:

[source, bash, subs="attributes+"]
----
mkdir dotnet-neo4j && cd dotnet-neo4j
dotnet new console
dotnet install package Neo4j.Driver --version {dotnet-driver-version-minor}
----

To compile and run, use `dotnet run`.
====

include::{common-partial}/install.adoc[tag=get-an-instance]


ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::{common-partial}/glossary.adoc[]
include::../partials/glossary.adoc[]
endif::[]
