= Further query mechanisms

[#implicit-transactions]
== Implicit (or auto-commit) transactions

This is the most basic and limited form with which to run a Cypher query.
The driver will not automatically retry implicit transactions, as it does instead for queries run with xref:query-simple.adoc[`.ExecutableQuery()`] and with xref:transactions#managed-transactions[managed transactions].
Implicit transactions should only be used when the other driver query interfaces do not fit the purpose, or for quick prototyping.

You run an implicit transaction with the method link:https://neo4j.com/docs/api/dotnet-driver/{dotnet-driver-version}/api/Neo4j.Driver.IAsyncSession.RunAsync.html[`ISessionAsync.RunAsync()]`.
It returns a link:https://neo4j.com/docs/api/dotnet-driver/{dotnet-driver-version}/api/Neo4j.Driver.IResultCursor.html[`IResultCursor`] object that needs to be xref:transactions#process-result[processed accordingly].

[source, csharp]
----
using var session = driver.AsyncSession(conf => conf.WithDatabase("<database-name>"));
await session.RunAsync("CREATE (a:Person {name: $name})", new { name = "Licia" });
----

An implicit transaction gets committed _at the latest_ when the session is destroyed, or before another transaction is executed within the same session.
Other than that, there is no clear guarantee on when exactly an implicit transaction will be committed during the lifetime of a session.
To ensure an implicit transaction is committed, you can call the `.ConsumeAsync()` method on its result.

Since the driver cannot figure out whether the query in a `ISessionAsync.RunAsync()` call requires a read or write session with the database, it defaults to write. If your implicit transaction contains read queries only, there is a performance gain in xref:transactions#request-routing[making the driver aware] through the config method `.WithDefaultAccessMode(AccessMode.Read)` when creating the session.

[TIP]
*Implicit transactions are the only ones that can be used for link:{neo4j-docs-base-uri}/cypher-manual/current/subqueries/subqueries-in-transactions[`CALL { ... } IN TRANSACTIONS`] queries*.


[#import-csv]
=== Import CSV files

The most common use case for using `IAsyncSession.RunAsync()` is for importing large CSV files into the database with the link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/load-csv[`LOAD CSV`] Cypher clause, and preventing timeout errors due to the size of the transaction.

.Import CSV data into a Neo4j database
[source, csharp]
----
using var session = driver.AsyncSession(conf => conf.WithDatabase("<database-name>"));
var result = await session.RunAsync(@"
    LOAD CSV FROM 'https://data.neo4j.com/bands/artists.csv' AS line
    CALL {
        WITH line
        MERGE (:Artist {name: line[1], age: toInteger(line[2])})
    } IN TRANSACTIONS OF 2 ROWS
    ");
var summary = await result.ConsumeAsync();
Console.WriteLine(summary.Counters);
----

[NOTE]
While `LOAD CSV` can be a convenience, there is nothing _wrong_ in deferring the parsing of the CSV file to your Java application and avoiding `LOAD CSV`.
In fact, moving the parsing logic to the application can give you more control over the importing process.
For efficient bulk data insertion, see xref:performance.adoc#batch-data-creation[Performance -> Batch data creation].

For more information, see link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/load-csv/[Cypher -> Clauses -> LOAD CSV].


[#tx-config]
=== Transaction configuration

You can exert further control on implicit transactions by providing a link:https://neo4j.com/docs/api/dotnet-driver/{dotnet-driver-version}/api/Neo4j.Driver.TransactionConfigBuilder.html[`TransactionConfigBuilder`] object as optional last parameter to `IAsyncSession.RunAsync()` calls.
The configuration callbacks allow to specify a query timeout and to attach metadata to the transaction.
For more information, see xref:transactions.adoc#tx-config[Transactions -> Transaction configuration].

[source, csharp]
----
using var session = driver.AsyncSession(conf => conf.WithDatabase("<database-name>"));
await session.RunAsync(
    "MATCH (p:Person) RETURN p",
    conf => conf
        .WithTimeout(new TimeSpan(5))
        .WithMetadata(new Dictionary<string, object>{ { "appName", "peopleTracker" } })
);
----


[#dynamic-advanced]
== Dynamic values in property keys, relationship types, and labels

In general, you should not concatenate parameters directly into a query, but rather use xref:query-simple#query-parameters[query parameters].
There can however be circumstances where your query structure prevents the usage of parameters in all its parts.
In fact, although parameters can be used for literals and expressions as well as node and relationship ids, they cannot be used for the following constructs:

- property keys, so `MATCH (n) WHERE n.$param = 'something'` is invalid;
- relationship types, so `MATCH (n)-[:$param]->(m)` is invalid;
- labels, so `MATCH (n:$param)` is invalid.

For those queries, you are forced to use string concatenation.
To protect against link:https://neo4j.com/developer/kb/protecting-against-cypher-injection/[Cypher injections], you should enclose the dynamic values in backticks and escape them yourself.
Notice that Cypher processes Unicode, so take care of the Unicode literal `\u0060` as well.

.Manually escaping dynamic labels before concatenation.
[source, csharp]
----
var label = "Person\\u0060n";
// convert \u0060 to literal backtick and then escape backticks
var escapedLabel = label.Replace("\\u0060", "`").Replace("`", "``");

var result = await driver.ExecutableQuery("MATCH (p:`" + escapedLabel + "` {name: $name}) RETURN p.name")
    .WithParameters( new { name = "Alice" })
    .WithConfig(new QueryConfig(database: "<database-name>"))
    .ExecuteAsync();
----

Another workaround, which avoids string concatenation, is using <<APOC>> procedures, such as link:{neo4j-docs-base-uri}/apoc/5/overview/apoc.merge/apoc.merge.node/[`apoc.merge.node`], which supports dynamic labels and property keys.

.Using `apoc.merge.node` to create a node with dynamic labels/property keys.
[source, csharp]
----
var propertyKey = "name";
var label = "Person";

var labels = new string[] { label };
var properties = new Dictionary<string, string>() {
    {propertyKey, "Alice"}
};

var result = await driver
    .ExecutableQuery("CALL apoc.merge.node($labels, $properties)")
    .WithParameters(new { labels = labels, properties = properties})
    .WithConfig(new QueryConfig(database: "<database-name>"))
    .ExecuteAsync();
----

[NOTE]
If you are running Neo4j in Docker, APOC needs to be enabled when starting the container.
See link:https://neo4j.com/docs/apoc/5/installation/#docker[APOC -> Installation -> Docker].


ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::{common-partial}/glossary.adoc[]
include::../partials/glossary.adoc[]
endif::[]
