:driver-changelog-url: https://github.com/neo4j/neo4j-dotnet-driver/wiki/5.X-Change-Log

= Upgrade from older versions

include::{common-partial}/upgrade.adoc[tag=intro]


[[new-features]]
== New features

[cols="1a,1a"]
|===

|
.Support for .NET 8
[%collapsible]
====
The driver supports the .NET Standard 2.0. For supported versions of the .NET Framework, see the link:https://dotnet.microsoft.com/en-us/platform/dotnet-standard[.NET Standard page].
====
|
.Run transactions with less knowledge of driver's internals
[%collapsible]
====
The new method `Driver.ExecutableQuery()` is a wrapper for `Session.ExecuteRead/Write()`, but it abstracts away the result processing part and returns a list of records to the caller directly.

For more information, see xref:query-simple.adoc[`ExecutableQuery`].
====

|
.Record to object mapping
[%collapsible]
====
Allows records to be mapped to objects simply and without endless boilerplate.

For more information, see xref:object-graph-mapping.adoc[Record to Object Mapping].
====
|
.Re-authentication
[%collapsible]
====
Allows for handling xref:connect-advanced.adoc#rotating-tokens[expiring authentication (rotating tokens)] as well as xref:transactions.adoc#impersonation[session scoped authentication].
====

|
.Mutual TLS (mTLS) as second authentication factor (2FA)
[%collapsible]
====
Allows for configuring client side TLS certificates to authenticate against the server.

For more information, see xref:connect-advanced.adoc#mtls[Mutual TLS].
====
|
.`BookmarkManager` support
[%collapsible]
====
Bookmark managers make it easier to achieve causal chaining of sessions.

See link:https://neo4j.com/docs/api/dotnet-driver/{dotnet-driver-version}/api/Neo4j.Driver.IBookmarkManager.html[interface `IBookmarkManager`].
====

|
.Notification filtering API
[%collapsible]
====
Filtering allows to receive only a subset of notifications from the server, and to improve performance server-side.

For more information, see xref:result-summary.adoc#notification-filtering[NotificationConfig].
====
|
.GQL statuses and errors
[%collapsible]
====
The property link:https://neo4j.com/docs/api/dotnet-driver/{dotnet-driver-version}/api/Neo4j.Driver.IResultSummary.GqlStatusObjects.html[`IResultSummary.GqlStatusObjects`] contains a sequence of link:https://neo4j.com/docs/api/dotnet-driver/{dotnet-driver-version}/api/Neo4j.Driver.IGqlStatusObject.html[`IGqlStatusObject`], holding information about the execution of the query.
This API is planned to supersede the current notifications API.

For more information, see xref:result-summary.adoc#notifications[Explore the query execution summary -> Notifications].

xref:data-types.adoc#exceptions[Exception objects] are also GQL-compliant.
====

|
.Telemetry
[%collapsible]
====
The driver sends anonymous API usage statistics to the server.
Use the driver configuration method `.WithTelemetryDisabled()` to opt out.

See link:https://github.com/neo4j/neo4j-dotnet-driver/pull/735[API Telemetry].
====
|

|===


[[breaking-changes]]
== Breaking changes and deprecations

Deprecated features are likely to be removed in version 6.

[cols="1,5a,1"]
|===
|Version |Message |Status

|5.0
|link:https://neo4j.com/docs/api/dotnet-driver/{dotnet-driver-version}/api/Neo4j.Driver.IServerInfo.html[`IServerInfo`] -- Method `.Version()` has been removed.
Use `.Agent()`, `.ProtocolVersion()`, or call the link:https://neo4j.com/docs/operations-manual/5/reference/procedures/#procedure_dbms_components[`dbms.components`] Cypher procedure instead.
|label:removed[]

|5.0
|link:[`ISession`], link:[`IRxSession`], link:https://neo4j.com/docs/api/dotnet-driver/{dotnet-driver-version}/api/Neo4j.Driver.IAsyncSession.html[`IAsyncSession`] -- Methods `.ReadTransaction()` and `.WriteTransaction()` are deprecated in favor of `.ExecuteRead()` and `.ExecuteWrite()`.
The same holds for the async coounterparts `.ReadTransactionAsync()` and `.WriteTransactionAsync()`, replaced by `.ExecuteReadAsync()` and `.ExecuteWriteAsync()`.

The new methods behave similarly, but the argument types are different and the new methods do not support the `.commit()`, `.rollback()`, `.close()`, and `.closed()` methods.
|label:deprecated[]

|5.0
|link:[`ISession`], link:https://neo4j.com/docs/api/dotnet-driver/{dotnet-driver-version}/api/Neo4j.Driver.IAsyncSession.html[`IAsyncSession`] -- Method `.LastBookmark()` is deprecated in favor of `.LastBookmarks()`.
|label:deprecated[]

|5.0
|Type `Bookmark` is deprecated in favor of link:[`Bookmarks`].
|label:deprecated[]

|5.0
|link:https://neo4j.com/docs/api/dotnet-driver/{dotnet-driver-version}/api/Neo4j.Driver.SessionConfigBuilder.html[`SessionConfigBuilder`] -- Method link:https://neo4j.com/docs/api/dotnet-driver/{dotnet-driver-version}/api/Neo4j.Driver.SessionConfigBuilder.WithBookmarks.html#Neo4j_Driver_SessionConfigBuilder_WithBookmarks_Neo4j_Driver_Bookmarks___[`.WithBookmarks()`] takes `Bookmarks[]` as argument rather than `Bookmark[]`.
|label:deprecated[]

// a backslash is needed in first url to avoid it becoming a <em> with the subsequent link __
|5.0
|`ZonedDateTime` -- Two constructors not including `DateTimeKind` are deprecated (link:https://neo4j.com/docs/api/dotnet-driver/{dotnet-driver-version}/api/Neo4j.Driver.ZonedDateTime.-ctor.html#Neo4j_Driver_ZonedDateTime\__ctor_System_Int32_System_Int32_System_Int32_System_Int32_System_Int32_System_Int32_Neo4j_Driver_Zone_[this] and link:https://neo4j.com/docs/api/dotnet-driver/{dotnet-driver-version}/api/Neo4j.Driver.ZonedDateTime.-ctor.html#Neo4j_Driver_ZonedDateTime__ctor_System_Int32_System_Int32_System_Int32_System_Int32_System_Int32_System_Int32_System_Int32_Neo4j_Driver_Zone_[this]).
|label:deprecated[]

|5.0
|link:https://neo4j.com/docs/api/dotnet-driver/{dotnet-driver-version}/api/Neo4j.Driver.IEntity.html[`IEntity`], link:https://neo4j.com/docs/api/dotnet-driver/{dotnet-driver-version}/api/Neo4j.Driver.INode.html[`INode`], link:https://neo4j.com/docs/api/dotnet-driver/{dotnet-driver-version}/api/Neo4j.Driver.IRelationship.html[`IRelationship`] -- Method `.Id()` (`long`) is deprecated in favor of `.ElementId()` (`string`).
|label:deprecated[]

|5.0
|link:https://neo4j.com/docs/api/dotnet-driver/{dotnet-driver-version}/api/Neo4j.Driver.IRelationship.html[`IRelationship`] -- Methods `.StartNodeId()` and `.EndNodeId()` are deprecated in favor of `.StartNodeElementId()` and `.EndNodeElementId()`. Old identifiers were `long`, wereas new ElementIds are `string`.
|label:deprecated[]

|5.7
|link:https://neo4j.com/docs/api/dotnet-driver/{dotnet-driver-version}/api/Neo4j.Driver.INotification.html[`INotification`] -- Property `Severity` is deprecated in favor of `SeverityLevel` or `RawSeverityLevel`.
|label:deprecated[]

|===
