= Run concurrent transactions

The driver is compatible with Python's `asyncio`, which allows implementing concurrent workflows.
To interact with the database in an asynchronous way, create an `AsyncDriver` with `AsyncGraphDatabase.driver()`.
The workflow is very similar to the synchronous version, except that you must use `await` on all async calls, and define as `async` all functions that should be awaited.
If you need <<causal_consistency>> across different transactions, use xref:bookmarks.adoc[bookmarks].

.An async driver example with `execute_query`
[source, python]
----
import asyncio
from neo4j import AsyncGraphDatabase


async def main():
    URI = "<URI for Neo4j database>"
    AUTH = ("<Username>", "<Password>")

    async with AsyncGraphDatabase.driver(URI, auth=AUTH) as driver:
        records, summary, keys = await driver.execute_query(
            "MATCH (a:Person) RETURN a.name AS name",
            database_="neo4j")
        names = [record["name"] for record in records]
        print(names)


if __name__ == "__main__":
    asyncio.run(main())
----

.An async driver example with transaction functions
[source, python]
----
import asyncio
from neo4j import AsyncGraphDatabase


async def main():
    URI = "<URI for Neo4j database>"
    AUTH = ("<Username>", "<Password>")

    async with AsyncGraphDatabase.driver(URI, auth=AUTH) as driver:
        async with driver.session(database="neo4j") as session:
            records = await session.read_transaction(get_people)
            print(records)


async def get_people(tx):
    result = await tx.run("MATCH (a:Person) RETURN a.name AS name")
    records = await result.values()
    return records


if __name__ == "__main__":
    asyncio.run(main())
----

[TIP]
Async implements a concurrency model, but it is not the only possible one.
Multithreading is also possible, although `asyncio` is often easier to implement in an application.

[WARNING]
There is a known issue with Python 3.8 and the async driver where it gradually slows down.
It is generally recommended to use the latest supported version of Python for the best performance, stability, and security.


ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::{common-partial}/glossary.adoc[]
include::../partials/glossary.adoc[]
endif::[]
