= Advanced connection information

== Connection protocols and security

Communication between the driver and the server is mediated by <<Bolt>>. The scheme of the server URI determines whether the connection is encrypted and, if so, what type of certificates are accepted.

[options="header", cols="20,40,40"]
|===
|URL scheme
|Encryption
|Comment

|neo4j
|{cross-mark}
|Default for local setups

|neo4j+s
|{check-mark} (only CA-signed certificates)
|Default for Aura

|neo4j+ssc
|{check-mark} (CA- and self-signed certificates)
|
|===

[TIP]
The driver receives a _routing table_ from the server upon successful connection, regardless of whether the instance is a proper cluster environment or a single-machine environment. The driver's routing behavior works in tandem with Neo4j's link:{neo4j-docs-base-uri}/operations-manual/current/clustering/[causal clustering] by directing read and write transactions to appropriate cluster members. If you want to target a _specific_ machine, use a link:{neo4j-docs-base-uri}/api/python-driver/current/api.html#bolt-driver-ref[`BoltDriver`] object and `bolt`, `bolt+s`, or `bolt+ssc` URI schemes instead.

The connection scheme to use is not your choice, but is rather determined by the server requirements.
You must know the right server scheme upfront, as no metadata is exposed prior to connection.
If you are unsure, ask the database administrator.

== Authentication methods

=== Basic authentication (default)

The basic authentication scheme relies on traditional username and password. These can either be the credentials for your local installation, or the ones provided with an Aura instance.

[source,python]
----
from neo4j import GraphDatabase

driver = GraphDatabase.driver(uri, auth=(user, password))
----

[INFO]
The basic authentication scheme can also be used to authenticate against an LDAP server (Enterprise Edition only).

=== Kerberos authentication
The Kerberos authentication scheme requires a base64-encoded ticket.
It can only be used if the server has the link:{neo4j-docs-base-uri}/kerberos-add-on/current/deployment/[Kerberos Add-on installed].

[source,python]
----
from neo4j import GraphDatabase, kerberos_auth

driver = GraphDatabase.driver(uri, auth=kerberos_auth(ticket))
----

=== Bearer authentication
The bearer authentication scheme requires a base64-encoded token provided by an Identity Provider through Neo4j's link:{neo4j-docs-base-uri}/operations-manual/current/authentication-authorization/sso-integration[Single Sign-On feature].

[source,python]
----
from neo4j import GraphDatabase, bearer_auth

driver = GraphDatabase.driver(uri, auth=bearer_auth(token))
----

[NOTE]
The bearer authentication scheme requires link:{neo4j-docs-base-uri}/operations-manual/current/authentication-authorization/sso-integration[configuring Single Sign-On on the server]. Once configured, clients can discover Neo4j's configuration through the link:{neo4j-docs-base-uri}/http-api/current/discovery/[Discovery API].

=== Custom authentication

Use the function link:{neo4j-docs-base-uri}/api/python-driver/current/api.html#neo4j.custom_auth[`custom_auth`] to log into a server having a custom authentication scheme.

[NOTE]
If authentication is disabled on the server, the `auth` parameter can be omitted entirely.


== Custom address resolver

You can specify a custom _resolver_ function to resolve host and port values ahead of DNS resolution. This function is called with a 2-tuple of `(host, port)` and should return an iterable of 2-tuples `(host, port)`.

In the following example, the connection to `example.com` on port `9999` is resolved to `localhost` on port `7687`:

[source,python]
----
from neo4j import GraphDatabase


def custom_resolver(socket_address):
    if socket_address == ("example.com", 9999):
        yield "::1", 7687
        yield "127.0.0.1", 7687
    else:
        from socket import gaierror
        raise gaierror("Unexpected socket address %r" % socket_address)


driver = GraphDatabase.driver("neo4j://example.com:9999",
                              auth=(user, password),
                              resolver=custom_resolver)
----


== Further connection parameters

You can find all `Driver` configuration parameters in the link:{neo4j-docs-base-uri}/api/python-driver/current/api.html#driver-configuration[API documentation].


[discrete.glossary]
== Glossary

include::{common-partial}/glossary.adoc[]
