= Connection

Once you have xref:install.adoc#install-driver[installed the driver] and have xref:install.adoc#get-an-instance[a running Neo4j instance], you are ready to connect your application to the database.

== Connect to the database

You connect to a database by creating a <<Driver>> object and providing a URL and an authentication token.

[source, python]
----
from neo4j import GraphDatabase

# URI examples: "neo4j://localhost", "neo4j+s://xxx.databases.neo4j.io"
URI = "<URI to Neo4j database>"
AUTH = ("<Username>", "<Password>")

with GraphDatabase.driver(URI, auth=AUTH) as driver: # <1>
    driver.verify_connectivity() # <2>
----


<1> Creating a `Driver` instance only provides information on _how_ to access the database, but does not actually _establish_ a connection.
Connection is instead deferred to when the first query is executed.
<2> To verify immediately that the driver can connect to the database (valid credentials, compatible versions, etc), use the `.VerifyConnectivity(ctx)` method after initializing the driver.

Both the creation of a `Driver` object and the connection verification can raise a number of different link:{neo4j-docs-base-uri}/api/python-driver/current/api.html#errors[exceptions].
Since error handling can get quite verbose, and a connection error is a blocker for any subsequent task, the most common choice is to let the program crash should an exception occur during connection.

`Driver` objects are _immutable_, _thread-safe_, and fairly _expensive to create_.
Share them across threads (but not across processes) and use xref:transactions#impersonation[impersonation] to query the database with a different user.
If you want to alter a `Driver` configuration, you will need to create a new object.


== Connect to an Aura instance

When you create an <<Aura>> instance, you may download a text file containing the connection information to the database.
The file has a name of the form `Neo4j-a0a2fa1d-Created-2023-11-06.txt`.

To connect to such an instance, you may either use the URI, username, and password explicitly in your application, or load the content of the connection file in the environment with `dotenv.load_dotenv()` and populate your local variables via `os.getenv()`.
This approach requires the package link:https://pypi.org/project/python-dotenv/[`python-dotenv`].

[source, python, role=test-skip]
----
import dotenv
import os
from neo4j import GraphDatabase

dotenv.load_dotenv("Neo4j-a0a2fa1d-Created-2023-11-06.txt")

URI = os.getenv("NEO4J_URI")
AUTH = (os.getenv("NEO4J_USERNAME"), os.getenv("NEO4J_PASSWORD"))

with GraphDatabase.driver(URI, auth=AUTH) as driver:
    driver.verify_connectivity()
----


== Close connections

Always close `Driver` objects to free up all allocated resources, even upon unsuccessful connection or runtime errors.
Either instantiate the `Driver` object using the `with` statement, or call the `Driver.close()` method explicitly.


== Further connection parameters

For more `Driver` configuration parameters and further connection settings, see xref:connect-advanced.adoc[Advanced connection information].

ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::{common-partial}/glossary.adoc[]
include::../partials/glossary.adoc[]
endif::[]
