[[python-driver-get-started]]
= Get started
:description: This section gives an overview of the official Neo4j Python Driver and how to connect to a Neo4j database with a "Hello World" example. 


[[python-driver-get-started-about]]
== About the official Python driver

include::{common-partial}/get-started.adoc[tag=about]

In the general case, only the xref:client-applications.adoc#python-driver-connection-uris[connection URI] needs to be modified when changes are made to the topology.

include::{common-partial}/get-started.adoc[tag=about-note]


[[python-driver-get-started-installation]]
== Driver versions and installation

include::{common-partial}/get-started.adoc[tag=versions]

.Acquire the driver
======
To find the latest stable version of the Python Driver, visit https://pypi.org/project/neo4j/

To find a list of all available releases, visit https://pypi.org/simple/neo4j/

To install the latest stable version of the Python Driver:

[source, shell, subs="attributes, specialcharacters", indent=0]
----
pip install neo4j
----

It is also an option to install a certain version of the driver.

.Installation with Python
========
The following is the syntax for installing a certain version of the Python Driver:
[source, shell, subs="attributes, specialcharacters", indent=0]
----
pip install neo4j==$PYTHON_DRIVER_VERSION
----

In the following example we are installing Python Driver version {python-driver-version}.
[source, shell, subs="attributes, specialcharacters", indent=0]
----
pip install neo4j=={python-driver-version}
----
========

.Installation with Python, get Python Driver prerelease
========
In the following example we get the latest prerelease version:
[source, shell, subs="attributes, specialcharacters", indent=0]
----
pip install neo4 --pre
----
========

The release notes for the Python Driver are available https://github.com/neo4j/neo4j-python-driver/wiki[here]

======


[[python-driver-get-started-hello-world-example]]
== A "Hello World" example

The example below shows the minimal configuration necessary to interact with *Neo4j* through the Python driver:

.Hello World
======
[source, python, indent=0]
----
include::{python-examples}/test_driver_introduction_example.py[tags=driver-introduction-example-import]
----

[source, python, indent=0]
----
include::{python-examples}/test_driver_introduction_example.py[tags=driver-introduction-example]
----
======


[[python-driver-api-docs]]
== Driver API docs

For a comprehensive listing of all driver functionality, please see the {api-docs-base-uri}/python-driver/{driver-version}/[Python API reference documentation].
