= Installation

To start creating a Neo4j Python application, you first need to install the Python Driver and get a Neo4j database instance to connect to.

.Server compatibility
[IMPORTANT]
The latest driver in the `5.28.x` series supports connection to Neo4j instances version 4.4.x, 5.x, 2025.x, and 2026.x.
Some of the features introduced in the server in versions 2025.01 and later are not available via the driver version `5.28.x`; use link:https://neo4j.com/docs/python-manual/current/[the latest version] instead.

[#install-driver]
== Install the driver

Use `pip` to install the link:https://pypi.org/project/neo4j/[Neo4j Python Driver] (requires Python >= 3.7):

[source,bash]
----
pip install neo4j~=5.28
----

.Activate Python's development mode
[%collapsible]
====
For development, running Python in link:https://docs.python.org/3/library/devmode.html[development mode] could help you uncover API misusages and performance leaks early on.
You can do so via the `-X dev` command line option or by setting the `PYTHONDEVMODE` environment variable to `1`. +
For the driver, this results in:

- `ResourceWarning` to be emitted if resources aren't properly closed.
- `DeprecationWarning` to be emitted if deprecated APIs are used.
- The driver's debug mode to be enabled (which can also be achieved by setting the environment variable `PYTHONNEO4JDEBUG`).
====

[TIP]
The link:https://github.com/neo4j-drivers/neo4j-python-driver-rust-ext[Rust extension to the Python driver] is an alternative driver package that yields a link:https://medium.com/neo4j/neo4j-python-driver-10x-faster-with-rust-7059c56e8674[3x to 10x speedup] compared to the regular driver.
You can install it with `pip install neo4j-rust-ext`, either alongside the `neo4j` package or as a replacement to it.
Usage-wise, the drivers are identical: everything in this guide applies to both packages.

[NOTE]
To get the driver on an air-gapped machine, link:https://pypi.org/project/neo4j/#files[download the latest driver] tarball and install it with `pip install neo4j-<version>.tar.gz`.


include::{common-partial}/install.adoc[tag=get-an-instance]


ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::{common-partial}/glossary.adoc[]
include::../partials/glossary.adoc[]
endif::[]
