[[python-driver-session-api]]
= The session API

include::{common-partial}/session-api.adoc[tag=abstract]


[[python-driver-simple-sessions]]
== Simple sessions

include::{common-partial}/session-api.adoc[tag=simple-sessions]


[[python-driver-simple-lifecycle]]
=== Lifecycle

include::{common-partial}/session-api.adoc[tag=simple-lifecycle]

[source, python, indent=0]
----
with driver.session(...) as session:
    // transactions go here
----

*_Sessions can be configured in a number of different ways_*.
This is carried out by supplying configuration inside the session constructor.
See xref:session-api.adoc#python-driver-session-configuration[Session configuration] for more details.


[[python-driver-simple-transaction-fn]]
=== Transaction functions

include::{common-partial}/session-api.adoc[tag=simple-transaction-fn]

.Transaction function
======
[source, python, indent=0]
----
include::{python-examples}/test_transaction_function_example.py[tags=transaction-function-import]
----

[source, python, indent=0]
----
include::{python-examples}/test_transaction_function_example.py[tags=transaction-function]
----
======


[[python-driver-simple-autocommit-transactions]]
=== Auto-commit transactions (or implicit transactions)

include::{common-partial}/session-api.adoc[tag=simple-autocommit-transactions]

.Simple auto-commit transactions
======
[source, python, indent=0]
----
include::{python-examples}/test_autocommit_transaction_example.py[tags=autocommit-transaction-import]
----

[source, python, indent=0]
----
include::{python-examples}/test_autocommit_transaction_example.py[tags=autocommit-transaction]
----
======


[[python-driver-simple-result-consume]]
=== Consuming results

include::{common-partial}/session-api.adoc[tag=simple-result-consume]

.Consuming results
======
[source, python, indent=0]
----
include::{python-examples}/test_result_consume_example.py[tags=result-consume]
----
======


[[python-driver-simple-result-retain]]
=== Retaining results

include::{common-partial}/session-api.adoc[tag=simple-result-retain]

[source, python, indent=0]
----
include::{python-examples}/test_result_retain_example.py[tags=result-retain]
----


[[python-driver-session-configuration]]
== Session configuration

include::{common-partial}/session-api.adoc[tag=Bookmarks]

include::{common-partial}/session-api.adoc[tag=DefaultAccessMode]

include::{common-partial}/session-api.adoc[tag=Database]

See more about xref:cypher-workflow.adoc#python-database-selection[Database selection].

`Fetch Size`::
The number of records to fetch in each batch from the server.
Neo4j 4.0 introduces the ability to pull records in batches, allowing the client application to take control of data population and apply back pressure to the server.
+
*Default:* 1000 records

include::{common-partial}/session-api.adoc[tag=ImpersonatedUser]


[[python-driver-transaction-configuration]]

include::{common-partial}/session-api.adoc[tag=TransactionConfiguration]

include::{common-partial}/session-api.adoc[tag=TransactionTimeout]

[source, python, indent=0]
----
include::{python-examples}/test_transaction_timeout_config_example.py[tags=transaction-timeout-config]
----

include::{common-partial}/session-api.adoc[tag=TransactionMetadata]

[source, python, indent=0]
----
include::{python-examples}/test_transaction_metadata_config_example.py[tags=transaction-metadata-config]
----
