:driver-changelog-url: https://github.com/neo4j/neo4j-python-driver/wiki/6.x-changelog

= Upgrade from older versions

include::{common-partial}/upgrade.adoc[tag=intro]

////
[[recommended-steps]]
== Recommended steps

Using the migration assistant, the recommended upgrade steps are:

1. Set up the environment for the assistant to work in.
Download the link:https://github.com/neo4j/drivers-migration-assistant/archive/refs/heads/dev.zip[Drivers Migration Assistant zip], extract it, and locate yourself in its directory.
Then, assuming `python3` and `pip3` are already installed,
+
[source, bash]
----
python3 -m venv virtualenvs/neo4j-migration
source virtualenvs/neo4j-migration/bin/activate
pip3 install -r requirements.txt
----

2. Run the migration assistant with its default configuration and address all the issues that it surfaces. The `path` argument supports link:https://www.man7.org/linux/man-pages/man7/glob.7.html[globbing], and can be repeated. +
+
[source, bash]
----
python3 main.py -l python /path/*.py /path-recursive/**/*.py
----

3. Re-run the assistant with the regex parser and check if any more legit issues are raised. +
+
[source, bash]
----
python3 main.py -l python --regex-parser /path/*.py /path-recursive/**/*.py
----
+
The regex parser can detect implicit function calls and other hard-to-parse expressions, but is likely to surface more false positives (for more information, see link:https://github.com/neo4j/drivers-migration-assistant?tab=readme-ov-file#accuracy[Neo4j Drivers Migration Assistant -> Accuracy]).
You can add any spurious entry to the ignored list, so that the assistant won't bring them up in future runs.

4. Although the assistant can detect most of the locations where action is needed, a few changelog entries can't be surfaced in this form, so you should still revise the xref:breaking-changes[breaking changes] section and audit your codebase for the changes marked with {cross-mark} in the table.

5. You are ready to upgrade the driver package to the new version. For example, using `pip`: +
+
[source, bash]
----
pip3 install -U neo4j==5.27
----
////


[[new-features]]
== New features

[cols="1a,1a"]
|===

|
.New type `Vector`
[%collapsible]
====
The type xref:data-types.adoc#vector[`Vector`] allows for storing and retrieving Cypher `VECTOR` objects to/from the database.
The `VECTOR` type is suitable for efficiently storing lists of homogeneous numbers, such as embeddings.
====
|
.GQL status objects in errors
[%collapsible]
====
Exception objects also expose errors as GQL-status objects.
The main difference between Neo4j error codes and GQL error codes is that the latter are more granular.
For more information, see xref:query-simple.adoc#error-handling[Error handling].
====

|
.Support for pandas 3
[%collapsible]
====
As of version 6.2, the driver is compatible with `pandas` 3.x.

The driver might indirectly behave differently when used with pandas 3. For example, calling `Result.to_df` on a `Result` containing a string-only column produces a `pandas.DataFrame` with `dtype` `object` for this column. When using pandas 3, the `dtype` will be `StringDtype` instead.
====
|

|===


[[breaking-changes]]
== Breaking changes and deprecations

Deprecated features are likely to be removed in the next major release.

[cols="1,5a,1"]
|===
|Version |Message |Status

|6.0
|*Environment*

- Dropped support for Python 3.7, 3.8, 3.9.
- Package-alias `neo4j-driver` stopped receiving updates starting with 6.0. Install `neo4j` instead.
- `setup.py` has been removed. Use a recent enough packaging/build tool supporting `pyproject.toml`.
|label:removed[]

|6.0
|link:https://neo4j.com/docs/api/python-driver/current/api.html#neo4j.Session[`Session`] -- Methods `.read_transaction()` and `.write_transaction()` have been removed in favor of link:https://neo4j.com/docs/api/python-driver/current/api.html#neo4j.Session.execute_read[`.execute_read()`] and link:https://neo4j.com/docs/api/python-driver/current/api.html#neo4j.Session.execute_write[`.execute_write()`].
Through the new methods, the first argument of transaction functions is a link:https://neo4j.com/docs/api/python-driver/current/api.html#neo4j.ManagedTransaction[`ManagedTransaction`] object. It behaves like a regular `Transaction` object, except it does not offer the `.commit()`, `.rollback()`, `.close()`, and `.closed()` methods.
|label:removed[]

|6.0
|Driver and session objects are not implicitly closed through `+++__del__()+++` (destructor) anymore.
This behaviour was non-deterministic as there is no guarantee that the destructor would ever be called.
A `ResourceWarning` is emitted instead. +
Call `driver.close()` explicitly or create the driver via a `with` statement.
|label:removed[]

|6.0
|link:https://neo4j.com/docs/api/python-driver/current/api.html#neo4j.Driver[`Driver`] -- The config option `trust` is not available anymore. The options link:https://neo4j.com/docs/api/python-driver/current/api.html#trusted-certificates-ref[`trusted_certificates`] and link:https://neo4j.com/docs/api/python-driver/current/api.html#ssl-context-ref[`ssl_context`] are available.
|label:removed[]

|6.0
|*Bookmarks*

- The method `Session.last_bookmark()` has been removed in favor of link:https://neo4j.com/docs/api/python-driver/current/api.html#neo4j.Session.last_bookmarks[`Session.last_bookmarks()`]. The logic is similar, but the new method returns https://neo4j.com/docs/api/python-driver/current/api.html#neo4j.Bookmarks[`Bookmarks`] instead of `str`.
- `Bookmark` has been removed in favor of link:https://neo4j.com/docs/api/python-driver/current/api.html#neo4j.Bookmarks[`Bookmarks`].
- `Driver.session()` no longer accepts raw string bookmarks as bookmarks argument. Use a https://neo4j.com/docs/api/python-driver/current/api.html#neo4j.Bookmarks[`Bookmarks`] object instead.
|label:removed[]

|6.0
|*Imports*

- Import of the following modules has been removed without replacement, as they are internal and should not be used by client code: `neo4j.packstream`, `neo4j.routing`, `neo4j.config`, `neo4j.meta`, `neo4j.data`.
`neo4j.meta.version` is exposed through `+++neo4j.__version__+++`.
- Importing submodules from `neo4j.time` is not possible anymore. Import everything from `neo4j.time` directly instead.
- Importing `neo4j.work` and its submodules is not possible anymore. Import everything from `neo4j` directly instead.
- The following objects have been removed without replacement, as they are internal and should not be used by client code: `neo4j.spatial.hydrate_point`, `neo4j.spatial.dehydrate_point`, `neoj4.Config`, `neoj4.PoolConfig`, `neoj4.SessionConfig`, `neoj4.WorkspaceConfig`, `neo4j.data.DataDehydrator`, `neo4j.data.DataHydrator`.
- The following modules have been removed: `neo4j.conf`, `neo4j.data`, `neo4j.meta`, `neo4j.packstream`, `neo4j.routing`, `neo4j.time.arithmetic`, `neo4j.time.clock_implementation`, `neo4j.time.hydration`, `neo4j.time.metaclasses`, `neo4j.work`, `neo4j.work.query`, `neo4j.work.summary`
- `api.Version` has been removed as it's unused now.
`ServerInfo.protocol_version` is now a `tuple[int, int]` instead of a `api.Version`. This should be drop-in replacement is most cases.
- Make undocumented constants, helper functions, and other internal items private. For a full list, see the link:https://github.com/neo4j/neo4j-python-driver/blob/6.x/CHANGELOG.md[changelog].
|label:removed[]

|6.0
|Class `SummaryNotificationPosition` has been removed in favor of link:https://neo4j.com/docs/api/python-driver/current/api.html#neo4j.SummaryInputPosition[`SummaryInputPosition`].
|label:removed[]

|6.0
|link:https://neo4j.com/docs/api/python-driver/current/api.html#neo4j.exceptions.Neo4jError[`Neo4jError`] -- Method `.is_retriable()` has been removed in favor of link:https://neo4j.com/docs/api/python-driver/current/api.html#neo4j.exceptions.Neo4jError.is_retryable[`.is_retryable()`].
|label:removed[]

|6.0
|The magic method `Record.\\__getslice__()` has been removed.
If you were calling it directly, use `Record.\\__getitem__(slice(...))` or simply `record[...]` instead.
|label:removed[]

|6.0
|Changed errors raised under certain circumstances. For a full list, see the link:https://github.com/neo4j/neo4j-python-driver/blob/6.x/CHANGELOG.md[changelog].
|label:removed[Changed]

|6.0
|Graph type sets (`neo4j.graph.EntitySetView`) can no longer be indexed by legacy `id` (`int`, e.g., `graph.nodes[0]`).
Use the `element_id` instead (`str`, e.g., `graph.nodes["..."]`).
|label:removed[Changed]

|5.0
|link:https://neo4j.com/docs/api/python-driver/current/api.html#neo4j.graph.Node[`Node`], link:https://neo4j.com/docs/api/python-driver/current/api.html#neo4j.graph.Relationship[`Relationship`] -- Property `id` (int) is deprecated in favor of `element_id` (str).
This also affects link:https://neo4j.com/docs/api/python-driver/current/api.html#neo4j.graph.Graph[`Graph`] objects, as indexing `graph.nodes[...]` and `graph.relationships[...]` with integers is deprecated in favor of indexing them with strings.
|label:deprecated[]

|6.0
|xref:result-summary.adoc#_notifications[*Notifications*] as Neo4j status codes are deprecated in favor of GQL status objects.

As a result,

- Object link:https://neo4j.com/docs/api/python-driver/current/api.html#neo4j.SummaryNotification[`SummaryNotification`] is deprecated in favor of link:https://neo4j.com/docs/api/python-driver/current/api.html#neo4j.GqlStatusObject[`GqlStatusObject`].
- Objects link:https://neo4j.com/docs/api/python-driver/current/api.html#neo4j.NotificationCategory[`NotificationCategory`] and link:https://neo4j.com/docs/api/python-driver/current/api.html#neo4j.NotificationDisabledCategory[`NotificationDisabledCategory`] are deprecated in favor of link:https://neo4j.com/docs/api/python-driver/current/api.html#neo4j.NotificationClassification[`NotificationClassification`] and link:https://neo4j.com/docs/api/python-driver/current/api.html#neo4j.NotificationDisabledClassification[`NotificationDisabledClassification`].
- Attributes link:https://neo4j.com/docs/api/python-driver/current/api.html#neo4j.ResultSummary.notifications[`ResultSummary.notifications`] and link:https://neo4j.com/docs/api/python-driver/current/api.html#neo4j.ResultSummary.summary_notifications[`ResultSummary.summary_notifications`] are deprecated in favor of link:https://neo4j.com/docs/api/python-driver/current/api.html#neo4j.ResultSummary.gql_status_objects[`ResultSummary.gql_status_objects`].
- xref:result-summary.adoc#_filter_notifications[Filtering notifications] via `notifications_disabled_categories` is deprecated in favor of `notifications_disabled_classifications`.
|label:deprecated[]

|6.0
|Module `neo4j.time.ClockTime` and its accessors are deprecated.
|label:deprecated[]

|6.0
|Passing raw string bookmarks as `initial_bookmarks` to link:https://neo4j.com/docs/api/python-driver/current/api.html#neo4j.GraphDatabase.bookmark_manager[`GraphDatabase.bookmark_manager()`] is deprecated.
Use a link:https://neo4j.com/docs/api/python-driver/current/api.html#neo4j.Bookmarks[`Bookmarks`] object instead.
|label:deprecated[]

|===
