// This doc is also sourced in the Aura Developer Hub.
// Because of that, cross-links are absolute and
// source blocks have copy=true .

The Neo4j Go driver is the official library to interact with a Neo4j instance through a Go application.

At the hearth of Neo4j lies <<Cypher>>, the query language to interact with a Neo4j database.
While this guide does not _require_ you to be a seasoned Cypher querier, it is going to be easier to focus on the Go-specific bits if you already know some Cypher.
For this reason, although this guide does _also_ provide a gentle introduction to Cypher along the way, consider checking out link:https://neo4j.com/docs/getting-started/cypher/[Getting started -> Cypher] for a more detailed walkthrough of graph databases modelling and querying if this is your first approach.
You may then apply that knowledge while following this guide to develop your Go application.


[#install]
== Install

From within a module, use `go get` to install the link:https://pkg.go.dev/github.com/neo4j/neo4j-go-driver/v5/[Neo4j Go Driver]:

[source, bash, copy=true]
----
go get github.com/neo4j/neo4j-go-driver/v5
----

link:https://neo4j.com/docs/go-manual/current/install/[More info on installing the driver]


[#connect]
== Connect to the database

Connect to a database by creating a `DriverWithContext` object and providing a URL and an authentication token.
Once you have a `DriverWithContext` instance, use the `.VerifyConnectivity()` method to ensure that a working connection can be established.

[source, go, role=nocollapse, copy=true]
----
package main

import (
    "fmt"
    "context"
    "github.com/neo4j/neo4j-go-driver/v5/neo4j"
)

func main() {
    ctx := context.Background()
    // URI examples: "neo4j://localhost", "neo4j+s://xxx.databases.neo4j.io"
    dbUri := "<database-uri>"
    dbUser := "<username>"
    dbPassword := "<password>"
    driver, err := neo4j.NewDriverWithContext(
        dbUri,
        neo4j.BasicAuth(dbUser, dbPassword, ""))
    defer driver.Close(ctx)

    err = driver.VerifyConnectivity(ctx)
    if err != nil {
        panic(err)
    }
    fmt.Println("Connection established.")
}
----

link:https://neo4j.com/docs/go-manual/current/connect/[More info on connecting to a database]


[#create-graph]
== Create an example graph

Run a Cypher query with the function `ExecuteQuery()`.
Do not hardcode or concatenate parameters: use placeholders and specify the parameters as keyword arguments.

.Create two `Person` nodes and a `KNOWS` relationship between them
[source, go, role=nocollapse, copy=true]
----
result, err := neo4j.ExecuteQuery(ctx, driver, `
    CREATE (a:Person {name: $name})
    CREATE (b:Person {name: $friendName})
    CREATE (a)-[:KNOWS]->(b)
    `,
    map[string]any{
        "name": "Alice",
        "friendName": "David",
    }, neo4j.EagerResultTransformer,
    neo4j.ExecuteQueryWithDatabase("neo4j"))
if err != nil {
    panic(err)
}

summary := result.Summary
fmt.Printf("Created %v nodes in %+v.\n",
    summary.Counters().NodesCreated(),
    summary.ResultAvailableAfter())
----

link:https://neo4j.com/docs/go-manual/current/query-simple/[More info on querying the database]


[#query-graph]
== Query a graph

To retrieve information from the database, use the Cypher clause `MATCH`:

.Retrieve all `Person` nodes who know other persons
[source, go, role=nocollapse, copy=true]
----
result, err := neo4j.ExecuteQuery(ctx, driver, `
    MATCH (p:Person)-[:KNOWS]->(:Person)
    RETURN p.name AS name
    `,
    nil,
    neo4j.EagerResultTransformer,
    neo4j.ExecuteQueryWithDatabase("neo4j"))
if err != nil {
    panic(err)
}

// Loop through results and do something with them
for _, record := range result.Records {
    name, _ := record.Get("name")  // .Get() 2nd return is whether key is present
    fmt.Println(name)
    // or
    // fmt.Println(record.AsMap())  // get Record as a map
}

// Summary information
fmt.Printf("The query `%v` returned %v records in %+v.\n",
    result.Summary.Query().Text(), len(result.Records),
    result.Summary.ResultAvailableAfter())
----

link:https://neo4j.com/docs/go-manual/current/query-simple/[More info on querying the database]


[#close]
== Close connections and sessions
Call the `.close()` method on all `DriverWithContext` and `SessionWithContext` instances to release any resources still held by them.
The best practice is to call the methods with the `defer` keyword as soon as you create new objects.

[source, go, copy=true]
----
driver, err := neo4j.NewDriverWithContext(dbUri, neo4j.BasicAuth(dbUser, dbPassword, ""))
defer driver.Close(ctx)
----

[source, go, copy=true]
----
session := driver.NewSession(ctx, neo4j.SessionConfig{DatabaseName: "neo4j"})
defer session.Close(ctx)
----
