[[go-driver-cypher-workflow]]
= Cypher workflow

include::{common-content}/cypher-workflow.adoc[tag=abstract]


== Overview

include::{common-content}/cypher-workflow.adoc[tag=overview]


[[go-driver-sessions]]
== Sessions

include::{common-content}/cypher-workflow.adoc[tag=sessions]

The session classes are described in <<go-driver-session-api>>.
For more details, please see the <<go-driver-api-docs, API documentation>>.


[[go-driver-transactions]]
== Transactions

include::{common-content}/cypher-workflow.adoc[tag=transactions]

To learn more about how to use unmanaged transactions, see <<go-driver-api-docs, API documentation>> for the relevant language.


[[go-driver-queries-results]]
== Queries and results

include::{common-content}/cypher-workflow.adoc[tag=queries-results]


[[go-driver-causal-chaining]]
== Causal chaining and bookmarks

include::{common-content}/cypher-workflow.adoc[tag=causal-chaining]

.Pass bookmarks
======
[source, go]
----
include::{go-examples}/examples_test.go[tags=pass-bookmarks]
----
======


[[go-driver-access-modes-transaction]]
== Routing transactions using access modes

include::{common-content}/cypher-workflow.adoc[tag=access-modes-transaction]

.Read-write transaction
======
[source, go]
----
include::{go-examples}/examples_test.go[tags=read-write-transaction]
----
======


[[go-driver-databases]]
== Databases and execution context


[role=enterprise-edition]
[[go-database-selection]]
=== Database selection

include::{common-content}/cypher-workflow.adoc[tag=database-selection]

.Database selection on session creation
======
[source, go]
----
include::{go-examples}/examples_test.go[tags=database-selection]
----
======


[[go-driver-type-mapping]]
== Type mapping

include::{common-content}/cypher-workflow.adoc[tag=type-mapping]

.Map Neo4j types to Go types
[options="header", cols="<40m,<60a"]
|===
| Neo4j type        | Go type
| null | `nil`
| List | `[]interface{}`
| Map | `map[string]interface{}`
| Boolean | `bool`
| Integer | `int64`
| Float | `float64`
| String | `string`
| ByteArray | `[]byte`
| Date | *`neo4j.Date`*
| Time | *`neo4j.OffsetTime`*
| LocalTime | *`neo4j.LocalTime`*
| DateTime | *`time.Time`**
| LocalDateTime | *`neo4j.LocalDateTime`*
| Duration | *`neo4j.Duration`*
| Point | *`neo4j.Point`*
| Node | *`neo4j.Node`*
| Relationship | *`neo4j.Relationship`*
| Path | *`neo4j.Path`*
|===

+*+ When a `time.Time` value is sent/received through the driver and its `Zone()` returns a name of `Offset`, the value is stored with its offset value rather than its zone name.

[[go-driver-geospartial-types]]
=== Geospatial Types
This section lists some basic usage of the geospatial types provided by the Go Driver.

[[go-driver-geospatial-types-point2d]]
==== `Point2D`

Represents a two-dimensional in Cartesian space or in the WGS84 space. The field `SpatialRefId` indicates the type of the coordinate.

The following table defines the list of possibles values for `SpatialRefId` and its meaning.

======
[options="header", cols="<20m,<80a"]
|===
| SpatialRefId        | Description
| `7203` | 2D point in the cartesian space.
| `4326` | 2D point in the WGS84 space.
|===
======

Examples of two-dimensions points instantiation and reading:

[source, golang]
----
include::{go-examples}/examples_test.go[tags=geospatial-types-point2d]
----

[[go-driver-geospatial-types-point3d]]
==== `Point3D`

Represents a three-dimensional point in Cartesian space or in the WGS84 space. The field `SpatialRefId` indicates the type of the coordinate.

The following table defines the list of possibles values for `SpatialRefId` and its meaning.

======
[options="header", cols="<20m,<80a"]
|===
| SpatialRefId  | Description
| `9157` | 3D point in the cartesian space.
| `4979` | 3D point in the WGS84 space.
|===
======

Examples of three-dimensions points instantiation and reading:

[source, golang]
----
include::{go-examples}/examples_test.go[tags=geospatial-types-point2d]
----

[[go-driver-exceptions-errors]]
== Exceptions and error handling

When executing *Cypher* or carrying out other operations with the driver, certain exceptions and error cases may arise.
*_Server-generated exceptions_* are each associated with a <<status-codes#status-codes, *_status code_*>> that describes the nature of the problem and a message that provides more detail.

The classifications are listed in the table below.

.Server status code classifications
[options="header"]
|===
| Classification 	| Description
|ClientError            | The client application has caused an error.
The application should amend and retry the operation.

|DatabaseError          | The server has caused an error.
Retrying the operation will generally be unsuccessful.

|TransientError         | A temporary error has occurred.
The application should retry the operation.
|===

=== Service unavailable

A *_Service Unavailable_* exception will be signalled when the driver is no longer able to establish communication with the server, even after retries.

Encountering this condition usually indicates a fundamental networking or database problem.

While certain mitigations can be made by the driver to avoid this issue, there will always be cases when this is impossible.
As such, it is highly recommended to ensure client applications contain a code path that can be followed when the client is no longer able to communicate with the server.

=== Transient errors

Transient errors are those which are generated by the server and marked as safe to retry without alteration to the original request.
Examples of such errors are deadlocks and memory issues.

When using transaction functions, the driver will usually be able to automatically retry when a transient failure occurs.
