[[go-driver-get-started]]
= Get started

[abstract]
--
This section gives an overview of the official Neo4j Go Driver and how to connect to a Neo4j database with a "Hello World" example.
--


[[driver-get-started-about]]
== About the official drivers

include::{common-content}/get-started.adoc[tag=about]


[[driver-get-started-installation]]
== Driver versions and installation

include::{common-content}/get-started.adoc[tag=versions]


.Acquire the driver
======

To find the latest version of the driver, visit https://github.com/neo4j/neo4j-go-driver/releases.

========

To install the latest version of the driver using `go get`:

[source, shell, subs="attributes, specialcharacters"]
----
go get github.com/neo4j/neo4j-go-driver
----

========

========

To install the latest version of the driver using `dep`:

[source, shell, subs="attributes, specialcharacters"]
----
dep ensure github.com/neo4j/neo4j-go-driver
----

It is also an option to install a certain version of the driver.
Below is the syntax for using a certain minor version of the driver.
Visit https://golang.github.io/dep/docs/Gopkg.toml.html#version-rules for a detailed description of version rules that can be used.

[source, shell, subs="attributes, specialcharacters"]
----
dep ensure github.com/neo4j/neo4j-go-driver@1.7.x
----

========

The release notes for this driver are available https://github.com/neo4j/neo4j-go-driver/wiki[here].

======


[[driver-get-started-hello-world-example]]
== A "Hello World" example

The example below shows the minimal configuration necessary to interact with *Neo4j* through the Go driver.

.Hello World
[source, go]
----
include::{go-examples}/examples_test.go[tags=hello-world]
----


[[driver-api-docs]]
== Driver API docs

For a comprehensive listing of all driver functionality, refer to the *API documentation*: https://pkg.go.dev/github.com/neo4j/neo4j-go-driver/v4
