[[go-driver-session-api]]
= The session API

include::{common-content}/session-api.adoc[tag=abstract]

Sessions provide a "classic" *_blocking style_* API for Cypher execution.
In general, sessions provide the easiest programming style to work with since API calls are executed in a strictly sequential fashion.

[[go-driver-simple-lifecycle]]
== Lifecycle

include::{common-content}/session-api.adoc[tag=simple-lifecycle]

[source, go ]
----
session := driver.NewSession(...)
defer session.Close()
// transactions go here
----

*_Sessions can be configured in a number of different ways_*.
This is carried out by supplying configuration inside the session constructor.
See <<go-driver-session-configuration>> for more details.


[[go-driver-simple-transaction-fn]]
== Transaction functions

include::{common-content}/session-api.adoc[tag=simple-transaction-fn]

[source, go]
----
include::{go-examples}/examples_test.go[tags=transaction-function]
----


[[go-driver-simple-autocommit-transactions]]
== Auto-commit transactions

include::{common-content}/session-api.adoc[tag=simple-autocommit-transactions]

[source, go]
----
include::{go-examples}/examples_test.go[tags=autocommit-transaction]
----


[[go-driver-simple-result-consume]]
== Consuming results

include::{common-content}/session-api.adoc[tag=simple-result-consume]

[source, go]
----
include::{go-examples}/examples_test.go[tags=result-consume]
----


[[go-driver-simple-result-retain]]
== Retaining results

include::{common-content}/session-api.adoc[tag=simple-result-retain]

[source, go]
----
include::{go-examples}/examples_test.go[tags=result-retain]
----


[[go-driver-session-configuration]]
== Session configuration

include::{common-content}/session-api.adoc[tag=Bookmarks]

include::{common-content}/session-api.adoc[tag=DefaultAccessMode]

include::{common-content}/session-api.adoc[tag=Database]

See more about <<go-database-selection>>.

`Fetch Size`::
The number of records to fetch in each batch from the server.
Neo4j 4.0 introduces the ability to pull records in batches, allowing the client application to take control of data population and apply back pressure to the server.
+
*Default:* 1000 records

include::{common-content}/session-api.adoc[tag=ImpersonatedUser]


[[go-driver-transaction-configuration]]

include::{common-content}/session-api.adoc[tag=TransactionConfiguration]

include::{common-content}/session-api.adoc[tag=TransactionTimeout]

[source, go]
----
include::{go-examples}/examples_test.go[tags=transaction-timeout-config]
----

include::{common-content}/session-api.adoc[tag=TransactionMetadata]

[source, go]
----
include::{go-examples}/examples_test.go[tags=transaction-metadata-config]
----
