[[concepts]]
= Concepts

[abstract]
--
Results are returned from Neo4j as a _stream of records_.
A _record cursor_ walks through the stream, giving access to individual _record views_.
--

When a statement is run, results are returned as a record stream.
The stream itself is represented by a result cursor (see <<result-cursor>>), which is used to access the individual records.
The individual records can be accessed one at a time, or all at once.

Results are valid until the next statement is run, or until the end of the current transaction, whichever comes first.
To hold on to the results while running further statements, or to use the results outside of the scope of the current transaction, the results must be retained (see <<result-retain>>).


[[result-cursor]]
== Result Cursor

A result cursor provides access to the stream of records that make up the results.
Initially, before the stream has begun to be consumed, all field values are `null`.
// TODO: What does that mean? Why does the developer care?
// TODO: Would it be possible to be trapped by this in some language?

[.tabbed-example]
.Result cursor example
====
[include-with-java]
--
[source, java]
----
include::{java-examples}/Examples.java[tags=result-cursor]
----
--

[include-with-javascript]
--
[source, javascript]
----
COMING SOON
----
--

[include-with-python]
--
[source, python]
----
COMING SOON
----
--
====


[[record-view]]
== Record View

The result record stream is made up of individual records.
These are accessed as record views.
The record view provides immutable access to a single record.

The underlying record is an ordered map of keys and values.
These key-value pairs are called _fields_.
As the fields are both keyed and ordered, the value of a field can be accessed either by position _(0-based integer)_ or by key _(string)_.

[NOTE]
.Access values by key or position
--
* To access values by key, use a string.
* To access values by position, use a ``0``-based integer.
--

[.tabbed-example]
.Record view example
====
[include-with-java]
--
[source,java]
----
COMING SOON
----
--

[include-with-javascript]
--
[source,javascript]
----
COMING SOON
----
--

[include-with-python]
--
[source,python]
----
COMING SOON
----
--
====


[[result-retain]]
== Retaining Results

The result record stream is available until another statement is run in the session, or until the current transaction is closed.
To hold on to the results beyond this scope, the results need to be explicitly _retained_.

[.tabbed-example]
.Retaining results example
====
[include-with-java]
--
[source,java]
----
COMING SOON
----
--

[include-with-javascript]
--
[source,javascript]
----
COMING SOON
----
--

[include-with-python]
--
[source,python]
----
COMING SOON
----
--
====


// TODO https://github.com/neo-technology/driver-compliance-kit/blob/08-results/08-results-synchronous.adoc
