[[concepts]]
= Concepts

Every result is a stream of <<term-record, records>>.
A record is an ordered map of keys and values.
These key-value pairs are called _fields_.
As the fields are both keyed and ordered, the value of a field can be accessed either by position (_0-based integer_) or by key (_string_).

[NOTE]
--
* To access values by position, use a 0-based integer.
* To access values by key, use a string.
--

Views and cursors are the primary ways of accessing results.

[[record-view]]
== Record View

The record view provides access to the individual result record.

[[record-view]]
== Record View

The record view provides access to the individual result record.

[.tabbed-example]
.Record view example
====
[include-with-java]
--
[source,java]
----
RecordView r = ...;
for (String key : r.keys())
{
    System.out.println(key + ": " + r.value(key));
}
----
--

[include-with-javascript]
--
[source,javascript]
----
COMING SOON
----
--

[include-with-python]
--
[source,python]
----
COMING SOON
----
--
====


[[record-cursor]]
== Record Cursor

A record cursor provides access to the record stream.
It is a record view with a dynamically changing underlying record.

[.tabbed-example]
.Record cursor example
====
[include-with-java]
--
[source, java]
----
RecordView r = ...;
for (String key : r.keys())
{
    System.out.println(key + ": " + r.value(key));
}
----
--

[include-with-javascript]
--
[source, javascript]
----
COMING SOON
----
--

[include-with-python]
--
[source, python]
----
COMING SOON
----
--
====

// TODO https://github.com/neo-technology/driver-compliance-kit/blob/08-results/08-results-synchronous.adoc
