[[driver-results]]
= Results

// TODO https://github.com/neo-technology/driver-compliance-kit/blob/08-results/08-results-synchronous.adoc

[abstract]
--
Results returned from Neo4j are presented as a stream of records.
--

When a statement is run, results are returned as a record stream.
The stream itself is represented by a result cursor which is used to access the individual records.
The individual records can be accessed one at a time, or all at once.
Results are valid until the next statement is run or until the end of the current transaction, whichever comes first.
To hold on to the results while running additional statements, or to use the results outside of the scope of the current transaction, the results must be retained by assigning them to a variable.


[[driver-result-cursor]]
== The result cursor

A result cursor provides access to the stream of records that make up the results.
The cursor is moved through the stream and points to each record in turn.
Before the cursor is moved onto the first record, it points _before_ the first record.
When the cursor has traversed to the end of the result stream, summary information and metadata are available.

[NOTE]
--
Result records are loaded lazily as the cursor is moved through the stream.
This means that the cursor must be moved to the first result before this result can be consumed.
It also means that the entire stream must be explicitly consumed before summary information and metadata is available.
It is generally best practice to explicitly consume results and close sessions, in particular when running update statements.
This applies even if the summary information is not required.
Failing to consume a result can lead to unpredictable behaviour as there will be no guarantee that the server has seen and handled the Cypher statement.
--

[.tabbed-example]
.Example: Use a result cursor
====
[.include-with-dotnet]
======
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=result-traversal]
----
======

[.include-with-java]
======
[source, java]
----
include::{java-examples}/Examples.java[tags=result-traversal]
----
======

[.include-with-javascript]
======
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=result-traversal]
----
======

[.include-with-python]
======
[source, python]
----
include::{python-examples}/test_examples.py[tag=result-traversal]
----
======
====


[[driver-result-record]]
== The record

The result record stream is made up of individual records.
A record provides an immutable view of a part of a result.
It is an ordered map of keys and values.
These key-value pairs are called _fields_.
As the fields are both keyed and ordered, the value of a field can be accessed either by position _(0-based Integer)_ or by key _(String)_.

[NOTE]
.Access values by key or position
--
* To access values by position, use a ``0``-based integer.
* To access values by key, use a string.
--

[.tabbed-example]
.Example: Use a record
====
[.include-with-dotnet]
======
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=access-record]
----
======

[.include-with-java]
======
[source, java]
----
include::{java-examples}/Examples.java[tags=access-record]
----
======

[.include-with-javascript]
======
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=access-record]
----
======

[.include-with-python]
======
[source, python]
----
include::{python-examples}/test_examples.py[tag=access-record]
----
======
====


[[driver-result-retain]]
=== Retaining Results

The result record stream is available until another statement is run in the session, or until the current transaction is closed.
To hold on to the results beyond this scope, the results need to be explicitly _retained_.
For retaining results, each driver offers methods that collect the result stream and translate it into standard data structures for each language.
Retained results can be processed, while the session is free to take on the next workload.
The saved results can also be used directly to run a new statement.



[.tabbed-example]
.Example: Retain results for further processing
====
[.include-with-dotnet]
======
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=retain-result]
----
======
[.include-with-java]
======
[source, java]
----
include::{java-examples}/Examples.java[tags=retain-result]
----
======
[.include-with-javascript]
======
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=retain-result]
----
======
[.include-with-python]
======
[source, python]
----
include::{python-examples}/test_examples.py[tags=retain-result]
----
======
====

[.tabbed-example]
.Example: Use results in a new query
====
[.include-with-dotnet]
======
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=nested-statements]
----
======

[.include-with-java]
======
[source, java]
----
include::{java-examples}/Examples.java[tags=nested-statements]
----
======
[.include-with-javascript]
======
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=nested-statements]
----
======
[.include-with-python]
======
[source, python]
----
include::{python-examples}/test_examples.py[tags=nested-statements]
----
======
====


[[result-summary]]
== Result summary

Metadata can be retrieved along with the result stream.
An example is the query plan obtained by prepending a Cypher query with `PROFILE` or `EXPLAIN`.
The following example will produce an explain plan with accurate numbers by running the query in the database.
This will output a query profile (see <<how-do-i-profile-a-query>> for more information about query profiling).

[.tabbed-example]
.Example: Profile query and print execution plan
====
[.include-with-dotnet]
======
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=result-summary-query-profile]
----
======

[.include-with-java]
======
[source, java]
----
include::{java-examples}/Examples.java[tags=result-summary-query-profile]
----
======
[.include-with-javascript]
======
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=result-summary-query-profile]
----
======
[.include-with-python]
======
[source, python]
----
include::{python-examples}/test_examples.py[tags=result-summary-query-profile]
----
======
====

Neo4j may also provide notifications for a query, for example, warning when a query will cause the execution engine to build a cartesian product.
The following example will produce an explain plan with estimated numbers, without actually running the query in the database.

[.tabbed-example]
.Example: Explain query and print notifications
====
[.include-with-dotnet]
======
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=result-summary-notifications]
----
======

[.include-with-java]
======
[source, java]
----
include::{java-examples}/Examples.java[tags=result-summary-notifications]
----
======
[.include-with-javascript]
======
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=result-summary-notifications]
----
======
[.include-with-python]
======
[source, python]
----
include::{python-examples}/test_examples.py[tags=result-summary-notifications]
----
======
====

