[[java-driver-get-started]]
= Get started

[abstract]
--
This section gives an overview of the official Neo4j Java Driver and how to connect to a Neo4j database with a "Hello World" example.
--

[[java-driver-get-started-about]]
== About the official drivers

include::{common-content}/get-started.adoc[tag=about]


[[java-driver-get-started-installation]]
== Driver versions and installation

include::{common-content}/get-started.adoc[tag=versions]


.Acquire the driver
======

To use the Java driver, it is recommended employing a dependency manager, such as Maven or Gradle.
To find the latest version of the driver, visit the https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.neo4j.driver%22%20AND%20a%3A%22neo4j-java-driver%22[Maven Central Repository].

*Dependencies*

* org.reactivestreams:reactive-streams
* org.apache.logging.log4j:log4j (optional)

The driver is dependent on the https://www.reactive-streams.org/[Reactive Streams API], thus maintaining JDK 8 compatibility.
To make optimal use of the reactive APIs, we suggest an additional framework like Project Reactor or RxJava2.
Both implement the Reactive Streams API and provide an exhaustive set of operators.


.Installation via Maven
========

When using Maven, add the following block to the _pom.xml_ file.
The driver version can either be declared as a property (as in the first example) or as an explicit version number (as in the second).

[source, xml, subs="attributes, specialcharacters"]
----
<dependencies>
    <dependency>
        <groupId>org.neo4j.driver</groupId>
        <artifactId>neo4j-java-driver</artifactId>
        <version>$JAVA_DRIVER_VERSION</version>
    </dependency>
</dependencies>
----

In the following example, driver version {java-driver-version} is added.

[source, xml, subs="attributes, specialcharacters"]
----
<dependencies>
    <dependency>
        <groupId>org.neo4j.driver</groupId>
        <artifactId>neo4j-java-driver</artifactId>
        <version>{java-driver-version}</version>
    </dependency>
</dependencies>
----
========

.Installation via Gradle
========

For Gradle, a compile line will be required. Again, this can use a property or an explicit version number.

[source, groovy, subs="attributes, specialcharacters"]
----
compile 'org.neo4j.driver:neo4j-java-driver:$JAVA_DRIVER_VERSION'
----

In the following example, a driver version {java-driver-version} is added.

[source, groovy, subs="attributes, specialcharacters"]
----
compile 'org.neo4j.driver:neo4j-java-driver:{java-driver-version}'
----
========

The release notes for this driver are available https://github.com/neo4j/neo4j-java-driver/wiki[here].

======


[[java-driver-get-started-hello-world-example]]
== A "Hello World" example

The example below shows the minimal configuration necessary to interact with *Neo4j* through a driver.

.Hello World
======
[source, java]
----
include::{java-examples}/HelloWorldExample.java[tags=hello-world-import]
----

[source, java]
----
include::{java-examples}/HelloWorldExample.java[tags=hello-world]
----
======


[[java-driver-api-docs]]
== Driver API docs

For a comprehensive listing of all driver functionality, refer to the *API documentation*: {api-docs-base-uri}/java-driver/{java-driver-apidoc-version}/
