[[js-drivers]]
ifndef::backend-pdf[]
= The Neo4j JavaScript Driver Manual v{driver-version}
endif::[]
ifdef::backend-pdf[]
= The Neo4j JavaScript Driver Manual v{driver-version}
endif::[]
:project-version:
:manual-title: Neo4j JavaScript Driver Manual {project-version}
:source-indent: 0
:icons: font
:iconfont-cdn: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.0.0/css/font-awesome.min.css
// :example-caption!:
// :table-caption!:
ifndef::javascript-root[:javascript-root: {project-root}/build/driver-sources/javascript-driver]
:javascript-examples: {javascript-root}/packages/neo4j-driver/test
:api-docs-base-uri: https://neo4j.com/docs/api


ifndef::backend-pdf[]
License: link:{common-license-page-uri}[Creative Commons 4.0]
endif::[]
ifdef::backend-pdf[]
Copyright (C) {copyright}

License: <<license, Creative Commons 4.0>>
endif::[]

[abstract]
--
This is the manual for Neo4j JavaScript Driver version {driver-version}, authored by the Neo4j Team.
--

This manual covers the following areas:

* <<js-driver-get-started>> -- An overview of the official Neo4j JavaScript Driver and how to connect to a Neo4j database.
* <<js-driver-client-applications>> -- How to manage database connections within an application.
* <<js-driver-cypher-workflow>> -- How to create units of work and provide a logical context for that work.
* <<js-driver-session-api>> -- How the types and values used by Cypher map to native language types.
* <<js-driver-terminology>> -- Terminology for drivers.

_Who should read this?_

This manual is written for JavaScript developers building a Neo4j client application.

[.discrete.ad]
== link:https://graphacademy.neo4j.com/?ref=guides[Learn with GraphAcademy^]

image::https://graphacademy.neo4j.com/courses/app-nodejs/badge/[float=left]

[.discrete]
=== link:https://graphacademy.neo4j.com/courses/app-nodejs/?ref=guides[Building Neo4j Applications with Node.js^]

In this free course, follow a walk through the steps to integrate Neo4j into your Node.js projects.
You will learn about the Neo4j Node.js Driver, how sessions and transactions work and how to query Neo4j from an existing application.

link:https://graphacademy.neo4j.com/courses/app-nodejs/?ref=guides[Learn more^,role=button]

include::get-started.adoc[leveloffset=+1]

include::client-applications.adoc[leveloffset=+1]

include::cypher-workflow.adoc[leveloffset=+1]

include::session-api.adoc[leveloffset=+1]

include::terminology.adoc[leveloffset=+1]
