[[driver-introduction]]
= Introduction

[abstract]
--
The preferred way to access Neo4j from an application is to use a Neo4j driver.
--

Neo4j drivers provide access to Neo4j for the application.
A driver instance is configured and provides sessions to use for multiple transactional interactions with the database.
Within a session transactions run statements to create and query data, define the schema, and call procedures for monitoring and administration.
When Neo4j is deployed in a Causal Cluster, the driver handles the routing of read and write operations.
With Causal Clustering the driver also provides bookmarking (see <<driver-bookmarking>>).
Bookmarking is used to ensure causal consistency: the application can run multiple queries on different members of the cluster while maintaining a guaranteed consistent view of the data.
Each query sees the state of graph at least as up-to-date as the graph seen by the previous query.

The Neo4j drivers use the Bolt protocol for communication.
This allows for a high degree of feature sympathy between driver and database, and across drivers.
A Causal Cluster provides discovery features that are used by the driver to be aware of the cluster topology.
It is necessary for the driver to be cluster-aware to provide routing and load balancing.

Finally, using Bolt provides compatibility across multiple versions of driver and database.

Official drivers exist for:

* .NET
* Java
* JavaScript
* Python

[TIP]
Click the corresponding tab on any of the examples to switch to the selected language.

The Java driver can be used from any JVM language, including Java, Groovy, Clojure, or Kotlin.
The .NET driver is written in C# and can be used from any .NET language, including C#, F#, and VB; or even directly from PowerShell.

