[[driver-get-started]]
= Get started

[abstract]
--
This section gives an overview of the official Neo4j drivers and how to connect to a Neo4j database with a "Hello World" example.
--

[[driver-get-started-about]]
== About the official drivers

Neo4j provides official drivers for many popular programming languages.
These drivers are supported by Neo4j and come with full cluster routing support.

Community drivers also exist for many languages, but vary greatly in terms of feature sets, maturity, and support.
To find out more about community drivers, visit https://neo4j.com/developer/language-guides/.

The following languages and frameworks are officially supported by Neo4j:

.Supported languages and frameworks for the 4.x driver series
[options="header"]
|===
| Language/framework | Versions supported
| .NET               | https://github.com/dotnet/standard/blob/master/docs/versions/netstandard2.0.md[.NET Standard 2.0]
| Java               | Java 8+ (latest patch releases).
| JavaScript         | All LTS versions of Node.JS, specifically the 4.x and 6.x series runtimes (https://github.com/nodejs/LTS).
|===

[NOTE]
--
* Python - The Python driver 4.0 GA will be delayed until 2020.
* Go - There will be no Go driver release at this time.
Please see <<TBA>>
--

The driver API is intended to be topologically agnostic.
This means that the underlying database topology — single instance, Causal Cluster, etc. — can be altered without requiring a corresponding alteration to application code.
In the general case, only the <<driver-connection-uris, connection URI>> needs to be modified when changes are made to the topology.

NOTE: The official drivers do not support HTTP communication.
If you need an HTTP driver, choose one of the community drivers.
See also the <<http-api#http-api, HTTP API documentation>>.

[[driver-get-started-installation]]
== Driver versions and installation

Starting with Neo4j 4.0, the versioning scheme for the database, driver and protocol have all been aligned.
This simplifies general compatibility concerns and reduces mental overhead.

That said, cross-version compatibility is still available, and we guarantee minimum support for current and previous versions between both server and driver.
Concretely, this means that Neo4j 4.0 is guaranteed compatible with both 4.0 and 1.7 series drivers, and the 4.0 series drivers are guaranteed compatible with both Neo4j 4.0 and Neo4j 3.5.
In cases where at least one peer is below version 4.0, communication will occur in fallback mode, limiting functionality to that available in the lowest-versioned component.

Wherever possible, it is recommended to use the latest driver release available.
This will provide the greatest degree of stability and will ensure that the full set of server functionality is available.
The drivers make no explicit distinction between editions, however, and simply operate with the functionality made available by Neo4j itself.

To install a driver or to find out more about which driver versions are available, use the relevant language distribution system, described below.


.Acquire the driver
[.tabbed-example]
====

[.include-with-dotnet]
======

The .NET driver is distributed via the NuGet Gallery.
To find out the latest version of the driver, visit https://www.nuget.org/packages/Neo4j.Driver/.

*Dependencies*

* NETStandard.Library (^1.6.1)
* System.Net.NameResolution (^4.3.0)
* System.Net.Security (^4.3.1)
* System.Net.Sockets (^4.3.0)
* System.Runtime.InteropServices.RuntimeInformation (^ .3.0)
* System.Runtime.Serialization.Primitives (^4.3.0)
* System.Threading.Thread (^4.3.0)

.Installation via Install-package
========
To install the latest version of the driver using NuGet in Visual Studio:

[source, csharp, subs="attributes, specialcharacters"]
----
PM> Install-Package Neo4j.Driver
----

You can also choose to install a certain version of the driver.

[source, csharp, subs="attributes, specialcharacters"]
----
PM> Install-Package Neo4j.Driver -Version $DOTNET_DRIVER_VERSION
----

In the following example we are installing driver version {dotnet-driver-version}.

[source, csharp, subs="attributes, specialcharacters"]
----
PM> Install-Package Neo4j.Driver -Version {dotnet-driver-version}
----
========

You can review the release notes for this driver https://github.com/neo4j/neo4j-dotnet-driver/releases[here].

======
[.include-with-java]
======

To use the Java driver, it is recommended employing a dependency manager, such as Maven or Gradle.
To find out the latest version of the driver, visit the https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.neo4j.driver%22%20AND%20a%3A%22neo4j-java-driver%22[Maven Central Repository].

*Dependencies*

* org.reactivestreams:reactive-streams
* org.apache.logging.log4j:log4j (optional)


.Installation via Maven
========

When using Maven, add the following block to your _pom.xml_ file.
The driver version can either be declared as a property (as in the first example) or as an explicit version number (as in the second).

[source, xml, subs="attributes, specialcharacters"]
----
<dependencies>
    <dependency>
        <groupId>org.neo4j.driver</groupId>
        <artifactId>neo4j-java-driver</artifactId>
        <version>$JAVA_DRIVER_VERSION</version>
    </dependency>
</dependencies>
----

In the following example, driver version {java-driver-version} is added.

[source, xml, subs="attributes, specialcharacters"]
----
<dependencies>
    <dependency>
        <groupId>org.neo4j.driver</groupId>
        <artifactId>neo4j-java-driver</artifactId>
        <version>4.0.0</version>
    </dependency>
</dependencies>
----
========

.Installation via Gradle
========

For Gradle, a compile line will be required. Again, this can use a property or an explicit version number.

[source, groovy, subs="attributes, specialcharacters"]
----
compile 'org.neo4j.driver:neo4j-java-driver:$JAVA_DRIVER_VERSION'
----

In the following example, a driver version {java-driver-version} is added.

[source, groovy, subs="attributes, specialcharacters"]
----
compile 'org.neo4j.driver:neo4j-java-driver:{java-driver-version}'
----
========

You can review the release notes for the Java driver https://github.com/neo4j/neo4j-java-driver/releases[here].

======

[.include-with-javascript]
======

To use the JavaScript driver, it is recommended employing `npm`.
To find out the latest version of the driver, use:

[source, shell, subs="attributes, specialcharacters"]
----
npm show neo4j-driver@* version
----

*Dependencies*

* Babel/Runtime (^7.5.5)
* rxjs (^6.5.2)
* text-encoding-utf-8 (^1.0.2)
* uri-js (^4.2.2)

.Installation via npm
========

To install the latest version of the driver:

[source, shell, subs="attributes, specialcharacters"]
----
npm install neo4j-driver
----

You can also choose to install a certain version of the driver.

[source, shell, subs="attributes, specialcharacters"]
----
npm install neo4j-driver@$JAVASCRIPT-DRIVER-VERSION
----

In the following example, driver version {javascript-driver-version} is installed.

[source, shell, subs="attributes, specialcharacters"]
----
npm install neo4j-driver@{javascript-driver-version}
----
========

You can review the release notes for this driver https://github.com/neo4j/neo4j-javascript-driver/releases[here].

======

====


[[driver-get-started-hello-world-example]]
== A "Hello World" example

The example below shows the minimal configuration necessary to interact with Neo4j through a driver.

[.tabbed-example]
.Hello World
====
[.include-with-dotnet]
======
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=hello-world]
----
======

//[.include-with-go]
//======
//[source, go]
//----
//include::{go-examples}/examples_test.go[tags=hello-world]
//----
//======

[.include-with-java]
======
[source, java]
----
include::{java-examples}/HelloWorldExample.java[tags=hello-world]
----
======

[.include-with-javascript]
======
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=hello-world]
----
======

//[.include-with-python]
//======
//[source, python]
//----
//include::{python-examples}/hello_world_example.py[tags=hello-world]
//----
//======
====


[[driver-api-docs]]
== Driver API docs

For a comprehensive listing of all driver functionality, refer to the API documentation for the specific language driver.

[.tabbed-example]
.API docs
====
[.include-with-dotnet]
======
{api-docs-base-uri}/dotnet-driver/{dotnet-driver-apidoc-version}/
======

[.include-with-go]
======
https://godoc.org/github.com/neo4j/neo4j-go-driver/neo4j
======

[.include-with-java]
======
{api-docs-base-uri}/java-driver/{java-driver-apidoc-version}/
======

[.include-with-javascript]
======
{api-docs-base-uri}/javascript-driver/{javascript-driver-apidoc-version}/
======

[.include-with-python]
======
{api-docs-base-uri}/python-driver/{python-driver-apidoc-version}/
======
====
