[[driver-get-started]]
= Get started

[abstract]
--
This section gives an overview of the official Neo4j drivers and how to connect to a Neo4j database with a "Hello World" example.
--

[[driver-get-started-about]]
== About the official drivers

Neo4j provides official drivers for a number of popular programming languages.
These drivers are supported by Neo4j.

Community drivers also exist for many languages, but vary greatly in terms of feature sets, maturity, and support.
To find out more about community drivers, visit https://neo4j.com/developer/language-guides/.

The following languages and frameworks are officially supported by Neo4j:

.Supported languages and frameworks for the 4.x driver series
[options="header"]
|===
| Language/framework | Versions supported
| .NET               | https://github.com/dotnet/standard/blob/master/docs/versions/netstandard2.0.md[.NET Standard 2.0]
| Java               | Java 8+ (latest patch releases).
| JavaScript         | All LTS versions of Node.JS, specifically the 4.x and 6.x series runtimes (https://github.com/nodejs/LTS).
|===

[NOTE]
--
The 4.0 release of the Python and Go drivers are a work in progress. There is currently no release date available.

The 4.0 Python Driver is in alpha release stage with support for Python 3.5, 3.6, 3.7, 3.8, and this manual includes examples for using this alpha version.

For more information on the 1.7 Driver documentation, including the 1.7 Go Driver, see {docs-base-uri}/driver-manual/1.7.
--

The driver API is intended to be topologically agnostic.
This means that the underlying database topology — single instance, Causal Cluster, etc. — can be altered without requiring a corresponding alteration to application code.
In the general case, only the <<driver-connection-uris, connection URI>> needs to be modified when changes are made to the topology.

NOTE: The official drivers do not support HTTP communication.
If you need an HTTP driver, choose one of the community drivers.
See also the <<http-api#http-api, HTTP API documentation>>.

[[driver-get-started-installation]]
== Driver versions and installation

Starting with *Neo4j 4.0*, *_the versioning scheme for the database, driver and protocol have all been aligned_*.
This simplifies general compatibility concerns.

That said, cross-version compatibility is still available, and minimum support for current and previous versions between both server and driver is guaranteed.
More specifically, this means that *Neo4j 4.0* is guaranteed to be compatible with both *4.0 Drivers* and *1.7 Drivers*, and the *4.0 Drivers* are guaranteed to be compatible with both *Neo4j 4.0* and *Neo4j 3.5*.
In cases where at least one peer is below version 4.0, communication will occur in *_fallback mode, limiting functionality to that available in the lowest-versioned component_*.

Wherever possible, it is recommended to use the latest stable driver release available.
This will provide the greatest degree of stability and will ensure that the full set of server functionality is available.
The drivers, when used with *Neo4j Enterprise Edition*, come with full cluster routing support.
The drivers make no explicit distinction between *Enterprise Edition* and *Community Edition* however, and simply operate with the functionality made available by *Neo4j* itself.

To install a driver or to find out more about which driver versions are available, use the relevant language distribution system, described below.


.Acquire the driver
[.tabbed-example]
====

[.include-with-dotnet]
======

The .NET driver is distributed via the NuGet Gallery.
To find out the latest version of the driver, visit https://www.nuget.org/packages/Neo4j.Driver/.

*Dependencies*

* .NETStandard (^2.0)
* System.Net.NameResolution (^4.3.0)
* System.Net.Security (^4.3.2)
* System.Net.Sockets (^4.3.0)
* System.Runtime.InteropServices.RuntimeInformation (^ 4.3.0)
* System.Runtime.Serialization.Primitives (^4.3.0)
* System.Threading.Thread (^4.3.0)
* System.ValueTuple (^4.5.0)

The .NET Reactive API is under package `Neo4j.Driver.Reactive`.
It is built upon https://github.com/dotnet/reactive[`System.Reactive`].
There is no extra dependency required use .NET reactive API.

.Installation via Install-package
========
To install the latest version of the driver using NuGet in Visual Studio:

[source, csharp, subs="attributes, specialcharacters"]
----
PM> Install-Package Neo4j.Driver
----

It is also an option to install a certain version of the driver.

[source, csharp, subs="attributes, specialcharacters"]
----
PM> Install-Package Neo4j.Driver -Version $DOTNET_DRIVER_VERSION
----

In the following example we are installing driver version {dotnet-driver-version}.

[source, csharp, subs="attributes, specialcharacters"]
----
PM> Install-Package Neo4j.Driver -Version {dotnet-driver-version}
----
========

The release notes for this driver are available https://github.com/neo4j/neo4j-dotnet-driver/releases[here].

======

// [.include-with-go]
// ======
//
// To find out the latest version of the driver, visit https://github.com/neo4j/neo4j-go-driver/releases.
//
// In order to get go driver running, you need to install our C connector, seabolt, on your build and production environments.
// Follow instructions at https://github.com/neo4j-drivers/seabolt for installing seabolt through one of our binary packages or by building from scratch.
//
// The go driver makes use of `cgo` and `pkg-config` to build against `seabolt` and thus requires a working `cgo` and `pkg-config` environment on your build environment.
//
// ========
//
// To install the latest version of the driver using `go get`:
//
// [source, shell, subs="attributes, specialcharacters"]
// ----
// go get github.com/neo4j/neo4j-go-driver
// ----
//
// ========
//
// ========
//
// To install the latest version of the driver using `dep`:
//
// [source, shell, subs="attributes, specialcharacters"]
// ----
// dep ensure github.com/neo4j/neo4j-go-driver
// ----
//
// It is also an option to install a certain version of the driver.
// Below is the syntax for using a certain minor version of the driver.
// Visit https://golang.github.io/dep/docs/Gopkg.toml.html#version-rules for a detailed description of version rules that can be used.
//
// [source, shell, subs="attributes, specialcharacters"]
// ----
// dep ensure github.com/neo4j/neo4j-go-driver@1.7.x
// ----
//
// ========
//
// The release notes for this driver are available https://github.com/neo4j/neo4j-go-driver/releases[here].
//
// ======

[.include-with-java]
======

To use the Java driver, it is recommended employing a dependency manager, such as Maven or Gradle.
To find out the latest version of the driver, visit the https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.neo4j.driver%22%20AND%20a%3A%22neo4j-java-driver%22[Maven Central Repository].

*Dependencies*

* org.reactivestreams:reactive-streams
* org.apache.logging.log4j:log4j (optional)

The driver is dependent on the https://www.reactive-streams.org/[Reactive Streams API], thus maintaining JDK 8 compatibility.
To make optimal use of the reactive APIs, we suggest an additional framework like Project Reactor or RxJava2.
Both implement the Reactive Streams API and provide an exhaustive set of operators.


.Installation via Maven
========

When using Maven, add the following block to the _pom.xml_ file.
The driver version can either be declared as a property (as in the first example) or as an explicit version number (as in the second).

[source, xml, subs="attributes, specialcharacters"]
----
<dependencies>
    <dependency>
        <groupId>org.neo4j.driver</groupId>
        <artifactId>neo4j-java-driver</artifactId>
        <version>$JAVA_DRIVER_VERSION</version>
    </dependency>
</dependencies>
----

In the following example, driver version {java-driver-version} is added.

[source, xml, subs="attributes, specialcharacters"]
----
<dependencies>
    <dependency>
        <groupId>org.neo4j.driver</groupId>
        <artifactId>neo4j-java-driver</artifactId>
        <version>4.0.0</version>
    </dependency>
</dependencies>
----
========

.Installation via Gradle
========

For Gradle, a compile line will be required. Again, this can use a property or an explicit version number.

[source, groovy, subs="attributes, specialcharacters"]
----
compile 'org.neo4j.driver:neo4j-java-driver:$JAVA_DRIVER_VERSION'
----

In the following example, a driver version {java-driver-version} is added.

[source, groovy, subs="attributes, specialcharacters"]
----
compile 'org.neo4j.driver:neo4j-java-driver:{java-driver-version}'
----
========

The release notes for this driver are available https://github.com/neo4j/neo4j-java-driver/releases[here].

======

[.include-with-javascript]
======

To use the JavaScript driver, it is recommended employing `npm`.
To find out the latest version of the driver, use:

[source, shell, subs="attributes, specialcharacters"]
----
npm show neo4j-driver@* version
----

*Dependencies*

* Babel/Runtime (^7.5.5)
* RxJS (^6.5.2)
* text-encoding-utf-8 (^1.0.2)
* URI-js (^4.2.2)


The JavaScript Reactive API is built and exposed via RxJs.
A dependency of RxJs is automatically installed with the driver.

.Installation via npm
========

To install the latest version of the driver:

[source, shell, subs="attributes, specialcharacters"]
----
npm install neo4j-driver
----

It is also an option to install a certain version of the driver.

[source, shell, subs="attributes, specialcharacters"]
----
npm install neo4j-driver@$JAVASCRIPT-DRIVER-VERSION
----

In the following example, driver version {javascript-driver-version} is installed.

[source, shell, subs="attributes, specialcharacters"]
----
npm install neo4j-driver@{javascript-driver-version}
----
========

The release notes for this driver are available https://github.com/neo4j/neo4j-javascript-driver/releases[here].

======

[.include-with-python]
======

To find out the latest stable version of the Python Driver, visit https://pypi.org/project/neo4j/

To find a list of all available releases, visit https://pypi.org/simple/neo4j/

To install the latest stable version of the Python Driver:
[source, shell, subs="attributes, specialcharacters"]
----
pip install neo4j
----

It is also an option to install a certain version of the driver.

.Installation with Python
========
The following is the syntax for installing a certain version of the Python Driver:
[source, shell, subs="attributes, specialcharacters"]
----
pip install neo4j==$PYTHON_DRIVER_VERSION
----

In the following example we are installing Python Driver version {python-driver-version}.
[source, shell, subs="attributes, specialcharacters"]
----
pip install neo4j=={python-driver-version}
----
========

.Installation with Python, get Python Driver prereleases
========
In the following example we get the latest version, including alphas:
[source, shell, subs="attributes, specialcharacters"]
----
pip install neo4j>=4.0.0a
----

In the following example we get the latest  version, including betas:
[source, shell, subs="attributes, specialcharacters"]
----
pip install neo4j>=4.0.0b
----

In the following example we get the latest version, including release candidates:
[source, shell, subs="attributes, specialcharacters"]
----
pip install neo4j>=4.0.0rc
----
========

The release notes for the Python Driver are available https://github.com/neo4j/neo4j-python-driver/releases[here]

*NOTE:* The pypi project name have changed from *neo4j-driver* to *neo4j*, the old project will coexist with the new.

======

====


[[driver-get-started-hello-world-example]]
== A "Hello World" example

The example below shows the minimal configuration necessary to interact with *Neo4j* through a driver.

[.tabbed-example]
.Hello World
====
[.include-with-dotnet]
======
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=hello-world]
----

// [source, csharp]
// ----
// include::{dotnet-examples}/Examples.cs[tags=hello-world-import]
// ----
======

//[.include-with-go]
//======
//[source, go]
//----
//include::{go-examples}/examples_test.go[tags=hello-world]
//----
//======

[.include-with-java]
======
[source, java]
----
include::{java-examples}/HelloWorldExample.java[tags=hello-world]
----

[source, java]
----
include::{java-examples}/HelloWorldExample.java[tags=hello-world-import]
----
======

[.include-with-javascript]
======
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=hello-world]
----

// [source, javascript]
// ----
// include::{javascript-examples}/examples.test.js[tags=hello-world-import]
// ----
======

[.include-with-python]
======
[source, python]
----
include::{python-examples}/test_hello_world_example.py[tags=hello-world]
----
[source, python]
----
include::{python-examples}/test_hello_world_example.py[tags=hello-world-import]
----
======

====


[[driver-api-docs]]
== Driver API docs

For a comprehensive listing of all driver functionality, refer to the *API documentation* for the specific driver language.

[.tabbed-example]
.API docs
====
[.include-with-dotnet]
======
{api-docs-base-uri}/dotnet-driver/{dotnet-driver-apidoc-version}/
======

// [.include-with-go]
// ======
// https://godoc.org/github.com/neo4j/neo4j-go-driver/neo4j
// ======


[.include-with-java]
======
{api-docs-base-uri}/java-driver/{java-driver-apidoc-version}/
======

[.include-with-javascript]
======
{api-docs-base-uri}/javascript-driver/{javascript-driver-apidoc-version}/
======

[.include-with-python]
======
{api-docs-base-uri}/python-driver/{python-driver-apidoc-version}-preview/
======

====
