[[driver-get-started]]
= Get started

[abstract]
--
This section gives an overview of the official Neo4j drivers and how to connect to a Neo4j database with a "Hello World" example.
--

[[driver-get-started-about]]
== About the official drivers

Both official and community database drivers are available to provide access to a Neo4j database for applications.
Official drivers exist for:

* C# -- works with any .NET language
* Java -- works with any JVM language
* JavaScript
* Python

The driver API is intended to be topologically agnostic.
By this, we mean that the underlying database topology — single instance, causal cluster, etc. — can be altered without requiring a corresponding alteration to application code.
In the general case, only the <<driver-connection-uris, connection URI>> needs to be modified when changes are made to the topology. 

NOTE: The official drivers do not support HTTP communication.
If you need an HTTP driver, there are a number of community drivers to choose from.
See also <<http-api>>.

[[driver-get-started-installation]]
== Driver versions and installation

The 1.x series drivers have been built for Neo4j 3.x.
The driver major version number correlates with the  <<term-bolt, Bolt protocol>> version, the minor version number describes the driver feature set and the patch number defines the patch level of the driver in the regular sense.
While minor versions of drivers will generally be released at the same time across languages, patch levels may vary.

It is recommended to always use the latest driver release within a major series.
This will ensure that all server functionality is made available to client applications.
To install a driver or to find out more about which driver versions are available, use the relevant language distribution system.

.Acquire the driver
[.tabbed-example]
====

[.include-with-dotnet]
======

To find out the latest version of the driver, visit https://www.nuget.org/packages/Neo4j.Driver/.

To install the latest version of the driver using NuGet in Visual Studio:

[source, csharp, subs="attributes, specialcharacters"]
----
PM> Install-Package Neo4j.Driver
----

You can also choose to install a certain version of the driver.

========

Below is the syntax for installing a certain version of the driver.

[source, csharp, subs="attributes, specialcharacters"]
----
PM> Install-Package Neo4j.Driver -Version $DOTNET_DRIVER_VERSION
----

In the following example we are installing driver version {dotnet-driver-version}.

[source, csharp, subs="attributes, specialcharacters"]
----
PM> Install-Package Neo4j.Driver -Version {dotnet-driver-version}
----
========

You can review the release notes for this driver https://github.com/neo4j/neo4j-dotnet-driver/releases[here].

======

[.include-with-java]
======

To find out the latest version of the driver, visit the https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.neo4j.driver%22%20AND%20a%3A%22neo4j-java-driver%22[maven repository].

.Install the Java driver using Maven
========

When using Maven, add the following block to your _pom.xml_ file.
Note the placeholder for the driver version.
You will have to find out the exact patch version that you wish to install.

[source, xml, subs="attributes, specialcharacters"]
----
<dependencies>
    <dependency>
        <groupId>org.neo4j.driver</groupId>
        <artifactId>neo4j-java-driver</artifactId>
        <version>$JAVA_DRIVER_VERSION</version>
    </dependency>
</dependencies>
----

In the following example we are adding driver version {java-driver-version}.

[source, xml, subs="attributes, specialcharacters"]
----
<dependencies>
    <dependency>
        <groupId>org.neo4j.driver</groupId>
        <artifactId>neo4j-java-driver</artifactId>
        <version>{java-driver-version}</version>
    </dependency>
</dependencies>
----
========

.Add the dependency for the Java driver for Gradle or Grails
========

For Gradle or Grails, this is how to add the dependency.
Again, note the placeholder for the driver version.
You will have to find out the exact patch version that you wish to install.

[source, groovy, subs="attributes, specialcharacters"]
----
compile 'org.neo4j.driver:neo4j-java-driver:$JAVA_DRIVER_VERSION'
----

In the following example we are adding driver version {java-driver-version}.

[source, groovy, subs="attributes, specialcharacters"]
----
compile 'org.neo4j.driver:neo4j-java-driver:{java-driver-version}'
----
========

You can review the release notes for this driver https://github.com/neo4j/neo4j-java-driver/releases[here].

======

[.include-with-javascript]
======

Use `npm` to find out the latest version of the driver:

[source, shell, subs="attributes, specialcharacters"]
----
npm show neo4j-driver@* version
----

To install the latest version of the driver:

[source, shell, subs="attributes, specialcharacters"]
----
npm install neo4j-driver
----

You can also choose to install a certain version of the driver.

========

Below is the syntax for installing a certain version of the driver.

[source, shell, subs="attributes, specialcharacters"]
----
npm install neo4j-driver@$JAVASCRIPT-DRIVER-VERSION
----

In the following example we are installing driver version {javascript-driver-version}.

[source, shell, subs="attributes, specialcharacters"]
----
npm install neo4j-driver@{javascript-driver-version}
----
========

You can review the release notes for this driver https://github.com/neo4j/neo4j-javascript-driver/releases[here].

======

[.include-with-python]
======

To find out the latest version of the driver, visit https://pypi.python.org/pypi/neo4j-driver.

To install the latest version of the driver:

[source, shell, subs="attributes, specialcharacters"]
----
pip install neo4j-driver
----

You can also choose to install a certain version of the driver.

========

The following is the syntax for installing a certain version of the driver.

[source, shell, subs="attributes, specialcharacters"]
----
pip install neo4j-driver==$PYTHON_DRIVER_VERSION
----

In the following example we are installing driver version {python-driver-version}.

[source, shell, subs="attributes, specialcharacters"]
----
pip install neo4j-driver=={python-driver-version}
----

========

You can review the release notes for this driver https://github.com/neo4j/neo4j-python-driver/releases[here].

======
====


== Supported language and framework versions

For each language/framework, there is a set of versions that are officially supported by Neo4j.

.Supported languages/frameworks for the 1.x driver series
[options="header"]
|===
| Language/framework | Versions supported
| Java               | Oracle JDK 7/8 and OpenJDK 7/8 (latest patch releases)
| Python             | CPython 2.7, 3.4, 3.5 and 3.6 (latest patch releases)
| JavaScript         | our drivers are built to work with all LTS versions of Node.JS, specifically the 4.x and 6.x series runtimes (see https://github.com/nodejs/LTS).
| .NET               | our drivers target the .NET standard 1.3 (see https://github.com/dotnet/standard/blob/master/docs/versions.md).
|===


[[driver-get-started-hello-world-example]]
== A "Hello World" example

The example below shows the minimal configuration necessary to interact with Neo4j through a driver.

[.tabbed-example]
.Hello World
====
[.include-with-dotnet]
======
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=hello-world]
----
======

[.include-with-go]
======
[source, go]
----
include::{go-examples}/examples_test.go[tags=hello-world]
----
======

[.include-with-java]
======
[source, java]
----
include::{java-examples}/HelloWorldExample.java[tags=hello-world]
----
======

[.include-with-javascript]
======
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=hello-world]
----
======

[.include-with-python]
======
[source, python]
----
include::{python-examples}/hello_world_example.py[tags=hello-world]
----
======
====


[[driver-api-docs]]
== Driver API docs

For a comprehensive listing of all driver functionality, refer to the API documentation for the specific language driver.

[.tabbed-example]
.API docs
====
[.include-with-dotnet]
======
{api-docs-base-uri}/dotnet-driver/{dotnet-driver-apidoc-version}/
======

[.include-with-java]
======
{api-docs-base-uri}/java-driver/{java-driver-apidoc-version}/
======

[.include-with-javascript]
======
{api-docs-base-uri}/javascript-driver/{javascript-driver-apidoc-version}/
======

[.include-with-python]
======
{api-docs-base-uri}/python-driver/{python-driver-apidoc-version}/
======
====

