[[drivers]]
= Drivers
:project-version:
:manual-title: Neo4j Driver Manual {project-version}
:source-indent: 0
:icons: font
:iconfont-cdn: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.0.0/css/font-awesome.min.css
// :example-caption!:
// :table-caption!:
ifndef::dotnet-root[:dotnet-root: {project-root}/build/driver-sources/dotnet-driver]
ifndef::java-root[:java-root: {project-root}/build/driver-sources/java-driver]
ifndef::javascript-root[:javascript-root: {project-root}/build/driver-sources/javascript-driver]
ifndef::python-root[:python-root: {project-root}/build/driver-sources/python-driver]
:dotnet-examples: {dotnet-root}/Neo4j.Driver/Neo4j.Driver.IntegrationTests
:java-examples: {java-root}/examples/src/main/java/org/neo4j/docs/driver
:javascript-examples: {javascript-root}/test/v1
:python-examples: {python-root}/test/examples

:api-docs-base-uri: https://neo4j.com/docs/api


[abstract]
--
This chapter contains the complete documentation of the official Neo4j drivers.
--

Driver version: {driver-version}.

Neo4j drivers provide application access to a Neo4j database.
These official drivers use the Bolt protocol.
They have been designed to strike a balance between an idiomatic API for each language, and a uniform surface across all supported languages.

The chapter describes the following:

* <<driver-get-started, Get started>> -- An overview of the official Neo4j drivers and how to connect to a Neo4j database.
* <<driver-client-applications, Client applications>> -- How to manage database connections within an application.
* <<driver-sessions-transactions, Sessions and transactions>> -- How to create units of work and provide a logical context for that work.
* <<driver-cypher-values, Working with Cypher values>> -- The types and values used by Cypher and how they map to native language types.


include::get-started.adoc[leveloffset=+1]

include::client-applications.adoc[leveloffset=+1]

include::sessions-and-transactions.adoc[leveloffset=+1]

include::working-with-cypher-values.adoc[leveloffset=+1]

