[[drivers]]
= The Neo4j Drivers Manual v{driver-version}
:project-version:
:manual-title: Neo4j Driver Manual {project-version}
:source-indent: 0
:icons: font
:iconfont-cdn: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.0.0/css/font-awesome.min.css
// :example-caption!:
// :table-caption!:
ifndef::dotnet-root[:dotnet-root: {project-root}/build/driver-sources/dotnet-driver]
ifndef::java-root[:java-root: {project-root}/build/driver-sources/java-driver]
ifndef::javascript-root[:javascript-root: {project-root}/build/driver-sources/javascript-driver]
ifndef::python-root[:python-root: {project-root}/build/driver-sources/python-driver]
:dotnet-examples: {dotnet-root}/Neo4j.Driver/Neo4j.Driver.IntegrationTests
:java-examples: {java-root}/examples/src/main/java/org/neo4j/docs/driver
:javascript-examples: {javascript-root}/test/v1
:python-examples: {python-root}/test/examples
:api-docs-base-uri: https://neo4j.com/docs/api

Copyright (C) {copyright}

ifndef::backend-pdf[]
License: link:{common-license-page-uri}[Creative Commons 4.0]
endif::[]
ifdef::backend-pdf[]
License: <<license, Creative Commons 4.0>>
endif::[]

[abstract]
--
This is the driver manual for Neo4j official drivers version {driver-version}, authored by the Neo4j Team.
--

This manual covers the following areas:

* <<driver-get-started>> -- An overview of the official Neo4j drivers and how to connect to a Neo4j database.
* <<driver-client-applications>> -- How to manage database connections within an application.
* <<driver-sessions-transactions>> -- How to create units of work and provide a logical context for that work.
* <<driver-cypher-values>> -- How the types and values used by Cypher map to native language types.
* <<driver-terminology>> -- Terminology for drivers.

_Who should read this?_

This manual is written for the developer of a Neo4j client application.

include::get-started.adoc[leveloffset=+1]

include::client-applications.adoc[leveloffset=+1]

include::sessions-and-transactions.adoc[leveloffset=+1]

include::working-with-cypher-values.adoc[leveloffset=+1]

include::terminology.adoc[leveloffset=+1]
