[appendix]
[[driver-terminology]]
= Driver terminology

[abstract]
--
This section lists the relevant terminology related to Neo4j drivers.
--

[[term-acquire-connection]]acquire (connection)::
To borrow a driver connection that is not currently in use from a connection pool.

[[term-auto-commit]]auto-commit::
A single query which is wrapped in a transaction and committed automatically.

[[term-bolt]]Bolt::
Bolt is a Neo4j proprietary, binary protocol used for communication between client applications and database servers.
Bolt is versioned independently from the database and the drivers.

[[term-bolt-routing-protocol]]Bolt Routing Protocol::
The steps required for a driver to obtain a routing table from a cluster member.

[[term-bolt-server]]Bolt server::
A Neo4j instance that can accept incoming Bolt connections.

[[term-bookmark]]bookmark::
A marker for a point in the transactional history of Neo4j.

[[term-causal-chaining]]causal chaining::
A mechanism to ensure that the transactions carried out in a session are executed in order, even when each transaction may be carried out on different cluster members.

[[term-client-application]]client application::
A piece of software that interacts with a database server via a driver.

[[term-connection]]connection::
A persistent communication channel between a client application and a database server.

[[term-connection-pool]]connection pool::
A set of connections maintained for quick access, that can be acquired and released as required.

[[term-direct-driver]]direct driver::
A driver that can connect to a single server address.

[[term-driver-object]]driver (object)::
A globally accessible controller for all database access.

[[term-driver-package]]driver (package)::
A software library that provides access to Neo4j from a particular programming language.
The Neo4j drivers implement the <<term-bolt, Bolt>> protocol.

[[term-release-connection]]release (connection)::
To return a connection back into a connection pool after use.

[[term-routing-driver]]routing driver::
A driver that can route traffic to multiple members of a cluster using the routing protocol.

[[term-routing-table]]routing table::
A set of server addresses that identify cluster members associated with roles.

[[term-server-address]]server address::
A combination of host name and port or IP address and port that targets a server.

[[term-session]]session::
A causally linked sequence of transactions.

[[term-statement-result]]statement result::
The stream of records that are returned on execution of a statement.

[[term-thread-safety]]thread safety::
See https://en.wikipedia.org/wiki/Thread_safety.

[[term-transaction]]transaction::
A transaction comprises a unit of work performed against a database.
It is treated in a coherent and reliable way, independent of other transactions.
A transaction, by definition, must be atomic, consistent, isolated, and durable.

[[term-transaction-function]]transaction function::
The method of grouping a number of queries together which, when run in a session, are retried on failure.

[[term-transaction-manager]]transaction manager::
The component/code responsible for deciding what to do if a transaction fails, i.e to retry, give up or do something else.
