= Coordinate parallel transactions

When working with a Neo4j cluster, <<causal_consistency>> is enforced by default in most cases, which guarantees that a query is able to read changes made by previous queries.
The same does not happen by default for multiple xref:transactions.adoc[transactions] running in parallel though.
In that case, you can use _bookmarks_ to have one transaction wait for the result of another to be propagated across the cluster before running its own work.
This is not a requirement, and *you should only use bookmarks if you _need_ casual consistency across different transactions*.

A _bookmark_ is a token that represents some state of the database.
By passing one or multiple bookmarks along with a query, the server will make sure that the query does not get executed before the represented state(s) have been established.


== Bookmarks with `.executeQuery()`

When xref:query-simple.adoc[querying the database with `.executeQuery()`], the driver manages bookmarks for you by using the driver's default link:{neo4j-docs-base-uri}/api/javascript-driver/current/class/lib6/driver.js~Driver.html#instance-get-executeQueryBookmarkManager[`executeQueryBookmarkManager`].
In this case, you have the guarantee that subsequent queries can read previous changes without taking further action.

[source, javascript]
----
driver.executeQuery('<QUERY 1>')

# subsequent executeQuery calls will be causally chained

driver.executeQuery('<QUERY 2>') # can read result of <QUERY 1>
driver.executeQuery('<QUERY 3>') # can read result of <QUERY 2>
----

To disable bookmark management and causal consistency, set the `bookmarkManager` option to `null` in `.executeQuery()` calls.

[source, javascript]
----
driver.executeQuery(
    '<QUERY>',
    {},
    {
      bookmarkManager: null
    }
)
----


== Bookmarks within a single session

Bookmark management happens automatically for queries run within a single session, so that you can trust that queries inside one session are causally chained.

[source, javascript]
----
let session = driver.session({database: 'neo4j'})
try {
  await session.executeWrite(async tx => {
    await tx.run("<QUERY 1>")
  })
  await session.executeWrite(async tx => {
    await tx.run("<QUERY 2>")  // can read result of QUERY 1
  })
  await session.executeWrite(async tx => {
    await tx.run("<QUERY 3>")  // can read result of QUERY 1, 2
  })
} finally {
  await session.close()
}
----


== Bookmarks across multiple sessions

If your application uses multiple sessions, you may need to ensure that one session has completed all its transactions before another session is allowed to run its queries.
In those cases, you can collect the bookmarks from some sessions using the method `Session.lastBookmarks()` *(1), (2)*, store them into a list, and use them to initialize another session with the `bookmarks` parameter *(3)*.

In the example below, `sessionA` and `sessionB` are allowed to run concurrently, while `sessionC` waits until their results have been propagated.
This guarantees the `Person` nodes `sessionC` wants to act on actually exist.

.Coordinate multiple sessions using bookmarks
[source, javascript]
----
const neo4j = require('neo4j-driver');

(async () => {
  const URI = 'neo4j://localhost'
  const USER = 'neo4j'
  const PASSWORD = 'verysecret'
  let driver
  try {
    driver = neo4j.driver(URI, neo4j.auth.basic(USER, PASSWORD))
    await driver.verifyConnectivity()
  } catch(err) {
    console.log(`-- Connection error --\n${err}\n-- Cause --\n${err.cause}`)
    return
  }
  await createFriends(driver)
})()

async function createFriends(driver) {
  let savedBookmarks = []  // To collect the sessions' bookmarks

  // Create the first person and employment relationship.
  const sessionA = driver.session({database: 'neo4j'})
  try {
    await createPerson(sessionA, 'Alice')
    await employPerson(sessionA, 'Alice', 'Wayne Enterprises')
    savedBookmarks.concat(sessionA.lastBookmarks())
  } finally {
    sessionA.close()
  }

  // Create the second person and employment relationship.
  const sessionB = driver.session({database: 'neo4j'})
  try {
    await createPerson(sessionB, 'Bob')
    await employPerson(sessionB, 'Bob', 'LexCorp')
    savedBookmarks.concat(sessionB.lastBookmarks())
  } finally {
    sessionB.close()
  }

  // Create (and show) a friendship between the two people created above.
  const sessionC = driver.session({database: 'neo4j', bookmarks: savedBookmarks})
  try {
    await createFriendship(sessionC, 'Alice', 'Bob')
    await printFriendships(sessionC)
  } finally {
    sessionC.close()
  }
}

// Create a person node.
async function createPerson(session, name) {
  await session.executeWrite(async tx => {
    await tx.run('CREATE (:Person {name: $name})', { name: name })
  })
}

// Create an employment relationship to a pre-existing company node.
// This relies on the person first having been created.
async function employPerson(session, personName, companyName) {
  await session.executeWrite(async tx => {
    await tx.run(`
      MATCH (person:Person {name: $personName})
      MATCH (company:Company {name: $companyName})
      CREATE (person)-[:WORKS_FOR]->(company)`,
      { personName: personName, companyName: companyName }
    )
  })
}

// Create a friendship between two people.
async function createFriendship(session, nameA, nameB) {
  await session.executeWrite(async tx => {
    await tx.run(`
      MATCH (a:Person {name: $nameA})
      MATCH (b:Person {name: $nameB})
      MERGE (a)-[:KNOWS]->(b)
      `, { nameA: nameA, nameB: nameB }
    )
  })
}

// Retrieve and display all friendships.
async function printFriendships(session) {
  const result = await session.executeRead(async tx => {
    return await tx.run('MATCH (a)-[:KNOWS]->(b) RETURN a.name, b.name')
  })
  for(record of result.records) {
    console.log(`${record.get('a.name')} knows ${record.get('b.name')}`)
  }
}
----

image:{common-image}/driver-passing-bookmarks.svg[]

[TIP]
The use of bookmarks can negatively impact performance, since all queries are forced to wait for the latest changes to be propagated across the cluster.
For simple use-cases, try to group queries within a single transaction, or within a single session.


== Mix `.executeQuery()` and sessions

To ensure causal consistency among transactions executed partly with `.executeQuery()` and partly with sessions, you can use the option `bookmarkManager` upon session creation, setting it to `driver.executeQueryBookmarkManager`.
Since that is the default bookmark manager for `.executeQuery()` calls, this will ensure that all work is executed under the same bookmark manager and thus causally consistent.

[source, javascript]
----
driver.executeQuery('<QUERY 1>')

session = driver.session({
    bookmarkManager: driver.executeQueryBookmarkManager
})
try {
  // every query inside this session will be causally chained
  // (i.e., can read what was written by <QUERY 1>)
  session.executeWrite(async tx => tx.run('<QUERY 2>'))
} finally {
  session.close()
}

// subsequent executeQuery calls will be causally chained
// (i.e., can read what was written by <QUERY 2>)
driver.executeQuery('<QUERY 3>')
----


== Implement a custom `BookmarkManager`

The _bookmark manager_ is an interface used by the driver for keeping track of the bookmarks and keeping sessions automatically consistent.

You can create your own bookmark manager by complying with the link:{neo4j-docs-base-uri}/api/javascript-driver/current/class/lib6/bookmark-manager.js~BookmarkManager.html[`BookmarkManager`] interface, or use the default implementation provided by the driver by calling the link:{neo4j-docs-base-uri}/api/javascript-driver/current/function/index.html#static-function-bookmarkManager[`bookmarkManager()`] function. When implementing a bookmark manager, keep in mind that all methods must be concurrency safe.


ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::{common-partial}/glossary.adoc[]
endif::[]
