= Connection

Once you have xref:install.adoc#install-driver[installed the driver] and have xref:install.adoc#get-an-instance[a running Neo4j instance], you are ready to connect your application to the database.


== Connect to the database

You connect to a database by creating a <<Driver>> object and providing a URL and an authentication token.

[source, javascript]
----
(async () => {
  var neo4j = require('neo4j-driver')

  // URI examples: 'neo4j://localhost', 'neo4j+s://xxx.databases.neo4j.io'
  const URI = '<URI to Neo4j database>'
  const USER = '<Username>'
  const PASSWORD = '<Password>'

  try {
    var driver = neo4j.driver(URI,  neo4j.auth.basic(USER, PASSWORD))  // <1>
    await driver.verifyConnectivity()  // <2>
  } catch(err) {
    console.log(`Connection error\n${err}\nCause: ${err.cause}`)
  }

  await driver.close()
})();
----

Creating a `Driver` instance *(1)* only provides information on _how_ to access the database, but does not actually _establish_ a connection.
Connection is instead deferred to when the first query is executed.
To verify immediately that the driver can connect to the database (valid credentials, compatible versions, etc), use the `.verifyConnectivity()` method *(2)* after initializing the driver.

Both the creation of a `Driver` object and the connection verification can raise exceptions, so error catching should include them both.

`Driver` objects are _immutable_, _thread-safe_, and fairly _expensive to create_.
Share them across threads (but not across processes) and use xref:transactions#impersonation[impersonation] to query the database with a different user.
If you want to alter a `Driver` configuration, you will need to create a new object.


== Close connections

Always close `Driver` objects with `driver.close()` to free up all allocated resources, even upon unsuccessful connection or runtime errors.


== Further connection parameters

For more `Driver` configuration parameters and further connection settings, see xref:connect-advanced.adoc[Advanced connection information].


ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::{common-partial}/glossary.adoc[]
endif::[]
