= Connection

Once you have xref:install.adoc#install-driver[installed the driver] and have xref:install.adoc#get-an-instance[a running Neo4j instance], you are ready to connect your application to the database.


== Connect to the database

You connect to a database by creating a <<Driver>> object and providing a URL and an authentication token.

[source, javascript, role=nocollapse]
----
(async () => {
  var neo4j = require('neo4j-driver')

  // URI examples: 'neo4j://localhost', 'neo4j+s://xxx.databases.neo4j.io'
  const URI = '<URI for Neo4j database>'
  const USER = '<Username>'
  const PASSWORD = '<Password>'
  let driver

  try {
    driver = neo4j.driver(URI,  neo4j.auth.basic(USER, PASSWORD))  // <1>
    const serverInfo = await driver.getServerInfo()  // <2>
    console.log('Connection estabilished')
    console.log(serverInfo)
  } catch(err) {
    console.log(`Connection error\n${err}\nCause: ${err.cause}`)
    await driver.close()
    return
  }

  // Use the driver to run queries

  await driver.close()  // <3>
})();
----

<1> Creating a `Driver` instance only provides information on _how_ to access the database, but does not actually _establish_ a connection.
Connection is instead deferred to when the first query is executed.
<2> To verify immediately that the driver can connect to the database (valid credentials, compatible versions, etc), use the `.getServerInfo()` method after initializing the driver.
<3> Always close `Driver` objects to free up all allocated resources, even upon unsuccessful connection or runtime errors in subsequent querying.

// in js .verifyConnectivity() is deprecated.

Both the creation of a `Driver` object and the connection verification can raise exceptions, so error catching should include both.

`Driver` objects are _immutable_, _thread-safe_, and fairly _expensive to create_.
Share them across threads (but not across processes) and use xref:transactions#impersonation[impersonation] to query the database with a different user.
If you want to alter a `Driver` configuration, you will need to create a new object.


== Connect to an Aura instance

When you create an <<Aura>> instance, you may download a text file containing the connection information to the database.
The file has a name of the form `Neo4j-a0a2fa1d-Created-2023-11-06.txt`.

To connect to such an instance, you may either use the URI, username, and password explicitly in your application, or load the content of the connection file in the environment with `dotenv.config()` and populate your local variables via `process.env.<NAME>`.
This approach requires the package link:https://www.npmjs.com/package/dotenv[`dotenv`].

[source, javascript, role=nocollapse]
----
(async () => {
  var neo4j = require('neo4j-driver')
  require('dotenv').config({
    path: 'Neo4j-a0a2fa1d-Created-2023-11-06.txt',
    debug: true  // to raise file/parsing errors
  })

  const URI = process.env.NEO4J_URI
  const USER = process.env.NEO4J_USERNAME
  const PASSWORD = process.env.NEO4J_PASSWORD
  let driver

  try {
    driver = neo4j.driver(URI,  neo4j.auth.basic(USER, PASSWORD))
    const serverInfo = await driver.getServerInfo()
    console.log('Connection estabilished')
    console.log(serverInfo)
  } catch(err) {
    console.log(`Connection error\n${err}\nCause: ${err.cause}`)
    await driver.close()
    return
  }

  // Use the driver to run queries

  await driver.close()
})();
----


== Further connection parameters

For more `Driver` configuration parameters and further connection settings, see xref:connect-advanced.adoc[Advanced connection information].


ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::{common-partial}/glossary.adoc[]
include::../partials/glossary.adoc[]
endif::[]
