= Data types and mapping to Cypher types

The tables in this section show the mapping between Cypher data types and JavaScript types.

== Core data types

[options="header"]
|===
| Cypher Type | JavaScript Type
| <<null>>    | `null`
| List        | `Array`
| Map         | `Object`
| Boolean     | `Boolean`
| Integer     | link:{neo4j-docs-base-uri}/api/javascript-driver/current/class/lib6/integer.js~Integer.html[`Integer`]
| Float       | `Number`
| String      | `String`
| ByteArray   | `Int8Array`
|===

[TIP]
link:{neo4j-docs-base-uri}/api/javascript-driver/current/class/lib6/integer.js~Integer.html[`Integer`] is not one of JavaScript's native types, but rather a custom one accomodating Cypher's precision.
You can disable this through the link:{neo4j-docs-base-uri}/api/javascript-driver/current/function/index.html#configuration[`disableLosslessIntegers` configuration entry] when instantiating the driver, so that JavaScript's native `Number` type is used instead.
Note that this can lead to a loss of precision.


== Temporal types

Temporal data types are ISO-8601-compliant.
To serialize them to string, use the `toString()` method.

Sub-second values are measured to nanosecond precision.
To convert between driver and native types, use the methods `.fromStandardDate()` and `.toStandardDate()` (does not apply to `Duration`). Since JavaScript date types do not support nanoseconds, `.fromStandardDate()` allows a nanoseconds argument (optional), and `toStandardDate()` drops the nanoseconds.

Temporal objects are immutable.

[options="header"]
|===
| Cypher Type   | JavaScript Type
| Date          | link:{neo4j-docs-base-uri}/api/javascript-driver/current/class/lib6/temporal-types.js~Date.html[`Date`]
| Time          | link:{neo4j-docs-base-uri}/api/javascript-driver/current/class/lib6/temporal-types.js~Time.html[`Time`]
| LocalTime     | link:{neo4j-docs-base-uri}/api/javascript-driver/current/class/lib6/temporal-types.js~LocalTime.html[`LocalTime`]
| DateTime      | link:{neo4j-docs-base-uri}/api/javascript-driver/current/class/lib6/temporal-types.js~DateTime.html[`DateTime`]
| LocalDateTime | link:{neo4j-docs-base-uri}/api/javascript-driver/current/class/lib6/temporal-types.js~LocalDateTime.html[`LocalDateTime`]
| Duration      | link:{neo4j-docs-base-uri}/api/javascript-driver/current/class/lib6/temporal-types.js~Duration.html[`Duration`]
|===

.How to use temporal types in queries
[source,python]
----
from datetime import datetime
import pytz
from neo4j import GraphDatabase
from neo4j.time import DateTime


URI = "neo4j://localhost:7687"
AUTH = ("neo4j", "secretgraph")


friends_since = DateTime(year=1999, month=11, day=23,
                         hour=7, minute=47, nanosecond=4123)
friends_since = pytz.timezone("US/Eastern").localize(friends_since)

# Python's native datetimes work as well.
# They don't support the full feature-set of Neo4j's type though.
# py_friends_since = datetime(year=1999, month=11, day=23, hour=7, minute=47)
# py_friends_since = pytz.timezone("US/Eastern").localize(py_friends_since)

# Create a friendship with the given DateTime, and return the DateTime
with GraphDatabase.driver(URI, auth=AUTH) as driver:
    with driver.session() as session:
        result = session.run("""
            MERGE (a:Person {name: $name})
            MERGE (b:Person {name: $friend})
            MERGE (a)-[friendship:KNOWS]->(b)
            SET friendship.since = $friends_since
            RETURN friendship.since
            """, name="Alice", friend="Bob",
            friends_since=friends_since  # or friends_since=py_friends_since
        )
        records = list(result)
        out_datetime = records[0]["friendship.since"]
        print(out_datetime)  # 1999-11-23T07:47:00.000004123-05:00

        # Converting DateTime to native datetime (lossy)
        py_out_datetime = out_datetime.to_native()  # type: datetime
        print(py_out_datetime)  # 1999-11-23 07:47:00.000004-05:00

----


=== `Date`

Represents an instant capturing the date, but not the time, nor the timezone.

[source, javascript]
----
d = new neo4j.Date(2021, 11, 2)
// Date { year: 2021, month: 11, day: 2 }
d.toString() // '2021-11-02'
----

For full documentation, see link:{neo4j-docs-base-uri}/api/javascript-driver/current/class/lib6/temporal-types.js~Date.html[API documentation -- Date].


=== `Time`

Represents an instant capturing the time, and the timezone offset in seconds, but not the date.

[source, javascript]
----
d = new neo4j.Time(7, 47, 0, 4123, -4*3600)
/*
Time {
  hour: 7,
  minute: 47,
  second: 0,
  nanosecond: 4123,
  timeZoneOffsetSeconds: -14400
}
*/
d.toString() // '07:47:00.000004123-04:00'
----

For full documentation, see link:{neo4j-docs-base-uri}/api/javascript-driver/current/class/lib6/temporal-types.js~Time.html[API documentation -- Time].


=== `LocalTime`

Represents an instant capturing the time of day, but not the date, nor the timezone.

[source, javascript]
----
d = new neo4j.LocalTime(7, 47, 0, 4123)
// LocalTime { hour: 7, minute: 47, second: 0, nanosecond: 4123 }
d.toString() // '07:47:00.000004123'
----

For full documentation, see link:{neo4j-docs-base-uri}/api/javascript-driver/current/class/lib6/temporal-types.js~LocalTime.html[API documentation -- LocalTime].


=== `DateTime`

Represents an instant capturing the date, the time, and the timezone identifier.
Timezone parameters (offset and identifier) are optional.

[source, javascript]
----
d = new neo4j.DateTime(2021, 11, 2, 7, 47, 0, 4123, -4*3600, 'US/Eastern')
/*
DateTime {
  year: 2021,
  month: 11,
  day: 2,
  hour: 7,
  minute: 47,
  second: 0,
  nanosecond: 4123,
  timeZoneOffsetSeconds: -14400,
  timeZoneId: 'US/Eastern'
}
*/
d.toString() // '2021-11-02T07:47:00.000004123-04:00[US/Eastern]'
----

For full documentation, see link:{neo4j-docs-base-uri}/api/javascript-driver/current/class/lib6/temporal-types.js~DateTime.html[API documentation -- DateTime].


=== `LocalDateTime`

Represents an instant capturing the date and the time, but not the timezone.

[source, javascript]
----
d = new neo4j.LocalDateTime(2021, 11, 2, 7, 47, 0, 4123)
/*
LocalDateTime {
  year: 2021,
  month: 11,
  day: 2,
  hour: 7,
  minute: 47,
  second: 0,
  nanosecond: 4123
}
*/
d.toString() // '2021-11-02T07:47:00.000004123'
----

For full documentation, see link:{neo4j-docs-base-uri}/api/javascript-driver/current/class/lib6/temporal-types.js~LocalDateTime.html[API documentation -- LocalDateTime].


=== `Duration`

Represents the difference between two points in time.

[source, javascript]
----
const d = new neo4j.Duration(1, 2, 3, 4)
/*
Duration {
  months: 1,
  days: 2,
  seconds: Integer { low: 3, high: 0 },
  nanoseconds: Integer { low: 4, high: 0 }
}
*/
d.toString() // 'P1M2DT3.000000004S'
----

For full documentation, see link:{neo4j-docs-base-uri}/api/javascript-driver/current/class/lib6/temporal-types.js~Duration.html[API documentation -- Duration].


== Spatial types

Cypher supports spatial values (points), and Neo4j can store these point values as properties on nodes and relationships.

The object attribute `srid` (short for _Spatial Reference Identifier_) is a number identifying the coordinate system the spatial type is to be interpreted in.
You can think of it as a unique identifier for each spatial type.

[options="header"]
|===
| Cypher Type       | Python Type
| Point             | `neo4j.spatial.Point`
| Point (Cartesian) | `neo4j.spatial.CartesianPoint`
| Point (WGS-84)    | `neo4j.spatial.WGS84Point`
|===

For full documentation, see link:{neo4j-docs-base-uri}/api/python-driver/current/types/spatial.html[API documentation -- Spatial types].

=== `CartesianPoint`

Represents a point in 2D/3D Cartesian space. +
Exposes properties `x`, `y`, `z` (the latter for 3D points only).

[source, javascript]
----
from neo4j.spatial import CartesianPoint

# A 2D CartesianPoint
point = CartesianPoint((1.23, 4.56))
print(point.x, point.y, point.srid)
# 1.23 4.56 7203

# A 3D CartesianPoint
point = CartesianPoint((1.23, 4.56, 7.89))
print(point.x, point.y, point.z, point.srid)
# 1.23 4.56 7.8 9157
----

For full documentation, see link:{neo4j-docs-base-uri}/api/python-driver/current/types/spatial.html#cartesianpoint[API documentation -- Spatial types -- CartesianPoint].

=== `WGS84Point`

Represents a point in the World Geodetic System (WGS84). +
Exposes properties `longitude`, `latitude`, `height` (the latter for 3D points only), which are aliases for `x`, `y`, `z`.

[source,python]
----
from neo4j.spatial import WGS84Point

# A 2D WGS84Point
point = WGS84Point((1.23, 4.56))
print(point.longitude, point.latitude, point.srid)
# or print(point.x, point.y, point.srid)
# 1.23 4.56 4326

# A 3D WGS84Point
point = WGS84Point((1.23, 4.56, 7.89))
print(point.longitude, point.latitude, point.height, point.srid)
# or print(point.x, point.y, point.z, point.srid)
# 1.23 4.56 7.89 4979
----

For full documentation, see link:{neo4j-docs-base-uri}/api/python-driver/current/types/spatial.html#wgs84point[API documentation -- Spatial types -- WSG84Point].


== Graph types

*Graph types are only passed as results and may not be used as parameters*.

[options="header"]
|===
| Cypher Type  | Python Type
| Node         | `neo4j.graph.Node`
| Relationship | `neo4j.graph.Relationship`
| Path         | `neo4j.graph.Path`
|===

For full documentation, see link:{neo4j-docs-base-uri}/api/python-driver/current/api.html#graph-data-types[API documentation -- Graph types].


=== `Node`
Represents a node in a graph. +
The property `element_id` provides an identifier for the entity.
This should be used with care, as no guarantees are given about the mapping between id values and elements outside the scope of a single transaction.

[source,python]
----
from neo4j import GraphDatabase


URI = "neo4j://localhost:7687"
AUTH = ("neo4j", "secretgraph")

with GraphDatabase.driver(URI, auth=AUTH) as driver:
    with driver.session() as session:
        result = session.run(
            "MERGE (p:Person {name: $name}) RETURN p AS person",
            name="Alice"
        )
        record = result.single()
        node = record["person"]
        print(f"Node ID: {node.element_id}\n"
              f"Labels: {node.labels}\n"
              f"Properties: {node.items()}\n"
        )

# Node ID: 4:73e9a61b-b501-476d-ad6f-8d7edf459251:0
# Labels: frozenset({'Person'})
# Properties: dict_items([('name', 'Alice')])
----

For full documentation, see link:{neo4j-docs-base-uri}/api/python-driver/current/api.html#neo4j.graph.Node[API documentation -- Graph types -- Node].


=== `Relationship`

Represents a relationship in a graph. +
The property `element_id` provides an identifier for the entity.
This should be used with care, as no guarantees are given about the mapping between id values and elements outside the scope of a single transaction.

[source,python]
----
from neo4j import GraphDatabase
from neo4j.time import Date


URI = "neo4j://localhost:7687"
AUTH = ("neo4j", "secretgraph")

with GraphDatabase.driver(URI, auth=AUTH) as driver:
    with driver.session() as session:
        result = session.run("""
            MERGE (p:Person {name: $name})
            MERGE (friend:Person {name: $friend_name})
            MERGE (p)-[r:KNOWS]->(friend)
            SET r.status = $status, r.since = $date
            RETURN r AS friendship
            """, name="Alice", status="BFF", date=Date.today(), friend_name="Bob",
        )
        record = result.single()
        relationship = record["friendship"]
        print(f"Relationship ID: {relationship.element_id}\n"
              f"Start node: {relationship.start_node}\n"
              f"End node: {relationship.end_node}\n"
              f"Type: {relationship.type}\n"
              f"Friends since: {relationship.get('since')}\n"
              f"All properties: {relationship.items()}\n"
        )

# Relationship ID: 5:73e9a61b-b501-476d-ad6f-8d7edf459251:1
# Start node: <Node element_id='4:73e9a61b-b501-476d-ad6f-8d7edf459251:0' labels=frozenset({'Person'}) properties={'name': 'Alice'}>
# End node: <Node element_id='4:73e9a61b-b501-476d-ad6f-8d7edf459251:2' labels=frozenset({'Person'}) properties={'name': 'Bob'}>
# Type: KNOWS
# Friends since: 2022-11-07
# All properties: dict_items([('since', neo4j.time.Date(2022, 11, 7)), ('status', 'BFF')])
----

For full documentation, see link:{neo4j-docs-base-uri}/api/python-driver/current/api.html#neo4j.graph.Relationship[API documentation -- Graph types -- Relationship].


=== `Path`

Represents a path in a graph.

[source,python]
----
from neo4j import GraphDatabase
from neo4j.time import Date


URI = "neo4j://localhost:7687"
AUTH = ("neo4j", "secretgraph")

def add_friend(tx, name, status, date, friend_name):
    tx.run("""
        MERGE (p:Person {name: $name})
        MERGE (friend:Person {name: $friend_name})
        MERGE (p)-[r:KNOWS]->(friend)
        SET r.status = $status, r.since = $date
        """, name=name, status=status, date=date, friend_name=friend_name
    )

with GraphDatabase.driver(URI, auth=AUTH) as driver:
    with driver.session() as session:
        # Create some :Person nodes linked by :KNOWS relationships
        session.execute_write(add_friend, name="Alice", status="BFF",
                              date=Date.today(), friend_name="Bob")
        session.execute_write(add_friend, name="Bob", status="Fiends",
                              date=Date.today(), friend_name="Sofia")
        session.execute_write(add_friend, name="Sofia", status="Acquaintances",
                              date=Date.today(), friend_name="Sara")

        # Follow :KNOWS relationships outgoing from Alice three times, return as path
        result = session.run("""
            MATCH path=(:Person {name: $name})-[:KNOWS*3]->(:Person)
            RETURN path
            """, name="Alice"
        )
        record = result.single()
        path = record["path"]

        print("-- Path breakdown --")
        for friendship in path:
            print("{name} is friends with {friend} ({status})".format(
                name=friendship.start_node.get("name"),
                friend=friendship.end_node.get("name"),
                status=friendship.get("status"),
            ))
----

For full documentation, see link:{neo4j-docs-base-uri}/api/python-driver/current/api.html#neo4j.graph.Path[API documentation -- Graph types -- Path].


== Exceptions

The driver can raise a number of different exceptions.
A full list is available in the link:{neo4j-docs-base-uri}/api/python-driver/current/api.html#errors[API documentation].
For a list of errors the server can return, see the link:{neo4j-docs-base-uri}/status-codes/current/[Status code] page.

.Root exception types
[options="header", cols="<25m,<75a"]
|===
| Classification    | Description
|Neo4jError         | Errors reported by the Neo4j server (e.g., wrong Cypher syntax, bad connection, wrong credentials, ...)

|DriverError        | Errors reported by the driver (e.g., bad usage of parameters or transactions, improper handling of results, ...)
|===

Some server errors are marked as safe to retry without need to alter the original request.
Examples of such errors are deadlocks and memory issues.
All driver's exception types implement the method `.is_retryable()`, which gives insights into whether a further attempt might be successful.
This is particular useful when running queries in xref:transactions#explicit-transactions[explicit transactions], to know if a failed query should be run again.

ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::{common-partial}/glossary.adoc[]
endif::[]
