[[js-driver-get-started]]
= Get started
:description: This section gives an overview of the official Neo4j JavaScript Driver and how to connect to a Neo4j database with a "Hello World" example. 


[[js-driver-get-started-about]]
== About the official JavaScript driver

include::{common-partial}/get-started.adoc[tag=about]

In the general case, only the xref:client-applications.adoc#js-driver-connection-uris[connection URI] needs to be modified when changes are made to the topology.

include::{common-partial}/get-started.adoc[tag=about-note]

[[js-driver-get-started-installation]]
== Driver versions and installation

include::{common-partial}/get-started.adoc[tag=versions]


.Acquire the driver
======
To use the JavaScript driver, it is recommended employing `npm`.
To find the latest version of the driver, use:

[source, shell, subs="attributes, specialcharacters", indent=0]
----
npm show neo4j-driver@* version
----

*Dependencies*

* Babel/Runtime (^7.5.5)
* RxJS (^6.5.2)
* text-encoding-utf-8 (^1.0.2)
* URI-js (^4.2.2)


The JavaScript Reactive API is built and exposed via RxJs.
A dependency of RxJs is automatically installed with the driver.

.Installation via npm
========

To install the latest version of the driver:

[source, shell, subs="attributes, specialcharacters", indent=0]
----
npm install neo4j-driver
----

It is also an option to install a certain version of the driver.

[source, shell, subs="attributes, specialcharacters", indent=0]
----
npm install neo4j-driver@$JAVASCRIPT-DRIVER-VERSION
----

In the following example, driver version {javascript-driver-version} is installed.

[source, shell, subs="attributes, specialcharacters", indent=0]
----
npm install neo4j-driver@{javascript-driver-version}
----
========

The release notes for this driver are available https://github.com/neo4j/neo4j-javascript-driver/wiki[here].

======


[[js-driver-get-started-hello-world-example]]
== A "Hello World" example

The example below shows the minimal configuration necessary to interact with *Neo4j* through the JavaScript driver.

.Hello World
======
[source, javascript, indent=0]
----
include::{javascript-examples}/examples.test.js[tags=hello-world]
----

//[source, javascript, indent=0]
//----
//include::{javascript-examples}/examples.test.js[tags=hello-world-import]
//----
======


[[js-driver-api-docs]]
== Driver API docs

For a comprehensive listing of all driver functionality, please see the {api-docs-base-uri}/javascript-driver/{driver-version}/[JavaScript API reference documentation].
