= Installation

To create a Neo4j JavaScript application, you first need to install the JavaScript Driver and get a Neo4j database instance to connect to.

.Server compatibility
[IMPORTANT]
The latest driver in the `6.x` series supports connection to Neo4j instances version 4.4.x, 5.x, 2025.x, and 2026.x.
It is also guaranteed to be forward-compatible with the next major release.

[#install-driver]
== Install the driver

Use `npm` to install the link:https://www.npmjs.com/package/neo4j-driver[Neo4j JavaScript Driver] (requires `npm` and any LTS version of `node.js`):

[source,bash]
----
npm i neo4j-driver
----

[NOTE]
--
There is also a link:https://www.npmjs.com/package/neo4j-driver-lite[lite version] of the Neo4j JavaScript Driver, which includes the same features as the regular driver but without support for the xref:query-async#_reactive_api[Reactive API].
You can install it with `npm i neo4j-driver-lite`.
--

== Include the driver

Unless you are going to xref:browser-websockets.adoc[use the driver within a web browser], you use the JavaScript driver in a Node.js or TypeScript application.
To include the driver in your application, use `require`:

[source, javascript]
----
const neo4j = require('neo4j-driver')
----


include::{common-partial}/install.adoc[tag=get-an-instance]


ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::{common-partial}/glossary.adoc[]
endif::[]
