= Type checking and object mapping

Neither JavaScript nor Neo4j are strongly typed, which can lead to mistakes where a property is set to the wrong type, or an unexpected type is returned from the database and causes errors in client code.

Object mapping helps contain such mistakes.
It allows you to map result records into classes with properties of explicit types, and to submit typed query parameters.

[[read]]
== Read from the database

To map records into objects of a specific type, define a class having the same attributes as the keys returned by the query. The class attributes must match exactly the query return keys (case included).

[[queries-properties]]
=== Queries returning properties

.Class and mapping definition
[source, typescript]
----
class Movie { // <.>
  title: string
  release?: number
  constructor(title: string, release: number) {
    this.title = title
    this.release = release
  }
};

const movieRules: Rules = { // <.>
  title: rule.asString({}),
  release: rule.asNumber({ isInteger: true, optional: true, from: "released" }) // <.>
};
----

<.> Each record from the query result must conform to the `Movie` class definition.
<.> `Rules` is a map-like object holding the typed mappings between the JavaScript class definitions and the database schema. Each property is specified via a link:https://neo4j.com/docs/api/javascript-driver/current/variable/index.html#static-variable-rule[`rule`] call.
<.> Type-specific (optional) attributes allow you to tweak the mapping behavior. For example, `release` is set to be optional, will automatically be converted from an integer in the database to a JavaScript number on the client, and is matched to the node property `released` even if the class attribute is called differently. For more information on allowed parameters, see link:https://neo4j.com/docs/api/javascript-driver/current/variable/index.html#static-variable-rule[API docs -> `rule`].

.Query execution
[source, typescript]
----
let res = await driver.executeQuery<MappedQueryResult<Movie>>(` // <.>
  MERGE (m:Movie {title: "Cloud atlas", released: 2013})
  RETURN m.title AS title, m.released AS released
  `, {},
  {resultTransformer: neo4j.resultTransformers.hydrated(Movie, movieRules)} // <.>
)

console.log(res.records[0])
// Movie { title: 'Cloud atlas', release: 2013 }
----

<.> The return type `MappedQueryResult<Movie>` is optional. If given, it must match the type provided in the `.hydrated()` call later.
<.> The link:https://neo4j.com/docs/api/javascript-driver/current/class/lib6/result-transformers.js~ResultTransformers.html#instance-method-hydrated[`.hydrated()`] call maps each return record to a `Movie` object according to `movieRules.`

////
.A full example
[source, typescript]
----
import neo4j, {Rules, rule, MappedQueryResult, Node} from 'neo4j-driver'

class Movie {
  title: string
  release?: number
  constructor(title: string, release: number) {
    this.title = title
    this.release = release
  }
};

const movieRules: Rules = {
  title: rule.asString({}),
  release: rule.asNumber({ isInteger: true, optional: true, from: "released" })
};

(async () => {

  // URI examples: 'neo4j://localhost', 'neo4j+s://xxx.databases.neo4j.io'
  const URI = '<database-uri>'
  const USER = '<username>'
  const PASSWORD = '<password>'
  let driver = neo4j.driver(URI, neo4j.auth.basic(USER, PASSWORD))

  let res = await driver.executeQuery<MappedQueryResult<Movie>>(`
    MERGE (m:Movie {title: "Cloud atlas", released: 2013})
    RETURN m.title AS title, m.released AS released
    `, {},
    {resultTransformer: neo4j.resultTransformers.hydrated(Movie, movieRules)}
  )

  console.log(res.records[0])
  // Movie { title: 'Cloud atlas', release: 2013 }

  await driver.close()

})().catch((e: Error) => {
  console.log(e)
});
----
////

[[queries-nodes-rels]]
=== Queries returning nodes or relationships

For queries returning graph entities (nodes/relationships), you need two classes: one with the inner properties of the node (ex. `Movie`), and one wrapping the node object itself (ex. `MovieNode`), which references the first class.

.Class definitions
[source, typescript]
----
class Movie { // <1>
  title: string
  release?: number
  constructor(title: string, release: number) {
    this.title = title
    this.release = release
  }
};
class MovieNode { // <1>
  movie: Movie
  constructor(movie: Movie) {
    this.movie = movie
  }
};
----

<.> Each record from the query result must conform to the `MovieNode` class definition, and the contents of nodes must conform to the `Movie` class. The mapper invokes class constructors with all arguments set to undefined and then populates them later, so don't rely on constructors to manipulate attributes.

.Mapping definitions
[source, typescript]
----
const movieRules: Rules = { // <1>
  title: rule.asString({}),
  release: rule.asNumber({ isInteger: true, optional: true, from: "released" }) // <2>
};
const movieNodeRules: Rules = { // <1>
  movie: rule.asNode({
    convert: (node:  Node) => node.as(Movie, movieRules)
  }),
};
----

<.> `movieRules` and `movieNodeRules` are map-like objects holding the typed mappings between the JavaScript class definitions and the database schema. Properties are specified via link:https://neo4j.com/docs/api/javascript-driver/current/variable/index.html#static-variable-rule[`rule`] calls.
<.> Type-specific (optional) attributes allow you to tweak the mapping behavior. For example, `release` is set to be optional, will automatically be converted from an integer in the database to a JavaScript number on the client, and is matched to the node property `released` even if the class attribute is called differently. For more information on allowed parameters, see link:https://neo4j.com/docs/api/javascript-driver/current/variable/index.html#static-variable-rule[API docs -> `rule`].

.Query execution
[source, typescript]
----
let res = await driver.executeQuery<MappedQueryResult<MovieNode>>( // <.>
  `MERGE (m:Movie {title: "Cloud atlas", released: 2013}) RETURN m AS movie`,
  {},
  {resultTransformer: neo4j.resultTransformers.hydrated(MovieNode, movieNodeRules)} // <.>
)

console.log(res.records[0])
// MovieNode { movie: Movie { title: 'Cloud atlas', release: 2013 } }
----

<.> The return type `MappedQueryResult<MovieNode>` is optional. If given, it must match the type provided in the `.hydrated()` call later.
<.> The link:https://neo4j.com/docs/api/javascript-driver/current/class/lib6/result-transformers.js~ResultTransformers.html#instance-method-hydrated[`.hydrated()`] call maps each return record to a `MovieNode` object according to `movieNodeRules.`

////
.A full example
[source, typescript]
----
import neo4j, {Rules, rule, MappedQueryResult, Node} from 'neo4j-driver'

class Movie {
  title: string
  release?: number
  constructor(title: string, release: number) {
    this.title = title
    this.release = release
  }
};
class MovieNode {
  movie: Movie
  constructor(movie: Movie) {
    this.movie = movie
  }
};

const movieRules: Rules = {
  title: rule.asString({}),
  release: rule.asNumber({ isInteger: true, optional: true, from: "released" })
};
const movieNodeRules: Rules = {
  movie: rule.asNode({
    convert: (node:  Node) => node.as(Movie, movieRules)
  }),
};

(async () => {

  // URI examples: 'neo4j://localhost', 'neo4j+s://xxx.databases.neo4j.io'
  const URI = '<database-uri>'
  const USER = '<username>'
  const PASSWORD = '<password>'
  let driver = neo4j.driver(URI, neo4j.auth.basic(USER, PASSWORD))

  let res = await driver.executeQuery<MappedQueryResult<MovieNode>>( // <.>
    `MERGE (m:Movie {title: "Cloud atlas", released: 2013}) RETURN m AS movie`,
    {},
    {resultTransformer: neo4j.resultTransformers.hydrated(MovieNode, movieNodeRules)} // <.>
  )

  console.log(res.records[0])
  // MovieNode { movie: Movie { title: 'Cloud atlas', release: 2013 } }

  await driver.close()

})().catch((e: Error) => {
  console.log(e)
});
----
////

[[queries-objects]]
=== Queries returning objects

With `rule.asObject()` you can create mappings for results returning subsets of properties.
Excluding some properties from return can save bandwidth, especially if the nodes contain large properties (such as vectors) which are not relevant for the mapping.

.Class definitions
[source, typescript]
----
class Person {
  name: string
  born?: number
  constructor(name: string, born: number) {
    this.name = name
    this.born = born
  }
};
class Movie {
  title: string
  release?: number
  constructor(title: string, release: number) {
    this.title = title
    this.release = release
  }
};
class Roles {
  roleNames: string[]
  constructor(roleNames: string[]) {
    this.roleNames = roleNames
  }
};
class ActingJob {
  person: Person
  movie: Movie
  roles: Roles
  constructor(person: Person, movie: Movie, roles: Roles) {
      this.person = person
      this.movie = movie
      this.roles = roles
  }
};
----

Properties for each objects are specified via link:https://neo4j.com/docs/api/javascript-driver/current/variable/index.html#static-variable-rule[`rule`] calls.

.Mapping definitions
[source, typescript]
----
const personRules: Rules = {
    name: rule.asString(),
    born: rule.asNumber({ isInteger: true, optional: true })
};
const movieRules: Rules = {
    title: rule.asString({}),
    release: rule.asNumber({ isInteger: true, optional: true, from: "released" }),
};
const rolesRules = {
    roleNames: rule.asList({apply: rule.asString(), from: "roles"})
};
const actingRules: Rules = {
  person: rule.asObject(Person, personRules),
  movie: rule.asObject(Movie, movieRules),
  roles: rule.asObject(Roles, rolesRules),
  costars: rule.asList({
    apply: rule.asObject(Person, personRules), // <.>
  })
};
----

<.> The `.asList()` rule applies the rule given in its `apply` parameter to every entry in the list. Here, each `costars` entry is made into a `Person` object.

.Query execution
[source, typescript]
----
let res = await driver.executeQuery<MappedQueryResult<ActingJob>>(` // <.>
  MATCH (p:Person)-[r:ACTED_IN]->(m:Movie)
  RETURN
    {name: p.name, born: p.born} AS person,
    {roles: r.roles} AS roles,
    {released: m.release, title: m.title} AS movie,
    COLLECT({name: c.name, born: c.born}) AS costars
  `, {},
  {resultTransformer: neo4j.resultTransformers.hydrated(ActingJob, actingRules)} // <.>
)

console.log(res.records[0])
----

<.> The return type `MappedQueryResult<ActingJob>` is optional. If given, it must match the type provided in the `.hydrated()` call later.
<.> The link:https://neo4j.com/docs/api/javascript-driver/current/class/lib6/result-transformers.js~ResultTransformers.html#instance-method-hydrated[`.hydrated()`] call maps each return record to a `ActingJob` object according to `actingRules.`

[[drivers-apis]]
== Mapping with different driver's APIs

[[driver-executequery]]
=== Usage with driver.executeQuery()

[source, typescript]
----
await driver.executeQuery<MappedQueryResult<movieNode>>(
    `MERGE (m:Movie {title: "Cloud atlas", released: 2013}) RETURN m AS movie`
    {},
    {resultTransformer: neo4j.resultTransformers.hydrated(movieNode, movieNodeRules)}
)
----

[[driver-tx-func]]
=== Usage with transaction functions

[source, typescript]
----
await session.executeRead(async (tx) => {
    return await tx.run(
      `MERGE (m:Movie {title: "Cloud atlas", released: 2013}) RETURN m AS movie`
    ).as(movieNode, movieNodeRules) // <.>
});
----

<.> The `Result` is converted to a `MappedResult<movieNode>` and can be consumed, subscribed to, or awaited like a normal result. The difference is that `Record` objects are replaced with `movieNode` objects.

[[driver-session-run]]
=== Usage with session.run()

[source, typescript]
----
await session.run(
    `MERGE (m:Movie {title: "Cloud atlas", released: 2013}) RETURN m AS movie`
).as(movieNode, movieNodeRules) // <.>
----

<.> The `Result` is converted to a `MappedResult<movieNode>` and can be consumed, subscribed to, or awaited like a normal result. The difference is that `Record` objects are replaced with `movieNode` objects.

[[write]]
== Write to the database

The Object Mapping rules also function for Object Parameter Mapping, allowing the same rules used to map records into object to be used to map objects to query parameters.

If a domain object is a simple JavaScript object with all the properties in the correct format to be sent as parameters there is no need for any mapping to occur, but if temporal data is stored as Neo4j temporal types in the database but used as strings in client code, or if a Domain Object includes functions or properties which can not or should not be sent as parameters, the mapping rules can assist in sanitizing the data for transmission.

[source, typescript]
----
class TestObj {
    number: number
    string: string
    date: string
    list: string[]
    constructor(number: number, string: string, date: string, list: string[]) {
        this.number = number
        this.string = string
        this.date = date
        this.list = list
    }
    function() {
        return "function string"
    } // the driver cannot send functions over bolt
}
const rules = {
    number: neo4j.rule.asNumber({isInteger: true}),
    string: neo4j.rule.asString(),
    date: neo4j.rule.asDate({stringify: true}), // this will ensure date is stored as a Date in the DB and retrieved as a string
    list: neo4j.rule.asList({ apply: neo4j.rule.asString() }),
    function: {
        parameterConversion: () => undefined, // explicitly skips the function when sending parameters
        optional: true // Record mapping will attempt to get all properties of the object from the Record, we need to explicitly mark that it's okay that there is no function. This is not needed if this is only mapped to parameter objects, and never used to map Records to TestObjs
    },
}

neo4j.RecordObjectMapping.register(TestObj, rules) // Register the rules object to the TestObj class

const res = await driver.executeQuery<MappedQueryResult<TestObj>>(
    'RETURN $string as string, $number as number, $big_int as big_int, $date as date, $dob as dob, $list as list',
    new TestObj(1, "hello", "2026-09-02", ["good", "bye"]), // executeQuery automatically applies the TestObj rules to this object.
    {resultTransformer: neo4j.resultTransformers.hydrated(TestObj)})
----

[[mapping-behavior]]
== Mapping behavior

- The mapper invokes class constructors with all arguments set to undefined and then populates them later, so don't rely on constructors to manipulate attributes.
- You can create custom `Rule` objects performing more advanced type validation or conversions. The `Rule` type is exported by the driver; for more information see link:[API docs -> `Rule`].
- global state

=== Registering per-type default rules.
In the examples above, both `ActingJob` and `actingJobRules` have been provided together, which requires these rules to be available in every part of the code where a query is run.

The following code registers the rules to the object, meaning the rules do not need to be provided when using Object Mapping except to override the default.
[source, typescript]
----
recordObjectMapping.register(ActingJob, actingJobRules)
----

This includes inside the rules themselves. When writing the `actingJobRules`, we had to set the rule for the `person` property as
[source, typescript]
----
person: rule.asNode({
        convert: (node: Node) => node.as(Person, personRules)
    })
----
however, if we know we have registed `personRules` to `Person` with `recordObjectMapping.register(ActingJob, actingJobRules)` we can replace that with:
[source, typescript]
----
person: rule.asNode({
        convert: (node: Node) => node.as(Person)
    })
----


// Alternatively, the rules can be registered in the mapping registry.
// This registry exists in global memory and will persist even between driver instances.

neo4j.RecordObjectMapping.register(Person, PersonRules)

// after registering the rule the transformer will follow them when mapping to the provided type
const summary = await driver.executeQuery('CREATE (p:Person{ name: $name }) RETURN p', { name: 'Person1'}, {
  resultTransformer: neo4j.resultTransformers.hydrated(Person)
})
