= Performance recommendations

[[target-database]]
== Always specify the target database

*Specify the target database on all queries* using the `database` parameter, both in xref:query-simple.adoc[`Driver.executeQuery()`] calls and when creating new xref:transactions.adoc[sessions].
If no database is provided, the driver has to send an extra request to the server to figure out what the default database is.
The overhead is minimal for a single query, but becomes significant over hundreds of them.

[discrete]
=== Good practices

[source, javascript]
----
await driver.executeQuery('<QUERY>', {}, {database: '<database-name>'})
----

[source, javascript]
----
driver.session({database: '<database-name>'})
----

[discrete]
=== Bad practices

[source, javascript]
----
await driver.executeQuery('<QUERY>')
----

[source, javascript]
----
driver.session()
----


[[transactions-cost]]
== Be aware of the cost of transactions

When submitting queries through xref:query-simple.adoc[`.executeQuery()`] or through xref:transactions.adoc#managed-transactions[`.executeRead/Write()`], the driver wraps them into a <<transaction>>.
This behavior ensures that the database always ends up in a consistent state, regardless of what happens during the execution of a transaction (power outages, software crashes, etc).
As a further robustness layer, the driver also retries failed transactions with an exponential backoff.

Creating a safe execution context around a query yields an overhead that is small, but that adds up as the number of transactions increases.
When each query is sent as a transaction of its own, if one transaction fails and needs to be rolled back, all the other transactions are unaffected.
This is the safest mode of execution with respect to failures, but also the slowest due to the overhead of transactions scaling with the number of queries.

.Each query as a separate transaction (low throughput)
[source, javascript]
----
for(let i=0; i<1000; i++) {
    await driver.executeQuery("<QUERY>", {}, {database: '<database-name>'})
    // or session.executeRead/Write() calls
}
----

A more performant approach is to group all queries into a single transaction.
In this way, the transaction as a whole is isolated from others, but individual queries in the transaction are not isolated, and failure of one results in a rollback of all queries.

.Group queries into one transaction (higher throughput)
[source, javascript]
----
let session = driver.session({ database: '<database-name>' })
await session.executeRead(async tx => {
  for(let i=0; i<1000; i++) {
    await tx.run('<QUERY>')
  }
})
----

An even faster approach is to skip `.executeRead/Write()` and call `.run()` directly on the session.
The queries run as auto-commit transactions, and are still isolated from other concurrent queries, but if any of them fail, they will not be retried.
With this method, you trade some robustness for more throughput, as the queries are shot to the server as fast as it can handle.
One upper limit on the client size is given by the size of the connection pool: each call to `.run()` borrows a connection, so the amount of parallel work is limited by the number of available connections.

.Queries as auto-commit transactions (highest throughput)
[source, javascript]
----
let session = driver.session({database: '<database-name>'})
for(let i=0; i<1000; i++) {
    await session.run("<QUERY>")
}
session.close()
----


[[read-mode]]
== Route read queries to cluster readers

In a cluster, *route read queries to any reader node*. You do this by:

- setting the xref:query-simple.adoc#_request_routing[`routing: READ` as configuration in `Driver.executeQuery()`] calls
- using `Session.executeRead()` instead of `Session.executeWrite()` (for managed transactions)
- setting xref:transactions.adoc#_request_routing[`AccessMode: neo4j.AccessModeRead` when creating a new session] (for explicit transactions).

[discrete]
=== Good practices

[source, javascript]
----
await driver.executeQuery(
  'MATCH (p:Person) RETURN p.name',
  {},
  {
    routing: 'READ',  // short for neo4j.routing.READ
    database: '<database-name>'
  }
)
----

[source, javascript]
----
let session = driver.session({ database: '<database-name>' })
await session.executeRead(async tx => {
  return await tx.run('MATCH (p:Person) RETURN p.name', {})
})
----


[discrete]
=== Bad practices

[source, javascript]
----
await driver.executeQuery(
  'MATCH (p:Person) RETURN p.name',
  {},
  {
    database: '<database-name>'
  }
)
// defaults to routing = writers
----

[source, javascript]
----
let session = driver.session({ database: '<database-name>' })
await session.executeRead(async tx => {
  return await tx.run('MATCH (p:Person) RETURN p.name', {})
})
// don't ask to write on a read-only operation
----


[[indexes]]
== Create indexes

*Create indexes for properties that you often filter against*.
For example, if you often look up `Person` nodes by the `name` property, it is beneficial to create an index on `Person.name`.
You can create indexes with the `CREATE INDEX` Cypher function, for both nodes and relationships.

[source, javascript]
----
// Create an index on Person.name
await driver.executeQuery('CREATE INDEX personName FOR (n:Person) ON (n.name)')
----

For more information, see link:{neo4j-docs-base-uri}/cypher-manual/current/indexes-for-search-performance/[Indexes for search performance].


include::{common-partial}/performance.adoc[tag=profile-queries]


[[node-labels]]
== Specify node labels

*Specify node labels* in all queries.
This allows the query planner to work more efficiently, and to leverage indexes where available.
To learn how to combine labels, see link:https://neo4j.com/docs/cypher-manual/current/patterns/reference/node-and-relationship-patterns/#label-expressions[Cypher -> Label expressions].

[discrete]
=== Good practices

[source, javascript]
----
await driver.executeQuery(
  'MATCH (p:Person|Animal {name: $name}) RETURN p',
  { name: 'Alice' }
)
----

[source, javascript]
----
let session = driver.session({database: '<database-name>'})
await session.run(
  'MATCH (p:Person|Animal {name: $name}) RETURN p',
  { name: 'Alice' }
)
----

[discrete]
=== Bad practices

[source, javascript]
----
await driver.executeQuery(
  'MATCH (p {name: $name}) RETURN p',
  { name: 'Alice' }
)
----

[source, javascript]
----
let session = driver.session({database: '<database-name>'})
await session.run(
  'MATCH (p {name: $name}) RETURN p',
  { name: 'Alice' }
)
----


[[batch-data-creation]]
== Batch data creation

*Batch queries when creating a lot of records* using the link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/with/[`WITH`] and link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/unwind/[`UNWIND`] Cypher clauses.

[discrete]
=== Good practice

[source, javascript]
----
numbers = []
for(let i=0; i<10000; i++) {
  numbers.push({value: Math.random()})
}
await driver.executeQuery(`
    UNWIND $numbers AS node
    MERGE (:Number {value: node.value})
    `, { numbers: numbers }
)
----

[discrete]
=== Bad practice

[source, javascript]
----
for(let i=0; i<10000; i++) {
  await driver.executeQuery(
    'MERGE (:Number {value: $value})',
    { value: Math.random() }
  )
}
----

[TIP]
The most efficient way of performing a _first import_ of large amounts of data into a new database is the link:{neo4j-docs-base-uri}/operations-manual/current/tutorial/neo4j-admin-import/[`neo4j-admin database import`] command.
// source:  https://community.neo4j.com/t5/neo4j-graph-platform/improving-data-writing-efficiency-in-python/td-p/39520


[[query-parameters]]
== Use query parameters

*Use xref:query-simple#query-parameters[query parameters]* instead of hardcoding or concatenating values into queries.
This allows to leverage the database's query cache.

[discrete]
=== Good practices

[source, javascript]
----
await driver.executeQuery(
  'MATCH (p:Person {name: $name}) RETURN p',
  { name: 'Alice' }  // query parameters
)
----

[source, javascript]
----
let session = driver.session({database: '<database-name>'})
await session.run(
  'MATCH (p:Person {name: $name}) RETURN p',
  { name: 'Alice' }  // query parameters
)
----

[discrete]
=== Bad practices

[source, javascript]
----
await driver.executeQuery('MATCH (p:Person {name: "Alice"}) RETURN p')

let name = "Alice"
await driver.executeQuery('MATCH (p:Person {name: "' + name + '"}) RETURN p')
----

[source, javascript]
----
let session = driver.session({database: '<database-name>'})
await session.run(
  'MATCH (p:Person {name: "Alice"}) RETURN p',
  // or 'MATCH (p:Person {name: ' + name + '}) RETURN p'
  {}
)
----


[[concurrency]]
== Concurrency

*Use xref:query-async.adoc[asynchronous querying]*.
This is likely to be more impactful on performance if you parallelize complex and time-consuming queries in your application, but not so much if you run many simple ones.


[[merge]]
== Use `MERGE` for creation only when needed

The Cypher clause link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/merge/[`MERGE`] is convenient for data creation, as it allows to avoid duplicate data when an exact clone of the given pattern exists.
However, it requires the database to run _two_ queries: it first needs to link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/match/[`MATCH`] the pattern, and only then can it link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/create/[`CREATE`] it (if needed).

If you know already that the data you are inserting is new, avoid using `MERGE` and use `CREATE` directly instead -- this practically halves the number of database queries.


[[filter-notifications]]
== Filter notifications

xref:result-summary.adoc#_filter_notifications[Filter the category and/or severity of notifications] the server should raise.


ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::{common-partial}/glossary.adoc[]
include::../partials/glossary.adoc[]
endif::[]
