= Further query mechanisms

[[implicit-transactions]]
== Implicit (or auto-commit) transactions

[TIP]
Implicit transactions are the only ones that can be used for link:{neo4j-docs-base-uri}/cypher-manual/current/subqueries/subqueries-in-transactions[`CALL { ... } IN TRANSACTIONS`] queries.

Implicit transactions are the most basic and limited form of transactions.
The driver does **not** automatically retry implicit transactions, as it does instead for queries run with xref:query-simple.adoc[`Driver.executeQuery()`] and with xref:transactions#managed-transactions[managed transactions].
Implicit transactions should only be used when the other query interfaces do not fit the purpose, or for quick prototyping.

You run an implicit transaction with the method link:{neo4j-docs-base-uri}/api/javascript-driver/current/class/lib6/session.js~Session.html#instance-method-run[`Session.run()`], which returns a link:{neo4j-docs-base-uri}/api/javascript-driver/current/class/lib6/result.js~Result.html[`Result`] object.

[source, javascript]
----
let session = driver.session({database: '<database-name>'})
try {
  const result = await session.run(
    'MERGE (a:Person {name: $name})',
    { name: 'Alice'}
  )
} finally {
  await session.close()
}
----

Since the driver cannot figure out whether the query in a `session.run()` call requires a read or write session with the database, it defaults to write. If your implicit transaction contains read queries only, there is a performance gain in xref:transactions#_request_routing[making the driver aware] by setting the argument `defaultAccessMode` to `neo4j.session.READ` when creating the session.

[TIP]
You can run an implicit transaction with a xref:query-async.adoc#_reactive_api[reactive session] as well.


=== Import CSV files

The most common use case for using `Session.run()` is for importing large CSV files into the database with the link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/load-csv[`LOAD CSV`] Cypher clause, and preventing timeout errors due to the size of the transaction.

.Import CSV data into a Neo4j database
[source, javascript]
----
let session = driver.session({database: '<database-name>'})
try {
  let result = await session.run(`
    LOAD CSV FROM 'https://data.neo4j.com/bands/artists.csv' AS line
    CALL {
        WITH line
        MERGE (:Artist {name: line[1], age: toInteger(line[2])})
    } IN TRANSACTIONS OF 2 ROWS
  `)
  console.log(result.summary.counters.updates())
} finally {
  await session.close()
}
----

[NOTE]
While `LOAD CSV` can be a convenience, there is nothing _wrong_ in deferring the parsing of the CSV file to your JavaScript application and avoiding `LOAD CSV`.
In fact, moving the parsing logic to the application can give you more control over the importing process.
For efficient bulk data insertion, see xref:performance.adoc#batch-data-creation[Performance -> Batch data creation].

For more information, see link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/load-csv/[Cypher -> Clauses -> Load CSV].


=== Transaction configuration

You can exert further control on implicit transactions by providing an optional third parameter of type link:{neo4j-docs-base-uri}/api/javascript-driver/current/typedef/index.html#static-typedef-TransactionConfig[`TransactionConfig`] to `session.run()`.
The configuration allows to specify a query timeout and to attach metadata to the transaction.
For more information, see xref:transactions.adoc#_transaction_configuration[Transactions -- Transaction configuration].

[source, javascript]
----
let session = driver.session({database: '<database-name>'})
let result = await session.run(
  'MATCH (a:Person) RETURN count(a) AS people',
  {},  // query parameters
  { timeout: 5000, metadata: {'appName': 'peopleTracker'} }  // transactionConfig
)
----


== Dynamic values in property keys, relationship types, and labels

In general, you should not concatenate parameters directly into a query, but rather use xref:query-simple#query-parameters[query parameters].
There can however be circumstances where your query structure prevents the usage of parameters in all its parts.
In fact, although parameters work for literals and expressions, as well as link:https://neo4j.com/docs/cypher-manual/current/clauses/match/#dynamic-match[node labels and relationship types], they can't be used for property keys, so `MATCH (n) WHERE n.$param = 'something'` is invalid.


When using string concatenation, enclose the dynamic values in backticks and escape them yourself to protect against link:https://neo4j.com/developer/kb/protecting-against-cypher-injection/[Cypher injections].
Notice that Cypher processes Unicode, so take care of the Unicode literal `\u0060` as well.

.Manually escaping dynamic property keys before concatenation
[source, javascript]
----
let dangerousKey = 'name\\u0060'
// convert \u0060 to literal backtick, then escape backticks
let escapedKey = dangerousKey.replace(/\\u0060/g, '`').replace(/`/g, '``')

let result = await driver.executeQuery(
  'MATCH (p:Person {`' + escapedKey + '`: $name}) RETURN p.name',
  { name: 'Alice' },
  {database: '<database-name>'}
)
console.log(`Executed query: ${result.summary.query.text}`)
// MATCH (p:Person {`name```: $name}) RETURN p.name
----

Another workaround to avoid string concatenation is to use <<APOC>> procedures, such as link:{neo4j-docs-base-uri}/apoc/current/overview/apoc.merge/apoc.merge.node/[`apoc.merge.node`], which supports dynamic labels and property keys.

.Using `apoc.merge.node` to create a node with dynamic labels/property keys
[source, javascript]
----
let propertyKey = 'name'
let label = 'Person'
let result = await driver.executeQuery(
  'CALL apoc.merge.node($labels, $properties)',
  {labels: [label], properties: {property_key: 'Alice'}},
  {database: '<database-name>'}
)
----

[NOTE]
If you are running Neo4j in Docker, APOC needs to be enabled when starting the container.
See link:https://neo4j.com/docs/apoc/5/installation/#docker[APOC -> Installation -> Docker].


== Logging

When creating a `Driver` instance, you may optionally specify its logging configuration.

Logging is off by default.
To turn it on, specify the `logging` option when you initialize the driver.
As value, use the function `neo4j.logging.console()`, which logs to console and takes an optional parameter `level`. The logging level can be either `error`, `warn`, `info`, or `debug`.
Enabling one level automatically enables all higher priority ones, and its default is `info`.

.Creating a driver with logging of level `debug` to console
[source, javascript]
----
neo4j.driver(
  URI,
  neo4j.auth.basic(USER, PASSWORD),
  {  // driver config
    logging: neo4j.logging.console('debug')
  }
)
----

.Example of log output upon driver connection
[source, log]
----
1681215847749 INFO Routing driver 0 created for server address localhost:7687
1681215847765 INFO Routing table is stale for database: "neo4j" and access mode: "WRITE": RoutingTable[database=neo4j, expirationTime=0, currentTime=1681215847765, routers=[], readers=[], writers=[]]
1681215847773 DEBUG Connection [0][] created towards localhost:7687(127.0.0.1)
1681215847773 DEBUG Connection [0][] C: HELLO {user_agent: 'neo4j-javascript/5.3.0', ...}
1681215847778 DEBUG Connection [0][] S: SUCCESS {"signature":112,"fields":[{"server":"Neo4j/5.8.0","connection_id":"bolt-1782","hints":{"connection.recv_timeout_seconds":{"low":120,"high":0}}}]}
1681215847778 DEBUG Connection [0][bolt-1782] created for the pool localhost:7687
1681215847778 DEBUG Connection [0][bolt-1782] acquired from the pool localhost:7687
1681215847779 DEBUG Connection [0][bolt-1782] C: ROUTE {"address":"localhost:7687"} [] {"db":"neo4j"}
1681215847781 DEBUG Connection [0][bolt-1782] S: SUCCESS {"signature":112,"fields":[{"rt":{"servers":[{"addresses":["localhost:7687"],"role":"WRITE"},{"addresses":["localhost:7687"],"role":"READ"},{"addresses":["localhost:7687"],"role":"ROUTE"}],"ttl":{"low":300,"high":0},"db":"neo4j"}}]}
----

You may also specify a custom logger function, for example to log to a file.
In that case, the `logging` option expects two properties:

- `level`: either `error`, `warn`, `info`, or `debug`.
Enabling one level automatically enables all higher priority ones.
Defaults to `info`.
- `logger`: a function invoked when a message needs to be logged.
Takes `level, message` as input.

.Creating a driver with logging of level `error` to console
[source, javascript]
----
neo4j.driver(
  URI,
  neo4j.auth.basic(USER, PASSWORD),
  {  // driver config
    logging: {
      level: 'error',
      logger: (level, message) => console.log(level + ' ' + message)
    }
  }
)
----

You can find more information about logging in the link:{neo4j-docs-base-uri}/api/javascript-driver/current/function/index.html#static-function-driver[API documentation].


ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::{common-partial}/glossary.adoc[]
endif::[]
