= Run non-blocking asynchronous queries

The examples in xref:query-simple.adoc[Query the database] use the `async/await` syntax, which forces the driver to work synchronously.
When using `await` with a query, your application waits for the server to retrieve all query results and transmit them to the driver.
This is not a problem for most use cases, but for queries that have a long processing time or a large result set, asynchronous handling may speed up your application.

There are several ways of running asynchronous queries:

- *Asynchronous iteration* -- the query result is processed (iteratively) as quickly as your application can handle.
- *Promise API* -- the query result is returned as a link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises[`Promise`].
The promise is only resolved when the full result set is available to the driver.
Best suited for queries with a large server processing time, but the result of which you want to process in one go.
Your application receives the result in bulk, for eager consumption.
- *Streaming API* -- the query result is returned as a stream, so that each result record is processed as soon as it is available.
Best suited for queries where records processing is individual.
Your application receives the result in bits, for lazy consumption.
- *Reactive API* -- for reactive applications.

[INFO]
Processing inside transaction function, except for Promise

== Asynchronous iteration

The `Result` object supports link:https://javascript.info/async-iterators-generators[asynchronous iteration].
This allows your application to process data at its own pace, with the driver modulating the speed at which records are streamed from the server accordingly, applying <<backpressure>>.
With async iterators, you get the guarantee that your application does not receive data faster than it can process.

[source, javascript]
----
const session = driver.session()
try {
  const peopleRecords = session.executeWrite(async tx => {
    const result = session.run(  // <1>
      'MERGE (p:Person {name: $name}) RETURN p.name AS name',
      {name: 'Alice'}
    )
    records = []
    for await (const record of result) {  // <2>
      console.log(`Processing ${record.get('name')}`)
      records.push(record)
    }
    return records  // <3>
  })
} finally {
  await session.close()
}
----

<1> Run a query
<2> Process records with async iteration
<3> Return _processed_ results (and not the raw query result)

There are two important points to the usage of the async iterator:

- *you can async-iterate only _once_ per query result*. Once the result _cursor_ reaches the end of the stream, it does not rewind, so you cannot iterate over a result more than once. If you need to process the data more than once in your application, you have to manually store it in an auxiliary data structure (like a list, as above).
- *the processing of the result happens _inside_ the <<transaction_function>>*. You *should not* return the raw result out of the transaction function and _then_ iterate over it. That workflow only works with the xref:_promise_api[Promise API].


== Promise API

The Promise API allows you to run a query and receive the result as a link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises[`Promise`].
You can think of this query method as allowing you to specify a Cypher query and a number of callbacks that are asynchronously executed depending on the query outcome.

[source, javascript, role=nocollapse]
----
const session = driver.session({database: 'neo4j'})
const result = session.executeWrite(async tx => {  // <1>
  return tx.run(
    'MERGE (p:Person {name: $name}) RETURN p.name AS name',
    {name: 'Alice'}
  )
})
result.then(result => {  // <2>
  result.records.forEach(record => {
    console.log(record.get('name'))
  })
  return result
})
.catch(error => {  // <3>
  console.log(error)
})
.then(() => session.close())  // <4>
----

<1> Run a query
<2> Specify callback for successful runs, taking query result as input
<3> Specify callback for failed runs, taking driver error as input
<4> Specify callback to run regardless of query outcome

[TIP]
====
The default return value of `tx.run()` is a `Promise`.
If you prepend `await` to `tx.run()` as shown in xref:query-simple.adoc[Query the database], you effectively force your application to wait until the result is ready, and you obtain the corresponding of either `result` or `error` from the example above.
====


=== Combine multiple transactions

To run multiple queries within the same transaction, use `Promise.all()`.
It runs asynchronous operations concurrently, so you can submit multiple queries at the same time and wait for them all to finish.

.Retrieve people's names and assign each of them to the company Neo4j
[source, javascript]
----
const companyName = 'Neo4j'
const session = driver.session({database: 'neo4j'})
try {
  const names = await session.executeRead(async tx => {
    const result = await tx.run('MATCH (p:Person) RETURN p.name AS name')
    return result.records.map(record => record.get('name'))
  })

  const relationshipsCreated = await session.executeWrite(tx =>
    Promise.all(  // group together all Promises
      names.map(name =>
        tx.run(`
          MATCH (emp:Person {name: $personName})
          MERGE (com:Company {name: $companyName})
          MERGE (emp)-[:WORKS_FOR]->(com)
          `, { personName: name, companyName: companyName }
        )
        .then(result => result.summary.counters.updates().relationshipsCreated)
      )
    ).then(values => values.reduce((a, b) => a + b))  // aggregate results
  )

  console.log(`Created ${relationshipsCreated} employees relationships.`)
} finally {
  await session.close()
}
----


== Streaming API

The Streaming API allows you to run a query and receive results individually, as soon as the server has them ready.
You can specify a callback to process each record.
This API is particularly fit for cases in which it may take the server a different time to retrieve the different records, but you want to process each of them as soon as they are available.

[source, javascript, role=nocollapse]
----
const session = driver.session({database: 'neo4j'})
let peopleNames = []

session
  .run('MERGE (p:Person {name: $name}) RETURN p.name AS name', {  // <1>
    name: 'Alice'
  })
  .subscribe({  // <2>
    onKeys: keys => {  // <3>
      console.log('Result columns are:')
      console.log(keys)
    },
    onNext: record => {  // <4>
      console.log(`Processing ${record.get('name')}`)
      peopleNames.push(record.get('name'))
    },
    onCompleted: () => {  // <5>
      session.close() // returns a Promise
    },
    onError: error => {  // <6>
      console.log(error)
    }
  })
----

<1> Run a query
<2> Attach a handler to the result stream
<3> The `onKeys` callback receives the list of result columns
<4> The `onNext` callback is invoked every time a record is received
<5> The `onCompleted` callback is invoked when the transaction is over
<6> The `onError` is triggered in case of error


== Reactive API

Typical of reactive programming, in a reactive flow consumers control the rate at which they consume records from queries, and the driver in turn manages the rate at which records are requested from the server.
The reactive API is typically used in applications that are already oriented towards the reactive style.

[source, javascript]
----
const rxjs = require('rxjs');

const rxSession = driver.rxSession()  // <1>
const rxResult = rxSession.executeRead(tx => {
  return tx
    .run('MERGE (p:Person {name: $name}) RETURN p.name AS name', {  // <2>
      name: 'Alice'
    })
    .records()  // <3>
    .pipe(  // <4>
      rxjs.map(record => record.get('name')),
      //rxjs.materialize(),  // optional, turns outputs into Notifications
      rxjs.toArray()
    )
  })
rxResult.subscribe((name) => console.log(name))
----
<1> Obtain a reactive session
<2> Run a query
<3> Obtain an observable for result records
<4> Reactive processing

[NOTE]
The reactive API requires a link:{neo4j-docs-base-uri}/docs/api/javascript-driver/current/class/src/session-rx.js~RxSession.html[`RxSession`] and returns a link:{neo4j-docs-base-uri}/api/javascript-driver/current/class/src/result-rx.js~RxResult.html[`RxResult`].


ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::{common-partial}/glossary.adoc[]
include::../partials/glossary.adoc[]
endif::[]
