= Query the database

You can run a query against the database using <<Cypher>> and the method `Driver.executeQuery()`.

[TIP]
`Driver.executeQuery()` was introduced with the version 5.8 of the driver. +
For queries with earlier versions, see xref:transactions.adoc[Run your own transactions].

[NOTE]
====
Due to the usage of `async/await`, the examples in this page need to be wrapped in an `async` function. See xref:_a_full_example[a full example] if you are unsure how to do it.
====


== Write to the database

To create a node representing a person named `Alice`, use the Cypher clause link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/merge/[`MERGE`]:

.Create a node representing a `Person` named `Alice`
[source, javascript]
----
const { records, summary } = await driver.executeQuery(
  'MERGE (p:Person {name: $name})',  // <1>
   {name: 'Alice'}  // <2>
   {database: 'neo4j'}  // <3>
)
console.log(
  `Created ${summary.counters.updates().nodesCreated} nodes ` +
  `in ${summary.resultAvailableAfter} ms.`
)
----

where *(1)* specifies the Cypher query, *(2)* is an object of _query parameters_, and *(3)* specifies which database the query should be run against.

[NOTE]
`MERGE` creates a new node matching the requirements unless one already exists, in which case nothing is done.
For strict node creation, use the link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/create/[`CREATE`] clause.


== Read from the database

To retrieve information from the database, use the Cypher clause link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/match/[`MATCH`]:

.Retrieve all `Person` nodes
[source, javascript]
----
const { records, summary } = await driver.executeQuery(
  'MATCH (p:Person) RETURN p.name AS name'
  {},
  {database: 'neo4j'}
)
console.log(
  `The query \`${summary.query.text}\` ` +
  `returned ${records.length} nodes.\n`
)
for(let record of records) {
  console.log(`Person with name: ${record.get('name')}`)
  console.log(`Available properties for this node are: ${record.keys}\n`)
}
----

where `result.records` contains the actual result as a list of link:{neo4j-docs-base-uri}/api/javascript-driver/current/class/lib6/record.js~Record.html[`Record`] objects, and `result.summary` is a link:{neo4j-docs-base-uri}/api/javascript-driver/current/class/lib6/result-summary.js~ResultSummary.html[`ResultSummary`] object, containing a summary of execution from the server.


== Update the database

To update a node's information in the database, use the Cypher clauses link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/match/[`MATCH`] and link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/set/[`SET`]:

.Update node `Alice` to add an `age` property
[source, javascript]
----
const { _, summary } = await driver.executeQuery(`
  MATCH (p:Person WHERE p.name = $name)
  SET p.age = $age
  `, { name: 'Alice', age: 42 },
  {database: 'neo4j'}
)
console.log('Query counters:')
console.log(summary.counters.updates())
----

To create new nodes and relationships linking it to an already existing node, use a combination of the Cypher clauses `MATCH` and `MERGE`:

.Create a relationship `KNOWS` between `Alice` and `Bob`
[source, javascript]
----
const { records, summary } = await driver.executeQuery(`
  MATCH (p:Person WHERE p.name = $name)
  MERGE (friend:Person {name: $friendName})
  MERGE (p)-[:KNOWS]->(friend)
  `, { name: 'Alice', friendName: 'Bob' },
  {database: 'neo4j'}
)
console.log('Query counters:')
console.log(summary.counters.updates())
----

[WARNING]
====
It may feel tempting to create new relationships with a single `MERGE` clause, such as: +
`MERGE (:Person {name: "Alice"})-[:KNOWS]->(:Person {name: "Bob"})`. +
However, this would result in the creation of an _extra_ `Alice` node, so that you would end up with unintended duplicate records.
To avoid this, always break out a path creation: `MATCH` (or `MERGE`) the nodes you need, and use the resulting references to `MERGE` the relationship (as shown in the previous example).
See link:https://neo4j.com/developer/kb/understanding-how-merge-works/[Understanding how MERGE works].
====


== Delete from the database
To remove a node and any relationship attached to it, use the Cypher clause link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/delete/[`DETACH DELETE`]:

.Remove the `Alice` node
[source, javascript]
----
const { _, summary } = await session.executeQuery(`
  MATCH (p:Person WHERE p.name = $name)
  DETACH DELETE p
  `, { name: 'Alice' },
  {database: 'neo4j'}
)
console.log('Query counters:')
console.log(summary.counters.updates())
----


[#query-parameters]
== How to pass parameters to queries

*Do not hardcode or concatenate parameters directly into queries*.
Instead, always use placeholders and specify the link:{neo4j-docs-base-uri}/cypher-manual/current/syntax/parameters/[Cypher parameters] as keyword arguments or in a dictionary, as shown in the previous examples.
This is for:

1. *performance benefits*: Neo4j compiles and caches queries, but can only do so if the query structure is unchanged;
2. *security reasons*: link:https://neo4j.com/developer/kb/protecting-against-cypher-injection/[protecting against Cypher injection].

[NOTE]
There can be circumstances where your query structure prevents the usage of parameters in all its parts.
For those advanced use cases, see xref:query-advanced#_dynamic_values_in_property_keys_relationship_types_and_labels[Dynamic values in property keys, relationship types, and labels].


== Error handling

To avoid an error in one query crashing your application, you can wrap queries into `try/catch` blocks.
We avoid proper error handling throughout this manual to make examples lighter to parse, and because appropriate error handling depends on the application.
Here below an example with a `try/catch/finally` block.

[source, javascript]
----
try {
  const result = await session.executeQuery('MATCH (p:Person) RETURN p')
} catch(err) {
  console.log(`Error in query\n${error}`)
} finally {
  await session.close()
}
----

[TIP]
The driver automatically retries to run a failed query, if the failure is deemed to be transient (for example due to temporary server unavailability).


== Query configuration

You can supply a link:{neo4j-docs-base-uri}/api/javascript-driver/current/class/lib6/driver.js~QueryConfig.html[`QueryConfig`] object as third (optional) parameter to alter the default behavior of `.executeQuery()`.


=== Database selection

It is recommended to *always specify the database explicitly* with the `database` parameter, even on single-database instances.
This allows the driver to work more efficiently, as it does not have to resolve the home database first.
If no database is given, the link:{neo4j-docs-base-uri}/operations-manual/current/manage-databases/introduction#manage-databases-default[user's home database] is used.

[source, javascript]
----
driver.executeQuery(
  'MATCH (p:Person) RETURN p.name',
  {},
  {
    database: 'neo4j'
  }
)
----


=== Request routing

In a cluster environment, all queries are directed to the leader node by default.
To improve performance on read queries, you can use the configuration `routing: 'READ'` to route a query to the read nodes.

[source, javascript]
----
driver.executeQuery(
  'MATCH (p:Person) RETURN p.name',
  {},
  {
    routing: 'READ',  // short for neo4j.routing.READ
    database: 'neo4j'
  }
)
----

Routing a _write_ query to `READ` nodes will likely result in a runtime error, but xref:transactions#access-control-note[do not rely on this for security purposes].


[#impersonation]
=== Run queries as a different user

You can execute a query under the security context of a different user with the parameter `impersonatedUser`, specifying the name of the user to impersonate.
For this to work, the user under which the `Driver` was created needs to have the link:{neo4j-docs-base-uri}/cypher-manual/current/administration/access-control/dbms-administration#access-control-dbms-administration-impersonation[appropriate permissions].
Impersonating a user is cheaper than creating a new `Driver` object.

[source, javascript]
----
driver.executeQuery(
  'MATCH (p:Person) RETURN p.name',
  {},
  {
    impersonatedUser: 'somebodyElse',
    database: 'neo4j'
  }
)
----

When impersonating a user, the query is run within the complete security context of the impersonated user and not the authenticated user (i.e., home database, permissions, etc.).


== A full example

[source, javascript]
----
const neo4j = require('neo4j-driver');

(async () => {
  const URI = 'neo4j://localhost'
  const USER = 'neo4j'
  const PASSWORD = 'verysecret'
  let driver, result

  let people = [{name: 'Alice', age: 42, friends: ['Bob', 'Peter', 'Anna']},
                {name: 'Bob', age: 19},
                {name: 'Peter', age: 50},
                {name: 'Anna', age: 30}]

  // Connect to database
  try {
    driver = neo4j.driver(URI,  neo4j.auth.basic(USER, PASSWORD))
    await driver.verifyConnectivity()
  } catch(err) {
    return
    console.log(`Connection error\n${err}\nCause: ${err.cause}`)
  }

  // Create some nodes
  for(let person of people) {
    await driver.executeQuery(
      'MERGE (p:Person {name: $person.name, age: $person.age})',
      { person: person }
    )
  }

  // Create some relationships
  for(let person of people) {
    if(person.friends != undefined) {
      await driver.executeQuery(`
        MATCH (p:Person {name: $person.name})
        UNWIND $person.friends AS friendName
        MATCH (friend:Person {name: friendName})
        MERGE (p)-[:KNOWS]->(friend)
        `, { person: person }
      )
    }
  }

  // Retrieve Alice's friends who are under 40
  result = await driver.executeQuery(`
    MATCH (p:Person {name: $name})-[:KNOWS]-(friend:Person)
    WHERE friend.age < $age
    RETURN friend
    `, { name: 'Alice', age: 40 }
  )

  // Loop through results and do something with them
  for(let person of result.records) {
    // `person.friend` is an object of type `Node`
    console.log(person.get('friend'))
  }

  // Summary information
  console.log(
    `The query \`${result.summary.query.text}\` ` +
    `returned ${result.records.length} records ` +
    `in ${result.summary.resultAvailableAfter} ms.`
  )

  await driver.close()
})();
----


ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::{common-partial}/glossary.adoc[]
include::../partials/glossary.adoc[]
endif::[]
