= Explore the query execution summary

After all records of a query result have been processed, the server ends the transaction by returning a summary of execution.
It comes as a link:{neo4j-docs-base-uri}/api/javascript-driver/current/class/lib6/result-summary.js~ResultSummary.html[`ResultSummary`] object, and it contains information among which:

- xref:_query_counters[**Query counters**] -- What changes the query triggered on the server
- xref:_query_execution_plan[**Query execution plan**] -- How the database would execute (or executed) the query
- xref:_notifications[**Notifications**] -- Extra information raised by the server while running the query
- Timing information and query request summary


== Retrieve the execution summary

When running queries with xref:query-simple.adoc[`Driver.executeQuery()`], the execution summary is part of the default return value, as second object.

[source, javascript]
----
let { records, summary } = await driver.executeQuery(`
  UNWIND ['Alice', 'Bob'] AS name
  MERGE (p:Person {name: name})
  `, {},
  { database: '<database-name>' }
)
// or summary = (await driver.executeQuery('<QUERY>')).summary
----

If you are using xref:transactions.adoc[transaction functions], you can retrieve the query execution summary with the attribute `Result.summary` if you used `await` to resolve the result promise, or with the method `Result.summary()` if you consumed the result as a promise.

**Notice that once you ask for the execution summary, the result stream is __exhausted__**: any record yet to be processed is not available anymore.

[source, javascript]
----
let session = driver.session({ database: '<database-name>' })
try {
  let summary = await session.executeWrite(async tx => {
    let result = await tx.run(`
        UNWIND ['Alice', 'Bob'] AS name
        MERGE (p:Person {name: name})
    `)
    return result.summary
    // or result.summary(), if you don't await tx.run()
  })
} finally {
  session.close()
}
----


== Query counters

The property `ResultSummary.counters` contains counters for the operations that a query triggered (as a link:{neo4j-docs-base-uri}/api/javascript-driver/current/class/lib6/result-summary.js~QueryStatistics.html[`QueryStatistics`] object).

.Insert some data and display the query counters
[source, javascript, role=nocollapse]
----
let { records, summary } = await driver.executeQuery(`
  UNWIND ['Alice', 'Bob'] AS name
  MERGE (p:Person {name: name})
  `, {},
  { database: '<database-name>' }
)
console.log(summary.counters.updates())
/*
{
  nodesCreated: 2,
  nodesDeleted: 0,
  relationshipsCreated: 0,
  relationshipsDeleted: 0,
  propertiesSet: 0,
  labelsAdded: 1,
  labelsRemoved: 0,
  indexesAdded: 0,
  indexesRemoved: 0,
  constraintsAdded: 0,
  constraintsRemoved: 0
}
*/
console.log(summary.counters.containsUpdates())  // true
console.log(summary.counters.containsSystemUpdates())  // false
----

Two additional methods on `ResultSummary.counters` act as meta-counters:

- `.containsUpdates()` -- whether the query triggered any write operation on the database on which it ran
- `.containsSystemUpdates()` -- whether the query triggered any write operation on the `system` database


== Query execution plan

If you prefix a query with `EXPLAIN`, the server returns the plan it _would_ use to run the query, but doesn't actually run it.
The plan is then available as a link:{neo4j-docs-base-uri}/api/javascript-driver/current/class/lib6/result-summary.js~Plan.html[`Plan`] object under the property `ResultSummary.plan`, and contains the list of link:https://neo4j.com/docs/cypher-manual/current/planning-and-tuning/operators/[Cypher operators] that would be used to retrieve the result set.
Use this information to locate bottlenecks or potential performance improvements (for example through the creation of indexes).

[source, javascript]
----
let result = await driver.executeQuery('EXPLAIN MATCH (p {name: $name}) RETURN p', { name: 'Alice' })
console.log(result.summary.plan.arguments['string-representation'])
/*
Planner COST
Runtime PIPELINED
Runtime version 5.0
Batch size 128

+-----------------+----------------+----------------+---------------------+
| Operator        | Details        | Estimated Rows | Pipeline            |
+-----------------+----------------+----------------+---------------------+
| +ProduceResults | p              |              1 |                     |
| |               +----------------+----------------+                     |
| +Filter         | p.name = $name |              1 |                     |
| |               +----------------+----------------+                     |
| +AllNodesScan   | p              |             10 | Fused in Pipeline 0 |
+-----------------+----------------+----------------+---------------------+

Total database accesses: ?
*/
----

If you instead prefix a query with the keyword `PROFILE`, the server returns the execution plan it has used to run the query, together with profiler statistics.
This includes the list of operators that were used and additional profiling information about each intermediate step.
The plan is available under the property `ResultSummary.profile`.
Notice that the query is also _run_, so the result object also contains any result records.

[source, javascript]
----
let result = await driver.executeQuery('PROFILE MATCH (p {name: $name}) RETURN p', { name: 'Alice' })
console.log(result.summary.profile.arguments['string-representation'])
/*
Planner COST
Runtime PIPELINED
Runtime version 5.0
Batch size 128

+-----------------+----------------+----------------+------+---------+----------------+------------------------+-----------+---------------------+
| Operator        | Details        | Estimated Rows | Rows | DB Hits | Memory (Bytes) | Page Cache Hits/Misses | Time (ms) | Pipeline            |
+-----------------+----------------+----------------+------+---------+----------------+------------------------+-----------+---------------------+
| +ProduceResults | p              |              1 |    1 |       3 |                |                        |           |                     |
| |               +----------------+----------------+------+---------+----------------+                        |           |                     |
| +Filter         | p.name = $name |              1 |    1 |       4 |                |                        |           |                     |
| |               +----------------+----------------+------+---------+----------------+                        |           |                     |
| +AllNodesScan   | p              |             10 |    4 |       5 |            120 |                 9160/0 |   108.923 | Fused in Pipeline 0 |
+-----------------+----------------+----------------+------+---------+----------------+------------------------+-----------+---------------------+

Total database accesses: 12, total allocated memory: 184
*/
----

For more information and examples, see link:{neo4j-docs-base-uri}/cypher-manual/current/query-tuning/basic-example/#_profile_query[Basic query tuning].


== Notifications

After executing a query, the server can return link:{neo4j-docs-base-uri}/status-codes/current/notifications/[notifications] alongside the query result.
Notifications contain recommendations for performance improvements, warnings about the usage of deprecated features, and other hints about sub-optimal usage of Neo4j.

.An unbounded shortest path raises a performance notification
[.tabbed-example]
=====
[.include-with-GQL-status-code]
======

The property `ResultSummary.gqlStatusObjects` contains a list of link:https://neo4j.com/docs/api/javascript-driver/current/class/lib6/notification.js~GqlStatusObject.html[`GqlStatusObject`]s.
These are GQL-compliant status objects.

Some (but not all) `GqlStatusObjects` are notifications, whereas some report an _outcome_ status: `00000` for "success", `02000` for "no data", and `00001` for "omitted result".
`Summary.GqlStatusObjects()` always contains at least one entry, containing the outcome status.

[source, javascript]
----
let { records, summary } = await driver.executeQuery(`
  MATCH p=shortestPath((:Person {name: 'Alice'})-[*]->(:Person {name: 'Bob'}))
  RETURN p
  `, {},
  { database: '<database-name>' }
)
console.log(summary.gqlStatusObjects)
/*
[
  GqlStatusObject {
    gqlStatus: '02000',
    statusDescription: 'note: no data',
    diagnosticRecord: { OPERATION: '', OPERATION_CODE: '0', CURRENT_SCHEMA: '/' },
    position: undefined,
    severity: 'UNKNOWN',
    rawSeverity: undefined,
    classification: 'UNKNOWN',
    rawClassification: undefined,
    isNotification: false
  },
  GqlStatusObject {
    gqlStatus: '03N91',
    statusDescription: "info: unbounded variable length pattern. The provided pattern `(:Person {name: 'Alice'})-[*]->(:Person {name: 'Bob'})` is unbounded. Shortest path with an unbounded pattern may result in long execution times. Use an upper limit (e.g. `[*..5]`) on the number of node hops in your pattern.",
    diagnosticRecord: {
      OPERATION: '',
      OPERATION_CODE: '0',
      CURRENT_SCHEMA: '/',
      _classification: 'PERFORMANCE',
      _status_parameters: [Object],
      _severity: 'INFORMATION',
      _position: [Object]
    },
    position: { offset: 24, line: 2, column: 24 },
    severity: 'INFORMATION',
    rawSeverity: 'INFORMATION',
    classification: 'PERFORMANCE',
    rawClassification: 'PERFORMANCE',
    isNotification: true
  }
]
*/
----

======

[.include-with-neo4j-status-code]
======
label:deprecated[Deprecated in 6.0]

The property `ResultSummary.notifications` contains a list of link:{neo4j-docs-base-uri}/api/javascript-driver/current/class/lib6/notification.js~Notification.html[`Notification`] objects.

[source, javascript]
----
let { records, summary } = await driver.executeQuery(`
  MATCH p=shortestPath((:Person {name: 'Alice'})-[*]->(:Person {name: 'Bob'}))
  RETURN p
  `, {},
  { database: '<database-name>' }
)
console.log(summary.notifications)
/*
[
  Notification {
    code: 'Neo.ClientNotification.Statement.UnboundedVariableLengthPattern',
    title: 'The provided pattern is unbounded, consider adding an upper limit to the number of node hops.',
    description: 'Using shortest path with an unbounded pattern will likely result in long execution times. It is recommended to use an upper limit to the number of node hops in your pattern.',
    severity: 'INFORMATION',
    position: { offset: 24, line: 2, column: 22 },
    severityLevel: 'INFORMATION',
    rawSeverityLevel: 'INFORMATION',
    category: 'PERFORMANCE',
    rawCategory: 'PERFORMANCE'
  }
]
*/
----

======

=====


=== Filter notifications

By default, the server analyses each query for all categories and severity of notifications.
Use the parameters `minimumSeverityLevel` and/or `disabledCategories`/`disabledClassifications` to restrict the severity and/or category/classification of notifications that you are interested into.
There is a slight performance gain in restricting the amount of notifications the server is allowed to raise.
You can use any of those parameters either when creating a `Driver` instance, or when creating a session.

The severity filter applies to both Neo4j and GQL notifications.
Category and classification filters exist separately only due to the discrepancy in lexicon between GQL and Neo4j; both filters affect either form of notification though, so you should use only one of them.
From version 6.0, `disabledCategories` is deprecated.

You can disable notifications altogether by setting the minimum severity to `'OFF'`.

.Allow only `WARNING` notifications, but not of `HINT` or `GENERIC` classifications
[source, javascript]
----
// at driver level
let driver = neo4j.driver(
  URI,  neo4j.auth.basic(USER, PASSWORD), {
    notificationsFilter: {
      minimumSeverityLevel: 'WARNING',  // or 'OFF' to disable entirely
      disabledClassifications: ['HINT', 'GENERIC']  // filters categories as well
    }
  }
)

// at session level
let session = driver.session({
    database: '<database-name>',
    notificationsFilter: {
      minimumSeverityLevel: 'WARNING',  // or 'OFF' to disable entirely
      disabledClassifications: ['HINT', 'GENERIC']  // filters categories as well
    }
})
----
