= Run your own transactions

When xref:query-simple.adoc[querying the database with transaction functions], the driver automatically creates a *<<transaction>>*.
You can easily include multiple queries in a single transaction function, but to design more involved use-cases it is important to understand how transactions work within the driver.


== Obtain a session

Before running a transaction, you need to obtain a _session_.
Sessions act as concrete query channels between the driver and the server.
In particular, sessions borrow connections from the _connection pool_ as needed, and ensure <<causal consistency>> is enforced.

Sessions are created with the method link:{neo4j-docs-base-uri}/api/javascript-driver/current/class/lib6/driver.js~Driver.html#instance-method-session[`Driver.session()`].
It takes a single (optional) object parameter, with the property `database` allowing to specify the xref:_database_selection[target database].
For further parameters, see xref:_session_configuration[Session configuration].

[source,python]
----
session = driver.session({database: 'neo4j'})
----

Session creation is a lightweight operation, so sessions can be created and destroyed without significant cost.
Always xref:_close_sessions[close sessions] when you are done with them.

*Sessions are _not_ thread safe*: you can share the main `Driver` object across threads, but make sure each thread creates its own sessions.


[#managed-transactions]
== Run a managed transaction

A transaction can contain any number of queries.
As Neo4j is <<ACID>> compliant, *queries within a transaction will either be executed as a whole or not at all*: you cannot get a part of the transaction succeeding and another failing.
Use transactions to group together related queries which work together to achieve a single _logical_ database operation.

A managed transaction is created with the methods link:{neo4j-docs-base-uri}/api/javascript-driver/current/class/lib6/session.js~Session.html#instance-method-executeRead[`Session.executeRead()`] and link:{neo4j-docs-base-uri}/api/javascript-driver/current/class/lib6/session.js~Session.html#instance-method-executeRead[`Session.executeWrite()`], depending on whether you want to _retrieve_ data from the database or _alter_ it.
Both methods take a _transaction function_ callback *(1)*, which is responsible of actually carrying out the queries and processing the result.
Queries are specified with the link:{neo4j-docs-base-uri}/api/javascript-driver/current/class/lib6/transaction.js~Transaction.html#instance-method-run[`Transaction.run()`] method *(2)*, where you provide a Cypher query *(3)* and an object of query parameters *(4)* which returns a link:{neo4j-docs-base-uri}/api/javascript-driver/current/class/lib6/result.js~Result.html[`Result`] object.
You can then process the result records and query summary *(5)*.

.Retrieve people whose name starts with `Al`.
[source, javascript]
----
let session, result
session = driver.session({database: 'neo4j'})
result = await session.executeRead(async tx => { // <1>
  return await tx.run(`  // <2>
    MATCH (p:Person) WHERE p.name STARTS WITH $filter  // <3>
    RETURN p.name as name ORDER BY name
    `, {filter: 'Al'}  // <4>
  )
})

console.log(`The query \`${result.summary.query.text}\`\nreturned ${result.records.length} nodes.\n`)
for(let person in result.records) {  // <5>
  console.log(person)
}
----

*Do not hardcode or concatenate parameters directly into the query*.
Use xref:query-simple#query-parameters[query parameters] instead, both for performance and security reasons.

Within a transaction function, a `return` statement results in the transaction being committed, while the transaction is automatically rolled back if an exception is raised.

.A transaction with multiple queries, client logic, and potential roll backs.
[source, javascript]
----
(async () => {
  var neo4j = require('neo4j-driver')

  const URI = 'neo4j://localhost'
  const USER = 'neo4j'
  const PASSWORD = 'verysecret'
  let driver, session, result
  let employeeThreshold=10

  try {
    driver = neo4j.driver(URI, neo4j.auth.basic(USER, PASSWORD))
    await driver.verifyConnectivity()
  } catch(err) {
    console.log(`-- Connection error --\n${err}\n-- Cause --\n${err.cause}`)
    return
  }

  session = driver.session({database: 'neo4j'})
  for(let i=0; i<100; i++) {
    let name = `Neo-${i.toString()}`
    let orgId = await session.executeWrite(async tx => {
      let result, orgInfo

      // Create new Person node with given name, if not already existing
      await tx.run(`
        MERGE (p:Person {name: $name})
        RETURN p.name AS name
        `, {name: name}
      )

      // Obtain most recent organization ID and the number of people linked to it
      result = await tx.run(`
        MATCH (o:Organization)
        RETURN o.id AS id, COUNT{(p:Person)-[r:WORKS_FOR]->(o)} AS employeesN
        ORDER BY o.createdDate DESC
        LIMIT 1
      `)
      if(result.records.length > 0) {
        orgInfo = result.records[0]
      }

      if(orgInfo != undefined && orgInfo['employeesN'] == 0) {
        throw new Error('Most recent organization is empty.')
        // Transaction will roll back -> not even Person is created!
      }

      // If org does not have too many employees, add this Person to that
      if(orgInfo != undefined && orgInfo['employeesN'] < employeeThreshold) {
        result = await tx.run(`
          MATCH (o:Organization {id: $orgId})
          MATCH (p:Person {name: $name})
          MERGE (p)-[r:WORKS_FOR]->(o)
          RETURN $orgId AS id
          `, {orgId: orgInfo['id'], name: name}
        )

      // Otherwise, create a new Organization and link Person to it
      } else {
        result = await tx.run(`
          MATCH (p:Person {name: $name})
          CREATE (o:Organization {id: randomuuid(), createdDate: datetime()})
          MERGE (p)-[r:WORKS_FOR]->(o)
          RETURN o.id AS id
          `, {name: name, date: neo4j.DateTime.fromStandardDate(new Date())}
        )
      }

      // Return the Organization ID to which the new Person ends up in
      return result.records[0].get('id')
    })
    console.log(`User ${name} added to organization ${orgId}`)
  }
  await session.close()
  await driver.close()
})()
----

Should a transaction fail for a reason that the driver deems transient, it automatically retries to run the transaction function (with an exponentially increasing delay).
For this reason, *transaction functions must be _idempotent_* (i.e., they should produce the same effect when run several times), because you do not know upfront how many times they are going to be executed.
In practice, this means that you should not edit nor rely on globals, for example.
Note that although transaction functions might be executed multiple times, the queries inside it will always run only once.

A session can chain multiple transactions, but *only one single transaction can be active within a session at any given time*.
This means that a query must be completed before the next one can run, and it is the reason why the previous examples all use the `async/await` syntax.
To maintain multiple concurrent transactions, see xref:query-async.adoc[how to run non-blocking queries].


[#unit_of_work-decorator]
=== Further transaction function configuration

The decorator link:{neo4j-docs-base-uri}/api/python-driver/current/api.html#neo4j.unit_of_work[`unit_of_work()`] allows to exert further control on transaction functions.
It allows to specify:

- a transaction timeout (in seconds).
Transactions that run longer will be terminated by the server.
The default value is set on the server side.
- a dictionary of metadata that gets attached to the transaction.
These metadata get logged in the server `query.log`, and are visible in the output of the `SHOW TRANSACTIONS` Cypher command.
Use this to tag transactions.

[source,python]
----
from neo4j import unit_of_work

@unit_of_work(timeout=5, metadata={"app_name": "people"})
def count_people(tx):
    result = tx.run("MATCH (a:Person) RETURN count(a) AS people")
    record = result.single()
    return record["people"]


with driver.session(database="neo4j") as session:
    people_n = session.execute_read(count_people)
----


[#explicit-transactions]
== Run an explicit transaction

You can achieve full control over transactions by manually beginning one with the method link:{neo4j-docs-base-uri}/api/python-driver/current/api.html#neo4j.Session.begin_transaction[`Session.begin_transaction()`].
You run queries inside an explicit transaction with the method link:{neo4j-docs-base-uri}/api/python-driver/current/api.html#neo4j.Transaction.run[`Transaction.run()`].

[source,python]
----
with driver.session(database="neo4j") as session:
    with session.begin_transaction() as tx:
        # use tx.run() to run queries
----

Closing an explicit transaction can either happen automatically at the end of a `with` block, or can be explicitly controlled through the methods link:{neo4j-docs-base-uri}/api/python-driver/current/api.html#neo4j.Transaction.commit[`Transaction.commit()`], link:{neo4j-docs-base-uri}/api/python-driver/current/api.html#neo4j.Transaction.rollback[`Transaction.rollback()`], or link:{neo4j-docs-base-uri}/api/python-driver/current/api.html#neo4j.Transaction.close[`Transaction.close()`].

Explicit transactions are most useful for applications that need to distribute Cypher execution across multiple functions for the same transaction, or for applications that need to run multiple queries within a single transaction but without the automatic retries provided by managed transactions.

[source,python]
----
from os import sleep
import neo4j


def transfer_to_other_bank(driver, customer_id, other_bank_id, amount):
    with driver.session(database="neo4j") as session:
        tx = session.begin_transaction()
        # or just use a `with` context on `tx` instead of try/finally
        try:
            if not customer_balance_check(tx, customer_id, amount):
                # give up
                return

            other_bank_transfer_api(customer_id, other_bank_id, amount)
            # Now the money has been transferred => can't rollback anymore
            # (cannot rollback external services interactions)

            try:
                decrease_customer_balance(tx, customer_id, amount)
                tx.commit()
            except Exception as e:
                request_inspection(customer_id, other_bank_id, amount, e)
                raise  # roll back
        finally:
            tx.close()  # rolls back if not yet committed


def customer_balance_check(tx, customer_id, amount):
    query = ("""
        MATCH (c:Customer {id: $id})
        RETURN c.balance >= $amount AS sufficient
    """)
    result = tx.run(query, id=customer_id, amount=amount)
    record = result.single(strict=True)
    return record["sufficient"]


def other_bank_transfer_api(customer_id, other_bank_id, amount):
    ...
 # make some API call to other bank


def decrease_customer_balance(tx, customer_id, amount):
    query = ("""
        MATCH (c:Customer {id: $id})
        SET c.balance = c.balance - $amount
    """)
    result = tx.run(query, id=customer_id, amount=amount)
    result.consume()


def request_inspection(customer_id, other_bank_id, amount, e):
    # manual cleanup required; log this or similar
    print("WARNING: transaction rolled back due to exception:", repr(e))
    print("customer_id:", customer_id, "other_bank_id:", other_bank_id,
          "amount:", amount)

----


== Session configuration

=== Database selection

It is recommended to *always specify the database explicitly* with the `database` parameter, even on single-database instances.
This allows the driver to work more efficiently, as it does not have to resolve the home database first.
If no database is given, the link:{neo4j-docs-base-uri}/operations-manual/current/manage-databases/introduction#manage-databases-default[default database] set in the Neo4j instance settings is used.

[source, python]
----
import neo4j

with driver.session(
    database="neo4j"
) as session:
    ...
----


=== Request routing

In a cluster environment, all sessions are opened in write mode, routing them to the leader.
You can change this by explicitly setting the `default_access_mode` parameter to either `neo4j.READ_ACCESS` or `neo4j.WRITE_ACCESS`.
Note that `.execute_read()` and `.execute_write()` automatically override the session's default access mode.

[source, python]
----
import neo4j

with driver.session(
    database="neo4j",
    default_access_mode=neo4j.READ_ACCESS
) as session:
    ...
----

[#access-control-note]
[NOTE]
====
Although executing a _write_ query in read mode likely results in a runtime error, *you should not rely on this for access control.* The difference between the two modes is that _read_ transactions will be routed to any node of a cluster, whereas _write_ ones will be directed to the leader.
Still, depending on the server version and settings, the server might allow none, some, or all _write_ statements to be executed even in _read_ transactions.

Similar remarks hold for the `.execute_read()` and `.execute_write()` methods.
====


[#impersonation]
=== Run queries as a different user (impersonation)

You can execute a query under the security context of a different user with the parameter `impersonated_user`, specifying the name of the user to impersonate.
For this to work, the user under which the `Driver` was created needs to have the link:{neo4j-docs-base-uri}/cypher-manual/current/access-control/dbms-administration#access-control-dbms-administration-impersonation[appropriate permissions].
Impersonating a user is cheaper than creating a new `Driver` object.

[source, python]
----
with driver.session(
    database="neo4j",
    impersonated_user="somebody_else"
) as session:
    ...
----

When impersonating a user, the query is run within the complete security context of the impersonated user and not the authenticated user (i.e., home database, permissions, etc.).


== Close sessions

Each connection pool has *a finite number of sessions*, so if you open sessions without ever closing them, your application could run out of them.
It is thus recommended to create sessions using the `with` statement, which automatically closes them when the application is done with them.
When a session is closed, it is returned to the connection pool to be later reused.

If you do not use `with`, remember to call the `.close()` method when you have finished using a session.

[source,python]
----
session = driver.session(database="neo4j")
# ...
# session usage
# ...
session.close()
----

ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::{common-partial}/glossary.adoc[]
endif::[]
