:driver-changelog-url: https://github.com/neo4j/neo4j-javascript-driver/wiki/5.0-changelog

= Upgrade from older versions

include::{common-partial}/upgrade.adoc[tag=intro]


[[recommended-steps]]
== Recommended steps

Using the migration assistant, the recommended upgrade steps are:

1. Set up the environment for the assistant to work in.
Download the link:https://github.com/neo4j/drivers-migration-assistant/archive/refs/heads/dev.zip[Drivers Migration Assistant zip], extract it, and locate yourself in its directory.
Then, assuming `python3` and `pip3` are already installed,
+
[source, bash]
----
python3 -m venv virtualenvs/neo4j-migration
source virtualenvs/neo4j-migration/bin/activate
pip3 install -r requirements.txt
----

2. Run the migration assistant with its default configuration and address all the issues that it surfaces. The `path` argument supports link:https://www.man7.org/linux/man-pages/man7/glob.7.html[globbing], and can be repeated. +
+
[source, bash]
----
python3 main.py -l javascript /path/*.js /path-recursive/**/*.js
----

3. Re-run the assistant with the regex parser and check if any more legit issues are raised. +
+
[source, bash]
----
python3 main.py -l javascript --regex-parser /path/*.js /path-recursive/**/*.js
----
+
The regex parser can detect implicit function calls and other hard-to-parse expressions, but is likely to surface more false positives (for more information, see link:https://github.com/neo4j/drivers-migration-assistant?tab=readme-ov-file#accuracy[Neo4j Drivers Migration Assistant -> Accuracy]).
You can add any spurious entry to the ignored list, so that the assistant won't bring them up in future runs.

4. Although the assistant can detect most of the locations where action is needed, a few changelog entries can't be surfaced in this form, so you should still revise the xref:breaking-changes[breaking changes] section and audit your codebase for the changes marked with {cross-mark} in the table.

5. You are ready to upgrade the driver package to the new version. For example, using `npm`: +
+
[source, bash]
----
npm update neo4j-driver@5.27
----


[[new-features]]
== New features

[cols="1a,1a"]
|===

|
.`Driver.executeQuery()` to run transactions with less knowledge of driver's internals
[%collapsible]
====
The new function is a wrapper for `Session.executeRead/Write()`, but it abstracts away the result processing part and returns a list of records to the caller directly.

See xref:query-simple.adoc[].
====
|
.Explicit resource management to `Driver`, `Session`, `Transaction` objects
[%collapsible]
====
Possible to create link:https://github.com/neo4j/neo4j-javascript-driver/pull/1154[drivers, sessions], and link:https://github.com/neo4j/neo4j-javascript-driver/pull/1155[transactions] using the `await using` keywords and not have to close the resource when done. The resources will be automatically closed when leaving the block that instantiated it.
====

|
.Type mapping for records from queries
[%collapsible]
====
Returned records from queries can be mapped to specific interface definitions, allowing safe access to the record's properties.

See link:https://github.com/neo4j/neo4j-javascript-driver/pull/1010[Type mapping to `Result`, `Session.run`, and `Transaction.run`].
====
|
.Re-authentication
[%collapsible]
====
Allows for xref:connect-advanced.adoc#rotating-tokens[rotating authentication tokens] as well as xref:transactions.adoc#impersonation[session-scoped] and xref:query-simple.adoc#impersonation[query-scoped] authentication.
====

|
.Mutual TLS (mTLS) as second authentication factor (2FA)
[%collapsible]
====
Allows for configuring client side TLS certificates to authenticate against the server.

See xref:connect-advanced.adoc#mtls[Mutual TLS].
====
|
.`BookmarkManager` support
[%collapsible]
====
Bookmark managers make it easier to achieve causal chaining of sessions.

See xref:bookmarks.adoc[].
====

|
.Notification filtering API
[%collapsible]
====
Filtering allows to receive only a subset of notifications from the server, and to improve performance server-side.

See xref:result-summary.adoc#_filter_notifications[Explore the query execution summary -> Filter notifications].
====
|
.GQL statuses of queries in the `ResultSummary`
[%collapsible]
====
The property `ResultSummary.gqlStatusObjects` contains a sequence of `GqlStatusObject`, holding information about the execution of the query.

This API is planned to supersede the current notifications API.

See xref:result-summary.adoc#_notifications[Explore the query execution summary -> Notifications].
====

|
.Telemetry
[%collapsible]
====
The driver sends anonymous API usage statistics to the server.
Use the driver configuration `telemetryDisabled: true` to opt out.

See link:https://github.com/neo4j/neo4j-javascript-driver/pull/1142[Metrics/Telemetry].
====
|

|===


[[breaking-changes]]
== Breaking changes and deprecations

The column `Assistant` denotes whether the Neo4j Drivers Migration Assistant can detect issues related to the given changelog entry.
Entries with a cross mark {cross-mark} require manual inspection.

Deprecated features are likely to be removed in version 6.

[cols="1,5a,1,1"]
|===
|Version |Message |Status |Assistant

|5.0
|link:https://neo4j.com/docs/api/javascript-driver/{javascript-driver-version}/class/lib6/result-summary.js~ServerInfo.html[`ResultSummary.ServerInfo`] -- `ResultSummary.server.version` has been removed.
Use `ResultSummary.server.agent`, `ResultSummary.server.protocolVersion`, or call the link:https://neo4j.com/docs/operations-manual/current/reference/procedures/#procedure_dbms_components[`dbms.components`] Cypher procedure instead.
|label:removed[]
|{check-mark}

|5.0
|RxJS was bumped to 7.5.5. +
`concat` was replaced by `concatWith`, `flatMap` was replaced by `mergeMap`.
|label:removed[Changed]
|{cross-mark}

|5.0
|link:https://neo4j.com/docs/api/javascript-driver/{javascript-driver-version}/class/lib6/session.js~Session.html[`Session`] -- Methods `.readTransaction()` and `.writeTransaction()` are deprecated in favor of link:https://neo4j.com/docs/api/javascript-driver/{javascript-driver-version}/class/lib6/session.js~Session.html#instance-method-executeRead[`.executeRead()`] and link:https://neo4j.com/docs/api/javascript-driver/{javascript-driver-version}/class/lib6/session.js~Session.html#instance-method-executeWrite[`.executeWrite()`].
Through the new methods, the first argument of transaction functions is a `ManagedTransaction` object. It behaves like a regular `Transaction` object, except it does not offer the `.commit()`, `.rollback()`, `.close()`, and `.closed()` methods.
|label:deprecated[]
|{check-mark}

|5.0
|link:https://neo4j.com/docs/api/javascript-driver/{javascript-driver-version}/class/lib6/session.js~Session.html[`Session`] -- Method `.lastBookmark()` is deprecated in favor of link:https://neo4j.com/docs/api/javascript-driver/{javascript-driver-version}/class/lib6/session.js~Session.html#instance-method-lastBookmarks[`.lastBookmarks()`].
|label:deprecated[]
|{check-mark}

|5.0
|link:https://neo4j.com/docs/api/javascript-driver/{javascript-driver-version}/class/lib6/graph-types.js~Node.html[`Node`], link:https://neo4j.com/docs/api/javascript-driver/{javascript-driver-version}/class/lib6/graph-types.js~Relationship.html[`Relationship`] -- Property `.identity` (NumberOrInteger) is deprecated in favor of `.elementId` (String).
|label:deprecated[]
|{check-mark}

|5.0
|link:https://neo4j.com/docs/api/javascript-driver/{javascript-driver-version}/class/lib6/graph-types.js~Relationship.html[`Relationship`] -- Properties `.start` and `.end` are deprecated in favor of `.startNodeElementId` and `.endNodeElementId`. Old identifiers were `NumberOrInteger`, wereas new ElementIds are `string`.
|label:deprecated[]
|{check-mark}

|5.0
|link:https://neo4j.com/docs/api/javascript-driver/{javascript-driver-version}/class/lib6/driver.js~Driver.html[`Driver`] -- The return value of link:https://neo4j.com/docs/api/javascript-driver/{javascript-driver-version}/class/lib6/driver.js~Driver.html#instance-method-verifyConnectivity[`.verifyConnectivity()`] is deprecated. The method still exists, but returns void. To retrieve the server info, use link:https://neo4j.com/docs/api/javascript-driver/{javascript-driver-version}/class/lib6/driver.js~Driver.html#instance-method-getServerInfo[`.getServerInfo()`].
|label:deprecated[]
|{check-mark}

|5.7
|link:https://neo4j.com/docs/api/javascript-driver/{javascript-driver-version}/class/lib6/notification.js~Notification.html[`Notification`] -- Property `.severity` is deprecated. Use `.rawSeverityLevel` for the raw value and `.severityLevel` for an enumerated value.
|label:deprecated[]
|{check-mark}

|5.27
|link:https://neo4j.com/docs/api/javascript-driver/{javascript-driver-version}/class/lib6/result-summary.js~ResultSummary.html[`ResultSummary`] -- Property `.notifications` is deprecated in favor of `.gqlStatusObjects`. The replacement contains GQL-complaint statuses (link:https://neo4j.com/docs/api/javascript-driver/{javascript-driver-version}/class/lib6/notification.js~GqlStatusObject.html[`GqlStatusObject`]), which are a superset of the old notifications.
|label:deprecated[]
|{check-mark}

|===
