The Neo4j .NET driver is the official library to interact with a Neo4j instance through a .NET application.

At the hearth of Neo4j lies <<Cypher>>, the query language to interact with a Neo4j database.
While this guide does not _require_ you to be a seasoned Cypher querier, it is going to be easier to focus on the .NET-specific bits if you already know some Cypher.
For this reason, although this guide does _also_ provide a gentle introduction to Cypher along the way, consider checking out link:https://neo4j.com/docs/getting-started/cypher/[Getting started -> Cypher] for a more detailed walkthrough of graph databases modelling and querying if this is your first approach.
You may then apply that knowledge while following this guide to develop your .NET application.


== Installation

Add the Neo4j .NET driver to your project:

[source, bash]
----
dotnet add package Neo4j.Driver
----

The driver supports the .NET Standard 2.0.

xref:install#install-driver[More info on installing the driver ->]


== Connect to the database

Connect to a database by creating an <<IDriver>> object and providing a URL and an authentication token.
Once you have a `IDriver` instance, use the `.VerifyConnectivityAsync()` method to ensure that a working connection can be established.

[source, csharp]
----
using Neo4j.Driver;

// URI examples: "neo4j://localhost", "neo4j+s://xxx.databases.neo4j.io"
const string dbUri = "<URI for Neo4j database>";
const string dbUser = "<Username>";
const string dbPassword = "<Password>";

await using var driver = GraphDatabase.Driver(dbUri, AuthTokens.Basic(dbUser, dbPassword));
await driver.VerifyConnectivityAsync();
Console.WriteLine("Connection established.");
----

xref:connect.adoc[More info on connecting to a database ->]


== Query the database

Execute a Cypher statement with the method `IDriver.ExecutableQuery()`.
Do not hardcode or concatenate parameters: use placeholders and specify the parameters as a map through the `.WithParameters()` method.

[source, csharp]
----
// Get all 42-year-olds
var result = await driver
    .ExecutableQuery("MATCH (p:Person {age: $age}) RETURN p.name AS name")
    .WithConfig(new QueryConfig(database: "neo4j"))
    .WithParameters(new { age = 42 } )
    .ExecuteAsync();

// Loop through results and print people's name
foreach (var record in result.Result) {
    Console.WriteLine(record.Get<string>("name"));
}

// Summary information
var summary = result.Summary;
Console.WriteLine($"The query `{summary.Query.Text}` returned {result.Result.Count()} results in {summary.ResultAvailableAfter.Milliseconds} ms.");
----

xref:query-simple.adoc[More info on querying the database ->]


== Run your own transactions

For more advanced use-cases, you can run <<transaction,transactions>>.
Use the methods `IAsyncSession.ExecuteReadAsync()` and `IAsyncSession.ExecuteWriteAsync()` to run managed transactions.

.A transaction with multiple queries, client logic, and potential roll backs
[source, csharp]
----
using Neo4j.Driver;

const string dbUri = "<URI for Neo4j database>";
const string dbUser = "<Username>";
const string dbPassword = "<Password>";

await using var driver = GraphDatabase.Driver(dbUri, AuthTokens.Basic(dbUser, dbPassword));
await driver.VerifyConnectivityAsync();

// Create & employ 100 people to 10 different organizations
using var session = driver.AsyncSession(conf => conf.WithDatabase("neo4j"));
for (int i=0; i<100; i++) {
    var name = $"Thor{i}";
    try {
        string orgId = await session.ExecuteWriteAsync(async tx => {
            return await employPersonTx(tx, name);
        });
        Console.WriteLine($"User {name} added to organization {orgId}.");
    } catch (Neo4jException e) {
        Console.WriteLine(e);
    }
}

async Task<string> employPersonTx(IAsyncQueryRunner tx, string name) {
    var employeeThreshold = 10;

    // Create new Person node with given name, if not exists already
    await tx.RunAsync("MERGE (p:Person {name: $name})", new { name = name });

    // Obtain most recent organization ID and the number of people linked to it
    var result = await tx.RunAsync(@"
        MATCH (o:Organization)
        RETURN o.id AS id, COUNT{(p:Person)-[r:WORKS_FOR]->(o)} AS employeesN
        ORDER BY o.createdDate DESC
        LIMIT 1
        ");

    string orgId = "";
    int employeesN = 0;
    bool org = await result.FetchAsync();
    if (org == false) {
        // If no organization exists, create one and add Person to it
        orgId = await createOrganization(tx);
        Console.WriteLine($"No orgs available, created {orgId}.");
    } else {
        orgId = result.Current.Get<string>("id");
        employeesN = result.Current.Get<int>("employeesN");
    }

    // If org does not have too many employees, add this Person to it
    if (employeesN < employeeThreshold) {
        await addPersonToOrganization(tx, name, orgId);
        // If the above throws, the transaction will roll back
        // -> not even Person is created!

    // Otherwise, create a new Organization and link Person to it
    } else {
        orgId = await createOrganization(tx);
        Console.WriteLine($"Latest org is full, created {orgId}.");
        await addPersonToOrganization(tx, name, orgId);
        // If any of the above throws, the transaction will roll back
        // -> not even Person is created!
    }

    return orgId;  // Organization ID to which the new Person ends up in
}

async Task<string> createOrganization(IAsyncQueryRunner tx) {
    var result = await tx.RunAsync(@"
        CREATE (o:Organization {id: randomuuid(), createdDate: datetime()})
        RETURN o.id AS id
    ");
    bool org = await result.FetchAsync();  // can't be false
    string orgId = result.Current.Get<string>("id");
    return orgId;
}

async Task addPersonToOrganization(IAsyncQueryRunner tx, string personName, string orgId) {
    await tx.RunAsync(@"
        MATCH (o:Organization {id: $orgId})
        MATCH (p:Person {name: $name})
        MERGE (p)-[:WORKS_FOR]->(o)
        ", new { orgId = orgId, name = personName }
    );
}
----

xref:transactions.adoc[More info on running transactions ->]


== Close connections and sessions

Unless you created them with the `using` keyword, remember to close all `IDriver` and `IAsyncSession` instances to release any resources still held by them.

[source, csharp, test-skip]
----
await session.CloseAsync();
await driver.CloseAsync();
----


== API documentation

For in-depth information about driver features, check out the link:https://neo4j.com/docs/api/dotnet-driver/{dotnet-driver-version}/[API documentation].
