// This doc is also sourced in the Aura Developer Hub.
// Because of that, cross-links are absolute and
// source blocks have copy=true .

The Neo4j .NET driver is the official library to interact with a Neo4j instance through a .NET application.

At the hearth of Neo4j lies <<Cypher>>, the query language to interact with a Neo4j database.
While this guide does not _require_ you to be a seasoned Cypher querier, it is going to be easier to focus on the .NET-specific bits if you already know some Cypher.
For this reason, although this guide does _also_ provide a gentle introduction to Cypher along the way, consider checking out link:https://neo4j.com/docs/getting-started/cypher/[Getting started -> Cypher] for a more detailed walkthrough of graph databases modelling and querying if this is your first approach.
You may then apply that knowledge while following this guide to develop your .NET application.


[#install]
== Install

Add the Neo4j .NET driver to your project:

[source, bash, copy=true]
----
dotnet add package Neo4j.Driver
----

The driver supports the .NET Standard 2.0.

link:https://neo4j.com/docs/dotnet-manual/current/[More info on installing the driver]


[#connect]
== Connect to the database

Connect to a database by creating an <<IDriver>> object and providing a URL and an authentication token.
Once you have a `IDriver` instance, use the `.VerifyConnectivityAsync()` method to ensure that a working connection can be established.

[source, csharp, copy=true]
----
using Neo4j.Driver;

// URI examples: "neo4j://localhost", "neo4j+s://xxx.databases.neo4j.io"
const string dbUri = "{neo4j-database-uri}";
const string dbUser = "{neo4j-username}";
const string dbPassword = "{neo4j-password}";

await using var driver = GraphDatabase.Driver(dbUri, AuthTokens.Basic(dbUser, dbPassword));
await driver.VerifyConnectivityAsync();
Console.WriteLine("Connection established.");
----

link:https://neo4j.com/docs/dotnet-manual/current/[More info on connecting to a database]


[#create-graph]
== Create an example graph

Run a Cypher query with the method `IDriver.ExecutableQuery()`.
Do not hardcode or concatenate parameters: use placeholders and specify the parameters as a map through the `.WithParameters()` method.

.Create two `Person` nodes and a `KNOWS` relationship between them
[source, csharp, copy=true]
----
var result = await driver.ExecutableQuery(@"
    CREATE (a:Person {name: $name})
    CREATE (b:Person {name: $friendName})
    CREATE (a)-[:KNOWS]->(b)
    ")
    .WithParameters(new { name = "Alice", friendName = "David" })
    .WithConfig(new QueryConfig(database: "neo4j"))
    .ExecuteAsync();

// Summary information
var summary = result.Summary;
Console.WriteLine($"Created {summary.Counters.NodesCreated} nodes in {summary.ResultAvailableAfter.Milliseconds} ms.");
----

link:https://neo4j.com/docs/dotnet-manual/current/[More info on querying the database]


[#query-graph]
== Query a graph

To retrieve information from the database, use the Cypher clause `MATCH`:

.Retrieve all `Person` nodes who like other `Person` s
[source, csharp, copy=true]
----
var result = await driver.ExecutableQuery(@"
    MATCH (p:Person)-[:KNOWS]->(:Person)
    RETURN p.name AS name
    ")
    .WithConfig(new QueryConfig(database: "neo4j"))
    .ExecuteAsync();

// Loop through results and print people's name
foreach (var record in result.Result) {
    Console.WriteLine(record.Get<string>("name"));
}

// Summary information
var summary = result.Summary;
Console.WriteLine($"The query `{summary.Query.Text}` returned {result.Result.Count()} results in {summary.ResultAvailableAfter.Milliseconds} ms.");
----

link:https://neo4j.com/docs/dotnet-manual/current/[More info on querying the database]


[#close]
== Close connections and sessions

Unless you created them with the `using` keyword, remember to close all `IDriver` and `IAsyncSession` instances to release any resources still held by them.

[source, csharp, test-skip, copy=true]
----
await session.CloseAsync();
await driver.CloseAsync();
----
