[[dotnet-driver-client-applications]]
= Client applications

[abstract]
--
This section describes how to manage database connections within an application.
--


[[dotnet-driver-driver-object]]
== The Driver Object

include::{common-content}/client-applications.adoc[tag=object-pt1]

To construct a driver instance, a <<dotnet-driver-connection-uris, connection URI>> and <<dotnet-driver-authentication, authentication information>> must be supplied.

include::{common-content}/client-applications.adoc[tag=object-pt2]

.The driver lifecycle
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=driver-lifecycle]
----

// .Import driver lifecycle
// [source, csharp]
// ----
// include::{dotnet-examples}/Examples.cs[tags=driver-lifecycle-import]
// ----


[[dotnet-driver-connection-uris]]
== Connection URIs

include::{common-content}/client-applications.adoc[tag=uris]


[NOTE]
====
https://neo4j.com/aura/[*Neo4j Aura*] is a *_secure hosted service_* backed by full certificates signed by a root certificate authority.

To connect to *Neo4j Aura*, driver users must *_enable encryption_* and the complete set of certificate checks (the latter of which are enabled by default).

For more information, see <<dotnet-driver-configuration-examples>> below.
====

include::{common-content}/client-applications.adoc[tag=default-security-changes]


[[dotnet-initial-address-resolution]]
=== Initial address resolution

include::{common-content}/client-applications.adoc[tag=initial-address-resolution]


[[dotnet-dns-resolution]]
==== DNS resolution

include::{common-content}/client-applications.adoc[tag=dns-resolution]


[[dotnet-custom-middleware]]
==== Custom middleware

include::{common-content}/client-applications.adoc[tag=custom-middleware]


[[dotnet-driver-resolver-function]]
==== Resolver function

include::{common-content}/client-applications.adoc[tag=resolver-function]

.Custom Address Resolver
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=config-custom-resolver]
----


[[dotnet-driver-routing-table]]
=== Routing table

include::{common-content}/client-applications.adoc[tag=routing-table]


[[dotnet-driver-routing-context]]
=== Routing context

include::{common-content}/client-applications.adoc[tag=routing-context]


[[dotnet-driver-configuration-examples]]
=== Examples

include::{common-content}/client-applications.adoc[tag=examples-pt1]

In a clustered environment, the URI address will resolve to one of more of the core members; for standalone installations, this will simply point to that server address.
The `ROUTING_CONTEXT` option allows for customization of the routing table and is discussed in more detail in <<dotnet-driver-routing-context>>.

include::{common-content}/client-applications.adoc[tag=examples-pt2]

.Connecting to a service
The table below illustrates examples of how to connect to a service with routing:

[options="header", cols="a,a,a,a"]
|===
|Product
|Security
|Code snippet
|Comments

|Neo4j Aura
|Secured with full certificate
|
[source, csharp]
----
GraphDatabase.Driver("neo4j+s://graph.example.com:7687", auth)
----

If you do not have at least the .NET Driver 4.0.1 patch installed, you will need this snippet instead:

[source, csharp]
----
String uri = "neo4j://graph.example.com:7687";
IDriver driver = GraphDatabase.Driver(uri, auth,
           o => o.WithEncryptionLevel(EncryptionLevel.Encrypted));
----
| This is the default (and only option) for Neo4j Aura

|Neo4j 4.x
|Unsecured
|
[source, csharp]
----
GraphDatabase.Driver("neo4j://graph.example.com:7687", auth);
----
|This is the default for Neo4j 4.x series

|Neo4j 4.x
|Secured with full certificate
|
[source, csharp]
----
GraphDatabase.Driver("neo4j+s://graph.example.com:7687", auth)
----

If you do not have at least the .NET Driver 4.0.1 patch installed, you will need this snippet instead:

[source, csharp]
----
String uri = "neo4j://graph.example.com:7687";
IDriver driver = GraphDatabase.Driver(uri, auth,
           o => o.WithEncryptionLevel(EncryptionLevel.Encrypted));
----
|

|Neo4j 4.x
|Secured with self-signed certificate
|
[source, csharp]
----
GraphDatabase.Driver("neo4j+ssc://graph.example.com:7687", auth)
----

If you do not have at least the .NET Driver 4.0.1 patch installed, you will need this snippet instead:

[source, csharp]
----
String uri = "neo4j://graph.example.com:7687";
IDriver driver = GraphDatabase.Driver(uri, auth,
           o => o.WithEncryptionLevel(EncryptionLevel.Encrypted)
                 .WithTrustManager(TrustManager.CreateInsecure()));
----
|

|Neo4j 3.x
|Secured with full certificate
|
[source, csharp]
----
GraphDatabase.Driver("neo4j+s://graph.example.com:7687", auth)
----

If you do not have at least the .NET Driver 4.0.1 patch installed, you will need this snippet instead:

[source, csharp]
----
String uri = "neo4j://graph.example.com:7687";
IDriver driver = GraphDatabase.Driver(uri, auth,
           o => o.WithEncryptionLevel(EncryptionLevel.Encrypted));
----
|

|Neo4j 3.x
|Secured with self-signed certificate
|
[source, csharp]
----
GraphDatabase.Driver("neo4j+ssc://graph.example.com:7687", auth)
----

If you do not have at least the .NET Driver 4.0.1 patch installed, you will need this snippet instead:

[source, csharp]
----
String uri = "neo4j://graph.example.com:7687";
IDriver driver = GraphDatabase.Driver(uri, auth,
           o => o.WithEncryptionLevel(EncryptionLevel.Encrypted)
                 .WithTrustManager(TrustManager.CreateInsecure()));
----
|This is the default for Neo4j 3.x series

|Neo4j 3.x
|Unsecured
|
[source, csharp]
----
GraphDatabase.Driver("neo4j://graph.example.com:7687", auth);
----
|

|===

[NOTE]
To connect to a service without routing, you can replace `neo4j` with `bolt`.


[[dotnet-driver-authentication]]
== Authentication

include::{common-content}/client-applications.adoc[tag=authentication]


[[dotnet-driver-authentication-basic]]
=== Basic authentication

include::{common-content}/client-applications.adoc[tag=authentication-basic]

.Basic authentication
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=basic-auth]
----

// .Import basic authentication
// [source, csharp]
// ----
// include::{dotnet-examples}/Examples.cs[tags=basic-auth-import]
// ----

include::{common-content}/client-applications.adoc[tag=authentication-basic-note]


[[dotnet-driver-authentication-kerberos]]
=== Kerberos authentication

include::{common-content}/client-applications.adoc[tag=authentication-kerberos]

.Kerberos authentication
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=kerberos-auth]
----

// .Import Kerberos authentication
// [source, csharp]
// ----
// include::{dotnet-examples}/Examples.cs[tags=kerberos-auth-import]
// ----

include::{common-content}/client-applications.adoc[tag=authentication-kerberos-note]


[[dotnet-driver-authentication-custom]]
=== Custom authentication

include::{common-content}/client-applications.adoc[tag=authentication-custom]

.Custom authentication
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=custom-auth]
----

// .Import custom authentication
// [source, csharp]
// ----
// include::{dotnet-examples}/Examples.cs[tags=custom-auth-import]
// ----


[[dotnet-driver-configuration]]
== Configuration

include::{common-content}/client-applications.adoc[tag=configuration-ConnectionAcquisitionTimeout]

.Configure connection pool
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=config-connection-pool]
----
// .Import connection pool configuration
// [source, csharp]
// ----
// include::{dotnet-examples}/Examples.cs[tags=config-connection-pool-import]
// ----

include::{common-content}/client-applications.adoc[tag=configuration-ConnectionTimeout]

.Configure connection timeout
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=config-connection-timeout]
----

// .Import connection timeout configuration
// [source, csharp]
// ----
// include::{dotnet-examples}/Examples.cs[tags=config-connection-timeout-import]
// ----

include::{common-content}/client-applications.adoc[tag=configuration-CustomResolver]

include::{common-content}/client-applications.adoc[tag=configuration-Encryption]

.Unencrypted configuration
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=config-unencrypted]
----
// .Import unencrypted configuration
// [source, csharp]
// ----
// include::{dotnet-examples}/Examples.cs[tags=config-unencrypted-import]
// ----

include::{common-content}/client-applications.adoc[tag=configuration-MaxConnectionLifetime]

include::{common-content}/client-applications.adoc[tag=configuration-MaxConnectionPoolSize]

include::{common-content}/client-applications.adoc[tag=configuration-MaxTransactionRetryTime]

.Configure maximum retry time
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=config-max-retry-time]
----
// .Import maximum retry time configuration
// [.include-with-dotnet]
// ======
// [source, csharp]
// ----
// include::{dotnet-examples}/Examples.cs[tags=config-max-retry-time-import]
// ----

include::{common-content}/client-applications.adoc[tag=configuration-TrustStrategy]

.Configure trusted certificates
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=config-trust]
----
// .Import trusted certificate configuration
// [source, csharp]
// ----
// include::{dotnet-examples}/Examples.cs[tags=config-trust-import]
// ----

include::{common-content}/client-applications.adoc[tag=configuration-KeepAlive]


[[dotnet-driver-logging]]
== Logging

include::{common-content}/client-applications.adoc[tag=logging]

[source, csharp]
----
#Please note that you will have to provide your own console logger implementing the ILogger interface.
IDriver driver = GraphDatabase.Driver(..., o => o.WithLogger(logger));
----
