[[dotnet-driver-session-api]]
= The session API

include::{common-content}/session-api.adoc[tag=abstract]


[[dotnet-driver-simple-sessions]]
== Simple sessions

include::{common-content}/session-api.adoc[tag=simple-sessions]


[[dotnet-driver-simple-lifecycle]]
=== Lifecycle

include::{common-content}/session-api.adoc[tag=simple-lifecycle]

[source, csharp ]
----
using (var session = driver.Session(...)) {
    // transactions go here
  }
----

*_Sessions can be configured in a number of different ways_*.
This is carried out by supplying configuration inside the session constructor.
See <<dotnet-driver-session-configuration>> for more details.


[[dotnet-driver-simple-transaction-fn]]
=== Transaction functions

include::{common-content}/session-api.adoc[tag=simple-transaction-fn]

[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=transaction-function]
----


[[dotnet-driver-simple-autocommit-transactions]]
=== Auto-commit transactions

include::{common-content}/session-api.adoc[tag=simple-autocommit-transactions]

[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=autocommit-transaction]
----


[[dotnet-driver-simple-result-consume]]
=== Consuming results

include::{common-content}/session-api.adoc[tag=simple-result-consume]

[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=result-consume]
----


[[dotnet-driver-simple-result-retain]]
=== Retaining results

include::{common-content}/session-api.adoc[tag=simple-result-retain]

[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=result-retain]
----


[[dotnet-driver-async-sessions]]
== Asynchronous sessions

include::{common-content}/session-api.adoc[tag=async-sessions]


[[dotnet-driver-async-lifecycle]]
=== Lifecycle

include::{common-content}/session-api.adoc[tag=async-lifecycle]

See <<dotnet-driver-session-configuration>> for more details.


[[dotnet-driver-async-transaction-fn]]
=== Transaction functions

include::{common-content}/session-api.adoc[tag=async-transaction-fn]

[source, csharp]
----
include::{dotnet-examples}/ExamplesAsync.cs[tags=async-transaction-function]
----


[[dotnet-driver-async-autocommit-transactions]]
=== Auto-commit transactions

include::{common-content}/session-api.adoc[tag=async-autocommit-transactions]

[source, csharp]
----
include::{dotnet-examples}/ExamplesAsync.cs[tags=async-autocommit-transaction]
----


[[dotnet-driver-async-result-consume]]
=== Consuming results

include::{common-content}/session-api.adoc[tag=async-result-consume]

[source, csharp]
----
include::{dotnet-examples}/ExamplesAsync.cs[tags=async-result-consume]
----


[[dotnet-driver-rx-sessions]]
== Reactive Sessions

include::{common-content}/session-api.adoc[tag=rx-sessions]

[NOTE]
--
Reactive sessions will typically be used in a client application that is already oriented towards the reactive style; it is expected that a reactive dependency or framework is in place.

Refer to <<dotnet-driver-get-started>> for more information on recommended dependencies.
--


[[dotnet-driver-rx-lifecycle]]
=== Lifecycle

include::{common-content}/session-api.adoc[tag=rx-lifecycle]


[[dotnet-driver-rx-transaction-fn]]
=== Transaction functions

include::{common-content}/session-api.adoc[tag=rx-transaction-fn]

[source, csharp]
----
include::{dotnet-examples}/ExamplesRx.cs[tags=rx-transaction-function]
----

Sessions can be configured in a number of different ways.
This is carried out by supplying configuration inside the session constructor.
See <<dotnet-driver-session-configuration>> for more details.


[[dotnet-driver-rx-autocommit-transactions]]
=== Auto-commit transactions

include::{common-content}/session-api.adoc[tag=rx-autocommit-transactions]

[source, csharp]
----
include::{dotnet-examples}/ExamplesRx.cs[tags=rx-autocommit-transaction]
----


[[dotnet-driver-rx-result-consume]]
=== Consuming results

include::{common-content}/session-api.adoc[tag=rx-result-consume]

[source, csharp]
----
include::{dotnet-examples}/ExamplesRx.cs[tags=rx-result-consume]
----


[[dotnet-driver-rx-cancellation]]
=== Cancellation

include::{common-content}/session-api.adoc[tag=rx-cancellation]


[[dotnet-driver-session-configuration]]
== Session configuration

include::{common-content}/session-api.adoc[tag=Bookmarks]

include::{common-content}/session-api.adoc[tag=DefaultAccessMode]

include::{common-content}/session-api.adoc[tag=Database]

`Fetch Size`::
The number of records to fetch in each batch from the server.
Neo4j 4.0 introduces the ability to pull records in batches, allowing the client application to take control of data population and apply back pressure to the server.
This `FetchSize` applies to <<dotnet-driver-simple-sessions, simple sessions>> and <<dotnet-driver-async-sessions, async-sessions>> whereas reactive sessions can be controlled directly using the request method of the subscription.
+
*Default:* 1000 records
