= Connection

Once you have xref:install.adoc#install-driver[installed the driver] and have xref:install.adoc#get-an-instance[a running Neo4j instance], you are ready to connect your application to the database.

== Connect to the database

You connect to a Neo4j database by creating a <<DriverWithContext>> object and providing a URL and an authentication token.

[source, go, role=nocollapse]
----
package main

import (
    "context"
    "github.com/neo4j/neo4j-go-driver/v5/neo4j"
)

func main() {
    ctx := context.Background() // <2>
    dbUri := "neo4j://localhost"
    dbUser := "neo4j"
    dbPassword := "verysecret"
    driver, err := neo4j.NewDriverWithContext(  // <1>
        dbUri,
        neo4j.BasicAuth(dbUser, dbPassword, ""))
    if err != nil {
        panic(err)
    }
    defer closeDriver(ctx, driver)  // <4>

    err = driver.VerifyConnectivity(ctx)  // <3>
    if err != nil {
        panic(err)
    }
}

func closeDriver(context.Context ctx, neo4j.DriverWithContext driver) {
    err := driver.Close(ctx)
    if err != nil {
        panic(err)
    }
}
----

<1> Creating a `DriverWithContext` instance only provides information on _how_ to access the database, but does not actually _establish_ a connection.
Connection is instead deferred to when the first query is executed.
<2> Most driver functions require a `context.Context` parameter, see the link:https://pkg.go.dev/context[context] package.
<3> To verify immediately that the driver can connect to the database (valid credentials, compatible versions, etc), use the `.VerifyConnectivity(ctx)` method after initializing the driver.
<4> Always close `DriverWithContext` objects to free up all allocated resources, even upon unsuccessful connection or runtime errors in subsequent querying.
The safest practice is to `defer` the call to `DriverWithContext.Close(ctx)` after the object is successfully created.

`DriverWithContext` objects are _immutable_, _thread-safe_, and fairly _expensive to create_, so your application should only create one instance.
If you need to query the database with a different user than the one you created the object with, use xref:transactions#impersonation[impersonation].
If you want to alter a `DriverWithContext` configuration, you will need to create a new object.


== Further connection parameters

For more `DriverWithContext` configuration parameters and further connection settings, see xref:connect-advanced.adoc[Advanced connection information].


ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::{common-partial}/glossary.adoc[]
include::../partials/glossary.adoc[]
endif::[]
