= Connection

Once you have xref:install.adoc#install-driver[installed the driver] and have xref:install.adoc#get-an-instance[a running Neo4j instance], you are ready to connect your application to the database.


== Connect to the database

You connect to a Neo4j database by creating a <<Driver>> object and providing a URL and an authentication token.

[source, go, role=nocollapse]
----
package main

import (
    "context"
    "fmt"
    "github.com/neo4j/neo4j-go-driver/v6/neo4j"
)

func main() {
    ctx := context.Background() // <2>
    dbUri := "<database-uri>"
    dbUser := "<username>"
    dbPassword := "<password>"
    driver, err := neo4j.NewDriver(  // <1>
        dbUri,
        neo4j.BasicAuth(dbUser, dbPassword, ""))
    if err != nil {
        panic(err)
    }
    defer driver.Close(ctx)  // <4>

    err = driver.VerifyConnectivity(ctx)  // <3>
    if err != nil {
        panic(err)
    }
    fmt.Println("Connection established.")
}
----

<1> Creating a `Driver` instance only provides information on _how_ to access the database, but does not actually _establish_ a connection.
Connection is deferred to when the first query is executed.
<2> Most driver functions require a `context.Context` parameter, see the link:https://pkg.go.dev/context[context] package.
<3> To verify immediately that the driver can connect to the database (valid credentials, compatible versions, etc), use the `.VerifyConnectivity(ctx)` method after initializing the driver.
In case of failure, xref:query-advanced.adoc#_logging[enabling the driver's logs] can help diagnosing the issue.
<4> Always close `Driver` objects to free up all allocated resources, even upon unsuccessful connection or runtime errors in subsequent querying.
The safest practice is to `defer` the call to `Driver.Close(ctx)` after the object is successfully created.
Note that there are corner cases in which `.Close()` might return an error, so you may want to catch that as well.

**`Driver` objects are immutable, thread-safe, and expensive to create**, so your application should create only one instance and pass it around (you can share `Driver` instances across threads).
If you need to query the database through several different users, use xref:query-simple#impersonation[impersonation] without creating a new `Driver` instance.
If you want to alter a `Driver` configuration, you need to create a new object.

[TIP]
The driver also supports other xref:connect-advanced.adoc#authentication-methods[authentication methods] (kerberos, bearer, custom).


== Connect to an Aura instance

When you create an <<Aura>> instance, you may download a text file (a so-called _Dotenv file_) containing the connection information to the database as environment variables.
The file has a name of the form `Neo4j-a0a2fa1d-Created-2023-11-06.txt`.

You can either  manually extract the URI and the credentials from that file, or use a third party-module (ex. link:https://pkg.go.dev/github.com/joho/godotenv[`godotenv`]) to load them.

[source, go]
----
package main

import (
    "context"
    "os"
    "fmt"
    "github.com/joho/godotenv"
    "github.com/neo4j/neo4j-go-driver/v6/neo4j"
)

func main() {
    ctx := context.Background()
    err := godotenv.Load("Neo4j-a0a2fa1d-Created-2023-11-06.txt")
    if err != nil {
        panic(err)
    }
    dbUri := os.Getenv("NEO4J_URI")
    dbUser := os.Getenv("NEO4J_USERNAME")
    dbPassword := os.Getenv("NEO4J_PASSWORD")
    driver, err := neo4j.NewDriver(
        dbUri,
        neo4j.BasicAuth(dbUser, dbPassword, ""))
    if err != nil {
        panic(err)
    }
    defer driver.Close(ctx)

    err = driver.VerifyConnectivity(ctx)
    if err != nil {
        panic(err)
    }
    fmt.Println("Connection established.")
}
----

[TIP]
An Aura instance is not conceptually different from any other Neo4j instance, as Aura is simply a _deployment mode_ for Neo4j.
When interacting with a Neo4j database through the driver, it doesn't make a difference whether it is an Aura instance it is working with or a different deployment.


[[cluster]]
== Connect to a cluster

When working with a link:https://neo4j.com/docs/operations-manual/current/clustering/[Neo4j cluster], you have a few options to connect to it, depending on how it's deployed.

Upon connection, the driver gets a _routing table_ containing information about all the machines in the cluster (including their roles), and will point requests to primaries or secondaries as needed. The routing table is periodically refreshed.

- If the cluster members are all link:https://neo4j.com/docs/operations-manual/current/clustering/setup/discovery/#clustering-discovery-dns[discoverable] via a hostname that provides multiple `A`/`AAAA` records, you can use the hostname and port.
- If the addresses of the cluster members are known, but not advertised via `A`/`AAAA` records, you can use a xref:connect-advanced.adoc#custom-address-resolver[Custom address resolver] to extend the DNS resolution on the client side. +
+
[source, go]
----
// import "github.com/neo4j/neo4j-go-driver/v6/neo4j/config"

addresses := []config.ServerAddress{
    neo4j.NewServerAddress("server01.example.com", "7687"),
    neo4j.NewServerAddress("server02.example.com", "7687"),
    neo4j.NewServerAddress("server03.example.com", "7687"),
    neo4j.NewServerAddress("backup.example.org", "7687"),
}

driver, err := neo4j.NewDriver(
    "neo4j://example.com:7687", neo4j.BasicAuth(dbUser, dbPassword, ""),
    func(conf *config.Config) {
        conf.AddressResolver = func(address config.ServerAddress) []config.ServerAddress {
            return addresses
        }
})
defer driver.Close(ctx)
----
- You can also use the address of any machine belonging to the cluster: the driver will discover the others. This is the least fail-safe option, because if the machine you use as entrypoint becomes unavailable, the driver won't be able to fetch a routing table.

You can also bypass the routing table and connect to a specific machine in the cluster using its address together with the `bolt[+s[sc]]://` scheme (see xref:connect-advanced.adoc#_connection_uri[connection URI] for more information).


== Further connection parameters

For more `Driver` configuration parameters and further connection settings, see xref:connect-advanced.adoc[Advanced connection information].


ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::{common-partial}/glossary.adoc[]
include::../partials/glossary.adoc[]
endif::[]
