= Installation

To start creating a Neo4j Go application, you first need to install the Go Driver and get a Neo4j database instance to connect to.

[#install-driver]
== Install the driver

If you are starting from scratch, the first step is to initialize a Go module.
You can do so by creating a directory, entering it, and using `go mod init`:

[source, bash]
----
mkdir neo4j-app
cd neo4j-app
go mod init neo4j-app
----

From within a module, use `go get` to install the link:https://pkg.go.dev/github.com/neo4j/neo4j-go-driver/v6/[Neo4j Go Driver]:

[source, bash]
----
go get github.com/neo4j/neo4j-go-driver/v6
----

The latest version of the driver is guaranteed to work with all <<LTS>> releases of the Neo4j server, as well as with the current and next major releases.
The latest `6.x` driver supports connection to Neo4j instances version 4.4, 5.x, and 2025.x.
For a detailed list of changes across versions, see the link:https://github.com/neo4j/neo4j-go-driver/wiki/6.x-changelog[driver's changelog].

[NOTE]
The Neo4j Go Driver is compatible (and requires) any link:https://go.dev/doc/devel/release#policy[officially maintained Go version].

include::{common-partial}/install.adoc[tag=get-an-instance]


ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::{common-partial}/glossary.adoc[]
include::../partials/glossary.adoc[]
endif::[]
