= Installation

To start creating a Neo4j Go application, you first need to install the Go Driver and get a Neo4j database instance to connect to.

.Server compatibility
[IMPORTANT]
The latest driver in the `5.28.x` series supports connection to Neo4j instances version 4.4.x, 5.x, 2025.x, and 2026.x.
Some of the features introduced in the server in versions 2025.01 and later are not available via the driver version `5.28.x`; use link:https://neo4j.com/docs/go-manual/current/[the latest version] instead.

[#install-driver]
== Install the driver

If you are starting from scratch, the first step is to initialize a Go module.
You can do so by creating a directory, entering it, and using `go mod init`:

[source, bash]
----
mkdir neo4j-app
cd neo4j-app
go mod init neo4j-app
----

From within a module, use `go get` to install the link:https://pkg.go.dev/github.com/neo4j/neo4j-go-driver/v5/[Neo4j Go Driver]:

[source, bash]
----
go get github.com/neo4j/neo4j-go-driver/v5
----

[NOTE]
The Neo4j Go Driver is compatible (and requires) any link:https://go.dev/doc/devel/release#policy[officially maintained Go version].

include::{common-partial}/install.adoc[tag=get-an-instance]


ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::{common-partial}/glossary.adoc[]
include::../partials/glossary.adoc[]
endif::[]
