= Query the database

Once you have xref:connect.adoc[connected to the database], you can run queries using <<Cypher>> and the function link:https://pkg.go.dev/github.com/neo4j/neo4j-go-driver/v6/neo4j#ExecuteQuery[`ExecuteQuery()`].


== Write to the database

To create two nodes representing persons named `Alice` and `David`, and a relationship `KNOWS` between them, use the Cypher clause link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/create/[`CREATE`]:

.Create two nodes and a relationship
[source, go]
----
result, err := neo4j.ExecuteQuery(ctx, driver, `
    CREATE (a:Person {name: $name})  // <1>
    CREATE (b:Person {name: $friendName})
    CREATE (a)-[:KNOWS]->(b)
    `,
    map[string]any{  // <2>
        "name": "Alice",
        "friendName": "David",
    }, neo4j.EagerResultTransformer,
    neo4j.ExecuteQueryWithDatabase("<database-name>"))  // <3>
if err != nil {
    panic(err)
}

summary := result.Summary  // <4>
fmt.Printf("Created %v nodes in %+v.\n",
    summary.Counters().NodesCreated(),
    summary.ResultAvailableAfter())
----

<1> The Cypher query
<2> A map of _query parameters_
<3> The database to run the query on
<4> The xref:result-summary.adoc[summary of execution] returned by the server


== Read from the database

To retrieve information from the database, use the Cypher clause link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/match/[`MATCH`]:

.Retrieve all `Person` nodes who like other `Person` s
[source, go, role=nocollapse]
----
result, err := neo4j.ExecuteQuery(ctx, driver, `
    MATCH (p:Person)-[:KNOWS]->(:Person)
    RETURN p.name AS name
    `,
    nil,
    neo4j.EagerResultTransformer,
    neo4j.ExecuteQueryWithDatabase("<database-name>"))
if err != nil {
    panic(err)
}

// Loop through results and do something with them
for _, record := range result.Records {  // <1>
    name, _ := record.Get("name")  // .Get() 2nd return is whether key is present
    fmt.Println(name)
    // or
    // fmt.Println(record.AsMap())  // get Record as a map
}

// Summary information  // <2>
fmt.Printf("The query `%v` returned %v records in %+v.\n",
    result.Summary.Query().Text(), len(result.Records),
    result.Summary.ResultAvailableAfter())
----

<1> `result.Records` contains the result as an array of `Record` objects
<2> `result.Summary` contains the xref:result-summary.adoc[summary of execution] returned by the server

[TIP]
*When accessing a record's content, all its properties are of type `any`.*
This means that you have to cast them to the relevant Go type if you want to use methods/features defined on such types.
For example, if the `name` property coming from the database is a string, `record.AsMap()["name"][1]` would result in an _invalid operation_ error at compilation time.
For it to work, cast the value to string _before_ using it as a string: `name := record.AsMap()["name"].(string)` and then `name[1]`.


== Update the database

To update a node's information in the database, use the Cypher clauses link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/match/[`MATCH`] and link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/set/[`SET`]:

.Update node `Alice` to add an `age` property
[source, go]
----
result, err := neo4j.ExecuteQuery(ctx, driver, `
    MATCH (p:Person {name: $name})
    SET p.age = $age
    `, map[string]any{
        "name": "Alice",
        "age": 42,
    }, neo4j.EagerResultTransformer,
    neo4j.ExecuteQueryWithDatabase("<database-name>"))
if err != nil {
    panic(err)
}
fmt.Println("Query updated the database?",
    result.Summary.Counters().ContainsUpdates())
----

To create a new relationship, linking it to two already existing node, use a combination of the Cypher clauses `MATCH` and `CREATE`:

.Create a relationship `:KNOWS` between `Alice` and `Bob`
[source, go]
----
result, err := neo4j.ExecuteQuery(ctx, driver, `
    MATCH (alice:Person {name: $name})  // <1>
    MATCH (bob:Person {name: $friend})  // <2>
    CREATE (alice)-[:KNOWS]->(bob)  // <3>
    `, map[string]any{
        "name": "Alice",
        "friend": "Bob",
    }, neo4j.EagerResultTransformer,
    neo4j.ExecuteQueryWithDatabase("<database-name>"))
if err != nil {
    panic(err)
}
fmt.Println("Query updated the database?",
    result.Summary.Counters().ContainsUpdates())
----

<1> Retrieve the person node named `Alice` and bind it to a variable `alice`
<2> Retrieve the person node named `Bob` and bind it to a variable `bob`
<3> Create a new `:KNOWS` relationship outgoing from the node bound to `alice` and attach to it the `Person` node named `Bob`


== Delete from the database

To remove a node and any relationship attached to it, use the Cypher clause link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/delete/[`DETACH DELETE`]:

.Remove the `Alice` node and all its relationships
[source, go]
----
// This does not delete _only_ p, but also all its relationships!
result, err := neo4j.ExecuteQuery(ctx, driver, `
    MATCH (p:Person {name: $name})
    DETACH DELETE p
    `, map[string]any{
        "name": "Alice",
    }, neo4j.EagerResultTransformer,
    neo4j.ExecuteQueryWithDatabase("<database-name>"))
if err != nil {
    panic(err)
}
fmt.Println("Query updated the database?",
    result.Summary.Counters().ContainsUpdates())
----


[#query-parameters]
== Query parameters

*Do not hardcode or concatenate parameters directly into queries*.
Instead, always use placeholders and provide dynamic data as link:{neo4j-docs-base-uri}/cypher-manual/current/syntax/parameters/[Cypher parameters], as shown in the previous examples.
This is for:

1. *performance benefits*: Neo4j compiles and caches queries, but can only do so if the query structure is unchanged;
2. *security reasons*: see link:https://neo4j.com/developer/kb/protecting-against-cypher-injection/[Protecting against Cypher Injection].

Query parameters should get grouped into a map and passed as second parameter to `ExecuteQuery()`.
If a query has no parameters, you can pass `nil` instead of an empty map.

[source, go]
----
parameters := map[string]any{
    "name": "Alice",
    "age": 42,
}
neo4j.ExecuteQuery(ctx, driver,
    "MERGE (:Person {name: $name, age: $age})",
    parameters,
    neo4j.EagerResultTransformer,
    neo4j.ExecuteQueryWithDatabase("<database-name>"))
----

[NOTE]
There can be circumstances where your query structure prevents the usage of parameters in all its parts.
For those rare use cases, see xref:query-advanced#_dynamic_values_in_property_keys_relationship_types_and_labels[Dynamic values in property keys, relationship types, and labels].


[#error-handling]
== Error handling

A query run may fail for a number of reasons.
When using `ExecuteQuery()`, the driver automatically retries to run a failed query if the failure is deemed to be transient (for example due to temporary server unavailability).
An error is raised if the operation keeps failing after the configured link:https://pkg.go.dev/github.com/neo4j/neo4j-go-driver/v6/neo4j/config#Config.MaxTransactionRetryTime[maximum retry time].

All link:https://neo4j.com/docs/status-codes/current/errors/all-errors/[errors coming from the server] are of type link:https://pkg.go.dev/github.com/neo4j/neo4j-go-driver/v6/neo4j#Neo4jError[`Neo4jError`].
You can use an exception's code to stably identify a specific error; error messages are instead not stable markers, and should not be relied upon.

.Basic error handling
[source, go]
----
result, err := neo4j.ExecuteQuery(ctx, driver, "MATCH (p:Person) RETURN", nil,
    neo4j.EagerResultTransformer,
    neo4j.ExecuteQueryWithDatabase("<database-name>"))
if err != nil {
    var neo4jErr *neo4j.Neo4jError
    if errors.As(err, &neo4jErr) {
        // error is of type Neo4jError
        fmt.Println("Neo4j error code:", neo4jErr.Code)
        fmt.Println("Error message:", neo4jErr.Msg)
    } else {
        fmt.Printf("Non-Neo4j error: %s\n", err.Error())
    }
}
/*
Neo4j error code: Neo.ClientError.Statement.SyntaxError
Error message: Invalid input '': expected an expression, '*', 'ALL' or 'DISTINCT' (line 1, column 24 (offset: 23))
"MATCH (p:Person) RETURN"
                        ^
*/
----

Exception objects also expose errors as GQL-status objects.
The main difference between link:https://neo4j.com/docs/status-codes/current/errors/all-errors/[Neo4j error codes] and link:https://neo4j.com/docs/status-codes/current/errors/gql-errors/[GQL error codes] is that the GQL ones are more granular: a single Neo4j error code might be broken in several, more specific GQL error codes.

The actual _cause_ that triggered an exception is sometimes found in the optional GQL-status object `.GqlCause`, which is itself a `Neo4jError`.
You might need to recursively traverse the cause chain before reaching the root cause of the exception you caught.
In the example below, the exception's GQL status code is `42001`, but the actual source of the error has status code `42I06`.

.Usage of `Neo4jError` with GQL-related methods
[source, go]
----
result, err := neo4j.ExecuteQuery(ctx, driver, "MATCH (p:Person) RETURN", nil,
    neo4j.EagerResultTransformer,
    neo4j.ExecuteQueryWithDatabase("<database-name>"))
if err != nil {
    var neo4jErr *neo4j.Neo4jError
    if errors.As(err, &neo4jErr) {
        // Error is of type Neo4jError
        fmt.Println("Error GQL status code:", neo4jErr.GqlStatus)
        fmt.Println("Error GQL status description:", neo4jErr.GqlStatusDescription)
        fmt.Println("Error GQL classification:", neo4jErr.GqlClassification)
        if neo4jErr.GqlDiagnosticRecord != nil {
            fmt.Printf("Error GQL diagnostic record: %+v\n", neo4jErr.GqlDiagnosticRecord)
        }
        if neo4jErr.GqlCause != nil {
            fmt.Println("Error GQL cause:", neo4jErr.GqlCause.Error())
        }
    } else {
        fmt.Println("Non-Neo4j error:", err.Error())
    }
}
/*
Error GQL status code: 42001
Error GQL status description: error: syntax error or access rule violation - invalid syntax
Error GQL classification: CLIENT_ERROR
Error GQL diagnostic record: map[CURRENT_SCHEMA:/ OPERATION: OPERATION_CODE:0 _classification:CLIENT_ERROR _position:map[column:24 line:1 offset:23]]
Error GQL cause: Neo4jError: Neo.DatabaseError.General.UnknownError (42I06: Invalid input '', expected: an expression, '*', 'ALL' or 'DISTINCT'.)
*/
----

GQL status codes are particularly helpful when you want your application to behave differently depending on the exact error that was raised by the server.

.Distinguishing between different error codes
[source, go]
----
result, err := neo4j.ExecuteQuery(ctx, driver, "MATCH (p:Person) RETURN", nil,
    neo4j.EagerResultTransformer,
    neo4j.ExecuteQueryWithDatabase("<database-name>"))
if err != nil {
    var neo4jErr *neo4j.Neo4jError
    if errors.As(err, &neo4jErr) {
        if neo4jErr.ContainsGqlStatus("42001") {
            // Neo.ClientError.Statement.SyntaxError
            // special handling of syntax error in query
            fmt.Println(neo4jErr.Error())
        } else if neo4jErr.ContainsGqlStatus("42NFF") {
            // Neo.ClientError.Security.Forbidden
            // special handling of user not having CREATE permissions
            fmt.Println(neo4jErr.Error())
        } else {
            // handling of all other exceptions
            fmt.Println(neo4jErr.Error())
        }
    }
}
----

[NOTE]
====
The GQL status code `50N42` is returned when an error does not have a GQL-status object.
This can happen if the driver is connected to an older Neo4j server.
Don't rely on this status code, as future Neo4j server versions might change it with a more appropriate one.
====

[TIP]
====
Transient server errors can be retried without need to alter the original request.
You can discover whether an error is transient via the function link:https://pkg.go.dev/github.com/neo4j/neo4j-go-driver/v6/neo4j#IsRetryable[`neo4j.IsRetryable(error)`], which gives insights into whether a further attempt might be successful.
This is particular useful when running queries in xref:transactions#explicit-transactions[explicit transactions], to know if a failed query is worth re-running.
====


== Query configuration

You can supply further configuration parameters to alter the default behavior of link:https://pkg.go.dev/github.com/neo4j/neo4j-go-driver/v6/neo4j#ExecuteQuery[`ExecuteQuery()`].
These are provided as an arbitrary number of callbacks from the 4th function argument onward.


=== Database selection

*Always specify the database explicitly* with the `neo4j.ExecuteQueryWithDatabase("<dbName>")` callback, even on single-database instances.
This allows the driver to work more efficiently, as it saves a network round-trip to the server to resolve the home database.
If no database is given, the link:{neo4j-docs-base-uri}/operations-manual/current/database-administration/#manage-databases-default[user's home database] is used.

[source, go]
----
neo4j.ExecuteQuery(ctx, driver,
    "MATCH (p:Person) RETURN p.name",
    nil,
    neo4j.EagerResultTransformer,
    neo4j.ExecuteQueryWithDatabase("<database-name>"))
----

[TIP]
Specifying the database through the configuration method is preferred over the link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/use/[`USE`] Cypher clause.
If the server runs on a cluster, queries with `USE` require link:https://neo4j.com/docs/operations-manual/current/clustering/setup/routing/#clustering-routing[server-side routing] to be enabled.
Queries can also take longer to execute as they may not reach the right cluster member at the first attempt, and need to be routed to one containing the requested database.


=== Request routing

In a cluster environment, all queries are directed to the leader node by default.
To improve performance on read queries, you can use the callback `neo4j.ExecuteQueryWithReadersRouting()` to route a query to the read nodes.

[source, go]
----
neo4j.ExecuteQuery(ctx, driver,
    "MATCH (p:Person) RETURN p.name",
    nil,
    neo4j.EagerResultTransformer,
    neo4j.ExecuteQueryWithDatabase("<database-name>"),
    neo4j.ExecuteQueryWithReadersRouting())
----

[NOTE]
====
Although executing a _write_ query in read mode results in a runtime error, *you should not rely on this for access control.* The difference between the two modes is that _read_ transactions will be routed to any node of a cluster, whereas _write_ ones are directed to primaries.
There is no security guarantee that a write query submitted in read mode will be rejected.
====


[#impersonation]
=== Run queries as a different user

You can execute a query through a different user with the configuration callback `neo4j.ExecuteQueryWithAuthToken()`.
Switching user at the query level is cheaper than creating a new `Driver` object.
The query is then run within the security context of the given user (i.e., home database, permissions, etc.). +

[source, go]
----
queryAuth := neo4j.BasicAuth("<username>", "<password>", "")
neo4j.ExecuteQuery(ctx, driver,
    "MATCH (p:Person) RETURN p.name",
    nil,
    neo4j.EagerResultTransformer,
    neo4j.ExecuteQueryWithDatabase("<database-name>"),
    neo4j.ExecuteQueryWithAuthToken(queryAuth))
----

The callback `neo4j.ExecuteQueryWithImpersonatedUser()` provides a similar functionality.
The difference is that you don't need to know a user's password to impersonate them, but the user under which the `Driver` was created needs to have the link:https://neo4j.com/docs/operations-manual/current/authentication-authorization/dbms-administration/dbms-impersonate-privileges/[appropriate permissions].

[source, go]
----
neo4j.ExecuteQuery(ctx, driver,
    "MATCH (p:Person) RETURN p.name",
    nil,
    neo4j.EagerResultTransformer,
    neo4j.ExecuteQueryWithDatabase("<database-name>"),
    neo4j.ExecuteQueryWithImpersonatedUser("<username>"))
----


== A full example

[source, go]
----
package main

import (
    "fmt"
    "context"
    "github.com/neo4j/neo4j-go-driver/v6/neo4j"
)

func main() {
    ctx := context.Background()

    // Connection to database
    dbUri := "<database-uri>"
    dbUser := "<username>"
    dbPassword := "<password>"
    driver, err := neo4j.NewDriver(
        dbUri,
        neo4j.BasicAuth(dbUser, dbPassword, ""))
    if err != nil {
        panic(err)
    }
    defer driver.Close(ctx)
    err = driver.VerifyConnectivity(ctx)
    if err != nil {
        panic(err)
    }

    // Prepare data
    people := []map[string]any {
       {"name": "Alice", "age": 42, "friends": []string{"Bob", "Peter", "Anna"},},
       {"name": "Bob", "age": 19,},
       {"name": "Peter", "age": 50,},
       {"name": "Anna", "age": 30,},
    }

    // Create some nodes
    for _, person := range people {
        _, err := neo4j.ExecuteQuery(ctx, driver,
            "MERGE (p:Person {name: $person.name, age: $person.age})",
            map[string]any{
                "person": person,
            }, neo4j.EagerResultTransformer,
            neo4j.ExecuteQueryWithDatabase("<database-name>"))
        if err != nil {
            panic(err)
        }
    }

    // Create some relationships
    for _, person := range people {
        if person["friends"] != "" {
            _, err := neo4j.ExecuteQuery(ctx, driver, `
                MATCH (p:Person {name: $person.name})
                UNWIND $person.friends AS friend_name
                MATCH (friend:Person {name: friend_name})
                MERGE (p)-[:KNOWS]->(friend)
                `, map[string]any{
                    "person": person,
                }, neo4j.EagerResultTransformer,
                neo4j.ExecuteQueryWithDatabase("<database-name>"))
            if err != nil {
                panic(err)
            }
        }
    }

    // Retrieve Alice's friends who are under 40
    result, err := neo4j.ExecuteQuery(ctx, driver, `
        MATCH (p:Person {name: $name})-[:KNOWS]-(friend:Person)
        WHERE friend.age < $age
        RETURN friend
        `, map[string]any{
            "name": "Alice",
            "age": 40,
        }, neo4j.EagerResultTransformer,
        neo4j.ExecuteQueryWithDatabase("<database-name>"))
    if err != nil {
        panic(err)
    }

    // Loop through results and do something with them
    for _, record := range result.Records {
        person, _ := record.Get("friend")
        fmt.Println(person)
        // or
        // fmt.Println(record.AsMap())
    }

    // Summary information
    fmt.Printf("\nThe query `%v` returned %v records in %+v.\n",
        result.Summary.Query().Text(), len(result.Records),
        result.Summary.ResultAvailableAfter())
}
----

For more information see link:https://pkg.go.dev/github.com/neo4j/neo4j-go-driver/v6/neo4j#ExecuteQuery[API documentation -> ExecuteQuery()].


ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::{common-partial}/glossary.adoc[]
include::../partials/glossary.adoc[]
endif::[]
