= Run your own transactions

When xref:query-simple.adoc[querying the database with `ExecuteQuery()`], the driver automatically creates a _transaction_. A transaction is a unit of work that is either _committed_ in its entirety or _rolled back_ on failure. You can include multiple Cypher statements in a single query, as for example when using `MATCH` and `MERGE` in sequence to xref:query-simple#_update_the_database[update the database], but you cannot have multiple queries and interleave some client-logic in between them.

For these more advanced use-cases, the driver provides functions to take full control over the transaction lifecycle. These are called _managed transactions_, and you can think of them as a way of unwrapping the flow of `ExecuteQuery()` and being able to specify its desired behavior in more places.


== Obtain a session

Before running a transaction, you need to obtain a _session_.
Sessions act as concrete query channels between the driver and the server.
In particular, sessions borrow connections from the _connection pool_ as needed, and ensure <<causal consistency>> is enforced.

Sessions are created with the method `DriverWithContext.NewSession()`.
Use the second argument to specify the xref:_database_selection[target database].
For further configuration parameters, see xref:_session_configuration[Session configuration].

[source, go]
----
session := driver.NewSession(ctx, neo4j.SessionConfig{DatabaseName: "neo4j"})
defer session.Close(ctx)
----

Session creation is a lightweight operation, so sessions can be created and destroyed without significant cost.
Always xref:_close_sessions[close sessions] when you are done with them.

*Sessions are _not_ thread safe*: share the main `DriverWithContext` object across threads, but make sure each routine creates its own sessions.


[#managed-transactions]
== Run a managed transaction

A transaction can contain any number of queries.
As Neo4j is <<ACID>> compliant, *queries within a transaction will either be executed as a whole or not at all*: you cannot get a part of the transaction succeeding and another failing.
Use transactions to group together related queries which work together to achieve a single _logical_ database operation.

A managed transaction is created with the methods link:https://pkg.go.dev/github.com/neo4j/neo4j-go-driver/v5/neo4j#SessionWithContext[`SessionWithContext.ExecuteRead()`] and link:https://pkg.go.dev/github.com/neo4j/neo4j-go-driver/v5/neo4j#SessionWithContext[`SessionWithContext.ExecuteWrite()`], depending on whether you want to retrieve data from the database or alter it.
Both methods take a _transaction function_ callback, which is responsible for actually carrying out the queries and processing the result.

.Retrieve people whose name starts with `Al`
[source, go, role=nocollapse]
----
session := driver.NewSession(ctx, neo4j.SessionConfig{DatabaseName: "neo4j"})  // <1>
defer session.Close(ctx)
people, err := session.ExecuteRead(ctx,  // <2>
    func(tx neo4j.ManagedTransaction) (any, error) {  // <3>
        result, err := tx.Run(ctx, `  // <4>
            MATCH (p:Person) WHERE p.name STARTS WITH $filter
            RETURN p.name as name ORDER BY name
            `, map[string]any{
                "filter": "Al",
            })
        if err != nil {
            return nil, err
        }
        records, err := result.Collect(ctx)  // <5>
        if err != nil {
            return nil, err
        }
        return records, nil
    })
for _, person := range people.([]*neo4j.Record) {
    fmt.Println(person.AsMap())
}
----

<1> Create a session. A single session can be the container for multiple queries. Remember to close it when done.
<2> The `.ExecuteRead()` (or `.ExecuteWrite()`) method is the entry point into a transaction.
<3> The transaction function callback is responsible of running queries.
<4> Use the method link:https://pkg.go.dev/github.com/neo4j/neo4j-go-driver/v5/neo4j#ManagedTransaction[`ManagedTransaction.Run()`] to run queries. Each query run returns a link:https://pkg.go.dev/github.com/neo4j/neo4j-go-driver/v5/neo4j#ResultWithContext[`ResultWithContext`] object.
<5> xref:process-result[Process the result] using any of the methods on `ResultWithContext`. The method `.Collect()` retrieves all records into a list.

*Do not hardcode or concatenate parameters directly into the query*.
Use xref:query-simple#query-parameters[query parameters] instead, both for performance and security reasons.

*Transaction functions should never return the result object directly*.
Instead, always xref:process-result[process the result] in some way.
Within a transaction function, a `return` statement results in the transaction being committed, while the transaction is automatically rolled back if an exception is raised.

.A transaction with multiple queries, client logic, and potential roll backs.
[source, go]
----
package main

import (
    "fmt"
    "context"
    "strconv"
    "errors"
    "github.com/neo4j/neo4j-go-driver/v5/neo4j"
)

func main() {
    ctx := context.Background()
    var employeeThreshold int64 = 10  // Neo4j's integer map to Go's int64

    // Connection to database
    dbUri := "neo4j://localhost"
    dbUser := "neo4j"
    dbPassword := "verysecret"
    driver, err := neo4j.NewDriverWithContext(
        dbUri,
        neo4j.BasicAuth(dbUser, dbPassword, ""))
    if err != nil {
        panic(err)
    }
    defer driver.Close(ctx)
    err = driver.VerifyConnectivity(ctx)
    if err != nil {
        panic(err)
    }

    session := driver.NewSession(ctx, neo4j.SessionConfig{DatabaseName: "neo4j"})
    defer session.Close(ctx)

    // Some error handling in query runs omitted for brevity
    for i := 0; i < 100; i++ {
        name := "Thor" + strconv.Itoa(i)
        orgId, _ := session.ExecuteWrite(ctx,
            func(tx neo4j.ManagedTransaction) (any, error) {
                var orgId string

                // Create new Person node with given name, if not exists already
                tx.Run(
                    ctx,
                    "MERGE (p:Person {name: $name})",
                    map[string]any{
                        "name": name,
                    })

                // Obtain most recent organization ID and the number of people linked to it
                result, err := tx.Run(
                    ctx, `
                    MATCH (o:Organization)
                    RETURN o.id AS id, COUNT{(p:Person)-[r:WORKS_FOR]->(o)} AS employeesN
                    ORDER BY o.createdDate DESC
                    LIMIT 1
                    `, nil)
                org, err := result.Single(ctx)

                // If no organization exists, create one and add Person to it
                if org == nil {
                    orgId, _ = createOrganization(ctx, tx)
                    fmt.Println("No orgs available, created", orgId)
                    err = addPersonToOrganization(ctx, tx, name, orgId)
                    if err == nil {
                        return nil, errors.New("Failed to add person to new org")
                        // Transaction will roll back
                        // -> not even Person and/or Organization is created!
                    }
                } else {
                    orgId = org.AsMap()["id"].(string)
                    if employeesN := org.AsMap()["employeesN"].(int64);
                       employeesN == 0 {
                        return nil, errors.New("Most recent organization is empty")
                        // Transaction will roll back
                        // -> not even Person is created!
                    }

                    // If org does not have too many employees, add this Person to it
                    if employeesN := org.AsMap()["employeesN"].(int64);
                       employeesN < employeeThreshold {
                        err = addPersonToOrganization(ctx, tx, name, orgId)
                        if err != nil {
                            return nil, err
                            // Transaction will roll back
                            // -> not even Person is created!
                        }
                    // Otherwise, create a new Organization and link Person to it
                    } else {
                        orgId, err = createOrganization(ctx, tx)
                        if err != nil {
                            return nil, err
                            // Transaction will roll back
                            // -> not even Person is created!
                        }
                        fmt.Println("Latest org is full, created", orgId)
                        err = addPersonToOrganization(ctx, tx, name, orgId)
                        if err != nil {
                            return nil, err
                            // Transaction will roll back
                            // -> not even Person and/or Organization is created!
                        }
                    }
                }
                // Return the Organization ID to which the new Person ends up in
                return orgId, nil
            })
        fmt.Println("User", name, "added to organization", orgId)
    }
}

func createOrganization(ctx context.Context, tx neo4j.ManagedTransaction) (string, error) {
    result, _ := tx.Run(
        ctx, `
        CREATE (o:Organization {id: randomuuid(), createdDate: datetime()})
        RETURN o.id AS id
        `, nil)
    org, err := result.Single(ctx)
    orgId, _ := org.AsMap()["id"]
    return orgId.(string), err
}

func addPersonToOrganization(ctx context.Context, tx neo4j.ManagedTransaction, personName string, orgId string) (error) {
    result, _ := tx.Run(
        ctx, `
        MATCH (o:Organization {id: $orgId})
        MATCH (p:Person {name: $name})
        MERGE (p)-[:WORKS_FOR]->(o)
        `, map[string]any{
            "orgId": orgId,
            "name": personName,
        })
    _, err := result.Consume(ctx)
    return err
}

----

Should a transaction fail for a reason that the driver deems transient, it automatically retries to run the transaction function (with an exponentially increasing delay).
For this reason, *transaction functions must be _idempotent_* (i.e., they should produce the same effect when run several times), because you do not know upfront how many times they are going to be executed.
In practice, this means that you should not edit nor rely on globals, for example.
Note that although transactions functions might be executed multiple times, the queries inside it will always run only once.

A session can chain multiple transactions, but *only one single transaction can be active within a session at any given time*.
To maintain multiple concurrent transactions, use multiple concurrent sessions.


=== Transaction function configuration

You can exert further control on transaction functions providing configuration callbacks to `.ExecuteRead()` and `.ExecuteWrite()`.
Use them to specify:

- a transaction timeout (in seconds).
Transactions that run longer will be terminated by the server.
The default value is set on the server side.
- a map of metadata that gets attached to the transaction.
These metadata get logged in the server `query.log`, and are visible in the output of the `SHOW TRANSACTIONS` Cypher command.
Use this to tag transactions.

[source, go]
----
session := driver.NewSession(ctx, neo4j.SessionConfig{DatabaseName: "neo4j"})
defer session.Close(ctx)
people, err := session.ExecuteRead(ctx,
    func(tx neo4j.ManagedTransaction) (any, error) {
        result, _ := tx.Run(ctx, "MATCH (:Person) RETURN count(*) AS n", nil)
        return result.Collect(ctx)
    },
    neo4j.WithTxTimeout(5*time.Second),  // remember to import time
    neo4j.WithTxMetadata(map[string]any{"appName": "peopleTracker"}))
----


[#explicit-transactions]
== Run an explicit transaction

You can achieve full control over transactions by manually beginning one with the method link:{neo4j-docs-base-uri}/api/python-driver/current/api.html#neo4j.Session.begin_transaction[`Session.begin_transaction()`].
You run queries inside an explicit transaction with the method link:{neo4j-docs-base-uri}/api/python-driver/current/api.html#neo4j.Transaction.run[`Transaction.run()`].

[source, python]
----
with driver.session(database="neo4j") as session:
    with session.begin_transaction() as tx:
        # use tx.run() to run queries
----

Closing an explicit transaction can either happen automatically at the end of a `with` block, or can be explicitly controlled through the methods link:{neo4j-docs-base-uri}/api/python-driver/current/api.html#neo4j.Transaction.commit[`Transaction.commit()`], link:{neo4j-docs-base-uri}/api/python-driver/current/api.html#neo4j.Transaction.rollback[`Transaction.rollback()`], or link:{neo4j-docs-base-uri}/api/python-driver/current/api.html#neo4j.Transaction.close[`Transaction.close()`].

Explicit transactions are most useful for applications that need to distribute Cypher execution across multiple functions for the same transaction, or for applications that need to run multiple queries within a single transaction but without the automatic retries provided by managed transactions.

[source, python]
----
import neo4j


def transfer_to_other_bank(driver, customer_id, other_bank_id, amount):
    with driver.session(database="neo4j") as session:
        tx = session.begin_transaction()
        # or just use a `with` context on `tx` instead of try/finally
        try:
            if not customer_balance_check(tx, customer_id, amount):
                # give up
                return

            other_bank_transfer_api(customer_id, other_bank_id, amount)
            # Now the money has been transferred => can't rollback anymore
            # (cannot rollback external services interactions)

            try:
                decrease_customer_balance(tx, customer_id, amount)
                tx.commit()
            except Exception as e:
                request_inspection(customer_id, other_bank_id, amount, e)
                raise  # roll back
        finally:
            tx.close()  # rolls back if not yet committed


def customer_balance_check(tx, customer_id, amount):
    query = ("""
        MATCH (c:Customer {id: $id})
        RETURN c.balance >= $amount AS sufficient
    """)
    result = tx.run(query, id=customer_id, amount=amount)
    record = result.single(strict=True)
    return record["sufficient"]


def other_bank_transfer_api(customer_id, other_bank_id, amount):
    ...
    # make some API call to other bank


def decrease_customer_balance(tx, customer_id, amount):
    query = ("""
        MATCH (c:Customer {id: $id})
        SET c.balance = c.balance - $amount
    """)
    result = tx.run(query, id=customer_id, amount=amount)
    result.consume()


def request_inspection(customer_id, other_bank_id, amount, e):
    # manual cleanup required; log this or similar
    print("WARNING: transaction rolled back due to exception:", repr(e))
    print("customer_id:", customer_id, "other_bank_id:", other_bank_id,
          "amount:", amount)

----


[[process-result]]
== Process query results

The driver's output of a query is a link:{neo4j-docs-base-uri}/api/python-driver/current/api.html#neo4j.Result[`Result`] object, which does not directly contain the result records.
Rather, it encapsulates the Cypher result in a rich data structure that requires some parsing on the client side.

When working with a `Result` object, there are two things to keep in mind:

- *The result records are not immediately and entirely fetched and returned by the server*.
Instead, results come as a _lazy stream_.
In particular, when the driver receives some records from the server, they are initially _buffered_ in a background queue.
Records stay in the buffer until they are _consumed_ by the application, at which point they are _removed from the buffer_.
When no more records are available, the result is _exhausted_.
- *The result acts as a _cursor_*.
This means that there is no way to retrieve a previous record from the stream, unless you saved it in an auxiliary data structure.

**The easiest way of processing a result is by casting it to list**, which yields a list of link:{neo4j-docs-base-uri}/api/python-driver/current/api.html#neo4j.Record[`Record`] objects.
Otherwise, a `Result` object implements a number of methods for processing records.
The most commonly needed ones are listed below.

// .An essential list of `Result` methods
[cols="2,3"]
|===
|Name |Description

|`value(key=0, default=None)`
|Return the remainder of the result as a list.
If `key` is specified, only the given property is included, while `default` allows to specify a value for nodes lacking that property.

|`fetch(n)`
|Return up to `n` records from the result.

|`single(strict=False)`
a|Return the next and only remaining record, or `None`.
Calling this method always exhausts the result.

If more (or less) than one record is available,

- `strict==False` -- a warning is generated and the first of these is returned (if any);
- `strict==True` -- a `ResultNotSingleError` is raised.

|`peek()`
|Return the next record from the result without consuming it.
This leaves the record in the buffer for further processing.

|`data(*keys)`
|Return a JSON-like dump of the raw result.
Only use it for debugging/prototyping purposes.

|`consume()`
|Return the query xref:result-summary.adoc[result summary].
It exhausts the result, so should only be called when data processing is over.
|===

For a complete list of `Result` methods, see link:{neo4j-docs-base-uri}/api/python-driver/current/api.html#result[API documentation -- Result].


== Session configuration

=== Database selection

It is recommended to *always specify the database explicitly* with the `database` parameter, even on single-database instances.
This allows the driver to work more efficiently, as it does not have to resolve the home database first.
If no database is given, the link:{neo4j-docs-base-uri}/operations-manual/current/manage-databases/introduction#manage-databases-default[default database] set in the Neo4j instance settings is used.

[source, python]
----
with driver.session(
    database="neo4j"
) as session:
    ...
----


=== Request routing

In a cluster environment, all sessions are opened in write mode, routing them to the leader.
You can change this by explicitly setting the `default_access_mode` parameter to either `neo4j.READ_ACCESS` or `neo4j.WRITE_ACCESS`.
Note that `.execute_read()` and `.execute_write()` automatically override the session's default access mode.

[source, python]
----
import neo4j

with driver.session(
    database="neo4j",
    default_access_mode=neo4j.READ_ACCESS
) as session:
    ...
----

[#access-control-note]
// .Routing ≠ Access control
[NOTE]
====
Although executing a _write_ query in read mode likely results in a runtime error, *you should not rely on this for access control.* The difference between the two modes is that _read_ transactions will be routed to any node of a cluster, whereas _write_ ones will be directed to the leader.
Still, depending on the server version and settings, the server might allow none, some, or all _write_ statements to be executed even in _read_ transactions.

Similar remarks hold for the `.execute_read()` and `.execute_write()` methods.
====


[#impersonation]
=== Run queries as a different user (impersonation)

You can execute a query under the security context of a different user with the parameter `impersonated_user`, specifying the name of the user to impersonate.
For this to work, the user under which the `Driver` was created needs to have the link:{neo4j-docs-base-uri}/cypher-manual/current/access-control/dbms-administration#access-control-dbms-administration-impersonation[appropriate permissions].
Impersonating a user is cheaper than creating a new `Driver` object.

[source, python]
----
with driver.session(
    database="neo4j",
    impersonated_user="somebody_else"
) as session:
    ...
----

When impersonating a user, the query is run within the complete security context of the impersonated user and not the authenticated user (i.e., home database, permissions, etc.).


== Close sessions

Each connection pool has *a finite number of sessions*, so if you open sessions without ever closing them, your application could run out of them.
It is thus recommended to create sessions using the `with` statement, which automatically closes them when the application is done with them.
When a session is closed, it is returned to the connection pool to be later reused.

If you do not use `with`, remember to call the `.close()` method when you have finished using a session.

[source, python]
----
session = driver.session(database="neo4j")

# session usage

session.close()
----

ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::{common-partial}/glossary.adoc[]
include::../partials/glossary.adoc[]
endif::[]
