[[driver-get-started]]
= Get started

# tag::abstract[]

[abstract]
--
This section gives an overview of the official Neo4j drivers and how to connect to a Neo4j database with a "Hello World" example.
--

# end::abstract[]

[[driver-get-started-about]]
== About the official drivers

# tag::about[]

Neo4j provides official drivers for a number of popular programming languages.
These drivers are supported by Neo4j.

Community drivers also exist for many languages, but vary greatly in terms of feature sets, maturity, and support.
To find more about community drivers, visit https://neo4j.com/developer/language-guides/.

The following languages and frameworks are officially supported by Neo4j:

.Supported languages and frameworks for the 4.x driver series
[options="header", cols="<25s,<75a"]
|===
| Language/framework
| Versions supported

| .NET
| https://github.com/dotnet/standard/blob/master/docs/versions/netstandard2.0.md[.NET Standard 2.0]

| Go
| All the Go versions officially supported, with 1.18 as a minimum (https://go.dev/doc/devel/release#policy)

| Java
| Java 8+ (latest patch releases).

| JavaScript
| All LTS versions of Node.JS, specifically the 4.x and 6.x series runtimes (https://github.com/nodejs/LTS).

| Python
| Python 3.6 and above.
|===

The driver API is intended to be topologically agnostic.
This means that the underlying database topology — single instance, Causal Cluster, etc. — can be altered without requiring a corresponding alteration to application code.

# end::about[]

In the general case, only the <<driver-connection-uris, connection URI>> needs to be modified when changes are made to the topology.

# tag::about-note[]

[NOTE]
====
The official drivers do not support HTTP communication.
If you need an HTTP driver, choose one of the community drivers.

See also the <<http-api#http-api, HTTP API documentation>>.
====

# end::about-note[]

[[driver-get-started-installation]]
== Driver versions and installation

# tag::versions[]

Starting with *Neo4j 4.0*, *_the versioning scheme for the database, driver and protocol have all been aligned_*.
This simplifies general compatibility concerns.

Cross-version compatibility is still available, and minimum support for current and previous versions between both server and driver is guaranteed.
More specifically, this means that *Neo4j 4.0* is guaranteed to be compatible with both *4.0 Drivers* and *1.7 Drivers*, and the *4.0 Drivers* are guaranteed to be compatible with both *Neo4j 4.0* and *Neo4j 3.5*.
In cases where at least one peer is below version 4.0, communication will occur in *_fallback mode, limiting functionality to that available in the lowest-versioned component_*.

[NOTE]
Drivers 1.7 do not support multiple databases and Neo4j Fabric, features introduced in Neo4j 4.0.
To be able to run multiple databases online concurrently and to do distributed queries over them, you must upgrade Drivers from 1.7 to 4.0.
For information, see link:https://neo4j.com/docs/migration-guide/4.0/upgrade-driver/[4.0 Migration Guide -> Chapter 6. Upgrade Neo4j drivers].


Wherever possible, it is recommended to use the latest stable driver release available.
This will provide the greatest degree of stability and will ensure that the full set of server functionality is available.
The drivers, when used with *Neo4j Enterprise Edition*, come with full cluster routing support.
The drivers make no explicit distinction between *Enterprise Edition* and *Community Edition* however, and simply operate with the functionality made available by *Neo4j* itself.

# end::versions[]

To install a driver or to find out more about which driver versions are available, use the relevant language distribution system, described below.


.Acquire the driver
[.tabbed-example]
====

[.include-with-dotnet]
======

The .NET driver is distributed via the NuGet Gallery.
To find the latest version of the driver, visit https://www.nuget.org/packages/Neo4j.Driver/.

*Dependencies*

* .NETStandard (^2.0)
* System.Net.NameResolution (^4.3.0)
* System.Net.Security (^4.3.2)
* System.Net.Sockets (^4.3.0)
* System.Runtime.InteropServices.RuntimeInformation (^4.3.0)
* System.Runtime.Serialization.Primitives (^4.3.0)
* System.Threading.Thread (^4.3.0)
* System.ValueTuple (^4.5.0)

The .NET Reactive API is under package `Neo4j.Driver.Reactive`.
It is built upon https://github.com/dotnet/reactive[`System.Reactive`].
There is no extra dependency required use .NET reactive API.

.Installation via Install-package
========
To install the latest version of the driver using NuGet in Visual Studio:

[source, csharp, subs="attributes, specialcharacters"]
----
PM> Install-Package Neo4j.Driver
----

It is also an option to install a certain version of the driver.

[source, csharp, subs="attributes, specialcharacters"]
----
PM> Install-Package Neo4j.Driver -Version $DOTNET_DRIVER_VERSION
----

The .Net driver uses asynchronous methods by default.
If you want to use blocking calls, the `Neo4j.Driver.Simple` NuGet package contains a set of extensions.
This can be found at https://www.nuget.org/packages/Neo4j.Driver.Simple/.
The initial examples make use of these extensions.

In the following example we are installing driver version {dotnet-driver-version}.

[source, csharp, subs="attributes, specialcharacters"]
----
PM> Install-Package Neo4j.Driver -Version {dotnet-driver-version}
----
========

The release notes for this driver are available https://github.com/neo4j/neo4j-dotnet-driver/releases[here].

======

// [.include-with-go]
// ======
//
// To find the latest version of the driver, visit https://github.com/neo4j/neo4j-go-driver/releases.
//
// In order to get go driver running, you need to install our C connector, seabolt, on your build and production environments.
// Follow instructions at https://github.com/neo4j-drivers/seabolt for installing seabolt through one of our binary packages or by building from scratch.
//
// The go driver makes use of `cgo` and `pkg-config` to build against `seabolt` and thus requires a working `cgo` and `pkg-config` environment on your build environment.
//
// ========
//
// To install the latest version of the driver using `go get`:
//
// [source, shell, subs="attributes, specialcharacters"]
// ----
// go get github.com/neo4j/neo4j-go-driver
// ----
//
// ========
//
// ========
//
// To install the latest version of the driver using `dep`:
//
// [source, shell, subs="attributes, specialcharacters"]
// ----
// dep ensure github.com/neo4j/neo4j-go-driver
// ----
//
// It is also an option to install a certain version of the driver.
// Below is the syntax for using a certain minor version of the driver.
// Visit https://golang.github.io/dep/docs/Gopkg.toml.html#version-rules for a detailed description of version rules that can be used.
//
// [source, shell, subs="attributes, specialcharacters"]
// ----
// dep ensure github.com/neo4j/neo4j-go-driver@1.7.x
// ----
//
// ========
//
// The release notes for this driver are available https://github.com/neo4j/neo4j-go-driver/wiki[here].
//
// ======

[.include-with-java]
======

To use the Java driver, it is recommended employing a dependency manager, such as Maven or Gradle.
To find the latest version of the driver, visit the https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.neo4j.driver%22%20AND%20a%3A%22neo4j-java-driver%22[Maven Central Repository].

*Dependencies*

* org.reactivestreams:reactive-streams
* org.apache.logging.log4j:log4j (optional)

The driver is dependent on the https://www.reactive-streams.org/[Reactive Streams API], thus maintaining JDK 8 compatibility.
To make optimal use of the reactive APIs, we suggest an additional framework like Project Reactor or RxJava2.
Both implement the Reactive Streams API and provide an exhaustive set of operators.


.Installation via Maven
========

When using Maven, add the following block to the _pom.xml_ file.
The driver version can either be declared as a property (as in the first example) or as an explicit version number (as in the second).

[source, xml, subs="attributes, specialcharacters"]
----
<dependencies>
    <dependency>
        <groupId>org.neo4j.driver</groupId>
        <artifactId>neo4j-java-driver</artifactId>
        <version>$JAVA_DRIVER_VERSION</version>
    </dependency>
</dependencies>
----

In the following example, driver version {java-driver-version} is added.

[source, xml, subs="attributes, specialcharacters"]
----
<dependencies>
    <dependency>
        <groupId>org.neo4j.driver</groupId>
        <artifactId>neo4j-java-driver</artifactId>
        <version>{java-driver-version}</version>
    </dependency>
</dependencies>
----
========

.Installation via Gradle
========

For Gradle, a compile line will be required. Again, this can use a property or an explicit version number.

[source, groovy, subs="attributes, specialcharacters"]
----
compile 'org.neo4j.driver:neo4j-java-driver:$JAVA_DRIVER_VERSION'
----

In the following example, a driver version {java-driver-version} is added.

[source, groovy, subs="attributes, specialcharacters"]
----
compile 'org.neo4j.driver:neo4j-java-driver:{java-driver-version}'
----
========

The release notes for this driver are available https://github.com/neo4j/neo4j-java-driver/wiki[here].

======

[.include-with-javascript]
======

To use the JavaScript driver, it is recommended employing `npm`.
To find the latest version of the driver, use:

[source, shell, subs="attributes, specialcharacters"]
----
npm show neo4j-driver@* version
----

*Dependencies*

* Babel/Runtime (^7.5.5)
* RxJS (^6.5.2)
* text-encoding-utf-8 (^1.0.2)
* URI-js (^4.2.2)


The JavaScript Reactive API is built and exposed via RxJs.
A dependency of RxJs is automatically installed with the driver.

.Installation via npm
========

To install the latest version of the driver:

[source, shell, subs="attributes, specialcharacters"]
----
npm install neo4j-driver
----

It is also an option to install a certain version of the driver.

[source, shell, subs="attributes, specialcharacters"]
----
npm install neo4j-driver@$JAVASCRIPT-DRIVER-VERSION
----

In the following example, driver version {javascript-driver-version} is installed.

[source, shell, subs="attributes, specialcharacters"]
----
npm install neo4j-driver@{javascript-driver-version}
----
========

The release notes for this driver are available https://github.com/neo4j/neo4j-javascript-driver/wiki[here].

======

[.include-with-python]
======

To find the latest stable version of the Python Driver, visit https://pypi.org/project/neo4j/

To find a list of all available releases, visit https://pypi.org/simple/neo4j/

To install the latest stable version of the Python Driver:
[source, shell, subs="attributes, specialcharacters"]
----
pip install neo4j
----

It is also an option to install a certain version of the driver.

.Installation with Python
========
The following is the syntax for installing a certain version of the Python Driver:
[source, shell, subs="attributes, specialcharacters"]
----
pip install neo4j==$PYTHON_DRIVER_VERSION
----

In the following example we are installing Python Driver version {python-driver-version}.
[source, shell, subs="attributes, specialcharacters"]
----
pip install neo4j=={python-driver-version}
----
========

.Installation with Python, get Python Driver prerelease
========
In the following example we get the latest prerelease version:
[source, shell, subs="attributes, specialcharacters"]
----
pip install neo4 --pre
----
========

The release notes for the Python Driver are available https://github.com/neo4j/neo4j-python-driver/wiki[here]

======

====


[[driver-get-started-hello-world-example]]
== A "Hello World" example

The example below shows the minimal configuration necessary to interact with *Neo4j* through a driver.

[.tabbed-example]
.Hello World
====
[.include-with-dotnet]
======
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=hello-world]
----

// [source, csharp]
// ----
// include::{dotnet-examples}/Examples.cs[tags=hello-world-import]
// ----
======

//[.include-with-go]
//======
//[source, go]
//----
//include::{go-examples}/examples_test.go[tags=hello-world]
//----
//======

[.include-with-java]
======
[source, java]
----
include::{java-examples}/HelloWorldExample.java[tags=hello-world-import]
----

[source, java]
----
include::{java-examples}/HelloWorldExample.java[tags=hello-world]
----
======

[.include-with-javascript]
======
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=hello-world]
----

//[source, javascript]
//----
//include::{javascript-examples}/examples.test.js[tags=hello-world-import]
//----
======

[.include-with-python]
======
[source, python]
----
include::{python-examples}/test_driver_introduction_example.py[tags=driver-introduction-example-import]
----

[source, python]
----
include::{python-examples}/test_driver_introduction_example.py[tags=driver-introduction-example]
----
======

====
