[[driver-session-api]]
= The session API

# tag::abstract[]

[abstract]
--
This section details the Session API that is made available by the driver.
--

# end::abstract[]


[[driver-simple-sessions]]
== Simple sessions

# tag::simple-sessions[]

Simple sessions provide a "classic" *_blocking style_* API for Cypher execution.
In general, simple sessions provide the easiest programming style to work with since API calls are executed in a strictly sequential fashion.

# end::simple-sessions[]


[[driver-simple-lifecycle]]
=== Lifecycle

# tag::simple-lifecycle[]

The session lifetime extends from session construction to session closure.
In languages that support them, simple sessions are usually scoped within a context block; this ensures that they are properly closed and that any underlying connections are released and not leaked.

# end::simple-lifecycle[]

[.tabbed-example]
.Session construction and closure
====
[.include-with-dotnet]
======
[source, csharp ]
----
using (var session = driver.Session(...)) {
    // transactions go here
  }
----
======

[.include-with-java]
======
[source, java]
----
try (Session session = driver.session(...)) {
    // transactions go here
}
----
======

[.include-with-python]
======
[source, python]
----
with driver.session(...) as session:
    // transactions go here
----
======

====

*_Sessions can be configured in a number of different ways_*.
This is carried out by supplying configuration inside the session constructor.
See <<driver-session-configuration>> for more details.


[[driver-simple-transaction-fn]]
=== Transaction functions

# tag::simple-transaction-fn[]

Transaction functions are used for containing transactional units of work.
This form of transaction requires minimal boilerplate code and allows for a clear separation of database queries and application logic.

Transaction functions are also desirable since they encapsulate retry logic and allow for the greatest degree of flexibility when swapping out a single instance of server for a cluster.

Transaction functions can be called as either read or write operations.
This choice will route the transaction to an appropriate server within a clustered environment.
If you are operating in a single instance environment, this routing has no impact. It does give you flexibility if you choose to adopt a clustered environment later on.

Before writing a transaction function *_it is important to ensure that it is designed to be idempotent_*.
This is because a function may be executed multiple times if initial runs fail.

Any query results obtained within a transaction function should be consumed within that function, as connection-bound resources cannot be managed correctly when out of scope.
To that end, transaction functions can return values but these should be derived values rather than raw results.

[NOTE]
====
*_Transaction functions are the recommended form for containing transactional units of work_*.

*_When a transaction fails, the driver retry logic is invoked_*.
For several failure cases, the transaction can be immediately retried against a different server.
These cases include connection issues, server role changes (e.g. leadership elections) and transient errors.
====

# end::simple-transaction-fn[]

[.tabbed-example]
.Transaction function
====
[.include-with-dotnet]
======
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=transaction-function]
----
======

[.include-with-java]
======
[source, java]
----
include::{java-examples}/TransactionFunctionExample.java[tags=transaction-function]
----
======

[.include-with-python]
======
[source, python]
----
include::{python-examples}/test_transaction_function_example.py[tags=transaction-function-import]
----

[source, python]
----
include::{python-examples}/test_transaction_function_example.py[tags=transaction-function]
----
======

====


[[driver-simple-autocommit-transactions]]
=== Auto-commit transactions

# tag::simple-autocommit-transactions[]

An auto-commit transaction is a basic but limited form of transaction.
Such a transaction consists of only one Cypher query and is not automatically retried on failure.
Therefore, any error scenarios will need to be handled by the client application itself.

Auto-commit transactions serve the following purposes:

* simple use cases such as when learning Cypher or writing one-off scripts.
* operations such as batched data load operations, where the driver cannot be aware of the committed state and therefore cannot safely request a retry.
The operator will have to perform a `retry` or `undo` under these circumstances.

[WARNING]
====
The driver does not retry auto-commit queries on failure since it is unaware of what state has been committed at the point of failure.
====

[NOTE]
====
Unlike other kinds of Cypher query, `CALL {} IN TRANSACTIONS` queries do not participate in the causal chain.
Therefore, the only way to execute these queries from a driver is to use auto-commit transactions.

Please refer to the following for more details:

* <<cypher-manual#subquery-call-in-transactions, Cypher Manual -> `CALL {} IN TRANSACTIONS`>>
====

# end::simple-autocommit-transactions[]

[.tabbed-example]
.Simple auto-commit transactions
====

[.include-with-dotnet]
======
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=autocommit-transaction]
----
======

[.include-with-java]
======
[source, java]
----
include::{java-examples}/AutocommitTransactionExample.java[tags=autocommit-transaction]
----
======

[.include-with-python]
======
[source, python]
----
include::{python-examples}/test_autocommit_transaction_example.py[tags=autocommit-transaction-import]
----

[source, python]
----
include::{python-examples}/test_autocommit_transaction_example.py[tags=autocommit-transaction]
----
======

====


[[driver-simple-result-consume]]
=== Consuming results

# tag::simple-result-consume[]

Query results are typically consumed as a stream of records.
The drivers provide a way to iterate through that stream.

# end::simple-result-consume[]

[.tabbed-example]
.Consuming results
====

[.include-with-dotnet]
======
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=result-consume]
----
======

[.include-with-java]
======
[source, java]
----
include::{java-examples}/ResultConsumeExample.java[tags=result-consume]
----
======

[.include-with-python]
======
[source, python]
----
include::{python-examples}/test_result_consume_example.py[tags=result-consume]
----
======

====


[[driver-simple-result-retain]]
=== Retaining results

# tag::simple-result-retain[]

Within a session, *_only one result stream can be active at any one time_*.
Therefore, if the result of one query is not fully consumed before another query is executed, the remainder of the first result will be automatically buffered within the result object.

image::driver-result-buffer.svg[title="Result buffer", role="middle"]

This buffer provides a staging point for results, and divides result handling into *_fetching_* (moving from the network to the buffer) and *_consuming_* (moving from the buffer to the application).

[NOTE]
====
For large results, the result buffer may require a significant amount of memory.

For this reason, *_it is recommended to consume results in order wherever possible_*.
====

Client applications can choose to take control of more advanced query patterns by explicitly retaining results.
Such explicit retention may also be useful when a result needs to be saved for future processing.
The drivers offer support for this process, as per the example below:

# end::simple-result-retain[]

[.tabbed-example]
.Retain results for further processing
====

[.include-with-dotnet]
======
[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=result-retain]
----
======

[.include-with-java]
======
[source, java]
----
include::{java-examples}/ResultRetainExample.java[tags=result-retain]
----
======

[.include-with-python]
======
[source, python]
----
include::{python-examples}/test_result_retain_example.py[tags=result-retain]
----
======

====


[[driver-async-sessions]]
== Asynchronous sessions

# tag::async-sessions[]

Asynchronous sessions provide an API wherein function calls typically return available objects such as futures.
This allows client applications to work within asynchronous frameworks and take advantage of cooperative multitasking.

# end::async-sessions[]


[[driver-async-lifecycle]]
=== Lifecycle

# tag::async-lifecycle[]

Session lifetime begins with session construction.
A session then exists until it is closed, which is typically set to occur after its contained query results have been consumed.

Sessions can be configured in a number of different ways. This is carried out by supplying configuration inside the session constructor.

# end::async-lifecycle[]

See <<driver-session-configuration>> for more details.


[[driver-async-transaction-fn]]
=== Transaction functions

# tag::async-transaction-fn[]

Transaction functions are *_the recommended form for containing transactional units of work_*.
This form of transaction requires minimal boilerplate code and allows for a clear separation of database queries and application logic.
Transaction functions are also desirable since they encapsulate retry logic and allow for the greatest degree of flexibility when swapping out a single instance of server for a cluster.

Functions can be called as either read or write operations.
This choice will route the transaction to an appropriate server within a clustered environment.
If you are in a single instance environment, this routing has no impact but it does give you the flexibility should you choose to later adopt a clustered environment.

Before writing a transaction function it is important to ensure that any side-effects carried out by a transaction function should be designed to be idempotent.
This is because a function may be executed multiple times if initial runs fail.

Any query results obtained within a transaction function should be consumed within that function, as connection-bound resources cannot be managed correctly when out of scope.
To that end, transaction functions can return values but these should be derived values rather than raw results.

[NOTE]
====
When a transaction fails, the driver retry logic is invoked. For several failure cases, the transaction can be immediately retried against a different server.

These cases include connection issues, server role changes (e.g. leadership elections) and transient errors.
Retry logic can be configured when creating a session.
====

# end::async-transaction-fn[]

[.tabbed-example]
.Asynchronous transaction functions
========

[.include-with-dotnet]
======
.Transaction function
[source, csharp]
----
include::{dotnet-examples}/ExamplesAsync.cs[tags=async-transaction-function]
----
======

[.include-with-java]
======
.Transaction function
[source, java]
----
include::{java-examples}/AsyncTransactionFunctionExample.java[tags=async-transaction-function]
----
======

[.include-with-javascript]
======
.Transaction function
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=async-transaction-function]
----
======

========


[[driver-async-autocommit-transactions]]
=== Auto-commit transactions

# tag::async-autocommit-transactions[]

An auto-commit transaction is a basic but limited form of transaction.
Such a transaction consists of only one Cypher query and is not automatically retried on failure.
Therefore, any error scenarios will need to be handled by the client application itself.

Auto-commit transactions serve two purposes:

* simple use cases such as when learning Cypher or writing one-off scripts.
* operations such as batched data load operations, where the driver cannot be aware of the committed state and therefore cannot safely request a retry.
The operator will have to perform a `retry` or `undo` under these circumstances.

[WARNING]
====
The driver does not retry auto-commit queries on failure since it is unaware of what state has been committed at the point of failure.
====

[NOTE]
====
Unlike other kinds of Cypher Query, `CALL {} IN TRANSACTIONS` queries do not participate in the causal chain.
Therefore, the only way to execute these queries from a driver is to use auto-commit transactions.

Please refer to the following for more details:

* <<cypher-manual#subquery-call-in-transactions, Cypher Manual -> `CALL {} IN TRANSACTIONS`>>
====

# end::async-autocommit-transactions[]

[.tabbed-example]
.Asynchronous auto-commit transactions
========

[.include-with-dotnet]
======
.Auto-commit transaction
[source, csharp]
----
include::{dotnet-examples}/ExamplesAsync.cs[tags=async-autocommit-transaction]
----
======

[.include-with-java]
======
.Auto-commit transaction
[source, java]
----
include::{java-examples}/AsyncAutocommitTransactionExample.java[tags=async-autocommit-transaction]
----
======

[.include-with-javascript]
======
.Auto-commit transaction
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=async-autocommit-transaction]
----
======

========


[[driver-async-result-consume]]
=== Consuming results

# tag::async-result-consume[]

The asynchronous session API provides language-idiomatic methods to aid integration with asynchronous applications and frameworks.

# end::async-result-consume[]

[.tabbed-example]
.Asynchronous consuming results
========

[.include-with-dotnet]
======
.Consuming results
[source, csharp]
----
include::{dotnet-examples}/ExamplesAsync.cs[tags=async-result-consume]
----
======

[.include-with-java]
======
.Consuming results
[source, java]
----
include::{java-examples}/AsyncResultConsumeExample.java[tags=async-result-consume]
----
======

[.include-with-javascript]
======
.Consuming results
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=async-result-consume]
----
======

[[driver-async-multiple-transactions]]
=== Combining Transactions

# tag::async-multiple-tx[]

The driver provides a language idiomatic way to combine multiple transactions within a single asynchronous session.

# end::async-multiple-tx[]

========


[[driver-rx-sessions]]
== Reactive Sessions

# tag::rx-sessions[]

Starting with *Neo4j 4.0*, the reactive processing of queries is supported.
This can be achieved through reactive sessions.
Reactive sessions allow for dynamic management of the data that is being exchanged between the driver and the server.

Typical of reactive programming, consumers control the rate at which they consume records from queries and the driver in turn manages the rate at which records are requested from the server.
Flow control is supported throughout the entire Neo4j stack, meaning that the query engine responds correctly to the flow control signals.
This results in far more efficient resource handling and ensures that the receiving side is not forced to buffer arbitrary amounts of data.

For more information about reactive stream, please see the following:

*  https://www.reactivemanifesto.org/[The Reactive Manifesto]
*  https://www.reactive-streams.org[Reactive Streams for JVM and JavaScript]
*  https://projectreactor.io/docs/core/release/reference/[Project Reactor reference documentation]
*  http://introtorx.com/[Introduction to Reactive Extensions to .NET]

# end::rx-sessions[]

[NOTE]
--
Reactive sessions will typically be used in a client application that is already oriented towards the reactive style; it is expected that a reactive dependency or framework is in place.

Refer to <<driver-get-started>> for more information on recommended dependencies.
--


[[driver-rx-lifecycle]]
=== Lifecycle

# tag::rx-lifecycle[]

Session lifetime begins with session construction.
A session then exists until it is closed, which is typically set to occur after its contained query results have been consumed.

# end::rx-lifecycle[]


[[driver-rx-transaction-fn]]
=== Transaction functions

# tag::rx-transaction-fn[]

This form of transaction requires minimal boilerplate code and allows for a clear separation of database queries and application logic.
Transaction functions are also desirable since they encapsulate retry logic and allow for the greatest degree of flexibility when swapping out a single instance of server for a cluster.

Functions can be called as either read or write operations.
This choice will route the transaction to an appropriate server within a clustered environment.
If you are in a single instance environment, this routing has no impact but it does give you the flexibility should you choose to later adopt a clustered environment.

Before writing a transaction function it is important to ensure that any side-effects carried out by a transaction function should be designed to be idempotent.
This is because a function may be executed multiple times if initial runs fail.

Any query results obtained within a transaction function should be consumed within that function, as connection-bound resources cannot be managed correctly when out of scope.
To that end, transaction functions can return values but these should be derived values rather than raw results.

[NOTE]
When a transaction fails, the driver retry logic is invoked.
For several failure cases, the transaction can be immediately retried against a different server.
These cases include connection issues, server role changes (e.g. leadership elections) and transient errors.
Retry logic can be configured when creating a session.

# end::rx-transaction-fn[]

[.tabbed-example]
.Reactive transaction functions
========

[.include-with-dotnet]
======
.Reactive transaction function
[source, csharp]
----
include::{dotnet-examples}/ExamplesRx.cs[tags=rx-transaction-function]
----
======

[.include-with-java]
======
.Reactive transaction function
[source, java]
----
include::{java-examples}/RxTransactionFunctionExample.java[tags=rx-transaction-function]
----
======

[.include-with-javascript]
======
.Reactive transaction function
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=rx-transaction-function]
----
======

========

Sessions can be configured in a number of different ways.
This is carried out by supplying configuration inside the session constructor.
See <<driver-session-configuration>> for more details.


[[driver-rx-autocommit-transactions]]
=== Auto-commit transactions

# tag::rx-autocommit-transactions[]

An auto-commit transaction is a basic but limited form of transaction.
Such a transaction consists of only one Cypher query and is not automatically retried on failure.
Therefore, any error scenarios will need to be handled by the client application itself.

Auto-commit transactions serve two purposes:

* simple use cases such as when learning Cypher or writing one-off scripts.
* operations such as batched data load operations, where the driver cannot be aware of the committed state and therefore cannot safely request a retry. The operator will have to perform a `retry` or `undo` under these circumstances.

[WARNING]
====
The driver does not retry auto-commit queries on failure since it is unaware of what state has been committed at the point of failure.
====

[NOTE]
====
Unlike other kinds of Cypher Query, `CALL {} IN TRANSACTIONS` queries do not participate in the causal chain.
Therefore, the only way to execute these queries from a driver is to use auto-commit transactions.

Please refer to the following for more details:

* <<cypher-manual#subquery-call-in-transactions, Cypher Manual -> `CALL {} IN TRANSACTIONS`>>
====

# end::rx-autocommit-transactions[]

[.tabbed-example]
.Reactive auto-commit transactions
========

[.include-with-dotnet]
======
.Auto-commit transactions
[source, csharp]
----
include::{dotnet-examples}/ExamplesRx.cs[tags=rx-autocommit-transaction]
----
======

[.include-with-java]
======
.Auto-commit transactions
[source, java]
----
include::{java-examples}/RxAutocommitTransactionExample.java[tags=rx-autocommit-transaction]
----
======

[.include-with-javascript]
======
.Auto-commit transactions
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=rx-autocommit-transaction]
----
======

========


[[driver-rx-result-consume]]
=== Consuming results

# tag::rx-result-consume[]

To consume data from a query in a reactive session, a subscriber is required to handle the results that are being returned by the publisher.

Each transaction corresponds to a data flow which supplies the data from the server.
Result processing begins when records are pulled from this flow.
Only one subscriber may pull data from a given flow.

# end::rx-result-consume[]

[.tabbed-example]
.Reactive consuming results
========

[.include-with-dotnet]
======
.Consuming results
[source, csharp]
----
include::{dotnet-examples}/ExamplesRx.cs[tags=rx-result-consume]
----
======

[.include-with-java]
======
.Consuming results
[source, java]
----
include::{java-examples}/RxResultConsumeExample.java[tags=rx-result-consume]
----
======

[.include-with-javascript]
======
.Consuming results
[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=rx-result-consume]
----
======

========


[[driver-rx-cancellation]]
=== Cancellation

# tag::rx-cancellation[]

As per the reactive stream specification, a reactive data flow can be cancelled part way through.
This prematurely commits or rolls back the transaction and stops the query engine from producing any more records.

# end::rx-cancellation[]


[[driver-session-configuration]]
== Session configuration

# tag::Bookmarks[]

[.compact]
`Bookmarks`::
The mechanism which ensures causal consistency between transactions within a session.
Bookmarks are implicitly passed between transactions within a single session to meet the causal consistency requirements.
There may be scenarios where you might want to use the bookmark from one session in a different new session.
+
*Default:* None (Sessions will initially be created without a bookmark)

# end::Bookmarks[]

# tag::DefaultAccessMode[]

`DefaultAccessMode`::
A fallback for the access mode setting when transaction functions are not used.
Typically, access mode is set per transaction by calling the appropriate transaction function method.
In other cases, this setting is inherited. Note that transaction functions will ignore/override this setting.
+
*Default:* Write

# end::DefaultAccessMode[]

# tag::Database[]

`Database`::
The database with which the session will interact.
When you are working with a database which is not the default (i.e. the `system` database or another database in Neo4j 4.0 Enterprise Edition), you can explicitly configure the database which the driver is executing transactions against.
+
[WARNING]
====
The resolution of database aliases occurs at connection creation time, which is not under the control of the session.
It is therefore not recommended to alter database aliases while there are live sessions.
The per-user home database is resolved at session creation and when first impersonating a user.
Therefore, the creation of a new session is necessary to reflect a changed home database.
====
+
See <<operations-manual#manage-databases-default, Operations Manual -> The default database>> for more information on databases.
+
See below and <<cypher-manual#access-control-dbms-administration-impersonation, Cypher Manual -> The `DBMS IMPERSONATE` privileges>> for more information on impersonation.
+
*Default:* the default database as configured on the server.

# end::Database[]

`Fetch Size`::
The number of records to fetch in each batch from the server.
Neo4j 4.0 introduces the ability to pull records in batches, allowing the client application to take control of data population and apply back pressure to the server.
This `FetchSize` applies to <<driver-simple-sessions, simple sessions>> and <<driver-async-sessions, async-sessions>> whereas reactive sessions can be controlled directly using the request method of the subscription.
+
*Default:* 1000 records

# tag::ImpersonatedUser[]

`ImpersonatedUser`::
Users can run transactions against the database as different users if they have been granted explicit permission for doing so.
When impersonating a user, the query is run within the complete security context of the impersonated user and not the authenticated user (i.e., home database, permissions, etc.).
+
See <<operations-manual#manage-databases-home, Operations Manual -> Per-user home databases>> for more information on default database per-user.
+
*Default:* None (Sessions will be created with the logged user)

# end::ImpersonatedUser[]


# tag::TransactionConfiguration[]

[[driver-transaction-configuration]]
== Transaction configuration

Additional configuration can be provided to transaction which are executed.

# end::TransactionConfiguration[]

# tag::TransactionTimeout[]

=== Transaction Timeout

A timeout value can be provided and transactions which take longer than this value to execute on the server will be terminated.
This value will override the value set by `+dbms.transaction.timeout+`. If no value is provided, the default is taken by the server setting
(see <<operations-manual#transaction-management, Operations Manual -> Transaction Management>>).

Note: Using with Neo4j 4.1 and earlier it is possible for the driver to override any value set with `+dbms.transaction.timeout+`.
In 4.2 and later, `+dbms.transaction.timeout+` also acts as a maximum which the driver cannot override. For example, with
a server setting of `+dbms.transaction.timeout=10s+` the driver can specify a shorter timeout (e.g. 5 seconds) but not a value
greater than 10 seconds. If a greater value is supplied the transaction will still timeout after 10 seconds.

*Default:* Configured on server with `+dbms.transaction.timeout+`.

# end::TransactionTimeout[]

# tag::TransactionMetadata[]

=== Metadata

Transactions can be tagged with metadata which will be attached to the executing transaction and visible in various output when listing
transactions and queries as well as appearing in the query log.

*Default:* None.

# end::TransactionMetadata[]
