[[get-the-driver]]
=== Get the driver

You can download the driver source or acquire it with one of the dependency managers of your language.

[[versions]]
==== Versions

Each version of a Driver supports up to four different versions of the Bolt protocol.
This means, that for immediate future each driver version will work with all available version of the protocol.
Once we start seeing Drivers that no longer support older versions of Bolt,
  we will make this information available here as an accessible overview.

==== Download

To dowload the driver do

[.tabbed-example]
.Download
====
[source, cs]
----
COMING SOON
----

// [source,java+maven]
[source,java]
----
<dependencies>
    <dependency>
        <groupId>org.neo4j.driver</groupId>
        <artifactId>neo4j-java-driver</artifactId>
        <version>1.0-SNAPSHOT</version>
    </dependency>
</dependencies>

<repositories>
    <repository>
        <id>neo4j-snapshot-repository</id>
        <name>Neo4j Maven 2 snapshot repository</name>
        <url>http://m2.neo4j.org/content/repositories/snapshots</url>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
        <releases>
            <enabled>false</enabled>
        </releases>
    </repository>
</repositories>
----

// [source,java]
// ----
// NB this is not a valid build script
// defaultTasks 'driver'

// def projectVersion = '1.0'

// buildscript {
//     dependencies {
//         ext {
//             gradleVersion = '2.9'
//             neo4jVersion = '2.3.1'
//             neo4jDriverVersion = '1.0.0-SNAPSHOT'
//         }

//         classpath "org.neo4j:neo4j:$neo4jVersion"
//         classpath "org.neo4j.driver:neo4j-java-driver:$neo4jDriverVersion"
//     }

//     repositories {
//         jcenter()
//     }
// }

// ----

[source,javascript]
----
var neo4j = require('lib/neo4j');
----

[source,python]
----
pip install neo4j-driver
----
====

