[[driver-use-the-driver]]
= Use the driver

Each Neo4j driver has a database object for creating a driver.
To use a driver, follow this pattern:

. Ask the _database_ object for a new driver.
. Ask the _driver_ object for a new session.
. Use the _session_ object to run statements.
  It returns an object representing the results.
. Process the _results_.
. Close the session.

[.tabbed-example]
.Example: Use the driver
====
[.include-with-dotnet]
======
For a minimal working example, the following imports are necessary.

[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=minimal-example-import]
----

These can then be used to run a statement against the server.

[source, csharp]
----
include::{dotnet-examples}/Examples.cs[tags=minimal-example]
----
======

[.include-with-java]
======
For a minimal working example, the following imports are necessary.

[source, java]
----
include::{java-examples}/MinimalWorkingExample.java[tags=minimal-example-import]
----

These can then be used to run a statement against the server.

[source, java]
----
include::{java-examples}/MinimalWorkingExample.java[tags=minimal-example]
----
======

[.include-with-javascript]
======
For a minimal working example, the following imports are necessary.

[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=minimal-example-import]
----

These can then be used to run a statement against the server.

[source, javascript]
----
include::{javascript-examples}/examples.test.js[tags=minimal-example]
----
======

[.include-with-python]
======
For a minimal working example, the following imports are necessary.

[source, python]
----
include::{python-examples}/test_examples.py[tags=minimal-example-import]
----

These can then be used to run a statement against the server.

[source, python]
----
include::{python-examples}/test_examples.py[tags=minimal-example]
----
======
====

As seen above, it is possible to run statements directly from the session object.
The session will take care of opening and closing the transaction.
The session also provides the opportunity for a user to manage the transaction explicitly.
See <<driver-transactions>> for details.
