[[use-the-driver]]
= Use the driver

Each Neo4j Driver has a database object for creating a driver.
To use a driver, follow this pattern:

. Ask the _database_ object for a new driver.
. Ask the _driver_ object for a new session.
. Use the _session_ object to run statements.
  It returns an object representing the results.
. Process the _results_.

[NOTE]
Remember to exhaust the returned results so that the session is ready to run the next statement!

[.tabbed-example]
.Usage example
====
[include-with-java]
--
[source,java]
----
COMING SOON
----
--

[include-with-javascript]
--
[source,javascript]
----
COMING SOON
----
--

[include-with-python]
--
[source,python]
----
COMING SOON
----
--
====

As seen above, it is possible to run statements directly from the session object.
The session will take care of opening and closing the transaction.
The session also provides the opportunity for a user to manage the transaction.
When explicitly told to begin a new transaction, the session will return a transaction object.
The transaction object allows for fine-grained transaction control.
See <<transactions>> for details.
