= Run non-blocking asynchronous queries

The examples in xref:query-simple.adoc[Query the database] and xref:transactions.adoc[Run your own transactions] use the driver in a synchronous way. 
This means that, when running a query against the database, your application waits for the server to retrieve all the results and transmit them to the driver. 
This is not a problem for most use cases, but for queries that have a long processing time or a large result set, asynchronous handling may speed up your application.

You may run an asynchronous transaction through an link:https://neo4j.com/docs/api/java-driver/current/org.neo4j.driver/org/neo4j/driver/async/AsyncSession.html[`AsyncSession`]. 
The flow is similar to that of regular xref:transactions.adoc[transactions], except that transaction functions return a link:https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/concurrent/CompletionStage.html[`CompletionStage`] object (which may be further converted into link:https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/concurrent/CompletableFuture.html[`CompletableFuture`]).


[source, java]
----
package demo;

import java.util.Map;
import java.util.concurrent.CompletionStage;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutionException;

import org.neo4j.driver.async.AsyncSession;
import org.neo4j.driver.AuthTokens;
import org.neo4j.driver.Driver;
import org.neo4j.driver.GraphDatabase;
import org.neo4j.driver.summary.ResultSummary;
import org.neo4j.driver.SessionConfig;

public class App {

    public static void main(String... args) throws ExecutionException, InterruptedException {
        final String dbUri = "neo4j://localhost";
        final String dbUser = "neo4j";
        final String dbPassword = "verysecret";

        try (var driver = GraphDatabase.driver(dbUri, AuthTokens.basic(dbUser, dbPassword))) {  // <1>
            driver.verifyConnectivity();
            var summary = printAllProducts(driver);
            // Block as long as necessary
            System.out.println(summary.get());  // <8>
        }
    }

    public static CompletableFuture<ResultSummary> printAllProducts(Driver driver) {
        var session = driver.session(AsyncSession.class, SessionConfig.builder().withDatabase("neo4j").build());  // <2>
        
        var query = "MERGE (p:Person {name: $name}) RETURN p.name";
        var parameters = Map.of("name", "Olivia");
        var summary = session.executeWriteAsync(tx -> {
            tx.runAsync(query, parameters) // <3>
            .thenCompose(resCursor -> resCursor.forEachAsync(record -> {  // <4>
                System.out.println(record.get(0).asString());
            }))
        })
        .whenComplete((result, error) -> {  // <5>
            session.closeAsync();
        })
        .toCompletableFuture();  // <6>

        return summary;  // <7>
    }
}
----

<1> Driver creation is the same in the synchronous and asynchronous versions.
<2> An asynchronous session is created by providing `AsyncSession.class` as first parameter to link:https://neo4j.com/docs/api/java-driver/current/org.neo4j.driver/org/neo4j/driver/Driver.html#session(java.lang.Class,org.neo4j.driver.SessionConfig)[`Driver.session()`].
<3> As for regular transactions, `.executeWriteAsync()` (and `executeReadAsync()`) take a transaction function callback. 
Inside the transaction function, run queries with link:https://neo4j.com/docs/api/java-driver/current/org.neo4j.driver/org/neo4j/driver/async/AsyncQueryRunner.html#runAsync(org.neo4j.driver.Query)[`.runAsync()`]. 
Each query run returns a link:https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/concurrent/CompletionStage.html[`CompletionStage`].
<4> Optionally use methods on `CompletionStage` to process the result in the asynchronous runner.
The query's result set is available as an link:https://neo4j.com/docs/api/java-driver/current/org.neo4j.driver/org/neo4j/driver/internal/cursor/AsyncResultCursor.html[`AsyncResultCursor`], which implements a similar set of methods for processing the result to those of synchronous transactions (see xref:transactions.adoc#process-result[Transactions -- Process query results]). +
Inner object types are the same as the synchronous case (i.e. `Record`, `ResultSummary`).
<5> Optionally run operations once the query has completed, such as closing the driver session.
<6> link:https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/concurrent/CompletableFuture.html[`CompletableFuture`] is a convenient type to return back to the caller.
<7> Contrary to synchronous transactions, `.executeWriteAsync()` and `executeReadAsync()` return the xref:result-summary.adoc[result summary] only.
**Result processing and handling must be done inside the asynchronous runner.**
<8> link:https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/concurrent/CompletableFuture.html#get()[`.get()`] waits as long as necessary for the future to complete, and then returns its result.


ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::{common-partial}/glossary.adoc[]
include::../partials/glossary.adoc[]
endif::[]
