= Connection

Once you have xref:install.adoc#install-driver[installed the driver] and have xref:install.adoc#get-an-instance[a running Neo4j instance], you are ready to connect your application to the database.


== Connect to the database

You connect to a database by creating a <<Driver>> object and providing a URL and an authentication token.

[source, java, role=nocollapse]
----
package demo;

import org.neo4j.driver.AuthTokens;
import org.neo4j.driver.GraphDatabase;

public class App {

    public static void main(String... args) {

        // URI examples: "neo4j://localhost", "neo4j+s://xxx.databases.neo4j.io"
        final String dbUri = "<URI for Neo4j database>";
        final String dbUser = "<Username>";
        final String dbPassword = "<Password>";

        try (var driver = GraphDatabase.driver(dbUri, AuthTokens.basic(dbUser, dbPassword))) {  // <1>
            driver.verifyConnectivity();  // <2>
        }
    }
}
----

<1> Creating a `Driver` instance only provides information on _how_ to access the database, but does not actually _establish_ a connection.
Connection is instead deferred to when the first query is executed.
<2> To verify immediately that the driver can connect to the database (valid credentials, compatible versions, etc), use the `.verifyConnectivity()` method after initializing the driver.

Both the creation of a `Driver` object and the connection verification can raise a number of different link:https://neo4j.com/docs/api/java-driver/current/org.neo4j.driver/org/neo4j/driver/exceptions/package-summary.html[exceptions].
Since a connection error is a blocker for any subsequent task, the most common choice is to let the program crash should an exception occur while estabilishing a connection.

`Driver` objects are _immutable_, _thread-safe_, and fairly _expensive to create_.
Share them across threads (but not across processes) and use xref:query-simple#impersonation[impersonation] to query the database with a different user.
If you want to alter a `Driver` configuration, you will need to create a new object.


== Connect to an Aura instance

When you create an <<Aura>> instance, you may download a text file (a so-called _Dotenv file_) containing the connection information to the database in the form of environment variables.
The file has a name of the form `Neo4j-a0a2fa1d-Created-2023-11-06.txt`.

You can either  manually extract the URI and the credentials from that file, or use a third party-module to load them.
We recommend the module link:https://github.com/cdimascio/dotenv-java/[`dotenv-java`] for that purpose.

.Using `dotenv-java` to extract credentials from a Dotenv file
[source, java]
----
package demo;

import io.github.cdimascio.dotenv.Dotenv;

import org.neo4j.driver.AuthTokens;
import org.neo4j.driver.GraphDatabase;

public class App {

    public static void main(String... args) {

        var dotenv = Dotenv.configure()
            //.directory("/path/to/env/file")
            .filename("Neo4j-a0a2fa1d-Created-2023-11-06.txt")
            .load();

        final String dbUri = dotenv.get("NEO4J_URI");
        final String dbUser = dotenv.get("NEO4J_USERNAME");
        final String dbPassword = dotenv.get("NEO4J_PASSWORD");

        try (var driver = GraphDatabase.driver(dbUri, AuthTokens.basic(dbUser, dbPassword))) {
            driver.verifyConnectivity();
        }
    }
}
----

[TIP]
An Aura instance is not conceptually different from any other Neo4j instance, as Aura is simply a _deployment mode_ for Neo4j.
When interacting with a Neo4j database through the driver, it doesn't make a difference whether it is an Aura instance it is working with or a different deployment.


== Close connections

Always close `Driver` objects to free up all allocated resources, even upon unsuccessful connection or runtime errors.
Either create the `Driver` object using the `try-with-resources` statement, or call the `Driver.close()` method explicitly.


== Further connection parameters

For more `Driver` configuration parameters and further connection settings, see xref:connect-advanced.adoc[Advanced connection information].


ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::{common-partial}/glossary.adoc[]
include::../partials/glossary.adoc[]
endif::[]
