= Installation

To start creating a Neo4j Java application, you first need to install the Java driver and get a Neo4j database instance to connect to.

.Server compatibility
[IMPORTANT]
The latest driver in the `6.x` series supports connection to Neo4j instances version 4.4.x, 5.x, 2025.x, and 2026.x.
It is also guaranteed to be forward-compatible with the next major release.

[NOTE]
The driver requires Java 17 or higher.


[#install-driver]
== Install the driver

If you already have a Maven project, you may add the driver as a dependency in your `pom.xml` file:

[source, xml, subs="attributes+"]
----
<dependency>
    <groupId>org.neo4j.driver</groupId>
    <artifactId>neo4j-java-driver</artifactId>
    <version>{java-driver-version-minor}</version>
</dependency>
----

.How to create a Maven project for a Neo4j Java application?
[%collapsible]
====
If you are new to Maven, you may download the xref:attachment$neo4j-demo-app.zip[Neo4j demo app example project] and use it as a base to experiment with the driver and build your application.

The file `App.java` provides a skeleton application.
You may compile and run the project with the commands:

[source, bash]
----
mvn package
java -jar target/neo4j-demo-app-1.0-SNAPSHOT-jar-with-dependencies.jar
----
====

For other dependency management systems, refer to the link:https://central.sonatype.com/artifact/org.neo4j.driver/neo4j-java-driver[driver's package page].

include::{common-partial}/install.adoc[tag=get-an-instance]


ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::{common-partial}/glossary.adoc[]
include::../partials/glossary.adoc[]
endif::[]
