= Performance recommendations

[[target-database]]
== Always specify the target database

*Specify the target database on all queries* with the `.withDatabase()` method, either in xref:query-simple.adoc#_database_selection[`Driver.executableQuery()`] calls or xref:transactions.adoc#_database_selection[when creating new sessions].
If no database is provided, the driver has to send an extra request to the server to figure out what the default database is.
The overhead is minimal for a single query, but becomes significant over hundreds of queries.

[discrete]
=== Good practices

[source, java]
----
driver.executableQuery("<QUERY>")
    .withConfig(QueryConfig.builder().withDatabase("<database-name>").build())
    .execute();
----

[source, java]
----
driver.session(SessionConfig.builder().withDatabase("<database-name>").build());
----

[discrete]
=== Bad practices

[source, java]
----
driver.executableQuery("<QUERY>")
    .execute();
----

[source, java]
----
driver.session();
----


[[transactions-cost]]
== Be aware of the cost of transactions

When submitting queries through xref:query-simple.adoc[`.executableQuery()`] or through xref:transactions.adoc#managed-transactions[`.executeRead/Write()`], the driver wraps them into a <<transaction>>.
This behavior ensures that the database always ends up in a consistent state, regardless of what happens during the execution of a transaction (power outages, software crashes, etc).
As a further robustness layer, the driver also retries failed transactions with an exponential backoff.

Creating a safe execution context around a query yields an overhead that is small, but that adds up as the number of transactions increases.
When each query is sent as a transaction of its own, if one transaction fails and needs to be rolled back, all the other transactions are unaffected.
This is the safest mode of execution with respect to failures, but also the slowest due to the overhead of transactions scaling with the number of queries.

.Each query as a separate transaction (low throughput)
[source, java]
----
for (int i=0; i<1000; i++) {
    driver.executableQuery("<QUERY>")
        .withConfig(QueryConfig.builder().withDatabase("<database-name>").build())
        .execute();
    // or session.executeRead/Write() calls
}
----

A more performant approach is to group all queries into a single transaction.
In this way, the transaction as a whole is isolated from others, but individual queries in the transaction are not isolated, and failure of one results in a rollback of all queries.

.Group queries into one transaction (higher throughput)
[source, java]
----
try (var session = driver.session(SessionConfig.builder().withDatabase("<database-name>").build())) {
    session.executeWriteWithoutResult(tx -> {
        for (int i=0; i<1000; i++) {
            tx.run("<QUERY>");
        }
    });
}
----

An even faster approach is to skip `.executeRead/Write()` and call `.run()` directly on the session.
The queries run as auto-commit transaction, and are still isolated from other concurrent queries, but if any of them fail, they will not be retried.
With this method, you trade some robustness for more throughput, as the queries are shot to the server as fast as it can handle.
One upper limit on the client size is given by the size of the connection pool: each call to `.run()` borrows a connection, so the amount of parallel work is limited by the number of available connections.

.Queries as auto-commit transactions (highest throughput)
[source, java]
----
try (var session = driver.session(SessionConfig.builder().withDatabase("<database-name>").build())) {
    for (int i=0; i<1000; i++) {
        session.run("<QUERY>");
    }
}
----


[[read-mode]]
== Route read queries to cluster readers

In a cluster, *route read queries to any reader node*. You do this by:

- using the method `.withRouting(RoutingControl.READ)` in xref:query-simple.adoc#_request_routing[`Driver.executableQuery()`] calls
- using `Session.executeRead()` instead of `Session.executeWrite()` (for xref:transactions.adoc#managed-transactions[managed transactions])
- using the method xref:transactions.adoc#_request_routing[`.withRouting(RoutingControl.READ)` when creating a new session] (for explicit transactions).

[discrete]
=== Good practices

[source, java]
----
// import org.neo4j.driver.RoutingControl;

driver.executableQuery("MATCH (p:Person) RETURN p")
    .withConfig(QueryConfig.builder()
        .withDatabase("<database-name>")
        .withRouting(RoutingControl.READ)
        .build())
    .execute();
----

[source, java]
----
try (var session = driver.session(SessionConfig.builder().withDatabase("<database-name>").build())) {
    session.executeRead(tx -> {
        var result = tx.run("MATCH (p:Person) RETURN p");
        return result.list();
    });
}
----


[discrete]
=== Bad practices

[source, java]
----
// defaults to routing = writers
driver.executableQuery("MATCH (p:Person) RETURN p")
    .withConfig(QueryConfig.builder()
        .withDatabase("<database-name>")
        .build())
    .execute();
----

[source, java]
----
// don't ask to write on a read-only operation
try (var session = driver.session(SessionConfig.builder().withDatabase("<database-name>").build())) {
    session.executeWrite(tx -> {
        var result = tx.run("MATCH (p:Person) RETURN p");
        return result.list();
    });
}
----


[[indexes]]
== Create indexes

*Create indexes for properties that you often filter against*.
For example, if you often look up `Person` nodes by the `name` property, it is beneficial to create an index on `Person.name`.
You can create indexes with the `CREATE INDEX` Cypher clause, for both nodes and relationships.

.Create an index on Person.name
[source, java]
----
driver.executableQuery("CREATE INDEX person_name FOR (n:Person) ON (n.name)").execute();
----

For more information, see link:{neo4j-docs-base-uri}/cypher-manual/current/indexes-for-search-performance/[Indexes for search performance].


[[profile-queries]]
== Profile queries

link:https://neo4j.com/docs/cypher-manual/current/appendix/tutorials/basic-query-tuning/#_profile_query[*Profile your queries*] to locate queries whose performance can be improved.
You can profile queries by prepending them with `PROFILE`.
The server output is available through the `.profile()` method of the xref:result-summary.adoc[`ResultSummary`] object.

[source, java]
----
var result = driver.executableQuery("PROFILE MATCH (p {name: $name}) RETURN p")
    .withParameters(Map.of("name", "Alice"))
    .withConfig(QueryConfig.builder().withDatabase("<database-name>").build())
    .execute();
var queryPlan = result.summary().profile().arguments().get("string-representation");
System.out.println(queryPlan);

/*
Planner COST
Runtime PIPELINED
Runtime version 5.0
Batch size 128

+-----------------+----------------+----------------+------+---------+----------------+------------------------+-----------+---------------------+
| Operator        | Details        | Estimated Rows | Rows | DB Hits | Memory (Bytes) | Page Cache Hits/Misses | Time (ms) | Pipeline            |
+-----------------+----------------+----------------+------+---------+----------------+------------------------+-----------+---------------------+
| +ProduceResults | p              |              1 |    1 |       3 |                |                        |           |                     |
| |               +----------------+----------------+------+---------+----------------+                        |           |                     |
| +Filter         | p.name = $name |              1 |    1 |       4 |                |                        |           |                     |
| |               +----------------+----------------+------+---------+----------------+                        |           |                     |
| +AllNodesScan   | p              |             10 |    4 |       5 |            120 |                 9160/0 |   108.923 | Fused in Pipeline 0 |
+-----------------+----------------+----------------+------+---------+----------------+------------------------+-----------+---------------------+

Total database accesses: 12, total allocated memory: 184
*/
----

In case some queries are so slow that you are unable to even run them in reasonable times, you can prepend them with `EXPLAIN` instead of `PROFILE`.
This will return the _plan_ that the server would use to run the query, but without executing it.
The server output is available through the `.plan()` method of the xref:result-summary.adoc[`ResultSummary`] object.

[source, java]
----
var result = driver.executableQuery("EXPLAIN MATCH (p {name: $name}) RETURN p")
    .withParameters(Map.of("name", "Alice"))
    .withConfig(QueryConfig.builder().withDatabase("<database-name>").build())
    .execute();
var queryPlan = result.summary().plan().arguments().get("string-representation");
System.out.println(queryPlan);

/*
Planner COST
Runtime PIPELINED
Runtime version 5.0
Batch size 128

+-----------------+----------------+----------------+---------------------+
| Operator        | Details        | Estimated Rows | Pipeline            |
+-----------------+----------------+----------------+---------------------+
| +ProduceResults | p              |              1 |                     |
| |               +----------------+----------------+                     |
| +Filter         | p.name = $name |              1 |                     |
| |               +----------------+----------------+                     |
| +AllNodesScan   | p              |             10 | Fused in Pipeline 0 |
+-----------------+----------------+----------------+---------------------+

Total database accesses: ?
*/
----


[[node-labels]]
== Specify node labels

*Specify node labels* in all queries.
This allows the query planner to work much more efficiently, and to leverage indexes where available.
To learn how to combine labels, see link:https://neo4j.com/docs/cypher-manual/current/patterns/reference/#label-expressions[Cypher -> Label expressions].

[discrete]
=== Good practices

[source, java]
----
driver.executableQuery("MATCH (p:Person|Animal {name: $name}) RETURN p")
    .withParameters(Map.of("name", "Alice"))
    .withConfig(QueryConfig.builder().withDatabase("<database-name>").build())
    .execute();
----

[source, java]
----
try (var session = driver.session(SessionConfig.builder().withDatabase("<database-name>").build())) {
    session.run("MATCH (p:Person|Animal {name: $name}) RETURN p", Map.of("name", "Alice"));
}
----


[discrete]
=== Bad practices

[source, java]
----
driver.executableQuery("MATCH (p {name: $name}) RETURN p")
    .withParameters(Map.of("name", "Alice"))
    .withConfig(QueryConfig.builder().withDatabase("<database-name>").build())
    .execute();
----

[source, java]
----
try (var session = driver.session(SessionConfig.builder().withDatabase("<database-name>").build())) {
    session.run("MATCH (p {name: $name}) RETURN p", Map.of("name", "Alice"));
}
----


[[batch-data-creation]]
== Batch data creation

*Batch queries when creating a lot of records* using the link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/with/[`WITH`] and link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/unwind/[`UNWIND`] Cypher clauses.

[discrete]
=== Good practice

.Submit one single queries with all values inside
[source, java]
----
// Generate a sequence of numbers
int start = 1;
int end = 10000;
List<Map> numbers = new ArrayList<>(end - start + 1);
for (int i=start; i<=end; i++) {
    numbers.add(Map.of("value", i));
}

driver.executableQuery("""
    UNWIND $numbers AS node
    MERGE (:Number {value: node.value})
    """)
    .withParameters(Map.of("numbers", numbers))
    .withConfig(QueryConfig.builder().withDatabase("<database-name>").build())
    .execute();
----

[discrete]
=== Bad practice

.Submit a lot of single queries, one for each value
[source, java]
----
for (int i=1; i<=10000; i++) {
driver.executableQuery("MERGE (:Number {value: $value})")
    .withParameters(Map.of("value", i))
    .withConfig(QueryConfig.builder().withDatabase("<database-name>").build())
    .execute();
}
----

[TIP]
The most efficient way of performing a _first import_ of large amounts of data into a new database is the link:{neo4j-docs-base-uri}/operations-manual/current/tutorial/neo4j-admin-import/[`neo4j-admin database import`] command.
// source:  https://community.neo4j.com/t5/neo4j-graph-platform/improving-data-writing-efficiency-in-python/td-p/39520


[[query-parameters]]
== Use query parameters

*Always use xref:query-simple#query-parameters[query parameters]* instead of hardcoding or concatenating values into queries.
Besides protecting from Cypher injections, this allows to better leverage the database query cache.

[discrete]
=== Good practices

[source, java]
----
driver.executableQuery("MATCH (p:Person {name: $name}) RETURN p")
    .withParameters(Map.of("name", "Alice"))
    .withConfig(QueryConfig.builder().withDatabase("<database-name>").build())
    .execute();
----

[source, java]
----
try (var session = driver.session(SessionConfig.builder().withDatabase("<database-name>").build())) {
    session.run("MATCH (p:Person {name: $name}) RETURN p", Map.of("name", "Alice"));
}
----

[discrete]
=== Bad practices

[source, java]
----
driver.executableQuery("MATCH (p:Person {name: 'Alice'}) RETURN p")
    .withConfig(QueryConfig.builder().withDatabase("<database-name>").build())
    .execute();
// or
String name = "Alice";
driver.executableQuery("MATCH (p:Person {name: '" + name + "'}) RETURN p")
    .withConfig(QueryConfig.builder().withDatabase("<database-name>").build())
    .execute();
----

[source, java]
----
try (var session = driver.session(SessionConfig.builder().withDatabase("<database-name>").build())) {
    session.run("MATCH (p:Person {name: 'Alice'}) RETURN p");
    // or
    String name = "Alice";
    session.run("MATCH (p:Person {name: '" + name + "'}) RETURN p");
}
----


[[concurrency]]
== Concurrency

**Use xref:async.adoc[asynchronous querying]**.
This is likely to be more impactful on performance if you parallelize complex and time-consuming queries in your application, but not so much if you run many simple ones.


[[merge]]
== Use `MERGE` for creation only when needed

The Cypher clause link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/merge/[`MERGE`] is convenient for data creation, as it allows to avoid duplicate data when an exact clone of the given pattern exists.
However, it requires the database to run _two_ queries: it first needs to link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/match/[`MATCH`] the pattern, and only then can it link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/create/[`CREATE`] it (if needed).

If you know already that the data you are inserting is new, avoid using `MERGE` and use `CREATE` directly instead -- this practically halves the number of database queries.


[[filter-notifications]]
== Filter notifications

xref:result-summary.adoc#_filter_notifications[Filter the category and/or severity of notifications] the server should raise.


ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::{common-partial}/glossary.adoc[]
include::../partials/glossary.adoc[]
endif::[]
