= Further query mechanisms

[[implicit-transactions]]
== Implicit (or auto-commit) transactions

[TIP]
Implicit transactions are the only ones that can be used for link:{neo4j-docs-base-uri}/cypher-manual/current/subqueries/subqueries-in-transactions[`CALL { ... } IN TRANSACTIONS`] queries.

Implicit transactions are the most basic and limited form of transactions.
Contrary to xref:query-simple.adoc[`.execute_query()`] and xref:transactions#managed-transactions[managed transactions], implicit transactions offer limited guarantees of automatic retrial.
As of version 6.1, implicit transactions are retried once on errors marked as idempotent by the server.
You can disable auto-retry on implicit transactions via the configuration method link:https://neo4j.com/docs/api/java-driver/6.1/org.neo4j.driver/org/neo4j/driver/Config.ConfigBuilder.html#withAutoCommitRetriesDisabled(boolean)[`.withAutoCommitRetriesDisabled()`] both at the driver and session level.

You run an implicit transaction with the method `Session.run()`.
It returns a link:https://neo4j.com/docs/api/java-driver/current/org.neo4j.driver/org/neo4j/driver/Result.html[`Result`] object that needs to be xref:transactions#process-result[processed accordingly].

[source, java]
----
// import java.util.Map
// import org.neo4j.driver.SessionConfig

try (var session = driver.session(SessionConfig.builder().withDatabase("<database-name>").build())) {
    session.run("CREATE (a:Person {name: $name})", Map.of("name", "Licia"));
}
----

To ensure an implicit transaction is committed, consume all records (either by calling `.consume()` on its result or by iterating over all records).
Not consuming all records yields potentially surprising behavior: there is no guarantee on when exactly an implicit transaction will be committed during the lifetime of a session.

Since the driver cannot figure out whether the query in a `Session.run()` call requires a read or write session with the database, it defaults to write.
If your implicit transaction contains read queries only, there is a performance gain in xref:transactions#_request_routing[making the driver aware] through the config method `.withRouting(RoutingControl.READ)` when creating the session.


=== Import CSV files

The most common use case for using `Session.run()` is for importing large CSV files into the database with the link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/load-csv[`LOAD CSV`] Cypher clause, and preventing timeout errors due to the size of the transaction.

.Import CSV data into a Neo4j database
[source, java]
----
// import java.util.Map
// import org.neo4j.driver.SessionConfig

try (var session = driver.session(SessionConfig.builder().withDatabase("<database-name>").build())) {
    var result = session.run("""
        LOAD CSV FROM 'https://data.neo4j.com/bands/artists.csv' AS line
        CALL {
            WITH line
            MERGE (:Artist {name: line[1], age: toInteger(line[2])})
        } IN TRANSACTIONS OF 2 ROWS
    """);
    var summary = result.consume();
    System.out.println(summary.counters());
}
----

[NOTE]
While `LOAD CSV` can be a convenience, there is nothing _wrong_ in deferring the parsing of the CSV file to your Java application and avoiding `LOAD CSV`.
In fact, moving the parsing logic to the application can give you more control over the importing process.
For efficient bulk data insertion, see xref:performance.adoc#batch-data-creation[Performance -> Batch data creation].

For more information, see link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/load-csv/[Cypher -> Clauses -> LOAD CSV].


=== Transaction configuration

You can exert further control on implicit transactions by providing a link:https://neo4j.com/docs/api/java-driver/current/org.neo4j.driver/org/neo4j/driver/TransactionConfig.html[`TransactionConfig`] object as optional last parameter to `Session.run()` calls.
The configuration callbacks allow to specify a query timeout and to attach metadata to the transaction.
For more information, see xref:transactions.adoc#_transaction_configuration[Transactions -> Transaction configuration].

[source, java]
----
// import java.util.Map
// import java.time.Duration
// import org.neo4j.driver.SessionConfig
// import org.neo4j.driver.TransactionConfig

try (var session = driver.session(SessionConfig.builder().withDatabase("<database-name>").build())) {
    var result = session.run("CREATE (a:Person {name: $name})", Map.of("name", "John"),
        TransactionConfig.builder()
            .withTimeout(Duration.ofSeconds(5))
            .withMetadata(Map.of("appName", "peopleTracker"))
            .build()
    );
}
----


== Dynamic values in property keys, relationship types, and labels

In general, you should not concatenate parameters directly into a query, but rather use xref:query-simple#query-parameters[query parameters].
There can however be circumstances where your query structure prevents the usage of parameters in all its parts.
In fact, although parameters work for literals and expressions, as well as link:https://neo4j.com/docs/cypher-manual/current/clauses/match/#dynamic-match[node labels and relationship types], they can't be used for property keys, so `MATCH (n) WHERE n.$param = 'something'` is invalid.

When using string concatenation, enclose the dynamic values in backticks and escape them yourself to protect against link:https://neo4j.com/developer/kb/protecting-against-cypher-injection/[Cypher injections].
Notice that Cypher processes Unicode, so take care of the Unicode literal `\u0060` as well.

.Manually escaping dynamic property keys before concatenation.
[source, java]
----
// import org.neo4j.driver.QueryConfig;

var dangerousKey = "name\\u0060n";
// convert \u0060 to literal backtick and then escape backticks
var escapedKey = dangerousKey.replace("\\u0060", "`").replace("`", "``");

var result = driver.executableQuery("MATCH (p:Person {`' + escapedKey + '`: $name}) RETURN p.name")
    .withParameters(Map.of("name", "Alice"))
    .withConfig(QueryConfig.builder().withDatabase("<database-name>").build())
    .execute();

// rewritten to
// MATCH (p:Person {`name```: $name}) RETURN p.name
----

Another workaround to avoid string concatenation is to use <<APOC>> procedures, such as link:{neo4j-docs-base-uri}/apoc/current/overview/apoc.merge/apoc.merge.node/[`apoc.merge.node`], which supports dynamic labels and property keys.

.Using `apoc.merge.node` to create a node with dynamic labels/property keys.
[source, java]
----
// import org.neo4j.driver.QueryConfig;

String propertyKey = "name";
String label = "Person";

var result = driver.executableQuery("CALL apoc.merge.node($labels, $properties)")
    .withParameters(Map.of("labels", List.of(label), "properties", Map.of(propertyKey, "Alice")))
    .withConfig(QueryConfig.builder().withDatabase("<database-name>").build())
    .execute();
----

[NOTE]
If you are running Neo4j in Docker, APOC needs to be enabled when starting the container.
See link:https://neo4j.com/docs/apoc/5/installation/#docker[APOC -> Installation -> Docker].


ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::{common-partial}/glossary.adoc[]
include::../partials/glossary.adoc[]
endif::[]
