= Query the database

Once you have xref:connect.adoc[connected to the database], you can execute <<Cypher>> queries through the method `Driver.executableQuery()`.

[TIP]
`Driver.executableQuery()` was introduced with the version 5.8 of the driver. +
For queries with earlier versions, see xref:transactions.adoc[Run your own transactions].


== Write to the database

To create a node representing a person named `Alice`, use the Cypher clause link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/create/[`CREATE`]:

.Create a node representing a person named `Alice`
[source, java]
----
// import java.util.Map;
// import org.neo4j.driver.QueryConfig;

var result = driver.executableQuery("CREATE (:Person {name: $name})")  // <1>
    .withParameters(Map.of("name", "Alice"))  // <2>
    .withConfig(QueryConfig.builder().withDatabase("neo4j").build())  // clunky  <3>
    .execute();
var summary = result.summary();
System.out.printf("Created %d records in %d ms.%n",
    summary.counters().nodesCreated(),
    summary.resultAvailableAfter(TimeUnit.MILLISECONDS)); // can't default??
----

<1> specifies the Cypher query
<2> is a map of _query parameters_
<3> specifies which database the query should be run against


== Read from the database

To retrieve information from the database, use the Cypher clause link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/match/[`MATCH`]:

.Retrieve all `Person` nodes
[source, java, role=nocollapse]
----
// import org.neo4j.driver.QueryConfig;

var result = driver.executableQuery("MATCH (p:Person) RETURN p.name AS name")
    .withConfig(QueryConfig.builder().withDatabase("neo4j").build())
    .execute();

// Loop through results and do something with them
var records = result.records()  // <1>
records.forEach(r -> {
    System.out.println(r);  // or r.get("name").asString()
});

// Summary information
var summary = result.summary();  // <2>
System.out.printf("The query %s returned %d records in %d ms.%n",
    summary.query(), records.length,
    summary.resultAvailableAfter(TimeUnit.MILLISECONDS));
----

<1> `records` contains the result as a list of link:https://neo4j.com/docs/api/java-driver/current/org.neo4j.driver/org/neo4j/driver/Record.html[`Record`] objects
<2> `summary` contains the xref:result-summary.adoc[summary of execution] returned by the server

[TIP]
Properties inside a link:https://neo4j.com/docs/api/java-driver/current/org.neo4j.driver/org/neo4j/driver/Record.html[`Record`] object are embedded within link:https://neo4j.com/docs/api/java-driver/current/org.neo4j.driver/org/neo4j/driver/Value.html[`Value`] objects.
To extract and cast them to the corresponding Java types, use .`as<type>()` (eg. `.asString()`, `asInt()`, etc).
For example, if the `name` property coming from the database is a string, doing `record.get("name").asString()` will yield the property value as a `String` object.


== Update the database

To update a node's information in the database, use the Cypher clauses link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/match/[`MATCH`] and link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/set/[`SET`]:

.Update node `Alice` to add an `age` property
[source, java]
----
// import java.util.Map;
// import org.neo4j.driver.QueryConfig;

var result = driver.executableQuery("""
    MATCH (p:Person {name: $name})
    SET p.age = $age
    """)
    .withConfig(QueryConfig.builder().withDatabase("neo4j").build())
    .withParameters(Map.of("name", "Alice", "age", 42))
    .execute();
var summary = result.summary();
System.out.println("Query updated the database?");
System.out.println(summary.counters().containsUpdates());
----

To create new nodes and relationships linking it to an already existing node, use a combination of the Cypher clauses `MATCH` and `CREATE`:

.Create a relationship `:KNOWS` between `Alice` and `Bob`
[source, java]
----
// import java.util.Map;
// import org.neo4j.driver.QueryConfig;

var result = driver.executableQuery("""
    MATCH (p:Person {name: $name})
    CREATE (p)-[:KNOWS]->(:Person {name: $friend})
    """)
    .withConfig(QueryConfig.builder().withDatabase("neo4j").build())
    .withParameters(Map.of("name", "Alice", "friend", "Bob"))
    .execute();
var summary = result.summary();
System.out.println("Query updated the database?");
System.out.println(summary.counters().containsUpdates());
----

[WARNING]
====
It might feel tempting to create new relationships with a single `CREATE` clause, such as: +
`CREATE (:Person {name: "Alice"})-[:KNOWS]->(:Person {name: "Bob"})`. +
However, this would result in the creation of an _extra_ `Alice` node, so that you would end up with unintended duplicate records.
To avoid this, always `MATCH` the elements that you want to update, and use the resulting reference in the `CREATE` clause (as shown in the previous example).
See link:https://neo4j.com/developer/kb/understanding-how-merge-works/[Understanding how MERGE works].
====


== Delete from the database
To remove a node and any relationship attached to it, use the Cypher clause link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/delete/[`DETACH DELETE`]:

.Remove the `Alice` node
[source, java]
----
// import java.util.Map;
// import org.neo4j.driver.QueryConfig;

// This does not delete _only_ p, but also all its relationships!
var result = driver.executableQuery("""
    MATCH (p:Person {name: $name})
    DETACH DELETE p
    """)
    .withConfig(QueryConfig.builder().withDatabase("neo4j").build())
    .withParameters(Map.of("name", "Alice"))
    .execute();
var summary = result.summary();
System.out.println("Query updated the database?");
System.out.println(summary.counters().containsUpdates());
----


[#query-parameters]
== Query parameters

*Do not hardcode or concatenate parameters directly into queries*.
Instead, always use placeholders and specify the link:{neo4j-docs-base-uri}/cypher-manual/current/syntax/parameters/[Cypher parameters], as shown in the previous examples.
This is for:

1. *performance benefits*: Neo4j compiles and caches queries, but can only do so if the query structure is unchanged;
2. *security reasons*: see link:https://neo4j.com/developer/kb/protecting-against-cypher-injection/[protecting against Cypher injection].

You may provide query parameters as a map through the `.withParameters()` method.

[source, java]
----
var result = driver.executableQuery("MATCH (p:Person {name: $name})")
    .withParameters(Map.of("name", "Alice"))  // mark-line
    .withConfig(QueryConfig.builder().withDatabase("neo4j").build())
    .execute();
----

[NOTE]
There can be circumstances where your query structure prevents the usage of parameters in all its parts.
For those advanced use cases, see xref:query-advanced#_dynamic_values_in_property_keys_relationship_types_and_labels[Dynamic values in property keys, relationship types, and labels].


== Error handling

Because `.executableQuery()` can potentially raise a number of different link:https://neo4j.com/docs/api/java-driver/current/org.neo4j.driver/org/neo4j/driver/exceptions/package-summary.html[exceptions], the best way to handle errors is to catch all exceptions in a single `try/catch` block:

[source, java]
----
try {
    driver.executableQuery(...).execute()
} catch (Exception as e) {
    ...  // handle exception
}
----

[TIP]
The driver automatically retries to run a failed query, if the failure is deemed to be transient (for example due to temporary server unavailability).


== Query configuration

You can supply further configuration parameters to alter the default behavior of `.executableQuery()`.
You do so through the method `.withConfig()`, which takes a link:https://neo4j.com/docs/api/java-driver/current/org.neo4j.driver/org/neo4j/driver/QueryConfig.html[`QueryConfig`] object.


=== Database selection

It is recommended to *always specify the database explicitly* with the `.withDatabase("<dbName>")` method, even on single-database instances.
This allows the driver to work more efficiently, as it saves a network round-trip to the server to resolve the home database.
If no database is given, the link:{neo4j-docs-base-uri}/operations-manual/current/manage-databases/introduction#manage-databases-default[user's home database] is used.

[source, java]
----
// import org.neo4j.driver.QueryConfig;

var result = driver.executableQuery("MATCH (p:Person) RETURN p.name")
    .withConfig(QueryConfig.builder().withDatabase("neo4j").build())  // mark-line
    .execute();
----

Do not rely on the link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/use/[`USE`] Cypher clause for database selection with the driver.


=== Request routing

In a cluster environment, all queries are directed to the leader node by default.
To improve performance on read queries, you can use the method `.withRouting(RoutingControl.READ)` to route a query to the read nodes.

[source, java]
----
// import org.neo4j.driver.QueryConfig;
// import org.neo4j.driver.RoutingControl;

var result = driver.executableQuery("MATCH (p:Person) RETURN p.name")
    .withConfig(QueryConfig.builder()
        .withDatabase("neo4j")
        .withRouting(RoutingControl.READ)  // mark-line
        .build())
    .execute();
----

Even though routing a _write_ query to _read_ nodes will likely result in a runtime error, xref:transactions#access-control-note[do not rely on this for security purposes].


[#impersonation]
=== Run queries as a different user

You can execute a query under the security context of a different user with the method `.withImpersonatedUser("<username>")`, specifying the name of the user to impersonate.
For this to work, the user under which the `Driver` was created needs to have the link:{neo4j-docs-base-uri}/cypher-manual/current/administration/access-control/dbms-administration#access-control-dbms-administration-impersonation[appropriate permissions].
Impersonating a user is cheaper than creating a new `Driver` object.

[source, java, test-skip]
----
// import org.neo4j.driver.QueryConfig;

var result = driver.executableQuery("MATCH (p:Person) RETURN p.name")
    .withConfig(QueryConfig.builder()
        .withDatabase("neo4j")
        .withImpersonatedUser("somebodyElse")  // mark-line
        .build())
    .execute();
----

When impersonating a user, the query is run within the complete security context of the impersonated user and not the authenticated user (i.e., home database, permissions, etc.).

////
=== Transform query result

You can transform a query's result into a different data structure using the `result_transformer_` argument.
The driver provides built-in methods to transform the result into a pandas dataframe or into a graph, but you can also craft your own transformer.

For more information, see xref:transformers.adoc[Manipulate query results].
////

== A full example

[source, java]
----
package demo;

import java.util.Map;
import java.util.List;
import java.util.concurrent.TimeUnit;

import org.neo4j.driver.AuthTokens;
import org.neo4j.driver.GraphDatabase;
import org.neo4j.driver.Record;
import org.neo4j.driver.QueryConfig;
import org.neo4j.driver.RoutingControl;

public class App {

    private static final String URI = "<URI for Neo4j database>";
    private static final String USER = "<Username>";
    private static final String PASSWORD = "<Password>";

    public static void main(String... args) {

        try (var driver = GraphDatabase.driver(URI, AuthTokens.basic(USER, PASSWORD))) {

            List<Map> people = List.of(
                Map.of("name", "Alice", "age", 42, "friends", Arrays.asList("Bob", "Peter", "Anna")),
                Map.of("name", "Bob", "age", 19),
                Map.of("name", "Peter", "age", 50),
                Map.of("name", "Anna", "age", 30)
            );

            try {

                //Create some nodes
                people.forEach(person -> {
                    var result = driver.executableQuery("CREATE (p:Person {name: $person.name, age: $person.age})")
                        .withConfig(QueryConfig.builder().withDatabase("neo4j").build())
                        .withParameters(Map.of("person", person))
                        .execute();
                });

                // Create some relationships
                people.forEach(person -> {
                    if(person.containsKey("friends")) {
                        var result = driver.executableQuery("""
                            MATCH (p:Person {name: $person.name})
                            UNWIND $person.friends AS friend_name
                            MATCH (friend:Person {name: friend_name})
                            CREATE (p)-[:KNOWS]->(friend)
                             """)
                            .withConfig(QueryConfig.builder().withDatabase("neo4j").build())
                            .withParameters(Map.of("person", person))
                            .execute();
                    }
                });

                // Retrieve Alice's friends who are under 40
                var result = driver.executableQuery("""
                    MATCH (p:Person {name: $name})-[:KNOWS]-(friend:Person)
                    WHERE friend.age < $age
                    RETURN friend
                     """)
                    .withConfig(QueryConfig.builder()
                        .withDatabase("neo4j")
                        .withRouting(RoutingControl.READ)
                        .build())
                    .withParameters(Map.of("name", "Alice", "age", 40))
                    .execute();

                // Loop through results and do something with them
                result.records().forEach(r -> {
                    System.out.println(r);  // doesn't unwrap properties, Record<{friend: node<4>}>, nor .fields() does
                    // python shows <Record friend=<Node element_id='4:5bad7cf2-d17e-4d07-9266-b88c8720ebd2:4' labels=frozenset({'Person'}) properties={'name': 'Bob', 'age': 19}>>
                });

                // Summary information
                System.out.printf("The query %s returned %d records in %d ms.%n",
                    result.summary().query(), result.records().size(),
                    result.summary().resultAvailableAfter(TimeUnit.MILLISECONDS));

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }
}
----

For more information see link:https://neo4j.com/docs/api/java-driver/current/org.neo4j.driver/org/neo4j/driver/ExecutableQuery.html[API documentation -- Driver.executableQuery()].


ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::{common-partial}/glossary.adoc[]
include::../partials/glossary.adoc[]
endif::[]
