= Control results flow with reactive streams

Typical of reactive programming, in a reactive flow consumers control the rate at which they consume records from queries, and the driver in turn manages the rate at which records are requested from the server.
The reactive API ensures that the receiving side is not forced to buffer arbitrary amounts of data.

The driver's reactive implementation lives in the link:https://neo4j.com/docs/api/java-driver/current/org.neo4j.driver/org/neo4j/driver/reactivestreams/package-summary.html[`reactivestreams` sub-package] and relies on the link:https://projectreactor.io/docs/core/release/reference/[`reactor-core` package] from link:https://projectreactor.io/[Project Reactor].


== Install dependencies

To use reactive features, you need to add the relevant dependencies to your project first (refer to link:https://projectreactor.io/docs/core/release/reference/#getting[Reactor -> Reference -> Getting reactor]).

1. Add Reactor's BOM to your `pom.xml` in a `dependencyManagement` section. Notice that this is in addition to the regular `dependencies` section. If a `dependencyManagement` section already exists in your pom, add only the contents.
+
[source, xml]
----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-bom</artifactId>
            <version>2023.0.2</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
----

2. Add the `reactor-core` dependency to the `dependencies` section. Notice that the version tag is omitted (it is picked up from Reactor's BOM).
+
[source, xml]
----
<dependency>
    <groupId>io.projectreactor</groupId>
    <artifactId>reactor-core</artifactId>
</dependency>
----

== Reactive queries

The basic driver's concepts are the same as the synchronous case, but queries are run through link:https://neo4j.com/docs/api/java-driver/current/org.neo4j.driver/org/neo4j/driver/reactivestreams/ReactiveSession.html[`ReactiveSession`], and the objects related to querying have a reactive counterpart and prefix.

[source, java]
----
package demo;

import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

import org.neo4j.driver.AuthTokens;
import org.neo4j.driver.Driver;
import org.neo4j.driver.GraphDatabase;
import org.neo4j.driver.SessionConfig;
import org.neo4j.driver.reactivestreams.ReactiveResult;
import org.neo4j.driver.reactivestreams.ReactiveSession;

public class App {

    public static void main(String... args) {
        final String dbUri = "neo4j://localhost";
        final String dbUser = "neo4j";
        final String dbPassword = "verysecret";

        try (var driver = GraphDatabase.driver(dbUri, AuthTokens.basic(dbUser, dbPassword))) {
            driver.verifyConnectivity();

            var rxSession = driver.session(
                ReactiveSession.class,  // <1>
                SessionConfig.builder().withDatabase("neo4j").build()
            );
            var rxResult = Mono.fromDirect(rxSession.run("UNWIND range (1, 5) AS x RETURN x")).block();  // <2>
            var records = Flux.from(rxResult.records());  // <3>
            records.subscribe(  // <4>
                record -> System.out.println(record.get("x")),  // <5>
                error -> System.err.println("Error " + error),  // <6>
                () -> System.out.println(Mono.fromDirect(rxResult.consume()).block())  // <7>
            );
            records.doOnComplete(rxSession::close);  // <8>
        }
    }
}
----


[source, java]
----
package demo;

import java.util.Map;

import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

import org.neo4j.driver.AuthTokens;
import org.neo4j.driver.Driver;
import org.neo4j.driver.GraphDatabase;
import org.neo4j.driver.SessionConfig;
import org.neo4j.driver.reactivestreams.ReactiveResult;
import org.neo4j.driver.reactivestreams.ReactiveSession;

public class App {

    public static void main(String... args) {
        final String dbUri = "neo4j://localhost";
        final String dbUser = "neo4j";
        final String dbPassword = "verysecret";

        try (var driver = GraphDatabase.driver(dbUri, AuthTokens.basic(dbUser, dbPassword))) {
            driver.verifyConnectivity();

            var records = Flux.usingWhen(
                Mono.just(driver.session(
                    ReactiveSession.class,
                    SessionConfig.builder().withDatabase("neo4j").build()
                )),
                reactiveSession -> Mono.fromDirect(reactiveSession.executeRead(
                    tx -> Mono
                            .fromDirect(tx.run("UNWIND range (1, 5) AS x RETURN x"))
                            .flatMapMany(ReactiveResult::records)
                )),
                ReactiveSession::close
            );

            // block for demonstration purposes
            var values = records.map(record -> record.get("x")).collectList().block();
            System.out.println(values);
        }
    }
}
----

.condensed
[source, java]
----
void demoSessionRun() {
        var config = Config.builder()
                .withLogging(Logging.console(Level.FINE))
                .build();
        var driver = GraphDatabase.driver(neo4j.uri(), neo4j.authTokenManager(), config);
        var records = Flux.usingWhen(
                Mono.just(driver.session(ReactiveSession.class)),
                reactiveSession -> Mono.fromDirect(reactiveSession.run("UNWIND range (1, 5) AS x RETURN x")).flatMapMany(ReactiveResult::records),
                ReactiveSession::close);
        // block for demonstration purposes
        var values = records.map(record -> record.get("x")).collectList().block();
        System.out.println(values);
        driver.close();
    }
----


ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::{common-partial}/glossary.adoc[]
include::../partials/glossary.adoc[]
endif::[]
