:driver-changelog-url: https://github.com/neo4j/neo4j-java-driver/wiki/6.x-changelog

= Upgrade from older versions

This page contains the list of new features and breaking changes of the driver from version 5.28 to to 6.x.
For a full list of changes, see the link:{driver-changelog-url}[Driver -> Changelog].

The latest driver version of the 6.x series is compatible with Neo4j server both 4.4, 5.x, and 202[56].x, so you can upgrade the driver before you upgrade the server.
At the same time, the driver version 5.28 is forward compatible with Neo4j server 202[56].x, so you could also upgrade the server before the driver; however, given that it's easier to roll back an application upgrade than a server upgrade, it's recommended to start with the driver.

[TIP]
When upgrading the Neo4j server to a newer version, the Cypher queries in your application may also need updating. +
See link:https://neo4j.com/docs/cypher-manual/current/deprecations-additions-removals-compatibility/[Cypher -> Deprecations, additions, and compatibility].

[[new-features]]
== New features

[cols="1a,1a"]
|===

|
.Value mapping
[%collapsible]
====
With the xref:value-mapping.adoc[Value Mapping feature], you can declare a Java Record containing the specification of the values your query is expected to return, and ask the driver to use that class to spawn new objects from a query result.
====
|
.New type `Vector`
[%collapsible]
====
The type xref:data-types.adoc#vector[`Vector`] allows for storing and retrieving Cypher `VECTOR` objects to/from the database.
The `VECTOR` type is suitable for efficiently storing lists of homogeneous numbers, such as embeddings.
====

|
.GQL status objects in exceptions
[%collapsible]
====
Exception objects also expose errors as GQL-status objects.
The main difference between Neo4j error codes and GQL error codes is that the latter are more granular.
For more information, see xref:query-simple.adoc#error-handling[Error handling].
====
|
.Unix sockets support
[%collapsible]
====
The new `bolt+unix` URI scheme allows connecting to a Neo4j server over Unix sockets.

For more information, see xref:connect-advanced.adoc#unix-sockets[Connecting through Unix sockets].
====

|
.Netty native transports support
[%collapsible]
====
link:https://netty.io/wiki/native-transports.html[Netty native transports] add features specific to a particular platform, generate less garbage, and generally improve performance when compared to the NIO based transport.

For more information, see xref:performance.adoc#netty-native-transports[Performance -> Switch to Netty native transports].
====
|

|===

////
experimental
|
.TCP Fast Open support
[%collapsible]
====
TCP Fast Open enables the server to send data already during the TCP handshake (either during the Bolt or TLS handshake, depending on the encryption settings).

For more information, see xref:performance.adoc#enable-tfo[Performance -> Enable TCP Fast Open (TFO)].
====
////


[[breaking-changes]]
== Breaking changes and deprecations

Deprecated features are likely to be removed in version 6.

[cols="1,5a,1"]
|===
|Version |Message |Status

|6.0
|link:https://neo4j.com/docs/api/java-driver/{java-driver-version}/org.neo4j.driver/org/neo4j/driver/Session.html[`Session`] -- Methods `.readTransaction()` and `.writeTransaction()` have been removed in favor of `.executeRead()` and `.executeWrite()`.
The same holds for their async conterparts `.executeReadAsync()` and `.executeWriteAsync()`.
The new methods behave similarly, but the argument types are different and the new methods do not support the `.commit()`, `.rollback()`, `.close()`, and `.closed()` methods.
|label:removed[]

|6.0
|link:https://neo4j.com/docs/api/java-driver/{java-driver-version}/org.neo4j.driver/org/neo4j/driver/Session.html[`Session`] -- Method `.lastBookmark()` has been removed in favor of link:https://neo4j.com/docs/api/java-driver/{java-driver-version}/org.neo4j.driver/org/neo4j/driver/Session.html#lastBookmarks()[`.lastBookmarks()`].
|label:removed[]

|5.0
|link:https://neo4j.com/docs/api/java-driver/{java-driver-version}/org.neo4j.driver/org/neo4j/driver/Session.html[`Session`] -- Methods `.asyncSession()` and `reactiveSession()` are deprecated. Use `Session(Class)`, with `Class` controlling what type of session you  wish for.
|label:deprecated[]

|5.0
|Reactive sessions -- Interface link:https://neo4j.com/docs/api/java-driver/{java-driver-version}/org.neo4j.driver/org/neo4j/driver/reactive/RxSession.html[`RxSession`] is deprecated in favor of link:https://neo4j.com/docs/api/java-driver/{java-driver-version}/org.neo4j.driver/org/neo4j/driver/reactive/ReactiveSession.html[`ReactiveSession` (Flow)] and link:https://neo4j.com/docs/api/java-driver/{java-driver-version}/org.neo4j.driver/org/neo4j/driver/reactivestreams/ReactiveSession.html[`ReactiveSession` (reactivestreams)].
|label:deprecated[]

|5.7
|link:https://neo4j.com/docs/api/java-driver/{java-driver-version}/org.neo4j.driver/org/neo4j/driver/summary/Notification.html[`Notification`] -- Method `.severity()` is deprecated. Use `.rawSeverityLevel()` for the raw value and `.severityLevel()` for an enumerated value.
|label:deprecated[]

|5.0
|link:https://neo4j.com/docs/api/java-driver/{java-driver-version}/org.neo4j.driver/org/neo4j/driver/types/Node.html[`Node`], link:https://neo4j.com/docs/api/java-driver/{java-driver-version}/org.neo4j.driver/org/neo4j/driver/types/Relationship.html[`Relationship`] -- Method `.id()` (`long`) is deprecated in favor of `.elementId()` (`string`).
|label:deprecated[]

|5.0
|link:https://neo4j.com/docs/api/java-driver/{java-driver-version}/org.neo4j.driver/org/neo4j/driver/types/Relationship.html[`Relationship`] -- Methods `.startNodeId()` and `.endNodeId()` are deprecated in favor of `.startNodeElementId()` and `.endNodeElementId()`. Old identifiers were `long`, whereas new ElementIds are `string`.
|label:deprecated[]

|===
