// This doc is also sourced in the Aura Developer Hub.
// Because of that, cross-links are absolute,
// source blocks have copy=true , and Antora attributes
// (version) are explicitly resolved.

The Neo4j Javascript driver is the official library to interact with a Neo4j instance through a Javascript application.

At the hearth of Neo4j lies <<Cypher>>, the query language to interact with a Neo4j database.
Although this guide does not _require_ you to be a seasoned Cypher querier, it's easier to focus on the Javascript-specific bits if you know some Cypher already.
You will also get a _gentle_ introduction to Cypher in these pages, but check out link:https://neo4j.com/docs/getting-started/cypher/[Getting started -> Cypher] for a more detailed walkthrough of graph databases modelling and querying if this is your first approach.


[#install]
== Install

Install the Neo4j Javascript driver with `npm`:

[source, bash, copy=true]
----
npm i neo4j-driver@~5.28.0
----

link:https://neo4j.com/docs/javascript-manual/current/install/[More info on installing the driver]


[#connect]
== Connect to the database

Connect to a database by creating a `Driver` object and providing a URL and an authentication token.
Once you have a `Driver` instance, use the `.getServerInfo()` method to ensure that a working connection can be established.

[source, javascript, copy=true]
----
var neo4j = require('neo4j-driver');
(async () => {
  // URI examples: 'neo4j://localhost', 'neo4j+s://xxx.databases.neo4j.io'
  const URI = '<database-uri>'
  const USER = '<username>'
  const PASSWORD = '<password>'
  let driver = neo4j.driver(URI, neo4j.auth.basic(USER, PASSWORD))
  const serverInfo = await driver.getServerInfo()
  console.log('Connection established')
  console.log(serverInfo)

  // Use the driver to run queries

  await driver.close()
})();
----

link:https://neo4j.com/docs/javascript-manual/current/connect/[More info on connecting to a database]


[#create-graph]
== Create an example graph

Run a Cypher query with the method `Driver.executeQuery()`.
Do not hardcode or concatenate parameters: use placeholders and specify the parameters as key-value pairs.

.Create two `Person` nodes and a `KNOWS` relationship between them
[source, javascript, copy=true]
----
let { records, summary } = await driver.executeQuery(`
  CREATE (a:Person {name: $name})
  CREATE (b:Person {name: $friendName})
  CREATE (a)-[:KNOWS]->(b)
  `,
  { name: 'Alice', friendName: 'David' },
  { database: '<database-name>' }
)
console.log(
  `Created ${summary.counters.updates().nodesCreated} nodes ` +
  `in ${summary.resultAvailableAfter} ms.`
)
----

link:https://neo4j.com/docs/javascript-manual/current/query-simple/[More info on querying the database]


[#query-graph]
== Query a graph

To retrieve information from the database, use the Cypher clause `MATCH`:

.Retrieve all `Person` nodes who know other persons
[source, javascript, copy=true]
----
let { records, summary } = await driver.executeQuery(`
  MATCH (p:Person)-[:KNOWS]->(:Person)
  RETURN p.name AS name
  `,
  {},
  { database: '<database-name>' }
)

// Loop through users and do something with them
for(let record of records) {
  console.log(`Person with name: ${record.get('name')}`)
  console.log(`Available properties for this node are: ${record.keys}\n`)
}

// Summary information
console.log(
  `The query \`${summary.query.text}\` ` +
  `returned ${records.length} nodes.\n`
)
----

link:https://neo4j.com/docs/javascript-manual/current/query-simple/[More info on querying the database]


[#close]
== Close connections and sessions

Call the `.close()` method on the `Driver` instance when you are finished with it, to release any resources still held by it.
The same applies to any open sessions.

[source, javascript, copy=true]
----
const driver = neo4j.driver(URI, neo4j.auth.basic(USER, PASSWORD))
let session = driver.session({ database: '<database-name>' })

// session/driver usage

session.close()
driver.close()
----
