The Neo4j JavaScript driver is the official library to interact with a Neo4j instance through a JavaScript application.

At the hearth of Neo4j lies <<Cypher>>, the query language to interact with a Neo4j database.
While this guide does not _require_ you to be a seasoned Cypher querier, it is going to be easier to focus on the JavaScript-specific bits if you already know some Cypher.
For this reason, although this guide does _also_ provide a gentle introduction to Cypher along the way, consider checking out link:https://neo4j.com/docs/getting-started/cypher/[Getting started -> Cypher] for a more detailed walkthrough of graph databases modelling and querying if this is your first approach.
You may then apply that knowledge while following this guide to develop your JavaScript application.


[#install]
== Installation

Install the Neo4j Javascript driver with `npm`:

[source,bash]
----
npm i neo4j-driver
----

xref:install#install-driver[More info on installing the driver ->]


[#connect]
== Connect to the database

Connect to a database by creating a <<Driver>> object and providing a URL and an authentication token.
Once you have a `Driver` instance, use the `.getServerInfo()` method to ensure that a working connection can be established.

[source, javascript]
----
var neo4j = require('neo4j-driver');
(async () => {
  // URI examples: 'neo4j://localhost', 'neo4j+s://xxx.databases.neo4j.io'
  const URI = '<URI to Neo4j database>'
  const USER = '<Username>'
  const PASSWORD = '<Password>'
  let driver

  try {
    driver = neo4j.driver(URI, neo4j.auth.basic(USER, PASSWORD))
    const serverInfo = await driver.getServerInfo()
    console.log('Connection established')
    console.log(serverInfo)
  } catch(err) {
    console.log(`Connection error\n${err}\nCause: ${err.cause}`)
  }
})();
----

xref:connect.adoc[More info on connecting to a database ->]


[#create-graph]
== Create an example graph

Run a Cypher query with the method `Driver.executeQuery()`.
Do not hardcode or concatenate parameters: use placeholders and specify the parameters as key-value pairs.

.Create two `Person` nodes and a `KNOWS` relationship between them
[source, javascript]
----
let { records, summary } = await driver.executeQuery(`
  CREATE (a:Person {name: $name})
  CREATE (b:Person {name: $friendName})
  CREATE (a)-[:KNOWS]->(b)
  `,
  { name: 'Alice', friendName: 'David' },
  { database: 'neo4j' }
)
console.log(
  `Created ${summary.counters.updates().nodesCreated} nodes ` +
  `in ${summary.resultAvailableAfter} ms.`
)
----

xref:query-simple.adoc[More info on querying the database ->]


[#query-graph]
== Query a graph

To retrieve information from the database, use the Cypher clause `MATCH`:

.Retrieve all `Person` nodes who like other `Person` s
[source, javascript]
----
let { records, summary } = await driver.executeQuery(`
  MATCH (p:Person)-[:KNOWS]->(:Person)
  RETURN p.name AS name
  `,
  {},
  { database: 'neo4j' }
)

// Loop through users and do something with them
for(let record of records) {
  console.log(`Person with name: ${record.get('name')}`)
  console.log(`Available properties for this node are: ${record.keys}\n`)
}

// Summary information
console.log(
  `The query \`${summary.query.text}\` ` +
  `returned ${records.length} nodes.\n`
)
----

xref:query-simple.adoc[More info on querying the database ->]


[#close]
== Close connections and sessions

Call the `.close()` method on the `Driver` instance when you are finished with it, to release any resources still held by it.
The same applies to any open sessions.

[source, javascript]
----
const driver = neo4j.driver(URI, neo4j.auth.basic(USER, PASSWORD))
let session = driver.session({ database: 'neo4j' })

// session/driver usage

session.close()
driver.close()
----
