The Neo4j JavaScript driver is the official library to interact with a Neo4j instance through a JavaScript application.

At the hearth of Neo4j lies <<Cypher>>, the query language you use to interact with a Neo4j database.
While this guide does not _require_ you to be a seasoned Cypher querier, it is going to be easier to focus on the JavaScript-specific bits if you already know some Cypher.
For this reason, although this guide does _also_ provide a gentle introduction to Cypher along the way, consider checking out link:{neo4j-docs-base-uri}/getting-started/cypher-intro/[Getting started -> Cypher] for a more detailed walkthrough of graph databases modelling and querying if this is your first approach.
You may then apply that knowledge while following this guide to develop your JavaScript application.


== Installation

Install the Neo4j Javascript driver with `npm`:

[source,bash]
----
npm i neo4j-driver
----

xref:install#install-driver[More info on installing the driver ->]


== Connect to the database

Connect to a database by creating a <<Driver>> object and providing a URL and an authentication token.
Once you have a `Driver` instance, use the `.getServerInfo()` method to ensure that a working connection can be established
by retrieving the server information.

[source, javascript]
----
var neo4j = require('neo4j-driver');
(async () => {
  // URI examples: 'neo4j://localhost', 'neo4j+s://xxx.databases.neo4j.io'
  const URI = '<URI to Neo4j database>'
  const USER = '<Username>'
  const PASSWORD = '<Password>'
  let driver

  try {
    driver = neo4j.driver(URI, neo4j.auth.basic(USER, PASSWORD))
    const serverInfo = await driver.getServerInfo()
    console.log('Connection established')
    console.log(serverInfo)
  } catch(err) {
    console.log(`Connection error\n${err}\nCause: ${err.cause}`)
  }
})();
----

xref:connect.adoc[More info on connecting to a database ->]


== Query the database

Execute a Cypher statement with the method `Driver.executeQuery()`.
Do not hardcode or concatenate parameters: use placeholders and specify the parameters as key-value pairs.

[source, javascript, role=nocollapse]
----
// Get the name of all 42 year-olds
const { records, summary, keys } = await driver.executeQuery(
  'MATCH (p:Person {age: $age}) RETURN p.name AS name',
  { age: 42 },
  { database: 'neo4j' }
)

// Summary information
console.log(
  `>> The query ${summary.query.text} ` +
  `returned ${records.length} records ` +
  `in ${summary.resultAvailableAfter} ms.`
)

// Loop through results and do something with them
console.log('>> Results')
for(record of records) {
  console.log(record.get('name'))
}
----

xref:query-simple.adoc[More info on querying the database ->]


== Run your own transactions

For more advanced use-cases, you can take control of the transaction lifecycle.
A transaction is a unit of work that is either committed in its entirety or rolled back on failure.
Use the methods `Session.executeRead()` and `Session.executeWrite()` to run managed transactions.

[source, javascript, role=nocollapse]
----
let session = driver.session({ database: 'neo4j' })
try {
  const result = await session.executeRead(async tx => {
    return await tx.run(`
      MATCH (p:Person WHERE p.name STARTS WITH $filter)
      RETURN p.name AS name ORDER BY name
      `, { filter: 'Al'}
    )
  })
  console.log(
    `The query ${result.summary.query.text} returned ${result.records.length} nodes.`
  )
  for(let record of result.records) {
    console.log(`Person with name: ${record.get('name')}`)
    console.log(`Available properties for this node are: ${record.keys}\n`)
  }
} finally {
  await session.close()
}
----

xref:transactions.adoc[More info on running transactions ->]


== Close connections and sessions

Call the `.close()` method on the `Driver` instance when you are finished with it, to release any resources still held by it.
The same applies to any open sessions.

[source, javascript]
----
const driver = neo4j.driver(URI, neo4j.auth.basic(USER, PASSWORD))
let session = driver.session({ database: 'neo4j' })

// session/driver usage

session.close()
driver.close()
----

== API documentation

For in-depth information about driver features, check out the link:https://neo4j.com/docs/api/javascript-driver/current/[API documentation].
