[[driver-session-api]]
= The session API
:description: This section details the Session API that are made available by the driver, with each Session class oriented towards a different form of programming.  This section describes simple sessions, transactions executed within a simple session and the results thereof.  This section describes asynchronous sessions, transactions executed within an asynchronous session and the results thereof.  This section describes reactive sessions, transactions executed within a reactive session and the results thereof.  This section details the configuration options available when constructing a session.

This chapter describes the following:

* xref:session-api/simple.adoc[Simple sessions]
** xref:session-api/index.adoc#driver-simple-lifecycle[Lifecycle]
** xref:session-api/index.adoc#driver-simple-transaction-fn[Transaction functions]
** xref:session-api/index.adoc#driver-simple-autocommit-transactions[Auto-commit transactions]
** xref:session-api/index.adoc#driver-simple-result-consume[Consuming results]
** xref:session-api/index.adoc#driver-simple-result-retain[Retaining results]
* xref:session-api/asynchronous.adoc[Asynchronous sessions]
** xref:session-api/index.adoc#driver-async-transaction-fn[Transaction functions]
** xref:session-api/index.adoc#driver-async-autocommit-transactions[Auto-commit transaction]
** xref:session-api/index.adoc#driver-async-result-consume[Consuming results]
* xref:session-api/reactive.adoc[Reactive sessions]
** xref:session-api/index.adoc#driver-rx-lifecycle[Lifecycle]
** xref:session-api/index.adoc#driver-rx-transaction-fn[Transaction functions]
** xref:session-api/index.adoc#driver-rx-autocommit-transactions[Auto-commit transactions]
** xref:session-api/index.adoc#driver-rx-result-consume[Consuming results]
** xref:session-api/index.adoc#driver-rx-cancellation[Cancellation]
* xref:session-api/configuration.adoc[Configuration]


[[driver-simple-sessions]]
== Simple sessions

[NOTE]
====
Available in:

- *.NET Driver*
- *Go Driver*
- *Java Driver*
- *Python Driver*
====

Simple sessions provide a "classic" *_blocking style_* API for Cypher execution.
In general, simple sessions provide the easiest programming style to work with since API calls are executed in a strictly sequential fashion.


[[driver-simple-lifecycle]]
=== Lifecycle

The session lifetime extends from session construction to session closure.
In languages that support them, simple sessions are usually scoped within a context block; this ensures that they are properly closed and that any underlying connections are released and not leaked.


[.tabbed-example]
.Session construction and closure
====
[.include-with-dotnet]
======
[source, csharp , indent=0]
----
using (var session = driver.Session(...)) {
    // transactions go here
  }
----
======

[.include-with-go]
======
[source, go , indent=0]
----
session := driver.NewSession(...)
defer session.Close()
// transactions go here
----
======

[.include-with-java]
======
[source, java, indent=0]
----
try (Session session = driver.session(...)) {
    // transactions go here
}
----
======

[.include-with-python]
======
[source, python, indent=0]
----
with driver.session(...) as session:
    // transactions go here
----
======

====

*_Sessions can be configured in a number of different ways_*.
This is carried out by supplying configuration inside the session constructor.
See xref:session-api/configuration.adoc[Session configuration] for more details.


[[driver-simple-transaction-fn]]
=== Transaction functions

Transaction functions are used for containing transactional units of work.
This form of transaction requires minimal boilerplate code and allows for a clear separation of database queries and application logic.

Transaction functions are also desirable since they encapsulate retry logic and allow for the greatest degree of flexibility when swapping out a single instance of server for a cluster.

Transaction functions can be called as either read or write operations.
This choice will route the transaction to an appropriate server within a clustered environment.
If you are operating in a single instance environment, this routing has no impact. It does give you flexibility if you choose to adopt a clustered environment later on.

Before writing a transaction function *_it is important to ensure that it is designed to be idempotent_*.
This is because a function may be executed multiple times if initial runs fail.

Any query results obtained within a transaction function should be consumed within that function, as connection-bound resources cannot be managed correctly when out of scope.
To that end, transaction functions can return values but these should be derived values rather than raw results.

[NOTE]
====
*_Transaction functions are the recommended form for containing transactional units of work_*.

*_When a transaction fails, the driver retry logic is invoked_*.
For several failure cases, the transaction can be immediately retried against a different server.
These cases include connection issues, server role changes (e.g. leadership elections) and transient errors.
====

[.tabbed-example]
.Transaction function
====
[.include-with-dotnet]
======
[source, csharp, indent=0]
----
include::{dotnet-examples}/Examples.cs[tags=transaction-function]
----
======

[.include-with-go]
======
[source, go, indent=0]
----
include::{go-examples}/examples_test.go[tags=transaction-function]
----
======

[.include-with-java]
======
[source, java, indent=0]
----
include::{java-examples}/TransactionFunctionExample.java[tags=transaction-function]
----
======

[.include-with-python]
======
[source, python, indent=0]
----
include::{python-examples}/test_transaction_function_example.py[tags=transaction-function-import]
----

[source, python, indent=0]
----
include::{python-examples}/test_transaction_function_example.py[tags=transaction-function]
----
======

====


[[driver-simple-autocommit-transactions]]
=== Auto-commit transactions

An *_auto-commit transaction_* is a *_basic but limited form of transaction_*.
Such a transaction consists of only one Cypher query and is not automatically replayed on failure.
Therefore any error scenarios must be handled by the client application itself.

Auto-commit transactions are *_intended to be used for simple use cases_* such as when learning *Cypher* or writing one-off scripts.

[WARNING]
====
It is not recommended to use auto-commit transactions in production environments.
====

[NOTE]
====
Unlike other kinds of Cypher Query, `PERIODIC COMMIT` queries do not participate in the causal chain.

Therefore, the only way to execute `PERIODIC COMMIT` from a driver is to use auto-commit transactions.

Please refer to the link:/docs/cypher-manual/4.1/query-tuning/using#query-using-periodic-commit-hint[Cypher Manual -> `PERIODIC COMMIT` query hint].
====

[.tabbed-example]
.Simple auto-commit transactions
====

[.include-with-dotnet]
======
[source, csharp, indent=0]
----
include::{dotnet-examples}/Examples.cs[tags=autocommit-transaction]
----
======

[.include-with-go]
======
[source, go, indent=0]
----
include::{go-examples}/examples_test.go[tags=autocommit-transaction]
----
======

[.include-with-java]
======
[source, java, indent=0]
----
include::{java-examples}/AutocommitTransactionExample.java[tags=autocommit-transaction]
----
======

[.include-with-python]
======
[source, python, indent=0]
----
include::{python-examples}/test_autocommit_transaction_example.py[tags=autocommit-transaction-import]
----

[source, python, indent=0]
----
include::{python-examples}/test_autocommit_transaction_example.py[tags=autocommit-transaction]
----
======

====


[[driver-simple-result-consume]]
=== Consuming results

Query results are typically consumed as a stream of records.
The drivers provide a language-idiomatic way to iterate through that stream.

[.tabbed-example]
.Consuming results
====

[.include-with-dotnet]
======
[source, csharp, indent=0]
----
include::{dotnet-examples}/Examples.cs[tags=result-consume]
----
======

[.include-with-go]
======
[source, go, indent=0]
----
include::{go-examples}/examples_test.go[tags=result-consume]
----
======

[.include-with-java]
======
[source, java, indent=0]
----
include::{java-examples}/ResultConsumeExample.java[tags=result-consume]
----
======

[.include-with-python]
======
[source, python, indent=0]
----
include::{python-examples}/test_result_consume_example.py[tags=result-consume]
----
======

====


[[driver-simple-result-retain]]
=== Retaining results

Within a session, *_only one result stream can be active at any one time_*.
Therefore, if the result of one query is not fully consumed before another query is executed, the remainder of the first result will be automatically buffered within the result object.

image::driver-result-buffer.svg[title="Result buffer", role="middle"]

This buffer provides a staging point for results, and divides result handling into *_fetching_* (moving from the network to the buffer) and *_consuming_* (moving from the buffer to the application).

[NOTE]
====
For large results, the result buffer may require a significant amount of memory.

For this reason, *_it is recommended to consume results in order wherever possible_*.
====

Client applications can choose to take control of more advanced query patterns by explicitly retaining results.
Such explicit retention may also be useful when a result needs to be saved for future processing.
The drivers offer support for this process, as per the example below:

[.tabbed-example]
.Retain results for further processing
====

[.include-with-dotnet]
======
[source, csharp, indent=0]
----
include::{dotnet-examples}/Examples.cs[tags=result-retain]
----
======

[.include-with-go]
======
[source, go, indent=0]
----
include::{go-examples}/examples_test.go[tags=result-retain]
----
======

[.include-with-java]
======
[source, java, indent=0]
----
include::{java-examples}/ResultRetainExample.java[tags=result-retain]
----
======

[.include-with-python]
======
[source, python, indent=0]
----
include::{python-examples}/test_result_retain_example.py[tags=result-retain]
----
======

====


[[driver-async-sessions]]
== Asynchronous sessions

[NOTE]
====
Available in:

- .NET Driver
- Java Driver
- JavaScript Driver
====

Asynchronous sessions provide an API wherein function calls typically return available objects such as futures.
This allows client applications to work within asynchronous frameworks and take advantage of cooperative multitasking.


[[driver-async-lifecycle]]
=== Lifecycle

Session lifetime begins with session construction.
A session then exists until it is closed, which is typically set to occur after its contained query results have been consumed.

Sessions can be configured in a number of different ways. This is carried out by supplying configuration inside the session constructor.
See xref:session-api/configuration.adoc[Session configuration] for more details.

[[driver-async-transaction-fn]]
=== Transaction functions

Transaction functions are *_the recommended form for containing transactional units of work_*.
This form of transaction requires minimal boilerplate code and allows for a clear separation of database queries and application logic.
Transaction functions are also desirable since they encapsulate retry logic and allow for the greatest degree of flexibility when swapping out a single instance of server for a cluster.

Functions can be called as either read or write operations.
This choice will route the transaction to an appropriate server within a clustered environment.
If you are in a single instance environment, this routing has no impact but it does give you the flexibility should you choose to later adopt a clustered environment.

Before writing a transaction function it is important to ensure that any side-effects carried out by a transaction function should be designed to be idempotent.
This is because a function may be executed multiple times if initial runs fail.

Any query results obtained within a transaction function should be consumed within that function, as connection-bound resources cannot be managed correctly when out of scope.
To that end, transaction functions can return values but these should be derived values rather than raw results.

[NOTE]
====
When a transaction fails, the driver retry logic is invoked. For several failure cases, the transaction can be immediately retried against a different server.

These cases include connection issues, server role changes (e.g. leadership elections) and transient errors.
Retry logic can be configured when creating a session.
====

[.tabbed-example]
.Asynchronous transaction functions
========

[.include-with-dotnet]
======
.Transaction function
[source, csharp, indent=0]
----
include::{dotnet-examples}/ExamplesAsync.cs[tags=async-transaction-function]
----
======

[.include-with-java]
======
.Transaction function
[source, java, indent=0]
----
include::{java-examples}/AsyncTransactionFunctionExample.java[tags=async-transaction-function]
----
======

[.include-with-javascript]
======
.Transaction function
[source, javascript, indent=0]
----
include::{javascript-examples}/examples.test.js[tags=async-transaction-function]
----
======

========


[[driver-async-autocommit-transactions]]
=== Auto-commit transactions

An auto-commit transaction is a basic but limited form of transaction.
Such a transaction consists of only one Cypher query and is not automatically replayed on failure.
Therefore any error scenarios must be handled by the client application itself.

Auto-commit transactions are intended to be used for simple use cases such as when learning Cypher or writing one-off scripts.

[WARNING]
====
It is not recommended to use auto-commit transactions in production environments.
====

[NOTE]
====
Unlike other kinds of Cypher Query, `PERIODIC COMMIT` queries do not participate in the causal chain.

Therefore, the only way to execute them from a driver is to use auto-commit transactions.

Please refer to the link:/docs/cypher-manual/4.1/query-tuning/using#query-using-periodic-commit-hint[Cypher Manual -> `PERIODIC COMMIT` query hint].
====

[.tabbed-example]
.Asynchronous auto-commit transactions
========

[.include-with-dotnet]
======
.Auto-commit transaction
[source, csharp, indent=0]
----
include::{dotnet-examples}/ExamplesAsync.cs[tags=async-autocommit-transaction]
----
======

[.include-with-java]
======
.Auto-commit transaction
[source, java, indent=0]
----
include::{java-examples}/AsyncAutocommitTransactionExample.java[tags=async-autocommit-transaction]
----
======

[.include-with-javascript]
======
.Auto-commit transaction
[source, javascript, indent=0]
----
include::{javascript-examples}/examples.test.js[tags=async-autocommit-transaction]
----
======

========


[[driver-async-result-consume]]
=== Consuming results

The asynchronous session API provides language-idiomatic methods to aid integration with asynchronous applications and frameworks.

[.tabbed-example]
.Asynchronous consuming results
========

[.include-with-dotnet]
======
.Consuming results
[source, csharp, indent=0]
----
include::{dotnet-examples}/ExamplesAsync.cs[tags=async-result-consume]
----
======

[.include-with-java]
======
.Consuming results
[source, java, indent=0]
----
include::{java-examples}/AsyncResultConsumeExample.java[tags=async-result-consume]
----
======

[.include-with-javascript]
======
.Consuming results
[source, javascript, indent=0]
----
include::{javascript-examples}/examples.test.js[tags=async-result-consume]
----
======

========


[[driver-rx-sessions]]
== Reactive sessions

[NOTE]
====
Available in:

- .NET Driver
- Java Driver
- JavaScript Driver
====

Starting with *Neo4j 4.0*, the reactive processing of queries is supported.
This can be achieved through reactive sessions.
Reactive sessions allow for dynamic management of the data that is being exchanged between the driver and the server.

Typical of reactive programming, consumers control the rate at which they consume records from queries and the driver in turn manages the rate at which records are requested from the server.
Flow control is supported throughout the entire Neo4j stack, meaning that the query engine responds correctly to the flow control signals.
This results in far more efficient resource handling and ensures that the receiving side is not forced to buffer arbitrary amounts of data.

For more information about reactive stream, please see the following:

*  https://www.reactivemanifesto.org/[The Reactive Manifesto]
*  https://www.reactive-streams.org[Reactive Streams for JVM and JavaScript]
*  https://projectreactor.io/docs/core/release/reference/[Project Reactor reference documentation]
*  http://introtorx.com/[Introduction to Reactive Extensions to .NET]


[NOTE]
--
Reactive sessions will typically be used in a client application that is already oriented towards the reactive style; it is expected that a reactive dependency or framework is in place.

Refer to xref:get-started.adoc[Get started] for more information on recommended dependencies.
--


[[driver-rx-lifecycle]]
=== Lifecycle

Session lifetime begins with session construction.
A session then exists until it is closed, which is typically set to occur after its contained query results have been consumed.


[[driver-rx-transaction-fn]]
=== Transaction functions

This form of transaction requires minimal boilerplate code and allows for a clear separation of database queries and application logic.
Transaction functions are also desirable since they encapsulate retry logic and allow for the greatest degree of flexibility when swapping out a single instance of server for a cluster.

Functions can be called as either read or write operations.
This choice will route the transaction to an appropriate server within a clustered environment.
If you are in a single instance environment, this routing has no impact but it does give you the flexibility should you choose to later adopt a clustered environment.

Before writing a transaction function it is important to ensure that any side-effects carried out by a transaction function should be designed to be idempotent.
This is because a function may be executed multiple times if initial runs fail.

Any query results obtained within a transaction function should be consumed within that function, as connection-bound resources cannot be managed correctly when out of scope.
To that end, transaction functions can return values but these should be derived values rather than raw results.

[NOTE]
When a transaction fails, the driver retry logic is invoked.
For several failure cases, the transaction can be immediately retried against a different server.
These cases include connection issues, server role changes (e.g. leadership elections) and transient errors.
Retry logic can be configured when creating a session.

[.tabbed-example]
.Reactive transaction functions
========

[.include-with-dotnet]
======
.Reactive transaction function
[source, csharp, indent=0]
----
include::{dotnet-examples}/ExamplesRx.cs[tags=rx-transaction-function]
----
======

[.include-with-java]
======
.Reactive transaction function
[source, java, indent=0]
----
include::{java-examples}/RxTransactionFunctionExample.java[tags=rx-transaction-function]
----
======

[.include-with-javascript]
======
.Reactive transaction function
[source, javascript, indent=0]
----
include::{javascript-examples}/examples.test.js[tags=rx-transaction-function]
----
======

========

Sessions can be configured in a number of different ways.
This is carried out by supplying configuration inside the session constructor.
See xref:session-api/configuration.adoc[Session configuration] for more details.


[[driver-rx-autocommit-transactions]]
=== Auto-commit transactions

An auto-commit transaction is a basic but limited form of transaction.
Such a transaction consists of only one Cypher Query and is not automatically replayed on failure.
Therefore any error scenarios will need to be handled by the client application itself.

Auto-commit transactions are intended to be used for simple use cases such as when learning *Cypher* or writing one-off scripts.

[WARNING]
====
It is not recommended to use auto-commit transactions in production environments.
====

[NOTE]
====
The only way to execute `PERIODIC COMMIT` Cypher Queries is to auto-commit the transaction.

Unlike other kinds of Cypher query, `PERIODIC COMMIT` queries do not participate in the causal chain.

Please refer to the link:/docs/cypher-manual/4.1/query-tuning/using#query-using-periodic-commit-hint[Cypher Manual -> `PERIODIC COMMIT` query hint].
====

[.tabbed-example]
.Reactive auto-commit transactions
========

[.include-with-dotnet]
======
.Auto-commit transactions
[source, csharp, indent=0]
----
include::{dotnet-examples}/ExamplesRx.cs[tags=rx-autocommit-transaction]
----
======

[.include-with-java]
======
.Auto-commit transactions
[source, java, indent=0]
----
include::{java-examples}/RxAutocommitTransactionExample.java[tags=rx-autocommit-transaction]
----
======

[.include-with-javascript]
======
.Auto-commit transactions
[source, javascript, indent=0]
----
include::{javascript-examples}/examples.test.js[tags=rx-autocommit-transaction]
----
======

========


[[driver-rx-result-consume]]
=== Consuming results

To consume data from a query in a reactive session, a subscriber is required to handle the results that are being returned by the publisher.

Each transaction corresponds to a data flow which supplies the data from the server.
Result processing begins when records are pulled from this flow.
Only one subscriber may pull data from a given flow.

[.tabbed-example]
.Reactive consuming results
========

[.include-with-dotnet]
======
.Consuming results
[source, csharp, indent=0]
----
include::{dotnet-examples}/ExamplesRx.cs[tags=rx-result-consume]
----
======

[.include-with-java]
======
.Consuming results
[source, java, indent=0]
----
include::{java-examples}/RxResultConsumeExample.java[tags=rx-result-consume]
----
======

[.include-with-javascript]
======
.Consuming results
[source, javascript, indent=0]
----
include::{javascript-examples}/examples.test.js[tags=rx-result-consume]
----
======

========


[[driver-rx-cancellation]]
=== Cancellation

As per the reactive stream specification, a reactive data flow can be cancelled part way through.
This prematurely commits or rolls back the transaction and stops the query engine from producing any more records.


[[driver-session-configuration]]
== Session configuration

[.compact]
`Bookmarks`::
The mechanism which ensures causal consistency between transactions within a session.
Bookmarks are implicitly passed between transactions within a single session to meet the causal consistency requirements.
There may be scenarios where you might want to use the bookmark from one session in a different new session.
+
*Default:* None (Sessions will initially be created without a bookmark)

Default Access Mode::
A fallback for the access mode setting when transaction functions are not used.
Typically, access mode is set per transaction by calling the appropriate transaction function method.
In other cases, this setting is inherited. Note that transaction functions will ignore/override this setting.
+
*Default:* Write

Database::
The database with which the session will interact.
When you are working with a database which is not the default (i.e. the `system` database or another database in Neo4j 4.0 Enterprise Edition), you can explicitly configure the database which the driver is executing transactions against.
See link:/docs/operations-manual/4.1/manage-databases/introduction#manage-databases-default[Operations Manual -> The default database] for more information on databases.
+
*Default:* the default database as configured on the server.

`Fetch Size`::
The number of records to fetch in each batch from the server.
Neo4j 4.0 introduces the ability to pull records in batches, allowing the client application to take control of data population and apply back pressure to the server.
This `FetchSize` applies to xref:session-api/simple.adoc[simple sessions] and xref:session-api/asynchronous.adoc[async-sessions] whereas reactive sessions can be controlled directly using the request method of the subscription.
+
*Default:* 1000 records
